### ISSUE TITLE
Body height of 0?

### ISSUE THREAD

**Issue by ryanjgill** [18F/web-design-standards#1000]
I was just curious why the body of the design standards have a height of 0 when inspecting it with the chrome dev tools. Does this have to do with the layout using absolutely positioned elements?

![screen shot 2016-02-17 at 9 04 31 am](https://cloud.githubusercontent.com/assets/2071064/13113671/99eb24da-d555-11e5-883a-7238dcec6faf.png)

Also, should I be setting the height of the body to 0 to ensure it doesn't block other content.

**Comment by msecret** [comment]
Hi @ryanjgill, so we're not manually setting the height to anything. The reason the body height is 0 is like you said, the position fixed elements. For instance, if you change the header to position: fixed to static, the height becomes the height of the header. 

I can't think of a reason why you'd need to set the height of body to 0 so might need more context there to understand what you mean. Another point: using position: fixed like on the standards site isn't necessary to use the standards, it's just how we happened to implement the styleguide.

**Comment by ryanjgill** [comment]
@msecret Ok great. Thanks for clearing that up for me.
