### ISSUE TITLE
NPM uploads seem not to be working

### ISSUE THREAD

**Issue by edwelker** [18F/web-design-standards#1003]
Hi USWDS,

I tried to follow the instructions on `master` to install via NPM, but it would seem that the NPM registry is returns the following: 
`npm install --save uswds --registry https://registry.npmjs.org/`

```
npm ERR! node v0.10.24
npm ERR! npm  v3.7.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/uswds
npm ERR! 404
npm ERR! 404  'uswds' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

and additionally:

https://registry.npmjs.org/uswds returns simply `{}`

**Comment by maya** [comment]
Hi @edwelker, we haven't published it to npmjs.org yet. It will be published in our next `v0.10.0` release. cc @rogeruiz

**Comment by msecret** [comment]
@edwelker, in the mean time you can install the standards through git with the following:

```
npm install --save git+https://git@github.com/18F/web-design-standards.git#18f-pages --registry https://registry.npmjs.org/
```

It should be noted that when we do publish to npm, the library will have a different structure, so some file paths may be different.

**Comment by edwelker** [comment]
Thanks!!   Just wanted to point out that your documentation on master currently says it's available.  :)
