### ISSUE TITLE
typo on .usa-width-five-sixth @ medium break point

### ISSUE THREAD

**Issue by lboonebah** [18F/web-design-standards#1006]
Documentation states that 1/6 goes to 1/3 @ medium break point. ".usa-width-five-sixths" should be 2/3 (65.05695%) but it is 5/6 (82.52847%) and breaks the layout

PR: https://github.com/18F/web-design-standards/pull/1005
<img width="852" alt="screen shot 2016-02-19 at 2 39 09 pm" src="https://cloud.githubusercontent.com/assets/13366987/13187051/fc4f0bb0-d716-11e5-8271-2f44abf15a83.png">

**Comment by msecret** [comment]
This may have been fixed

**Comment by maya** [comment]
Yes, fixed via #1005.
