### ISSUE TITLE
Checked but disabled checkbox

### ISSUE THREAD

**Issue by amyfens** [18F/web-design-standards#1014]
Hi there,

We've encountered a need to design for a checked but disabled checkbox (where one of the options in the fieldset is automatically selected, driven by the underlying data conditions). For now, we've simply made the checkbox visually identical to other active checkboxes, but have disallowed the ability to uncheck/check it.

Would love to hear thoughts on this--ideally there would be a visual cue to identify the required/default selections, so that users don't simply think part of the form is broken or buggy.

Thanks!
Amy

**Comment by carodew** [comment]
Hi @amyfens – I do think there needs to be a visual cue that indicates the checkbox is disabled. I am not aware of any research specifically about the usability of disabled and checked checkboxes, but the general guidance of affordance would indicate that there should be some kind of indication. 

You could try using the current disabled styling for the unchecked box and add a check, so it's consistent with both the disabled state and the enabled checkbox. Just be sure to consider appropriate color contrast for the thing. 

We may possibly address this when we focus on building out our form components, which is upcoming, but I can't give a specific timeline on this.

**Comment by amyfens** [comment]
We'll definitely look into that. Another thing to consider is that in our experience so far, the disabled option of both radio and checkbox forms appears to be a slightly smaller selector/image, and also (in the case of the radio button) appears to affect the styling of the associated label. I'm working on establishing the cause, and once I do I'll pass along for evaluation/remediation, but figured I would mention.

**Comment by amyfens** [comment]
Here's what we did for the disabled checkbox--pretty easy fix for now:

Added a **:checked:disabled** option with the same image styling as **:checked**
`input[type="checkbox"]:checked + label::before,
input[type="checkbox"]:checked:disabled + label::before {
  background-image: url("../img/correct8.png");
  background-image: url("../img/correct8.svg");
  background-position: 50%;
  background-repeat: no-repeat; }`

Darkened the disabled color (within the palette options) to improve contrast for both checkboxes and radio buttons:
`input[type="checkbox"]:disabled + label::before,
input[type="radio"]:disabled + label::before {
  background: #aeb0b5;
  box-shadow: 0 0 0 1px #5b616b;
  cursor: not-allowed; }`

Hopefully this helps. Looks like it will be a workable solution for us!

**Comment by maya** [comment]
We can currently use checked and disabled together. Closing this out!
