### ISSUE TITLE
Question about _list.scss

### ISSUE THREAD

**Issue by gigifrias** [18F/web-design-standards#1027]
Hi, I'm part of the team at BBG’s ODDI working with the standards on WordPress and we are having a hard time understanding your approach to styling lists.

Can you please walk us through the thought process behind setting the display of all lists to "table" and that of each `<li>` to "table-row"? More specifically, we'd like to know why you're defining the bullet glyph by using `content: "•";` within a separate table cell rather than using the native list-style-type property.  
```
ul li {
  display: table-row;

  &:before {
    content: "•";
    display: table-cell;
    padding-right: 0.4em;
  }
}
```
We've noticed that the spacing between the bullet and the text on lists varies based on the length of the longest list item since table cells adapt accordingly. That doesn't usually cause any issues, but it creates visual inconsistencies when you have multiple lists on one page. 

I apologize if we are being a little dense, but we are not seeing the big picture advantage to your approach, and it would really help us to know how you arrived at this solution.

Here's a screenshot of a post with multiple lists in case I didn't make myself clear enough. 
<img width="740" alt="screen shot 2016-03-03 at 1 47 14 pm" src="https://cloud.githubusercontent.com/assets/7237264/13505283/8463606c-e146-11e5-9283-44b372fadaca.png">

Thanks so much for your help,
Gigi

**Comment by maya** [comment]
Hi @gigifrias! Thanks for your question. The reason we're using that strategy is to align lists flush left. Browsers behave very differently and it's surprisingly hard to align them across different browsers. We followed the approach here: https://j.eremy.net/align-lists-flush-left/ which goes into more detail.

I haven't seen different spacing before between bullet and text, and tested it locally and am not seeing that either, so wonder if something else is going on in the CSS.

For reference, this is what we get with a very long list item:
<img width="782" alt="screen shot 2016-03-03 at 11 13 26 am" src="https://cloud.githubusercontent.com/assets/5249443/13506054/ff27472a-e130-11e5-8c05-50cd679ce2f8.png">

**Comment by gigifrias** [comment]
Thanks for the quick reply, @maya! 

To be clear, the spacing is not different within one list (inside of the same ul/ol tag), it's just that it varies from list to list when you have more than one set on a page separated by other elements. 

I'll take a closer look at the article you used in your approach, but would love to know if you are able to replicate our issue on your end.

Thanks again!

**Comment by maya** [comment]
No problem, @gigifrias! I forgot to ask in the previous message, do you have a live link for us to look at?

I understand the spacing is not different within one list but I was not able to get a different spacing no matter the length of the list item I used, which is why I wasn't able to reproduce the issue.

**Comment by gigifrias** [comment]
We figured out the issue!

In order to center our main content column on the page, we had to add `width: 100%;` with auto margins on both the left and right for all lists which is what was making the cell widths vary from list to list. We've now added a width to the cell with the bullet/number and that fixed the issue.

The link you shared helped us to better understand your approach and pinpoint our mistake. Thanks so much for your quick attention and help.

P.S. We are not quite ready to publicly share our site just yet but we are getting very close and will definitely let you and your team know so that you can give us your feedback.

**Comment by maya** [comment]
Awesome! So glad to hear you figured it out. Keep us posted on the new site :tada:
