### ISSUE TITLE
https://playbook.cio.gov/designstandards 404 on uswds js file

### ISSUE THREAD

**Issue by bsmithgall** [18F/web-design-standards#1058]
Hello! Not sure if this is the right place (please redirect me if it isn't), but it appears as though a JS file is not loading properly on playbook.cio.gov/designstandards, which appears to be breaking accordions, code examples, and some other pieces.

<img width="1280" alt="screen shot 2016-03-14 at 9 17 28 pm" src="https://cloud.githubusercontent.com/assets/1957344/13764861/4e30a634-ea2a-11e5-933a-6e9d207bb382.png">

<img width="546" alt="screen shot 2016-03-14 at 9 21 56 pm" src="https://cloud.githubusercontent.com/assets/1957344/13764910/e4d9d6e6-ea2a-11e5-9376-00b9071aa7ba.png">

**Comment by rogeruiz** [comment]
Thanks @bsmithgall! This issue has been resolved in #1059 :tada:
