### ISSUE TITLE
Deliver External Assets via HTTPS

### ISSUE THREAD

**Issue by daderonan** [18F/web-design-standards#1062]
Deliver External Assets via HTTPS for full security authentication.

If you use a secure site (https) and are trying to load an external asset from a non-secure site (http), then it breaks the security rules and is technically not secure. All external assets (javascripts, css, pdf, etc.) need to be delivered from a secure site (https) for a site to be fully authenticated as secure, if not it will display errors and not be green in the address bar.

The errors will display grey with no padlock for IE, Chrome or FF instead of green. In FF it will say “This website does not supply any identity information.” In Chrome it will say “This page is trying to load scripts from unauthenticated sources.”

**Comment by maya** [comment]
Hi @daderonan, thanks for opening this. Just to clarify, are you noticing an issue with HTTPS assets with our system or making more general suggestions?

**Comment by daderonan** [comment]
@maya 
I have noticed an issue with HTTPS assets. I am recommending a prevention control system for when an asset is to be served to the user from an external non-https location.  
Why?
It is Federal government policy that all assets be delivered via https. "This Memorandum requires that all publicly accessible Federal websites and web services1 only provide service through a secure connection." (https://www.whitehouse.gov/sites/default/files/omb/memoranda/2015/m-15-13.pdf)
"Mixed Content8: Websites served over HTTPS need to **ensure** that **all external resources (images, scripts, fonts, iframes, etc.) are also loaded over a secure connection**. Modern browsers will refuse to load many insecure resources referenced from within a secure website. When migrating existing websites, this can involve a combination of automated and manual effort to update, replace, or remove references to insecure resources. For some websites, this can be the most time consuming aspect of the migration process."

For example: usa.gov wants to display some data to the user on a webpage, but the data is from a non-secure site http. That would break the secure connection thereby disabling the secure connection and causing browser errors, not to mention the fact that it is against federal government policy.

Suggested Solution:
In order to **ensure**...when inserting an asset, have a validation system checking if the source is from https, if it is not, then prevent insertion with a warning "All assets must be delivered from a secure location HTTPS. If that is not possible, then simply link to it."

I can also provide some validating script if that would help.

I hope that adds some clarification to the issue.

**Comment by msecret** [comment]
Hi @daderonan. Thank you for writing. I understand what you're saying but would like some clarification on how it could fit into our Standards project.

Currently, the standards is a front-end CSS and JS library. It doesn't really make any assumptions of how it's assets are being served and what the backend server is. So for example, if you wrote a validating script, what programming language would you write it in? When would it be run?

We can encourage good practice of using HTTPS assets by ensuring our own documentation site, `https://playbook.cio.gov/designstandards/`. While we could also make a recommendation on always using https when including other off-site assets, we're still determining the scope of recommendations the standards should make. 

We do have a team that's measuring how federal government domains are meeting best security practices on the web. Their website is here: https://pulse.cio.gov/.

**Comment by juliaelman** [comment]
@daderonan thank you for your issue! 

As @msecret mentioned, we encourage good practice of HTTPS and security measures. However, implementing a validation system is something that is not in scope of the overall WDS project.
