### ISSUE TITLE
Spawn issues on windows

### ISSUE THREAD

**Issue by lobsteropteryx** [18F/web-design-standards#1068]
The `bundle-gems` task (in `website.js`) is failing for me on win7; I guess that this is due to the fact that `bundle` itself is a .bat file (see:  https://github.com/nodejs/node-v0.x-archive/issues/2318).

Pulling in [cross-spawn](https://www.npmjs.com/package/cross-spawn) fixes the issue for me.

I haven't tested this solution on other platforms, but can submit a PR if you like.

@jonahadkins

**Comment by rogeruiz** [comment]
Interesting! Thanks @lobsteropteryx for testing this on Windows. A PR with the Windows fix would be great. Do any of the other commands fail on your machine? I can take a look at your PR and make sure there are no regressions on other platforms.

**Comment by rogeruiz** [comment]
Leaving this documentation reference here for the sake of visibility.

https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

**Comment by lobsteropteryx** [comment]
That looks like a better solution, perhaps...I will test, and submit a PR.

**Comment by lobsteropteryx** [comment]
Looking at the link you added, I'm not sure how to make that work cross-platform; I went ahead and submitted a PR with cross-spawn.

This PR also includes the changes from #1072 , since the require statements for `spawn` were changed there as well.

**Comment by rogeruiz** [comment]
Fixed by #1073
