### ISSUE TITLE
Date Input Field

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1076]
Was using the default date input in Safari, which adds a stepper component to the element. This causes the last digit to be lost from view using the default container widths.

Changing stylesheets/elements/_inputs.css to the following solves the issue.

``````
.usa-form-group-day, 
.usa-form-group-month, 
.usa-form-group-year {
  clear: none;
  float: left;
  margin-right: 1.5rem;
  width: 6rem; // was 5rem
}

.usa-form-group-year {
  width: 8rem; // was 6rem
}
`````

**Comment by jbruce-gsa** [comment]
**With Error Handling**

Adding the same error handling pattern to the date field input results in the fields being butted against each other when the border is applied. Also, the float to the left causes the wrapper to break.

HTML

```
<fieldset>
<div class="usa-input-error">
    <legend>Broadcast On...</legend>
    <span class="usa-input-error-message" id="broadcast_on-input-error" role="alert">The alert needs a broadcast on date.</span>		
    <span class="usa-form-hint usa-datefield-hint">The date to begin displaying the alert.</span>
    <div class="usa-datefield usa-form-group usa-form-group-month">
        <label for="broadcast_on_1">Month</label>
        <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_1" pattern="0?[1-9]|1[012]" type="number" min="1" max="12" value="12" required="required">
    </div>
    <div class="usa-datefield usa-form-group usa-form-group-day">
        <label for="broadcast_on_2">Day</label>
        <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_2" pattern="0?[1-9]|1[0-9]|2[0-9]|3[01]" type="number" min="1" max="31" value="" required="required">
    </div>
    <div class="usa-datefield usa-form-group usa-form-group-year">
        <label for="broadcast_on_3">Year</label>
        <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_3" pattern="[0-9]{4}" type="number" min="1900" max="2000" value="1900" required="required">
    </div> 
</div>	
</fieldset>
```

CSS: _inputs.scss

```
.usa-form-group-day, 
.usa-form-group-month, 
.usa-form-group-year {
  clear: none;
  float: left;
  margin-right: 2rem; // was 1.5rem
  width: 6rem; // was 5rem
}

.usa-form-group-year {
  width: 8rem; // was 6rem

  // new
  &::after {
  	content: '<div style="clear:both;">&nbsp;</div>'
  }
}
```

**Comment by jbruce-gsa** [comment]
Putting the date field into a grid inner-container usa-width-one-half, for example, causes misalignment of hint text.

CSS used to correct

```
.usa-form-hint {
	display: block; // new property
}
```

**Comment by maya** [comment]
Hey @jbruce-gsa! Thanks for submitting this issue. Could you provide some screenshots of the problem you're experiencing?  What is a stepper component?

**Comment by jbruce-gsa** [comment]
@maya - Sure! I think. Never done that here and didn't have time in the moment to research how to do it - let's see if the drag-and-drop actually works.

**Before**
<img width="323" alt="screen shot 2016-03-23 at 1 36 18 pm" src="https://cloud.githubusercontent.com/assets/15252830/13994731/86422222-f0fc-11e5-9004-9f52c1f1bbfc.png">

**After**
<img width="313" alt="screen shot 2016-03-23 at 1 36 40 pm" src="https://cloud.githubusercontent.com/assets/15252830/13994702/64432716-f0fc-11e5-84de-ca22a3b5e5f1.png">

ps. The "stepper" is one of the OS X UI Components - sorry, I do iOS and OS X dev as well - that's not a common term?! ;)

[Apple Docs](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ControlsSelection.html#//apple_ref/doc/uid/20000957-CH49-SW18), if you're curiosity gets the better of you.

**Comment by maya** [comment]
Thanks for those screenshots! That gives me a much better idea of what's happening. 

Quick question: is the stepper appearing when you view the date input here: https://playbook.cio.gov/designstandards/form-controls/#date-input

Or just on your implementation?

**Comment by jbruce-gsa** [comment]
Interestingly enough, no.

Wonder if something got changed when I ported it over to being a reusable component.

My output:
```
<fieldset>
    <legend>Publish On...</legend>
    <div>
        <span class="usa-form-hint usa-datefield-hint">The date to begin displaying the alert.</span>
        <div class="usa-datefield usa-form-group usa-form-group-month">
            <label for="broadcast_on_1">Month</label>
            <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_1" pattern="0?[1-9]|1[012]" type="number" min="1" max="12" value="" required="required">
        </div>
        <div class="usa-datefield usa-form-group usa-form-group-day">
            <label for="broadcast_on_2">Day</label>
            <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_2" pattern="0?[1-9]|1[0-9]|2[0-9]|3[01]" type="number" min="1" max="31" value="" required="required">
        </div>
        <div class="usa-datefield usa-form-group usa-form-group-year">
            <label for="broadcast_on_3">Year</label>
            <input aria-describedby="dobHint" class="usa-form-control" name="broadcast_on_3" pattern="[0-9]{4}" type="number" min="1900" max="2000" value="" required="required">
        </div>
        <div style="clear: both; overflow: hidden; height: 1px;">&nbsp;</div>
    </div>	
</fieldset>
```

The only difference I see is that I removed the "usa-date-of-birth" class from the containing div - as I don't think it is, strictly speaking, a DOB-specific element (unless I'm using it incorrectly)?

**Comment by maya** [comment]
I think I know what's happening. There should be a div with the class `usa-date-of-birth` wrapped around the inputs. This is missing from your code sample. You can see it in the code sample on the Draft Standards website.

We are hiding the spinners.

```html
  <fieldset>
    <legend>Date of birth</legend>
    <span class="usa-form-hint usa-datefield-hint" id="dobHint">For example: 04 28 1986</span>
    <div class="usa-date-of-birth">
      <div class="usa-datefield usa-form-group usa-form-group-month">
        <label for="date_of_birth_1">Month</label>
        <input aria-describedby="dobHint" class="usa-form-control" id="date_of_birth_1" name="date_of_birth_1" pattern="0?[1-9]|1[012]" type="number" min="1" max="12" value="">
      </div>
      <div class="usa-datefield usa-form-group usa-form-group-day">
        <label for="date_of_birth_2">Day</label>
        <input aria-describedby="dobHint" class="usa-form-control" id="date_of_birth_2" name="date_of_birth_2" pattern="0?[1-9]|1[0-9]|2[0-9]|3[01]" type="number" min="1" max="31" value="">
      </div>
      <div class="usa-datefield usa-form-group usa-form-group-year">
        <label for="date_of_birth_3">Year</label>
        <input aria-describedby="dobHint" class="usa-form-control" id="date_of_birth_3" name="date_of_birth_3" pattern="[0-9]{4}" type="number" min="1900" max="2000" value="">
      </div>
    </div>
  </fieldset>
```

**Comment by jbruce-gsa** [comment]
Oops. Sorry - I hid the following at the bottom of that comment:

"The only difference I see is that I removed the "usa-date-of-birth" class from the containing div - as I don't think it is, strictly speaking, a DOB-specific element (unless I'm using it incorrectly)?"

It's a semantics concern as well as a, "Am I only supposed to use this for DOB fields" question.

**Comment by maya** [comment]
That's a great question! Looping in our UX-er @carodew - can/should this field be applied more widely to all date inputs?

I remember there was some earlier conversation about other date inputs being better suited with different kinds of patterns.

**Comment by carodew** [comment]
Hi! My belief is that different types of date inputs will be more or less appropriate depending on the context. Given the short amount of time we had to launch the alpha version, we didn't have time to design, validate, and build additional input styles, but you can get a sense of the different types that might be viable from GDS: https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html

It may make more sense if we abstract the CSS class to something more like `usa-memorable-date` instead of being DOB specific.

**Comment by jbrucegsa** [comment]
@carodew - I definitely think the rename of class would be worthwhile. I will keep the ticket open for now, as a reminder to myself when I have time.

**Comment by juliaelman** [comment]
As mentioned [here](https://github.com/18F/web-design-standards/issues/1108#issuecomment-220610156), we're going to aim for a more wholistic approach.

Refs #860
