### ISSUE TITLE
Advanced Grid Customization Docs / Question

### ISSUE THREAD

**Issue by stevenhaddox** [18F/web-design-standards#1077]
I tried to implement this on a custom app for our contract a few days ago. We work with a lot of OSS projects and have a custom header we implement across all the projects we work with. This banner sees a lot of CSS overrides and hacking to make it work responsively and properly given that it has to be abused to work on bootstrap, foundation, etc., etc. depending upon the respective OSS tool we are working with.

Because we have a custom header that isn't using a specific framework the integration of USWDS draft was deemed to be too much work as it would require more overrides and ugly CSS to beat it into the same fit as we've had to do with bootstrap and friends.

Is there any clear documentation or has their been any thought to help address how to integrate and/or customize Neat's custom grid sizing and responsiveness with your classes rather than just saying "advanced users can use Neat" and pointing us to their documentation? Are there any considerations for needing to respect USWDS grid class names or if we go the advanced route are we ignoring your recommended grid and that's okay as long as we use the same framework?

Related issues are probably: #983, #787, #901

**Comment by maya** [comment]
Hi @stevenhaddox, tanks for opening this issue. 

In general, you're free to include other CSS into your implementation of the Draft Standards, so would encourage you to use what makes sense for your project. Of course, using a single grid system would be the most consistent. 

If you'd like to provide more details of what you need out of a grid system, we'll be better able to assess if it can be modified to meet your needs.
