### ISSUE TITLE
Sentence or title case for headers?

### ISSUE THREAD

**Issue by debracleaver** [18F/web-design-standards#1081]
We're using the web design standards for Vote.org (launching very soon) and we're stuck on header capitalization.  Should we use sentence or title case for headers?  I'm leaning toward sentence case for all headers, but i could be persuaded to use title case for H1 and sentence case for the others.

What says you?

**Comment by maya** [comment]
Hey @debracleaver, we use sentence case for headings. See info here: https://pages.18f.gov/content-guide/capitalization/#headings
