### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by fulldecent** [18F/web-design-standards#1093]
Please host these on CDN for simple reuse

**Comment by maya** [comment]
@fulldecent thanks for this request. We'll keep this open for consideration, but don't have a timeframe on when we can do this. 

Related to #870.

**Comment by fulldecent** [comment]
It is done! CDNJS has added this and will maintain it automatically based on the npm.

Pull request coming to update the documentation.

**Comment by lukefretwell** [comment]
@fulldecent is this available? If so, where can I find? Thank you.

**Comment by fulldecent** [comment]
This is hosted by CDNJS, it is not an official US government CDN server, so only use this server if you trust it.

I trust it.

It is at:

https://cdnjs.com/libraries/uswds/?

**Comment by juliaelman** [comment]
Thank you everyone for you enthusiasm for the Draft USWDS! 

Per @jpyuda comment [here](https://github.com/18F/web-design-standards/pull/1100#issuecomment-207456638), we are not looking at officially supporting a CDNJS version at this time.

**Comment by s2t2** [comment]
Hey I just wanted to chime in that an officially-supported CDN would be a desired way to leverage this library, especially helpful for rapid prototyping. 

See also: [Twitter Bootstrap - Getting Started w/ CDN](https://getbootstrap.com/docs/3.3/getting-started/#download-cdn).
