### ISSUE TITLE
Date Input Error Width

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1094]
Still compiling a view generator. Added error design pattern to the Date Input element. Ran into an issue with the input width setting:

<img width="1057" alt="screen shot 2016-04-01 at 8 34 25 am" src="https://cloud.githubusercontent.com/assets/15252830/14207517/a5e3b300-f7e8-11e5-9479-03de0853bd5c.png">

After appending:

.usa-input-error input {
	width: 100% !important;
}

<img width="1046" alt="screen shot 2016-04-01 at 8 36 06 am" src="https://cloud.githubusercontent.com/assets/15252830/14207538/bc107cf8-f7e8-11e5-9029-f4dbe8ae0ca5.png">

**Comment by maya** [comment]
@jbrucegsa thanks for opening this! Is the issue only with date inputs or was there an issue with standard text inputs as well?

**Comment by jbrucegsa** [comment]
@maya No worries - really hoping to help this project out. 

Unfortunately, I haven't made it through everything yet. 

With the standard CSS, there did not seem to be a visual change to other text inputs - almost like the declaration could be removed without any side-effects.

The only other pattern of inputs I think might be affected would be in the name or address forms, but I have not gotten there yet in the following project: https://github.com/jbrucegsa/uswds

(Hope that project is kosher with y'all. Starting with PHP and available through Packagist to set up a prototyping environment locally. Considering ports to straight JS in the near future. If you setup a PHP server and point to "public" you should see the outputs using the compiled CSS and UI generator.)
