### ISSUE TITLE
Guidance, tools, and examples for documents on the web

### ISSUE THREAD

**Issue by philipashlock** [18F/web-design-standards#1102]
Government agencies continue to post a lot of word documents and PDFs online despite the fact that these don't provide the responsiveness, accessibility, and machine readable requirements for Americans with the current state of screen sizes, screen-readers, search engines, and data analysis tools. 

Typically this is done because uploading a single self-contained file to the web is easier than assembling the assets and markup for web content or navigating the technical or organizational bureaucracy of a government run content management system. The larger problem of solving those challenges isn't something these U.S. design guidelines should necessarily tackle and there does seem to be some progress elsewhere, e.g. [ePub updates](https://rdeltour.github.io/xmlprague2016-epub31/) (hat tip @rdeltour) and [Portable Web Publications](https://www.w3.org/TR/pwp/), but I think a lot can be done to provide guidance, tools, and templates that make it as easy as possible to apply the visual style to traditional documents and make it as easy as possible to output that to the web. 

For one, the guidelines should make it clear that they're not just for what we traditionally think of as websites, but for just about any text-based content that might make it's way to the web, including many things that start out within applications like Microsoft Word or Adobe InDesign. 

Secondly, we should provide templates for applications like Microsoft Word and Adobe InDesign that not only apply these styles, but include a workflow for outputting their content to the web. For instance, we can offer a Word to Markdown [converter](http://word-to-markdown.herokuapp.com/) or [exporter](http://www.writage.com/) that points to an instance of Jekyll/[Federalist](http://federalist.18f.gov/) that comes preloaded with these styles. 

This is riff on #759 but specifically focused on things formatted as simple documents

**Comment by jpyuda** [comment]
Right now, channels outside of the web are out of scope for our efforts, though I have had some discussions with folks at a couple of other agencies who are looking into print guidelines. I'm not quite sure this fits there, either, but it seems a better it. I'll point them to this issue and encourage them to reach out.

**Comment by Drakenhart** [comment]
A suggesting might be to encourage them to create web content as they normally would and have a designer who is print styles savvy to go in and create a printed version of the web document. It may be a bit "weird" for some folks to think of it that way, but if someone can come up with a solid example of how this would work and show them, they might be okay with it.

Plus sides to this: Time and effort reduction - you can modify the website content once when edits are needed, where as you would also have to update the pdf as well.

**Comment by philipashlock** [comment]
@jpyuda I was referring to web hosted content that is not properly published as web native content. This makes up a large portion of government content on the web and since these aren't "channels outside of the web" I don't think that's out of scope is it? 

Sorry if I wasn't clear, but everything I was describing in my original description of the issue was referring to web content. 

@Drakenhart yes, this is the workflow I was getting at. Ensuring that any content which will primarily be shared via the web is managed in a toolchain the focuses on a web-native export, but which can also facilitate other mediums as needed.

**Comment by jpyuda** [comment]
This is out of scope at the present time.
