### ISSUE TITLE
Styles in the documentation are not in the distributed file?  Why?

### ISSUE THREAD

**Issue by edwelker** [18F/web-design-standards#1104]
Hi US-WDS, I'm looking at the documentation here:

https://playbook.cio.gov/designstandards/visual-style/#text-accessibility

where it's recommended to use the listed color combinations, with css classes, etc., however they're not actually included in the {uswds.css}, they're only in {styleguide.css} therefore they can't be used in a real project w/o re-compiling the SCSS files.  This leads to a lot of confusion.

**Comment by edwelker** [comment]
cc: @ducklet

**Comment by maya** [comment]
Thanks for noting this @edwelker! 

We originally considered whether or not we should include helper classes for colors in the CSS. The reason why we'd include it would be to help people easily access colors with classes and prototype more quickly. The reason against it was that users should apply the classes semantically to their use case and not rely on helper classes. Also, it would save some space from the file size.

At this moment, we just include the color variables in Sass and don't include code samples for colors on that page, like you'll find in other components, so this is a clue that there aren't any classes we offer. 

However, I'll discuss it with the team to talk about this more and consider if there's a strong need for this.

**Comment by hursey013** [comment]
When I was poking around the standards yesterday, I made the same mistake of adding some of those color classes to elements thinking that they were in the actual stylesheets.  I could see those being beneficial if someone wanted to use the compiled version or did not have the ability to use SCSS.

**Comment by joshbruce** [comment]
See #1129

**Comment by joshbruce** [comment]
Not sure why this one jumped up to the top of the issues feed for me, but I'll take it. :)

See #1244

**Comment by donjo** [comment]
Closing this issue since the architecture of the project has changed and the documentation site exists as its own repo at 18F/web-design-standards-docs with its own stylesheet.
