### ISSUE TITLE
Field-set class - no attributes - ??

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1108]
Continue to refactor the generator I'm working on.

Was generalizing the introduction text for inputs and field sets. (Labels for text inputs and areas and drop-downs, field sets for radio, checkbox, and date input.)

Ran across this:

For radio and checkboxes there is a class on the <fieldset>: class="usa-fieldset-inputs isa-sans"

For date input - that class does not exist.

When I perform inspect element on the radio and checkboxes to see what attributes are assigned to class - I don't see any. 

Orphaned class? Or, a possible discrepancy between the sass generated here versus from NPM?

Just curious.

**Comment by maya** [comment]
Looks like it's used for this styling:

```
.usa-fieldset-inputs label {
    margin-top: 0;
}
```

I wonder if it's better to use this class or target the `fieldset` element directly.

**Comment by jbrucegsa** [comment]
@maya - Thanks! I noticed that when I ran into another issue - sort of related to #1094.

The question you asked was whether I saw it affecting other inputs.

http://uswdsx.local:8888 - I created this project to extend the USWDS project I have - it has a static page to show the components in various configurations. 

When the radio and checkboxes are placed inside the error container - that style causes a bunching of the options. But, not the same issue as seen #1094.

Hope that's not confusing - brain is a little fried and distracted.

**Comment by jbrucegsa** [comment]
<img width="945" alt="screen shot 2016-04-11 at 9 03 36 pm" src="https://cloud.githubusercontent.com/assets/15252830/14446904/f0d7a900-0028-11e6-88c5-ff7a69410b05.png">

@maya - As you can see, applying the input-error-label to the <code>legend</code> gives us a different font-size when not using <code>usa-sr-only</code>. I would actually prefer to see the <code>legend</code> text the same as a label - separate multiple radios or checkboxes and offers consistency with the select and other inputs.

The label margin-top setting to 0 makes sense for all other input types.

Here is the sass I'm using to create consistency:

```
ul label {
	margin-top: 2rem;
}

.usa-input-error {
	input {
		width: 100% !important;
	}
	
	.usa-field-set {
		margin-top: 0;

	}

	ul label {
		margin-top: 2rem;
	}
}
```

Note: We have reduced the spacing between the radio and checkboxes slightly from the Standard.

**Comment by msecret** [comment]
@jbrucegsa thanks for writing and showing what code you're using to fix this inconsistency. 

We'll take a look at this when we start to work through our roadmap. I've attempted to label this issue so it's categorized correctly. Also feel free to open a PR if you have a recommended fix.

**Comment by jbrucegsa** [comment]
@msecret - Will do!

Just demoed the UIKit we've been building; so, not sure how much time I will have to contribute for a minute - need to port to JS and make it properly open sourced. I was thinking of doing the error wrapping for all the form controls - with modified scss.

**Comment by jbrucegsa** [comment]
@msecret - ps. Would you prefer a separate PR for radio, checkbox, dropdown, and date input? Or, on consolidated PR?

**Comment by msecret** [comment]
@jbrucegsa I think a consolidated PR would work, as it's one shared idea.

**Comment by juliaelman** [comment]
@joshbruce thank you very much for your continued support and contribution to the Standards!

We're going to be taking a holistic approach to how we are refactoring the form elements and are noting this inconsistency as part of that work. Closing this issue for now, but referencing for future consideration.

Refs #860
