### ISSUE TITLE
Form Templates - Address Form - State Dropdown

### ISSUE THREAD

**Issue by jbrucegsa** [18F/web-design-standards#1109]
&lt;select id="state" name="state" type="text"&gt;

I might be able to do a PR on this later - but I don't believe 'type="text"' should be there - because it's a dropdown - not an input with a type.

<select id="state" name="state">

**Comment by maya** [comment]
@jbrucegsa thanks for catching! Yes, let's definitely remove that - type isn't a valid attribute of select.
