### ISSUE TITLE
Misspelling in Sketch file

### ISSUE THREAD

**Issue by OpenGlobe** [18F/web-design-standards#1110]
In Components_sticker_sheet_v.8.sketch file, more is mispelled: 

_Wherever appropriate, we have created type styles and layer styles to make these components **moree**  easily adapted._

Would suggest simply changing to:

"Where appropriate we have created type and layer styles to make the components easier to adapt."

**Comment by maya** [comment]
@OpenGlobe thanks! I've opened an issue in our assets repo here: https://github.com/18F/web-design-standards-assets/issues/18

**Comment by OpenGlobe** [comment]
:+1:

**Comment by carodew** [comment]
This has been fixed! 🎉
