### ISSUE TITLE
Accordion semantics

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1136]
#1120, #1121, #1122 

Not to throw another log on this fire, but:

I was looking at the markup for the accordions and I'm curious about the decision to place them inside a list.

From a dev-perspective it seems the only reason to do it is to be able to add multiple accordions within a single usa-accordion-bordered or usa-accordion div. The reason I say this is that if we place a single accordion inside that those class, **without the li**, the accordion works fine. Almost like the li is used to add a top margin when multiple accordions are at play.

I will see if I can put together a PR for this particular part of the overarching conversation related to accordions. Otherwise, if someone else has the bandwidth before I get to it, by all means.

**Comment by msecret** [comment]
From my perspective, the reason for the list is semantic: it's a list of headings with content. If we were to work to improve the accordion, I'd be happier to focus on ensuring it works with both lists and a single div if there isn't more then one element.

**Comment by joshbruce** [comment]
@msecret - Interesting point and I think I see where you're coming from with it. 

What you're describing sounds like a `dl` - a list of heading-content pairs. Where the heading would be the `dt` and the content would the `dd`. Otherwise, wouldn't it be a single list item containing two distinct pieces of content - semantically?

From the spec (http://www.w3.org/TR/html5/grouping-content.html#the-dl-element): The dl element represents an association list consisting of zero or more name-value groups (a description list).

The documentation in PR #1137 references the HTML spec for other pieces of the current implementation; so, I won't bog this conversation down with that, unless it would be helpful.

From an AT and alternative perspective, I think it would be possible to use straight semantic markup (sorry if the class names are incorrect):

```
<h*>Lead in for accordion group</h*>
<div class="usa-accordion">
    <h*+1 class="usa-accordion-button">Heading</h*>
    <section="usa-accordion-content">
        <p>First paragraph</p>
        <ul>
            <li>List item</li>
            <li>List item</li>
        </ul>
    </section>
</div>
```

Think my semantic assertion would be: That accordions are just collapsed content sections - not a list in the fashion of:

1. List item.
2. List item.

However, the concept of using the `dl` is starting to sound like a viable option.

As an aside, I ran into an issue with putting list content with an accordion content block.

**Comment by joshbruce** [comment]
For completeness in response:

'''
<dl class="usa-accordion">
    <dt class="usa-accordion-button">button title</dt>
    <dd class="usa-accordion-content">
        <p>Hello world!</p>
    </dd>
</dl>
'''

At this point, might be able to clear out classes on 'dt' and 'dd' as Sass and JS can just look for the 'dl' and affect the two valid child elements...I don't believe a 'dl' can take any other direct children - semantically.

**Comment by Drakenhart** [comment]
@joshbruce You are correct the dl can _only_ take the dt and dd elements, semantically. 

The dt can take other [flow elements](https://www.w3.org/TR/html5/dom.html#flow-content-1) except section-creating elements (header, footer, section, h-tags, etc).

The dd element can take any flow content elements.

So using the definition lists for the accordions might be a way to go. It would be a lot cleaner and semantic as well over all. (Avoiding span-salad and div-soup).

In regards to AT it would depend on what browsers supported the mark up, but there would be an understood (or should be an understood) context between the elements as well.
https://www.w3.org/TR/WCAG20-TECHS/H40.html

I think it's worth giving it a shot and testing it. :)

**Comment by msecret** [comment]
First off, what does the acronym AT refer to? Working in government, we often have too many acronyms floating around to remember any new ones.

For now, I think `dt` not being able to take h-tag elements might mean that we don't want to use `dl`s in our main example of how to use the accordion. That being said, we thrive to ensure our styling code works with whatever markup our developers want to use. So if you want to use `dl`'s for accordions and that doesn't work because of the way our CSS is structured, we'd be very happy to look at that and fix our CSS code so it will work in any context.

So feel free to test out the `dl` accordion, I don't think we'll change our main example for now though.

**Comment by joshbruce** [comment]
@msecret - Sorry about that, saw AT used by others and figured it was common vernacular here: Assistive Technologies.

I'm not sure I agree with the `dt` being the issue, as it would be used for the buttons. Would we want to put h-tags in the button?

The `dd` does not have the same restrictions regarding sectioning content - more like an `li` in that regard.

As always, thanks for the consideration.

**Comment by maya** [comment]
Is `h*+1` a real thing in HTML? That would be amazing if so.

To your first point, I don't see why it should be coded as a list. Most accordions I've seen do not and would love to drop it bc it causes a host of other issues.

**Comment by joshbruce** [comment]
h*+1 not a thing...same with h* not being a thing. Was making the argument that accordions should *not* use lists...they used to - with `div` inside the `li` - technically correct from the HTML spec (unless I’m not following where I mentioned a list).

Was saying that one could have a well-formed document that just so happened to use expand collapse (like Wikipedia for mobile) and wouldn’t have to change the JS...much.

```html
<h1>The h* bit</h1>
<section>
<h2>The h*+1 bit</h2>
</section>
```

Where each section is an accordion. Again, same direction as the PR...probably with a lot less JS, just not sure about why some of the JS decisions were made to get the one we have now.
