### ISSUE TITLE
Show password doesn't work [Sign in form]

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1141]
When I click show password, nothing happens.

https://pages.18f.gov/designstandards/form-templates/#login-form

<img width="415" alt="screen shot 2016-04-29 at 1 27 49 pm" src="https://cloud.githubusercontent.com/assets/5249443/14928784/d2c3b47e-0e0e-11e6-9361-da383b4eed79.png">

**Comment by msecret** [comment]
Should be fixed in v0.9.2
