### ISSUE TITLE
Methinks $ gulp website:serve doth remove too much

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1148]
Ran `$ bundle update` and `$ npm update` prior to:

`$ gulp website:serve`

Seems to clear out the entire `/docs/_scss` directory and replacing all but `/docs/_scss/lib`.

Also cleans out the `/dist` directory and replacing all but `/dist/css`.

Results in:

> jekyll 3.1.3 | Error: File to import not found or unreadable: lib/bourbon. Load path: /Users/Alex/Documents/GSA/web-design-standards/docs/_scss on line 3 

This should be the same outcome for `$ npm start` - which seems to be an alias for `$ gulp website:serve`.

This was not the behavior or outcome I used to get - not sure which commit made the change to the `/config/gulp/`.

************************
It seems the behavior that we were going for was a way to align the `/src` and `/assets` directory. In other words, we update a file within `/src` and the change is reflected ultimately in `/assets` - not the previous behavior.

If that is the case, then I might be able to PR the work I've done on a cloned extension (not fork) to get us there.

If not, that's cool, but I'm bummed and not sure what we are needing to do to correct.

#1128 

***************************
ps. I might also be thinking of the other project - remembering that I usually serve the Standards using `$ ./go serve` but switched the other project over to the gulp command...hmmmm...

**Comment by msecret** [comment]
@joshbruce it's true that we switched the standards from using just a Jekyll build process to using an npm gulp workflow. We haven't completely figured this process out yet and are spending time right now fixing some of the issues people are having.

I'll keep this issue open in the mean time as an example of some of the trouble people are having.

**Comment by joshbruce** [comment]
@msecret - Sounds good. And no worries - trying to figure out the gulp thing myself.

I think our conversation in #1137 helped a great deal on this score...at least it helped me.

1. `$ bundle update` - to avoid kramdown error (must be done prior to `$ npm start`).
1. `$ npm update`
1. `$ npm start` - runs copy-vendor-sass as `prestart` and sticks to `npm` commands instead of switching.

Alternatively, using `gulp`:

1. `$ bundle update`
1. `$ npm install` - runs copy-vendor-sass
1. `$ gulp website:serve`

I'll close #1137 momentarily based on conversations elsewhere.

**Comment by juliaelman** [comment]
This issue seems to be fixed with the re-config done in #1164 (removal of `dist/`). Tested locally and everything checks out.

@joshbruce going to close for now, but please feel free to re-open if the issue persists.
