### ISSUE TITLE
Responsive Main Menu (horizontal and with children) 

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1149]
Got questions:

- Is this feature under development or use 3rd party library (refill / pure) for now?

- Where is the codebase for the responsive left navigation again? 

Thanks.

**Comment by juliaelman** [comment]
Hi @dalfaro1 and thank you for your questions! 

1) Please see our [Product Roadmap](https://github.com/18F/web-design-standards/wiki/Product-Roadmap) for future development. 

2) The code base for the left navigation of standards.usa.gov can be found here: https://github.com/18F/web-design-standards/blob/18f-pages-staging/docs/_includes/sidenav.html

**Comment by dalfaro1** [comment]
Thanks Julia!

________________________________

**Comment by dalfaro1** [comment]
Responsive Left Nav code please? Thanks.
________________________________

**Comment by pj-bea** [comment]
+1 for horizontal nav. This is a missing piece of the standards and precludes its adoption for my needs.
