### ISSUE TITLE
Responsive left nav code

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1154]
Responsive left nav code location? 

Thanks!

**Comment by juliaelman** [comment]
Hello @dalfaro1! 

We currently do not have a specific UI component for a left side nav. However, please feel free to checkout our implementation of the left side nav on the website. You can find the code that makes this side nav work in the following locations:

* https://github.com/18F/web-design-standards/blob/18f-pages-staging/docs/_includes/sidenav.html
* https://github.com/18F/web-design-standards/blob/18f-pages-staging/docs/assets/js/styleguide.js

**Comment by dalfaro1** [comment]
Thanks Julia! You guys rock so keep it up!

________________________________
