### ISSUE TITLE
Add Javascript testing

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#1156]
In order for contributors to know when they've broken JS functionality, there should be a suite of tests for the whole JS codebase.

Acceptance criteria
- [x] The tests should fail if some DOM functionality is broken, such as a selector being wrong.
- [x] The tests should run with the `npm run test` command.
- [x] The tests should be runnable on circle or travis CI.
- [x] The tests should be repeatable and stateless.

**Comment by juliaelman** [comment]
Ref https://github.com/18F/web-design-standards/issues/770

**Comment by el-mapache** [comment]
Based on the acceptance criteria, it sounds like this request is more about writing end-to-end tests to ensure the page behaves the way we expect it to. Does that seem right? We should open a separate issue, I think, to write unit tests for the individual JS components. Let me know what ya'll think of that!

**Comment by msecret** [comment]
Most of this was done in #1159.

**Comment by msecret** [comment]
@el-mapache, can we build off #1159 and add the tests so they run in circle ci?

**Comment by el-mapache** [comment]
@msecret Actually, the tests are already running in circle. I just hooked in to the `npm test` command that was already in the package.json. If you go here https://circleci.com/gh/18F/web-design-standards/82 and checkout the npm test section you can see the test output! 🎉

**Comment by el-mapache** [comment]
Although, I'm not sure if test failures will cause the build to fail as well, since I didn't update the circle.yml at all. Looking into that.

**Comment by rogeruiz** [comment]
@el-mapache take a look at this WIP PR. https://github.com/18F/web-design-standards/pull/1041

It's considered WIP as it would break the deployment since we still have a lot of linting errors. But once they're fixed, that branch can be merged.

**Comment by el-mapache** [comment]
@roger awesome, looks like a useful utility! Rebasing that branch on top of master and fixing the errors would allow it to be merged, right?

**Comment by el-mapache** [comment]
@msecret I believe this issue can be closed. PR is merged and the tests are running on circle 🍨

**Comment by msecret** [comment]
Thanks @el-mapache !
