### ISSUE TITLE
Background color mixins

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1158]
**Description**

When applying background colors to elements, it would be nice if there was a simple way to also apply the proper text colors based on the text accessibility portion of the Standards. 

Mixins can facilitate this move and is in keeping with our use of [Bourbon](http://bourbon.io).

See PR #1129

**Ask**

@msecret, @maya, and @carodew, and I were discussing this in the aforementioned PR, which has been closed for further discussion by the community. 

The ask is described by the _To do_.

**To do**

Bringing over the ideas I saw mentioned from the PR - let me know if I missed something.
- [x] Determine the naming convention to be used. The PR used usa-bgcolor-*.
- [x] Determine how to handle `a` tags - should links be defined within the mixin - when a developer chooses a background-color they automatically get the `a` color; or, let the developer handle this?
- [x] Modify `/src` files to ensure proper incorporation.
  - [ ] Update alerts and label components to use mixin.

**Comment by donjo** [comment]
Closing this out for now since it looks like the associated PRs were closed. However, utility classes and/or mixins to add color may be on our radar in the future and we'll reference the previous discussions when we come to it.
