### ISSUE TITLE
[Refactor HTML/CSS] Button vs Link semantics

### ISSUE THREAD

**Issue by el-mapache** [18F/web-design-standards#1162]
## Use of `<button>` vs. `<a>`

In our example templates, we have a few instances of using an anchor tag with an href of '#' to control page or component behavior. Semantically speaking, `<a>` should be used to link either to external resources or another section of the current document; a `<button>` should be used to control behavior.

Here are some links around the issue: 
* http://stackoverflow.com/a/11899663
* https://davidwalsh.name/html5-buttons

**Acceptance Criteria**
- [ ] create new css class for styling buttons like links
- [ ] update `<a>` to `<button>` with the new class

**Comment by maya** [comment]
@el-mapache we do have a button class for anchor links, it's `usa-button` also stated in the documentation. Is there something else you need?

**Comment by msecret** [comment]
@maya we need to go the other way: a class to turn a `<button>` into a normal looking link, ie `<a>`.

**Comment by Drakenhart** [comment]
I'm curious and a bit confused.

Why would you make a button not look like a button?

It's a classic piece to a form, and buttons look inherently actionable (which is what in part gave rise to the links that look like buttons trend). Links can get lost, especially if there is a bunch of them on a page (ie, use case: Add, Edit, Delete, Cancel buttons as links).

I suppose I'd need more convincing. ^.^

**Comment by el-mapache** [comment]
I'm definitely not suggesting that we style every button to not look like a button. Buttons are definitely a super standard part of a form and it would be weird to style call-to-action buttons (like 'Submit' or 'Add') in a non standard way.

This issue is only asking if we care that we are using anchor tags to control form behavior, when semantically we should be using a button tag. Simplified: \<a\> tags change the url, \<button\> tags denote an action.

I thinking that based on the questions this is probably semantically irrelevant.

**Comment by maya** [comment]
I think it's a little risky for the team to provide a button style override so it looks like an anchor link, mainly bc we shouldn't be promoting this as an approved pattern. Buttons with actions should look like buttons.

If individual teams need to override this for their use case, they should feel free to.

**Comment by el-mapache** [comment]
Understood! Going ahead an closing this issue then.

**Comment by msecret** [comment]
@maya I think this is a pattern that is actively on our docs site and it something that's been discussed in the front end world. Here's an example on our docs site:

![screen shot 2016-05-31 at 3 36 58 pm](https://cloud.githubusercontent.com/assets/1701077/15692812/7dd0a472-2745-11e6-864e-bdd66c439a81.png)

It sounds like there's a use case for this: textual buttons that aren't links. Why isn't it an approved pattern?

**Comment by maya** [comment]
@msecret I didn't realize we were using this pattern. Is it only achievable with a `<button>` tag? I'd loop in @bradnunnally and @nickbristow on this issue for further guidance.

**Comment by nickbristow** [comment]
Traditionally things that do button things should be buttons. Links are best reserved for navigating to new resources. I personally don't have an issue with styling buttons to look like links. 

Screen reader users expect links to navigate them, and buttons to do something to the current page, so when they do the opposite it can be confusing. 

It's less confusing for sighted users, so I don't mind the `<button class='link-style'>` pattern.

**Comment by maya** [comment]
Thanks @nickbristow for the background info. Sounds like we're a-go to add this in then. If/when we add this in, it would be great to update our buttons accessibility section with this info?

**Comment by Drakenhart** [comment]
Those are some strong points. I generally agree that buttons should do button things. With some interfaces there can be too many buttons that can be visually distracting. I'm still torn though. It's going against the grain of what has been done for years... But maybe that shake up is needed?

**Comment by juliaelman** [comment]
Refs https://github.com/18F/web-design-standards/issues/1342

**Comment by maya** [comment]
I realized that we already do have this via the unstyled button mixin (`@mixin button-unstyled`) and `usa-button-unstyled` class located here: https://github.com/18F/web-design-standards/blob/staging/src/stylesheets/elements/_buttons.scss#L173

@el-mapache would this meet your need?

**Comment by maya** [comment]
Closing as this seems to be addressed already via https://github.com/18F/web-design-standards/issues/1162#issuecomment-245035130.
