### ISSUE TITLE
Website: compiled and copied assets should not be checked into the repository

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#1163]
## Issue type
* Website
* Build process
* Coding/contributing workflow

## Description
When we originally created the build, we were constrained by having to work within 18f-pages, meaning we couldn't run any commands before jekyll served. Now we can leverage the CI build and cloud.gov deploy to change how this is done.

Before we had the `dist` directory checked into the repo. We also had copied files such as scss, fonts, images, and js copied into the `docs` directory.

Now the `dist` directory and these copied assets will not be checked into the repo. This means contributors will have to run teh build in order to see the site and see the files in the dist repository.

This change means we'll have much less merge conflicts from contributor PRs due to changes in JS map files. It also will lessen confusion on what files contributors are supposed to edit because there won't be two versions of the src scss files.

## Steps to reproduce the issue
- The checked in `dist` folder can be seen here: https://github.com/18F/web-design-standards/tree/18f-pages-staging/dist
- The copied over scss files can be seen here: https://github.com/18F/web-design-standards/tree/18f-pages-staging/docs/_scss

Referenced issues:
- #1148

**Comment by joshbruce** [comment]
Would something like this get us close?

```
# Ignore website:serve generated files.
# Note: The reserved files are not generated by gulp; therefore, should be kept.
/assets/
!assets/css/homepage.scss
!assets/css/prism.css
!assets/css/styleguide.scss
!assets/js/styleguide.js
```

I saw the note in the `.gitignore` and needed something similar for the project I'm on. This should still allow contributors to make changes to only the style guide, while only using `/src` files for the rest.

**Comment by msecret** [comment]
@joshbruce see #1164.

**Comment by joshbruce** [comment]
@msecret - Saw that. Thanks for letting me know as well.

Elegant solution - think I might follow you on the idea of moving the style guide specific assets into a separate directory to allow for ignoring `/assets` all around.

**Comment by juliaelman** [comment]
@msecret assigning to you in reference to the work you are doing here: https://github.com/18F/web-design-standards/pull/1164

**Comment by juliaelman** [comment]
Work completed here #1164.
