### ISSUE TITLE
UI components: Remove variables.scss file

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1168]
## Issue type
What kind of issue are you working on?

* Draft Standards code base

## Description

We don't need a `variables.scss` file and a `defaults.scss` file, so should probably remove the `variables.scss` file bc it's duplicative.

**Comment by joshbruce** [comment]
I actually appreciate having the `variables.scss` file.

I was confused as to why when I first started using the Standards. The conversation I found in GitHub was to allow an override point (`variables.scss`), while maintaining a reference (`defaults.scss`), without having to comment out things in `defaults.scss`.

I suppose I could still create my own `variables.scss` to ensure `defaults.scss` doesn't override my customizations. So, just throwing copper.

**Comment by maya** [comment]
@joshbruce yeah I think a better idea would be each person has their own `variables.scss` file in their custom stylesheets that they'd use to override `defaults.scss`. I guess the only thing `variables.scss` is good for now is to easily let you copy and paste them into your own stylesheet.

**Comment by joshbruce** [comment]
@maya - Agreed. It would clean things up a bit and be less confusion for users.

Maybe a comment in `defaults.scss` regarding overriding and setting up a `variables.scss`?

Not sure how often users are overriding versus extending.
