### ISSUE TITLE
[Website]: Update password requirements per latest NIST guidance

### ISSUE THREAD

**Issue by brendansudol** [18F/web-design-standards#1186]
## Description

The latest NIST guidance / best practices, as I understand it, is for long passwords, but with no special character requirements, but allowing spaces and most other characters.

Current guidance: https://github.com/usnistgov/800-63-3/blob/nist-pages/sp800-63b/appA_memorized.md

We may want to update the "password reset form" component to reflect this, namely by removing the uppercase and numerical requirements (https://standards.usa.gov/form-templates/?username=&password=sdfsdfsd#password-reset-form)

![image](https://cloud.githubusercontent.com/assets/1060893/15550698/b778a432-2280-11e6-8957-2f6110c59479.png)

I'd be happy to make these changes if the team agrees :)

**Comment by juliaelman** [comment]
@brendansudol thank you for submitting this issue! 🎉  We'd love your help on the issue once it has been reviewed and accepted. 

Also, check out our [component maturity scale](https://github.com/18F/web-design-standards/wiki/Component-Maturity-Scale) and [workflow](https://github.com/18F/web-design-standards/wiki/Workflow) wiki pages to learn more about our processes.

**Comment by msecret** [comment]
This question has come up before, and I'm of the opinion that we shouldn't be making recommendations on security as it's out of our goals for the WDS.

If we agree with that, I think the fix here is to add language that this UI is not a reflection of security recommendations but an example use case of the reset password component.

**Comment by jpyuda** [comment]
Ultimately, the web design standards will (and will _have_ to) make a number of recommendations in areas that are either immediately adjacent to security or in the realm of security themselves. And that's not outside the goals; security has a profound affect on users' experience with government websites, and we are uniquely positioned to provide recommendations about how to meet security requirements usably.

Regardless, in a case like this, a disclaimer that the text is only an example is very unlikely to carry much weight with implementors, who in many cases will likely lift this lock, stock, and barrel. I think it would be wise to have our recommendations agree with the latest NIST recommendations (which, ultimately, are moving in the direction of better usability).

As luck would have it, I think we're probably looking at identity and login recommendations coming to us from the login.gov team soon regardless. If not, we'll want to tackle login and signup as a coherent group sometime relatively soon anyway.

In the meantime, @brendansudol, if you submit a PR with the updated requirements, that would be fantastic.

**Comment by maya** [comment]
Does this mean we'd only need one requirement: "password must be X characters long"? 

I noticed NIST does not say how long it should be, so it makes it tough for us to enforce a rule that most people we'll copy straight out of the code. Their guidance is:
>The minimum password length that should be required depends to a large extent on the threat model being addressed.

**Comment by jpyuda** [comment]
> Does this mean we'd only need one requirement: "password must be X characters long"?

Good question. I think it's one that I defer to @brendansudol, @esgoodman, and the login.gov team on - they've been working much more closely with NIST and have a better understanding of the new guidance.

**Comment by hursey013** [comment]
@maya @jpyuda - It's sort of buried in the NIST documentation, but they do specific in [5.1.1.1](https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-authenticators) that the password should be at least eight characters long.  Some additional guidance NIST provides:

- SHALL be minimum of 8 characters. Regardless of single or two-factor
- SHOULD (with heavy leaning to SHALL) be:
 - Any allowable unicode character
 - 40 characters or more
 - No composition rules
 - Won’t expire
 - Dictionary rules

cc @brendansudol

**Comment by jpyuda** [comment]
So at that point we're looking at:
* at least 8 characters, but stronger is better
* avoid one or more dictionary words
* feel free to use spaces/create a passphrase

(I for one think it's appropriate to use some of that space suggesting what makes a password stronger, instead of just saying what the bare minimum is)

**Comment by toolness** [comment]
At the very least, should we provide a link to the NIST documentation? For example, the "guidance" section of our password reset forms currently says:

> * The requirements shown above are just provided as an example and should not be taken as recommendations.

A quick way of making this situation better might be to add the sentence "For more guidance, see NIST's [Appendix A—Strength of Memorized Secrets](https://github.com/usnistgov/800-63-3/blob/nist-pages/sp800-63b/appA_memorized.md)" to the end of that list item.

That said, I do like the idea of at least trying to make this sample form conform to the NIST guidance as much as possible, and I generally agree with what @jpyuda [mentioned](https://github.com/18F/web-design-standards/issues/1186#issuecomment-221978989) earlier in this thread.

**Comment by toolness** [comment]
@rtwell has thoughts on this so I'm adding this issue to the current sprint to make sure we don't forget about it!

**Comment by maya** [comment]
Adding a comment we got from email:

>Please consider being more opinionated and updating the Reset Password example to reflect updated NIST guidelines on strong passwords, specifically emphasizing effective length instead of entropy-reductions like uppercase or numerical characters.
>
>Thanks for the good work.

**Comment by maya** [comment]
Fixed in #403 and https://github.com/18f/web-design-standards-docs/issues/371.
