### ISSUE TITLE
[Website] Replace 18f-pages(-staging) branches with orphans only containing redirects

### ISSUE THREAD

**Issue by yozlet** [18F/web-design-standards#1188]
## Issue type
- Website
## Description

Now that we've moved the default branches to `staging` & `master`, the old defaults (`18f-pages-staging` & `18f-pages`) are still being watched by the [18F Pages server](https://pages.18f.gov/) and being published to https://pages.18f.gov/designstandards/ & https://pages-staging.18f.gov/designstandards/ . 
These front pages need to be replaced with redirects to [the new site](https://standards.usa.gov/)
## Additional information

We're going to delete the existing branches and replace them with [orphan branches](http://www.bitflop.dk/tutorials/how-to-create-a-new-and-empty-branch-in-git.html) that only contain a (mostly) empty Jekyll setup with a redirect page.

**Comment by rogeruiz** [comment]
💡 This came up while we created this issue.

When creating these `--orphan` branches, should they contain redirects to all internal pages ( for example `https://pages-staging.18f.gov/designstandards/getting-started/` ) or should it contain only one redirect for the homepage ( for example `https://pages-staging.18f.gov/designstandards` ). Please emoji vote this comment with a 

👍 for all internal pages
👎 for only the homepage

**Comment by juliaelman** [comment]
Closing this in favor of https://github.com/18F/web-design-standards-docs/issues/102
