### ISSUE TITLE
Defaults set $color-gray to #205493 and $base-font-size to 16px

### ISSUE THREAD

**Issue by humancompanion** [18F/web-design-standards#1191]
## Issue type

* Website

## Description

The core/defaults.scss sets the $color-gray variable to #205493 which is the $color-primary-darker color (as well as $color-cool-blue) and looks to be, to my eyes, dark blue. In core/variables.scss it is set to #5b616b which is the value it had in previous releases. I'd expect defaults.scss to set $color-gray to #5b616b. 

Also, the $base-font-size in defaults is defined as rem(16px) whereas in variables.scss it is defined as rem(17px). $lead-font-size is also different (22px in defaults and 20px in variables). This causes me to question which size you prefer as the default my project should pick up. While I'm unlikely to alter from 17px for USAJOBS at this point I am curious if you decided on 16px as the new default or if it is an oversight. In short, if I were picking a base font size today I'd be confused as to your intent.

**Comment by maya** [comment]
@humancompanion `_defaults.scss` is matching `_variables.scss`. See: https://github.com/18F/web-design-standards/blob/staging/src/stylesheets/core/_defaults.scss and https://github.com/18F/web-design-standards/blob/staging/src/stylesheets/core/_variables.scss

Perhaps this error was on an older version of the Draft Standards.

**Comment by humancompanion** [comment]
@maya - Sorry about that. package.json error on my part. We're back on 0.9.1. You fixed both issues on 4/15. Apologies.
