### ISSUE TITLE
src Sass not triggering regeneration on save

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1208]
## Issue type

* Website

## Description

The `src/stylesheets/` directory is not triggering a Jekyll regeneration because it lives outside of the Jekyll `source: docs` directory. 

## Steps to reproduce the issue

1. Run `npm start` (wait for build to complete)
2. Edit a file in `src/stylesheets/` and save
3. Refresh page you were editing and check to see if changes are made

Potential fix is to save any of the two Sass files that import `all` like `docs/doc_assets/styleguide.scss` or `docs/doc_assets/homepage.scss`

**Comment by rogeruiz** [comment]
Looks like the regression was [introduced in this commit](https://github.com/18F/web-design-standards/commit/aa3b3cb9c94aaa582701a496728f026f5a2bd377#diff-150b96ca2a378526f6a28dfc8c3e7687L36).

We can refactor the copying over of Sass files into the `docs/` directory to mitigate the fact that Jekyll doesn't watch changes outside of it's `source` directory defined in the `_config.yml`. When the Sass files are copied over they should be ignored by `git` so they aren't checked in in a duplicated directory.

**Comment by maya** [comment]
@juliaelman and I paired and figured this out. Reassigning.

**Comment by maya** [comment]
Closed via #1263.
