### ISSUE TITLE
[Website] Update design for standards.usa.gov

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1227]
## Description

This is the main issue for work around the updated WDS website designs based off of user research and feedback. It is the first iteration of the WDS website post launch.

Below are PNG's for each page (with/out annotations) to help build from, as well as separate issues that reference this main issue.

- [Update navigation structure with new designs](https://github.com/18F/web-design-standards/issues/1228)
- [Add "Design principles" page](https://github.com/18F/web-design-standards/issues/1229)
- [Add "about our work" page and sub-sections](https://github.com/18F/web-design-standards/issues/1231)
- [Mobile side nav to open on right](https://github.com/18F/web-design-standards/issues/1232)
- [Update homepage to UI components layout](https://github.com/18F/web-design-standards/issues/1233)

### Homepage (Annotated)
![1a ui components annotated](https://cloud.githubusercontent.com/assets/955558/15790004/08085078-299d-11e6-87f4-071d30313497.png)

### Typography
![1b ui components - typography](https://cloud.githubusercontent.com/assets/955558/15790009/0d208a30-299d-11e6-99e7-913277894a16.png)

### Getting started
![2a getting started](https://cloud.githubusercontent.com/assets/955558/15790020/15e234f2-299d-11e6-856d-9363173b035f.png)

### Getting started - Developers
![2b getting started - for developers](https://cloud.githubusercontent.com/assets/955558/15790029/1f3f7104-299d-11e6-85f1-1b7c881c2e3e.png)

### Design principles
![3 design principles](https://cloud.githubusercontent.com/assets/955558/15790033/25550a0e-299d-11e6-9fac-a676ecea01c3.png)

### About our work
![4a about our work](https://cloud.githubusercontent.com/assets/955558/15790039/2d9adb26-299d-11e6-8747-b70f72ae709e.png)

### About our work - product roadmap
![4b about our work - product roadmap](https://cloud.githubusercontent.com/assets/955558/15790049/377f3ca4-299d-11e6-86b5-b9790f95ee56.png)

### Mobile layout examples

![m menu](https://cloud.githubusercontent.com/assets/955558/15790056/43c2f94c-299d-11e6-8c00-42db82600028.png)

![m menu2](https://cloud.githubusercontent.com/assets/955558/15790055/43c1865c-299d-11e6-889f-08fbda647a7a.png)

![m1 ui components](https://cloud.githubusercontent.com/assets/955558/15790057/43c38b50-299d-11e6-948a-461b91aef82e.png)

**Comment by kategarklavs** [comment]
@juliaelman Howdy! Here's the mondo Drive doc with all of the site copy, which I've edited (and which @ericadeahl and @carodew have edited, too):

https://docs.google.com/document/d/13QnhIvUbNkqeRFZSQLDKmYZ9TdEUpIViNDdvcbYETVU/edit#heading=h.c86gqxb4zj91
