### ISSUE TITLE
[Website] Create "Design principles" page

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1229]
## Description

This is a sub-issue in reference to #1227 website design update. With the new structure, there is a new design principles page in the navigation structure. Below is the mock-up to build the page from.

![3 design principles](https://cloud.githubusercontent.com/assets/955558/15791248/2bfae066-29a4-11e6-8075-f0f2bec923cf.png)

**Comment by jsimon727** [comment]
Hey, I am going to work on this.

**Comment by bradnunnally** [comment]
@jsimon727 Awesome! Let me know how it goes and if you have any questions or comments.

**Comment by maya** [comment]
Closed via #1274.
