### ISSUE TITLE
[Website] Create "About our work" page

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1231]
## Description

This is a sub-issue in reference to #1227 website design update. With the new structure, there is a new "About our work" page with sub-sections. Below are the mock-ups to build the page from.

![4a about our work](https://cloud.githubusercontent.com/assets/955558/15791305/9236aa5e-29a4-11e6-8158-192dd8c2b9be.png)

![4b about our work - product roadmap](https://cloud.githubusercontent.com/assets/955558/15791309/97f483b2-29a4-11e6-875e-98ab3d398af1.png)

**Comment by stephmarx** [comment]
Hey there, I'm going to try tackling this issue!

**Comment by lisli** [comment]
I'm going to take a look at this one today at write/speak/code!

**Comment by bradnunnally** [comment]
@stephmarx & @lisli - Awesome! Let me know if you run into any issues or have any comments.

**Comment by stephmarx** [comment]
Nevermind, was asked to leave this for core team. 👍

**Comment by maya** [comment]
Closed via #1274.
