### ISSUE TITLE
[Website] Make mobile side nav open on the right

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1232]
## Description

This is a sub-issue in reference to #1227 website design update. Based off of the research done by the core team, it was determined that the side navigation should open to the right of the screen for smaller screen sizes. Below are the mock-ups to build the page from.

![m menu](https://cloud.githubusercontent.com/assets/955558/15791400/1bb9c7c0-29a5-11e6-8e86-3745eca13f0f.png)

![m menu2](https://cloud.githubusercontent.com/assets/955558/15791401/1bba231e-29a5-11e6-9f4a-5e0a0dd7b5da.png)

![m1 ui components](https://cloud.githubusercontent.com/assets/955558/15791399/1bb8e5b2-29a5-11e6-82cb-4c63950c8ef9.png)

**Comment by cella** [comment]
Hey, I'm at Write/Speak/Code w/ Fureigh and going to check into this one during our coding session :)

**Comment by bradnunnally** [comment]
@cella Awesome! Let me know how it goes and if you have any questions.

**Comment by maya** [comment]
Closed via #1274.
