### ISSUE TITLE
[Website] Update homepage to UI components layout

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1233]
## Description

This is a sub-issue in reference to #1227 website design update. 

The homepage is now being replaced with the UI components page, as outlined in the mockups below.

![1a ui components annotated](https://cloud.githubusercontent.com/assets/955558/15791473/88f10d12-29a5-11e6-95d2-813c03043841.png)

![1a ui components](https://cloud.githubusercontent.com/assets/955558/15791474/88f481e0-29a5-11e6-97c9-24d4f9cb59df.png)

**Comment by mollieru** [comment]
Happened to be looking for guidance on homepage layouts so was snooping around and this looks SO SO COOL!!! Awesome work y'all -- so excited to see this evolving!! 🇺🇸

**Comment by maya** [comment]
@ericadeahl slight issue with the footer in this design. I don't think we'll be able to have it span the full width of the page bc they both function independently of each other (you can scroll each of them). At the moment we'll only be able to keep it as it is in the main section. If the sidebar wasn't "sticky" we may be able to do this, but it would mean we'd lose the sidebar when scrolling through the main content.

**Comment by ericadeahl** [comment]
@maya Hmm yeah I wondered if that was going to be an issue. I wondered if there might be a workaround, where we could keep the sticky sidebar but still have the footer appear once you scroll down past the end of it — but I wasn't sure if that was feasible. 

If we change the footer so it doesn't span the full width, what would you recommend doing on the pages that don't have a side nav? They look pretty odd with a footer that doesn't go all the way across. Would we have two versions of the footer?

**Comment by maya** [comment]
@ericadeahl Yeah pages without the sidebar would have a full-width footer.

**Comment by maya** [comment]
@ericadeahl do you think they'd be designed differently or would they be the same?

**Comment by ericadeahl** [comment]
@maya I think they'd have to be a bit different. Something like:

12 column (Design principles, Future case studies page):

![screen shot 2016-06-15 at 4 18 32 pm](https://cloud.githubusercontent.com/assets/5911280/16100681/ddf81c10-3314-11e6-9962-47fc9ae13a06.png)

9 column (Components, Getting started, About our work): 

![screen shot 2016-06-15 at 4 17 35 pm](https://cloud.githubusercontent.com/assets/5911280/16100682/dffb294e-3314-11e6-8332-0c07fc7a975e.png)

**Comment by maya** [comment]
Closed via #1274.
