### ISSUE TITLE
[Website]: [Use Contact Form Instead of Typing In Email Address To Prevent Harvesting By Spam Bot]

### ISSUE THREAD

**Issue by djeraseit** [18F/web-design-standards#1235]
The problem with typing mailto: links and directly inputting email on websites is that they get harvested by spam bots looking for email addresses. This practice should be abandoned and contact forms used instead.

Benefits would be less spam and slowly but surely transitioning to a stand form, contact, and/or form platform for all future inputs.

**Comment by llolly** [comment]
unsubscribe

‏في السبت، ٤ يونيو، ٢٠١٦, Theodis Butler <notifications@github.com> كتب:

> The problem with typing mailto: links and directly inputting email on
> websites is that they get harvested by spam bots looking for email
> addresses. This practice should be abandoned and contact forms used instead.
>
> Benefits would be less spam and slowly but surely transitioning to a stand
> form, contact, and/or form platform for all future inputs.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/web-design-standards/issues/1235>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AKoR4QwTeip9ClwKdXMSSZr3UYGMaxBnks5qIPiPgaJpZM4IuC4t>
> .
>


-- 
❤️llolly

**Comment by donjo** [comment]
Closing this out for now as it's beyond the current scope of the standards. Will re-open if we ever look into providing more guidance around information collection.
