### ISSUE TITLE
[Website] Component Labeling - Lifecycle Stage

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1239]
## Issue type
What kind of issue are you working on?

* Website

## Description

Include a label for each component that tells users what stage of the component lifecycle it is in. 

## Additional information [optional]

The initial design work of this has been started by @ericadeahl and this issue is meant to capture the final design and to provide the necessary direction for development.

**Comment by ericadeahl** [comment]
These labels correspond to the three stages of the [component maturity scale](https://github.com/18F/web-design-standards/wiki/Component-Maturity-Scale) that will appear on the Standards site: alpha, beta, and recommended

I propose adding a simple label next to each component's title to indicate its maturity. (These are the small labels from the Standards with color coding added.)
<img width="247" alt="screen shot 2016-06-07 at 5 18 50 pm" src="https://cloud.githubusercontent.com/assets/5911280/15878906/f5972254-2cd3-11e6-96b5-50b71d784e82.png">

When there's a single component on the page, the label should go next to the H1 title:

<img width="1021" alt="screen shot 2016-06-07 at 5 16 35 pm" src="https://cloud.githubusercontent.com/assets/5911280/15878908/02aaf934-2cd4-11e6-8848-e4071b8d6fc7.png">

For components that are subsections, the label should go next to the H2 title:

<img width="1018" alt="screen shot 2016-06-07 at 5 19 57 pm" src="https://cloud.githubusercontent.com/assets/5911280/15878916/1a685ba2-2cd4-11e6-81f7-58f5114655be.png">

We'll also need to help folks understand what the labels mean. I think we could add a short explanation to the "Getting started" sections. We could also potentially have the labels link to the component maturity scale wiki — I wonder if that would be annoying/confusing. Thoughts, @bradnunnally?

**Comment by bradnunnally** [comment]
I think linking to the wiki is a great idea, we will just want to make sure it opens in a new tab and doesn't take them fully away from the site. 

However, if we include it in getting started section we could link to that. 

One final thought - What about a tool tip? That gives a brief description with a call to action to learn more either on the wiki or getting started? I'm not sure what history there as been discussing tooltips so if tooltips are bad then we can just ignore this thought. :D

**Comment by ericadeahl** [comment]
@bradnunnally What if we give the label a rollover state (just bumped the background color to the darker shade), and when you hover over it you see a tool tip indicating that clicking the label will take you to an explanation of the component maturity scale. Then we can just link folks to the wiki in a new tab.

I like this approach but just want to verify whether there are accessibility concerns.

<img width="1023" alt="screen shot 2016-06-08 at 2 18 47 pm" src="https://cloud.githubusercontent.com/assets/5911280/15911275/f82079c0-2d83-11e6-8001-a0601bf03553.png">


<img width="1023" alt="screen shot 2016-06-08 at 2 20 01 pm" src="https://cloud.githubusercontent.com/assets/5911280/15911305/233c0a34-2d84-11e6-8eba-305c61213b2e.png">

**Comment by joshbruce** [comment]
If we are linking, the label element itself doesn't denote that it is an interactive element compared to the other interactive element styles. If #1244 is accepted, it would add an underline to indicate and style the link based on the background color. 

Mobile also replaces hover states with a click vent; so, I'm not sure if this would cause a double-click requirement to actually hit the link versus the hover state on mobile.

Maybe instructive text on the first label of the page? 

"Alpha - click to see maturity scale"

From a UX perspective that should train our more active users quickly - while still giving new users a stepping stone.

We could also switch to a button styled link (not that the `label` and `button` styles are completely different beyond `all-caps` and padding)?

**Comment by maya** [comment]
There are accessible ways to create tooltips from a development side, but I think there may be usability issues around tooltips in general which we should verify before moving forward.

**Comment by bradnunnally** [comment]
Agreed about wanting to check in on accessibility concerns regarding the tool tip. As shown I think it solves the problem nicely. 

I think @joshbruce is on to something too regarding the clickablity of the label. For mobile, I wonder if we just present the content by default and only use the tooltip on desktop? 

Thoughts?

**Comment by bradnunnally** [comment]
@maya As long as the information behind the tooltip isn't required reading/necessary to complete a task there doesn't tend to be usability issues with them. Tooltips are good elements to use when showing supplemental information, which I think is what we are trying to do here with a short explanation.

**Comment by maya** [comment]
@bradnunnally I think what you're suggesting is doable. 

Another question - do we think people will understand the label is clickable/interactive (on desktop) without indication? The way we present labels on the standards, they're static and more for presentational purposes.

**Comment by bradnunnally** [comment]
@maya Since the tooltip, and the label really, are low priority elements on the screen. They are mostly "FYI" in nature, I'm not too concerned about the overall affordances of them. These aren't actions we want to ensure that every user can do every time they come to the site. 

The context of use is more around supporting a sub-set of users curiosity.

**Comment by maya** [comment]
Note: for building this out, maybe we can store this info in a single data file so it's easy to update.

`_data/maturity.yml`
```
accordions: alpha
buttons: beta
footers: beta
...
```

`<a href="#">{{ site.data.maturity.buttons }}</a>`

**Comment by ericadeahl** [comment]
@bradnunnally @maya @juliaelman Agreed with Brad's point that the tooltip information is not critical information; plus this information will be added into "Getting Started", so many folks will be familiar with the maturity scale if they've reviewed that section. Let's proceed to build this out and we can make any necessary adjustments after getting it in front of users.

**Comment by ericadeahl** [comment]
Some specs on the labels:

<img width="701" alt="screen shot 2016-06-17 at 10 56 49 am" src="https://cloud.githubusercontent.com/assets/5911280/16159921/3d4a15f4-347a-11e6-8fb9-2cb2b1ae7b03.png">

**Comment by maya** [comment]
@bradnunnally or @ericadeahl - can you specify the labels as above in https://github.com/18F/web-design-standards/issues/1239#issuecomment-225068056? Ideally in the order they appear on the site.

**Comment by ericadeahl** [comment]
@maya Yep I can provide that, but I have a few questions for @bradnunnally about the labels we've assigned to some components in the UX audit. I'd like a chance to review with him before handing that over.

**Comment by juliaelman** [comment]
From @ericadeahl:

>  I believe the components are all labeled correctly now (there were two different versions of this and we decided to go with the one where most things are in alpha)

@bradnunnally want to make sure to get your sign-off too. Should all of the UI components be marked off as alpha for this release or use what is based in the WDS UX Audit doc?

**Comment by bradnunnally** [comment]
Just fixed the last that had ??? in the cells.

**Comment by ericadeahl** [comment]
@bradnunnally @juliaelman @maya Cool, so let's go with what's in the spreadsheet as the definitive source of truth now. Looks like there's just one discrepancy with the site - "labels" should be beta instead of alpha.
