### ISSUE TITLE
[Architecture] Set up a branch for research and testing

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1249]
## Issue type
What kind of issue are you working on?
Set up a branch that can be a clone of staging to be used for any kind of research or testing that needs to occur on a version of the site/standards that isn't always in flux.

## Description

By having a branch of Staging, it would give the team an environment to perform research, both design and technical, on a semi-stable build.

## Additional information [optional]
This was discussed by myself, @jpyuda, and @juliaelman for context.

**Comment by juliaelman** [comment]
Branch has been create [here](https://github.com/18F/web-design-standards/tree/user-testing) and url is [here](https://wds-microsite-user-testing.apps.cloud.gov/).

Closing this, as #1254 is more for automation and the initial work is completed.
