### ISSUE TITLE
Clarify what step #4 of CONTRIBUTING.md

### ISSUE THREAD

**Issue by Yulia-O** [18F/web-design-standards#1267]
## Issue type

Documentation
## Description

Documentation could be more clear for new comers. This is like text looks right now:
"Ensure that your contribution works via npm, if applicable. See below under Install the package locally via nom-link." 

**My questions:** 
1. How to know if it is "applicable"? 
2. During step 4, should we building the project? Should we move immediately to the next section: "Building the project locally with gulp"?
3. And there is no link provided to  "Install the package locally via nom-link." Should that link to the following section?
## Steps to reproduce the issue

none.
Just opening Contributing.md
## Additional information [optional]

none

**Comment by bradnunnally** [comment]
@Yulia-O This is great feedback! If you have a free moment today I'd love to discuss this further with you.

**Comment by donjo** [comment]
Closing this out since `contributing.md` has since had a number of updates and this may no longer apply. Feel free to open up a new issue (or re-open this) if there are still any pieces of the documentation that could use extra clarification.
