### ISSUE TITLE
[Github Wiki]: Links in CONTRIBUTING.md are broken

### ISSUE THREAD

**Issue by terminaltraces** [18F/web-design-standards#1270]
## Issue type
Documentation.  Instructions for new contributors in the Github Wiki.

## Description
While going through the CONTRIBUTING.md page, I noticed that the links to the project's LICENSE and README were broken.  

## Steps to reproduce the issue

1. Access https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md
2. Click the links in the Welcome section to access the site's LICENSE and README.
3. You're redirected to Github's 404 page.

## Additional information [optional]
None

**Comment by terminaltraces** [comment]
I can submit a pull request for this!

**Comment by juliaelman** [comment]
@terminaltraces fantastic! We welcome your contribution 😄

**Comment by juliaelman** [comment]
Fixed in #1271
