### ISSUE TITLE
[documentation] Add missing period to CONTRIBUTING.md

### ISSUE THREAD

**Issue by fureigh** [18F/web-design-standards#1272]
## Issue type
* Documentation: CONTRIBUTING.md

## Description

The file [CONTRIBUTING.md](https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md) includes the sentence "The command is aliased by `npm start`". That sentence is missing a period.

## Steps to reproduce the issue

1. Open [CONTRIBUTING.md](https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md).
2. Look at the last line before the "Licenses and attribution" section. Notice that it's missing a period.

## Additional information

* This is a great task for someone who's new to creating pull requests! :)

**Comment by kamxhmartin** [comment]
On it!

**Comment by juliaelman** [comment]
Fixed via #1273  - thanks @kamxhmartin!
