### ISSUE TITLE
Make scss-lint warnings come at the end of console

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1288]
## Issue type
- Maintenence
## Description

Can we make the scss-lint warnings come at the end of console. Currently the copying of files to docs shows up and it would be nice if I could immediately see if I was adding in new errors.

**This is what it looks like:**

<img width="656" alt="screen shot 2016-06-21 at 10 17 48 am" src="https://cloud.githubusercontent.com/assets/5249443/16239455/c4299c4e-3799-11e6-815d-a0f1d5d45d14.png">

cc: @rogeruiz

**Comment by rogeruiz** [comment]
💭 we could add a linting checker that can run in another terminal separate from the build / watch process. Like a watch task for linting only. Right now, the linter only runs as a dependency of the build / serve tasks. __Ideally the linter wouldn't have any errors, and would break the build if it encountered them.__

**Comment by maya** [comment]
@rogeruiz ah gotcha. thanks for clarifying! For some reason I thought I remembered seeing them at the end. Agree that ideally we wouldn't have errors.

**Comment by maya** [comment]
Seems like this may have gotten fixed bc I'm seeing the errors close to the end.
