### ISSUE TITLE
Downloadable Zip File button doesn't follow standards

### ISSUE THREAD

**Issue by StraightfaceStudios** [18F/web-design-standards#1291]
The "Downloadable Zip File" button on the [Getting Started page](https://standards.usa.gov/getting-started/) has underlined text which does not follow the web-design-standards for button text. 

![2016-06-22 12_39_40-draft u s web design standards _ getting started - microsoft edge](https://cloud.githubusercontent.com/assets/2539036/16280877/941c681e-3876-11e6-90a8-f709c2a19222.png)

Ironically it breaks nearly all of the standards.  It doesn't use [Sentence case], it doesn't start with a verb, it drops in halfway through a sentence and it is a redundant link to the code at the top of the page.  At least it should just be a link.

**Comment by maya** [comment]
@StraightfaceStudios thanks for filing this issue! It's already been addressed in: #1260. Stay tuned for the next release to see it!
