### ISSUE TITLE
Checkbox and Radio Button Label Mis-Aligned on IE-11

### ISSUE THREAD

**Issue by egrivel** [18F/web-design-standards#1299]
## Issue type
 - UI component

## Description

When reviewing the Checkbox component on the IE-11 browser, the labels are visually not quite aligned correctly. The labels are positioned a few pixels higher than they should be.

## Steps to reproduce the issue

1. Use an IE-11 browser (on Windows 7)
2. Navigate to https://standards.usa.gov/form-controls/
3. Scroll down to the Checkbox and Radio button section respectively
4. Observe the alignmnet

## Additional information

* IE-11 and Windows-7 is the federal government issued equipment at the agency where I work, and as such federal government websites should work with them.
* I'm using my private account to file this issue since I do not have a government-issued Github account.
* Screen shot images attached

![image](https://cloud.githubusercontent.com/assets/16628402/16539884/25455144-401e-11e6-8020-b93e03f28041.png)

![image](https://cloud.githubusercontent.com/assets/16628402/16539885/2dff1306-401e-11e6-8b1b-d42fe8c8efd1.png)

**Comment by maya** [comment]
@egrivel thanks so much for opening this issue. We'll take a look at it and get back to you soon!

**Comment by egrivel** [comment]
Confirming the fix, thanks!
