### ISSUE TITLE
ReadMe: link for assets v0.9.5zip is broken

### ISSUE THREAD

**Issue by patrickm02L** [18F/web-design-standards#1303]
I would like to download the latest version of the assets but the link in the ReadMe is broken. 

Here's the original text: 

* Developers: Follow the instructions in this README to get started.
    * [CSS, JavaScript, image, and font files of all the assets on this site are available for download](https://github.com/18F/web-design-standards/releases/download/v0.9.5/uswds-0.9.5.zip).

**Comment by juliaelman** [comment]
@patrickm02L thanks for opening this issue! We are currently preparing for release `v0.9.5` and are updating our docs accordingly. Seems that we need to re-think this workflow to help avoid future confusion. 

I'll be closing this issue and we will address it in #1304 - thanks again for bringing this to our attention!
