### ISSUE TITLE
Website: 404 on download link for v0.9.5

### ISSUE THREAD

**Issue by saracope** [18F/web-design-standards#1306]
The links in readme.md to download v0.9.5 are 404'ing. 

https://github.com/18F/web-design-standards/releases/download/v0.9.5/uswds-0.9.5.zip

**Comment by rogeruiz** [comment]
Thanks @saracope! The current download is in a [**draft** within our Releases tab](https://github.com/18F/web-design-standards/releases). I don't believe that non-maintainers can see it though. We're going to be deploying a new release very shortly, and we rely on the structure of the URL to be there when we publish the release.

**Comment by rogeruiz** [comment]
Thanks again @saracope! After we've shipping [`v0.9.5`](https://github.com/18F/web-design-standards/releases/tag/v0.9.5) the link now works. We have some [documentation related to our release process in our wiki](https://github.com/18F/web-design-standards/wiki/Release-Process). We're going to be iterating on that release process in the future to hopefully mitigate any issues that might come up similar to this one in the future. 👍

**Comment by saracope** [comment]
Thank you @rogeruiz!!
