### ISSUE TITLE
Website: update product roadmap copy on site

### ISSUE THREAD

**Issue by ericadeahl** [18F/web-design-standards#1309]
I just updated the copy in the Product Roadmap wiki to reflect milestones (priorities) rather than themes: https://github.com/18F/web-design-standards/wiki/Product-roadmap

We need to make the same update to the copy on the WDS site. Mock up below shows type styles.

![4b about our work - product roadmap](https://cloud.githubusercontent.com/assets/5911280/16697655/92f0fbf4-44ff-11e6-9148-626c3b290700.png)

**Comment by maya** [comment]
What do you think about adding a status to the milestones?

<img width="850" alt="screen shot 2016-07-11 at 6 12 07 pm" src="https://cloud.githubusercontent.com/assets/5249443/16752097/7f264e44-4793-11e6-91bd-0e26aafa4478.png">

**Comment by bradnunnally** [comment]
I think this makes a lot of sense, especially to show folks outside of
github that things are actively being worked on

On Mon, Jul 11, 2016 at 8:16 PM, Maya Benari <notifications@github.com>
wrote:

> What do you think about adding a status to the milestones?
>
> [image: screen shot 2016-07-11 at 6 12 07 pm]
> <https://cloud.githubusercontent.com/assets/5249443/16752097/7f264e44-4793-11e6-91bd-0e26aafa4478.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/web-design-standards/issues/1309#issuecomment-231911641>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AL73GLFPUkGMOnvnDaoKXs26Lij5m8CAks5qUur7gaJpZM4JISPR>
> .
>



-- 
Brad Nunnally

*Innovation Specialist*

*18F  <https://18f.gsa.gov/>*

*|*

*GSA <http://www.gsa.gov/portal/category/100000>*

*618-407-6490 | brad.nunnally@gsa.gov <brad.nunnally@gsa.gov>*

**Comment by maya** [comment]
And each status label could link to the milestone: https://github.com/18F/web-design-standards/milestone/13, with a descriptive tooltip like "See our progress on this milestone."

**Comment by ericadeahl** [comment]
@maya Sounds like a great idea, as long as we're willing to keep it updated.

Small detail: could we say "in progress" instead of "doing"

**Comment by maya** [comment]
@bradnunnally @ericadeahl if one of you could send me a list of the status of each item in Milestone 1, we can add them in.

**Comment by bradnunnally** [comment]
@maya and @ericadeahl  - This is based on the workshops results from last week. If anything has changed, lets flag it and make sure we all agree. 

- A public, up-to-date product road map. **50%**
- A public maintenance plan. **75%**
- A bare-bones HTML starter page, with CSS and JS pre-linked and necessary tags and classes. **25%**
- Defined processes for active and public implementer support. **50%**
- Contribution guidelines for both designers and developers. **75%**
- Form patterns that include recommendations for just-in-time instructions. **0%**
- UI components are comprised of clean, semantic code. **50%**
- Simple "Getting Started" process and instructions. **50%**
- A core set of common, usable web components. **50%**
- Ready to go HTML templates (and related design stencils) for common types of government site pages. **0%**

**Comment by maya** [comment]
@bradnunnally won't "A public, up-to-date product road map. 50%" be 100% when this launches?

For everything not 0%, shall I add `in progress`?

**Comment by bradnunnally** [comment]
@maya There ya go using logic! ;D

Yes you are correct, and making everything else in progress works! Thanks!

**Comment by ericadeahl** [comment]
That all sounds good!
