### ISSUE TITLE
Website: Add component maturity scale to website

### ISSUE THREAD

**Issue by ericadeahl** [18F/web-design-standards#1311]
Add a new page "Component maturity scale" to the "About our work" section of the site.

Content can be pulled directly from: https://github.com/18F/web-design-standards/wiki/Component-Maturity-Scale

The component maturity labels on UI components currently link to the wiki and will need to be updated to link to the page on the site.

![4b about our work - component maturity scale](https://cloud.githubusercontent.com/assets/5911280/16698166/cdef0b2c-4501-11e6-9927-bee927e82a32.png)

**Comment by maya** [comment]
@ericadeahl should this have any lead text?

**Comment by maya** [comment]
Done in #1314.
