### ISSUE TITLE
New UI component: Headers and navigation

### ISSUE THREAD

**Issue by ericadeahl** [18F/web-design-standards#1312]
New header designs for desktop and mobile! @maya 

## Workflow
- [x] Research
- [x] Design
    - [x] Visual design
    - [x] Content
- [x] Build
    - [x] Design
    - [ ] Front end

## **Desktop**

**Basic header**
1. Selected state
2. Hover state

![desktop copy 4](https://cloud.githubusercontent.com/assets/5911280/16859194/b0ffe8b2-49e1-11e6-94fe-e5fb9a3cc9aa.png)

**Basic header with dropdown**
3. Dropdown opens and closes on click.
4. Hover state

![desktop copy 8](https://cloud.githubusercontent.com/assets/5911280/16859224/fb324a92-49e1-11e6-8717-8382cf52a522.png)

**Extended header**
5. Selected state
6. Hover state
7. Hover state (secondary link)

![desktop copy 5](https://cloud.githubusercontent.com/assets/5911280/16859124/18b06ca8-49e1-11e6-8e03-216eee7f0bb1.png)

**Extended header with mega menu**
8. Menu opens and closes on click.
9. Hover state
10. Search bar expands on click and closes when you click outside the search bar.

![desktop copy 6](https://cloud.githubusercontent.com/assets/5911280/16859134/33381706-49e1-11e6-95ea-af6248f3e84e.png)

## **Mobile**

**Header**
![m1 ui components copy](https://cloud.githubusercontent.com/assets/5911280/16859248/3f7958ee-49e2-11e6-8f50-3e626dcab568.png)

**Menu (collapsed sections)**
![m menu](https://cloud.githubusercontent.com/assets/5911280/16698378/ce671c88-4502-11e6-97b9-1850256204a3.png)

**Menu (expanded sections)**
![m menu2](https://cloud.githubusercontent.com/assets/5911280/16698385/d968ec60-4502-11e6-994f-995eb71e9b2c.png)

**Comment by mebates** [comment]
Hey @ericadeahl this is great to see - I have been working on a top navigation on my project for a while and the team is about to implement it next week. What's the timeline on this component?

**Comment by mebates** [comment]
Will you create designs for a page with a header navigation AND a left navigation?

**Comment by ericadeahl** [comment]
Hi @mebates ! We don't have an exact timeline on this yet. Probably a few weeks - you can keep an eye on progress here.

We are releasing something this week that might be helpful to you though. We've done a slight redesign of the WDS site itself, which features a header navigation used along with a side navigation. Although the top nav isn't integrated into the components package yet, it will be the basis for these future components and might be a helpful example to borrow from.

**Comment by ericadeahl** [comment]
@maya @bradnunnally Here's a mockup of how the headers could look on the site. The headers would be pngs, then you would click to preview a full-width version on an otherwise blank page. 

I think we could improve the clarity of how this is visually presented (the "Basic" and "Extended" titles aren't super visible, plus it's a bit odd to have a white element on a white background.) But those styles are used across the site and I didn't want to break with them — perhaps that's something we can tackle across the board at a later point.

One question: it's a bit odd that we're showing the actual footer component on the site (which is full width, so it has the same challenges as the header), but we're doing a different thing here. I like this new approach because people will be able to see the element full-width, without a lot of clutter around it. Perhaps we could go back and change how we show the footers since we're planning to use this new approach with the page templates and any other full-width components.

Also tagging @kategarklavs : a heads up that we'll need an introduction and some documentation for this!

![headers_site](https://cloud.githubusercontent.com/assets/5911280/16859649/71115836-49e5-11e6-9164-9c5a398c89b8.png)

**Comment by kategarklavs** [comment]
@ericadeahl Hey! Thanks for the heads up — what's the timeline for the intro text/documentation?

**Comment by maya** [comment]
@kategarklavs Hi! since Erica's out, I might jump in.... No strong rush on this, but would by next Friday be doable?

**Comment by kategarklavs** [comment]
@maya Hey! Thank you for picking up this conversational thread 😎 Yep, next Friday seems doable. I'll work up a draft & send it along to the team for review.

**Comment by kategarklavs** [comment]
Hey all! @jameshupp has offered to take this task on -- I'm going to reassign the issue to him 🎉

**Comment by kategarklavs** [comment]
(Err, the content portion of this issue, that is.)

**Comment by jameshupp** [comment]
Going to work on content here. https://docs.google.com/document/d/1zMNdp5UqJlMUWmDOboirop2kBMg5U50cOfSOajA_Vt8/edit#heading=h.9jgomg873wfw

**Comment by kategarklavs** [comment]
@ericadeahl Thanks again for all your help with the header content — I made the final batch of updates this morning, and I think the copy is good to go. (There's still a note for @maya to check one section, but that shouldn't prohibit us from publishing it.) 

I just checked off Content in the to-do list — let me know if you need me to do anything else 👍
