### ISSUE TITLE
Deadlink on https://standards.usa.gov/form-controls/#text-inputs

### ISSUE THREAD

**Issue by debracleaver** [18F/web-design-standards#1313]
steps to reproduce
1. navigate to https://standards.usa.gov/form-controls/#text-inputs
2. click on the links that says  "accessibility guidelines for all form controls"

expected results:
this is an actual link that takes you to an actual page

actual results:
negative.  it's just a fun thing to click on, doesn't actually link anywhere.

**Comment by ericadeahl** [comment]
@debracleaver Thanks for the tip! Agreed that we probably don't want links that are just fun things to click on. After reviewing the content, it looks like there was never an external link, and the text is in fact referring to itself.

@maya @kategarklavs let's remove the link and change that sentence to:
"As you customize these templates, make sure they meet the accessibility guidelines in this introduction and as described for each control."
