### ISSUE TITLE
Main Top Nav

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1320]
## Issue type

Main Top Nav (Bourbon Refill Pattern) (with search)
http://refills.bourbon.io
## Description

Since USWDS doesn't have Top Nav for now, i'm trying to use Bourbon Refill Nav pattern (with Search). It is conflicting with USWDS in terms of styling. 

Do you guys have any recommendation on how to avoid further customization? 

Thanks!

**Comment by mebates** [comment]
For context, our nav on this SBA project looks like this:
![certify_template_analyst review nav](https://cloud.githubusercontent.com/assets/6223901/16812777/994cc9dc-48fc-11e6-846d-f49019e868e6.png)

Let us know if you need more details!

**Comment by mebates** [comment]
This looks like it might relate to issue #1312

**Comment by juliaelman** [comment]
Closing this issue, since we now have a main top nav component as part of the headers work: https://standards.usa.gov/headers/

🎉
