### ISSUE TITLE
[variables]: Add documentation about how to add custom variables

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1334]
## Description

Include documentation around adding custom variables to your project using the WDS.

Essentially, we need to say that you add your custom `variables.scss` import before the WDS `all` import in your `main.scss` file.

We can now do this bc of: #1330.

cc: @msecret @kategarklavs

**Comment by kategarklavs** [comment]
Sounds good to me! Thanks for pinging me, @maya
