### ISSUE TITLE
[Website] Longer-term comms plan 

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1341]
## Description

Right now, the WDS doesn't have a comprehensive comms plan. To ensure consistency of messaging (and to make sure we're reaching all the audiences we'd like to reach), we'd like to develop a longer-term comms plan.

More specifically, here's what we'll be tackling this sprint:

* Internal user research: Interview core WDS team to get their input on audiences to target, what messages we need to communicate, and the best channels for that communication.
* Plan construction: For each audience, draft a plan for the next six months; share out with team.
* Start implementing! 

## Steps to reproduce the issue

N/A — no comms plan exists yet, so this doesn't really apply. 

## Additional information 

#1343 (separation of repos) will require comms work

**Comment by kategarklavs** [comment]
Note: @jameshupp and I began our internal interview process yesterday — we're hoping to have responses from the team by COB 7/20/16.

**Comment by kategarklavs** [comment]
Tentative to-do list:

- [ ] Conduct internal interviews to identify core team members' needs/ideas around a comms plan
- [ ] Synthesize research/identify audience priority order
- [ ] Develop external comms strategy (6 mos.)
- [ ] Develop strategy for soliciting contributions (from 18F team members + outside contributors)
- [ ] Metrics for tracking strategies' success

**Comment by kategarklavs** [comment]
An update on this issue: @jameshupp and I have mapped out comms to-dos for this sprint, the next month, the next three months, and the next six months. (Naturally, these might shift around a bit, but we do have a tentative plan.) 

We shared our initial comms plan draft with the team and are in the process of incorporating folks' feedback/refining. 

cc @juliaelman and @bradnunnally

**Comment by Journerdism** [comment]
@kategarklavs Hey Kate, this hasn't been updated in a while so I just wanted to check in, is this completed for the current launch of 1.0 in the next 2-3 sprints? (I'm trying to clean up the "sprint 1" items that are still hanging.) If we need to keep it open, is there an artifact or document for the comms plan you that can be posted here for future referal?

**Comment by kategarklavs** [comment]
@Journerdism Howdy! So, the comms plan itself is done, but some of the sub-tasks I've listed above (checklist) aren't. If it's OK with you, I'll close this issue and open new issues for the remaining subtasks (develop strategy for soliciting contributions, metrics tracking, etc.). How does this sound?

**Comment by kategarklavs** [comment]
Created new issues for the outstanding sub-tasks — closing this issue now.
