### ISSUE TITLE
Create interview schedule to meet with users at least twice a week

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1344]
## Description

Create a schedule which uses the team's participant pool of folks using the draft web design standards which can be contacted about future user interviews and usability studies. 

## Additional information [optional]

If you'd like to be included in the participant pool please contact - uswebdesignstandards@gsa.gov

**Comment by bradnunnally** [comment]
#1345

**Comment by bradnunnally** [comment]
@donjo and I created this email template to help recruit folks for upcoming user research. 

https://docs.google.com/document/d/1G0hVVsuvSPlDzF4_CqtICiVOhWliRFtqZVsSkM0bMcc/edit

@kategarklavs & @jameshupp - Could you take a pass at this please?

**Comment by kategarklavs** [comment]
@bradnunnally Yep, on it! Will take a look & make any comments in Suggesting mode.

**Comment by kategarklavs** [comment]
Made a few tiny changes -- this looks good to me!

**Comment by joshbruce** [comment]
@bradnunnally and @kategarklavs - Are we accepting sign ups already; or, will that be a different pass?

Want to make sure my program gets in the running.

**Comment by bradnunnally** [comment]
@joshbruce It's not too late! We haven't kicked off this effort just yet. Can you email me some info about your project and agency? brad.nunnally@gsa.gov

Thanks!

**Comment by Journerdism** [comment]
Closing!
