### ISSUE TITLE
[Documentation]: Simple instructions for getting started (+ research)

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1347]
## Description

During each sprint, we'll make changes that need to be reflected in our documentation. This issue will act as a reminder to review our instructions at the end of each sprint to make sure they're still up to date.

Also relevant: Adding relevant questions to our user interviews. (For example, Where would you go to find out how to start using the Standards? How would you rate the comprehensiveness of our instructions? The clarity? What changes would you make to our instructions? And so on.) 

## Additional information

Related to #1344 (or rather, related to the need to update our interview guide to include documentation-specific questions).

**Comment by kategarklavs** [comment]
Interview questions are now in the latest version of the interview guide -- this portion of the task is complete!

**Comment by kategarklavs** [comment]
@jameshupp and I are discussing how to create better documentation re: release-related content tasks. Will keep this card open until we've come up with said documentation.

**Comment by Journerdism** [comment]
GOOD ENOUGH TO SHIP FOR 1.0!
