### ISSUE TITLE
[Website] Context-of-use copy

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1348]
## Description

Per a conversation with @bradnunnally: This issue addresses researching other pattern libraries & the sort of descriptive copy they include + updating our site's copy to be as concise and informative as possible. (Brad, please add on to this description as you see fit! And @jameshupp — if you'd like to help out with this, let me know! Am still researching but am hoping to start drafting copy later this week.)

**Comment by kategarklavs** [comment]
Link to some notes on Yahoo's pattern library: https://docs.google.com/document/d/1_PEbVegQ-5b7S2Ff2Sqdc-Z46V0AFzZoeyZ_22Dn8Hk/edit

**Comment by kategarklavs** [comment]
Just wrapped up some notes — @bradnunnally and @jameshupp, want to check out the recommendations for copy updates? If you're on board with the recommendations, I can start making edits!

**Comment by kategarklavs** [comment]
Updated the document to reflect what will accompany each  component. Right now, here's the list:

* A description of what it is
* A description of what it does
* Examples of when to use it
* Examples of when not to use it
* A “further reading” or “additional resources” section containing links to useful articles/posts/etc.

As far as next steps go, @jameshupp and I need to figure out who will claim which components, and then we can start reviewing the existing content and writing new stuff, when necessary.

**Comment by kategarklavs** [comment]
Just a heads up to @bradnunnally — @jameshupp and I will be asking for the team's help in assembling resources (blog posts/articles/etc.) for the "Additional resources" sections to accompany each component. (Our assumption is that folks may already know of great resources, and we'd love to make the best use of people's extant knowledge.)

**Comment by jameshupp** [comment]
@kategarklavs and I have divided up the list of existing components (or those that are just about to), including sub-components (for example, specific issues related to color). We're going to provide the copy Kate describes in the list above, but we need help from the rest of the team. For each component we need an SME to perform two roles:

- provide the "further reading" or "additional resources" content
- draft any copy that's totally absent from existing copy (this can be super rough)

List of who's doing which components is here:
https://docs.google.com/spreadsheets/d/1eFts437UQeTRCz-CsrdH6uifewwTxQwZSLiJqnFxRpg/edit#gid=0

**Comment by kategarklavs** [comment]
Update on this: @jameshupp and I will have copy to share with @bradnunnally and @ericadeahl tomorrow!

**Comment by kategarklavs** [comment]
Just shared the draft document with the team & requested feedback by Friday.

**Comment by maya** [comment]
I don't know if this was implemented, but here is the link to the doc: https://docs.google.com/a/gsa.gov/document/d/1oTesssKfURI9jsOX5iBJe1LHz5inw3qxFZ-B3WZ-2Mg/edit?usp=sharing I think there was some testing that showed users were happy with the current level of documentation.

**Comment by maya** [comment]
Closing out for now, can reopen if our content needs change.
