### ISSUE TITLE
Buttons - improper code

### ISSUE THREAD

**Issue by allanj-uaag** [18F/web-design-standards#1349]
## Buttons page https://standards.usa.gov/buttons/

> For example, a secondary button style would use the following code: `<a class="usa-button usa-button-secondary" href="/my-link">My button</a>`

UI component: The above is code for a LINK not a button. 

> When styling links to look like buttons, remember that screen readers handle links slightly differently than they do buttons. Pressing the Space key triggers a button, but pressing the Enter key triggers a link.

the above recommended code will not function with a Space. 

Please change recommended code.

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and are currently triaging the work.

**Comment by maya** [comment]
After looking through this, the documentation does not say that this will produce a button functionality, but a button style which refers to the visual aspects of this. The second paragraph referenced makes the distinction between the function of links and buttons, so I don't see any issue with this.
