### ISSUE TITLE
Forms - "required" placement

### ISSUE THREAD

**Issue by allanj-uaag** [18F/web-design-standards#1350]
## Form Templates https://standards.usa.gov/form-templates/

Specifically "Name Form"

UI Component: the placement of the "required" at the right edge of text boxes and text areas will cause low vision users to scroll to the right on every text input to see if it is required. Suggest moving the "required" next to or below the label

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and are currently triaging the work.

**Comment by nickbristow** [comment]
thanks @allanj-uaag! 

This is a good point and we will put it on the to do list.

**Comment by jpyuda** [comment]
Recommendation: put the required status of a field in parentheses just after the field name. This is helpful not just for low-vision users but also those with cognitive disabilities.

Like this:
```Name (required):```

```Middle name (optional):```

**Comment by maya** [comment]
Fixed in #1504 on Sep 27, 2016. 

Also, found there's an inconsistency between required and optional styles. It's using: "Label - _optional_" and "Label (*Required)". If anyone has thoughts on feel free to respond in #2183.
