### ISSUE TITLE
[ Website ] [ UI component]: Re-evaluate best practices for HTML / Accessibility

### ISSUE THREAD

**Issue by rogeruiz** [18F/web-design-standards#1352]
## Description

Let's re-evaluate some of the `html` and accessibility decisions for both the UI components and the website. This is a maintenance task.

## Acceptance Criteria

- [ ] Verify `html` markup passes linting ( http://www.html-tidy.org )
- [ ] Verify `html` markup is 508-compliant

**Comment by Journerdism** [comment]
Talked to Yuda for his feedback on getting this into 1.0: We're going to make this part of our workflow going forward on components we modify/update and for new components. In the future we can do a full audit, but until then we'll close this.
