### ISSUE TITLE
[ Website ]: Refactor JavaScript dependency

### ISSUE THREAD

**Issue by rogeruiz** [18F/web-design-standards#1353]
## Description

Most of the of the JavaScript for the website should be coming either from functionality within the standards itself, or from the build system deploying the site. Little to no JavaScript code should exist on the website unless it fits into specific scopes of functionality. The reasoning behind this is that there should be less code that exists as a custom one-off for the website and instead this code should be available within the standards UI component themselves. Examples of this code is below:

```shell
├──  sticky-nav.js # used to stick the navigation on scroll. (experimental)
├──  scroll-to-top-for-hash.js # used to scroll when internal hash links are clicked.
├──  handle-disabled-links.js # used to disable any links with `href="#"`.
├──  generate-code-snippets.js # used to generate code accordions on the client-side.
└──  calculate-anchor-position.js # used by `scroll-to-top-for-hash` to anchor the scroll position properly.
```

## Explanation of scope for JavaScript on the website

- If the JS is used to gather user-data about the website, such as analytics, then it should remain on the site. 
- If the JS is used to test upcoming components, such as a sticky navigation currently on the website and not in the standards UI components, then it should remain on the site with a message in the `console` and in the code that mention it is in an experimental state.
    - If the JS is used to provide progressive enhancement to users of the documentation site, such as scrolling anchored text below a fixed navigation element, it should remain on the site with a similar message to the above ☝️ 

## Acceptance Criteria

- [x] Code snippets should be generated during the build step
- [x] Anchor tags `<a>` should be explicitly set to `href="javascript:void(0);"` to avoid jumping to the top of the page where appropriate
- [ ] Any JS code that still exists in the website should come with a `console` warning and documentation around it's reasoning along with information as to when it may or may not be making it back into the standards.

**Comment by juliaelman** [comment]
Referencing #1343 so that we can track the work that happens between these two issues, as they possibly relate with one another.

**Comment by maya** [comment]
> Anchor tags <a> should be explicitly set to href="javascript:void(0);" to avoid jumping to the top of the page where appropriate

This is what we had initially. So will we revert the decision made here: https://github.com/18F/web-design-standards/issues/743 ?

**Comment by rogeruiz** [comment]
@maya yes I would say so. Because since using this `handle-disabled-links` JavaScript we've had an issue with the website and PR work associated with it.

Issue: #990
PR: #1285

**Comment by francisrupert** [comment]
If the motivation to change to `href="javascript:void(0);"` is purely to avoid "jumping to the top of the page", that can be done via `href="#some-totally-made-up-text-here"`. 

That won't scroll anywhere since it can’t find an element with `id="some-totally-made-up-text-here"` (though it does mess your browser history).

(Probably moot for now as I see #1378 is resolved).

**Comment by Journerdism** [comment]
Console warning is a nice to have, maybe in the future, but for shipping 1.0, we'll close this.
