### ISSUE TITLE
[Website]: Why the duplication of including the sidenavs?

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1365]
## Description

I am working on updating the standards for the program I'm on and I saw something interesting in the `styleguide.html` layout.

In the top portion of the layout:

```
    <aside class="sidenav">
      {% if page.category == 'UI components' or page.title == 'UI components' %}
        {% include sidenav/ui-components.html %}
      {% elsif page.category == 'Getting started' or page.title == 'Getting started' %}
        {% include sidenav/getting-started.html %}
      {% elsif page.category == 'About our work' or page.title == 'About our work' %}
        {% include sidenav/about-our-work.html %}
      {% endif %}
    </aside>
    {% include sidenav/mobile.html %}
```

Then in the site-footer portion of the layout:

```
        <div class="site-footer-nav usa-grid">
          {% if page.url == '/' %}
            {% include download-buttons.html %}
          {% endif %}
          {% if page.category != null %}
            <h6>{{ page.category }}</h6>
          {% endif %}
          {% if page.category == 'UI components' or page.title == 'UI components' %}
            {% include sidenav/ui-components.html %}
          {% elsif page.category == 'Getting started' or page.title == 'Getting started' %}
            {% include sidenav/getting-started.html %}
          {% elsif page.category == 'About our work' or page.title == 'About our work' %}
            {% include sidenav/about-our-work.html %}
          {% endif %}
        </div>
```

It appears this is strictly a mobile consideration, is that a fair assessment?

## Steps to reproduce the issue

1. Open `/layouts/styleguide.html`
2. Go to page: [https://standards.usa.gov/labels/](https://standards.usa.gov/labels/)
3. View source
4. Scroll to bottom - see duplicate side navigation
5. Inspect footer element
6. Select `.site-footer-nav` - see `display: none`
7. Make browser narrow - see style attribute changes

**Comment by maya** [comment]
@joshbruce yes, the site-footer navigation only gets displayed on smaller screen widths.

**Comment by joshbruce** [comment]
@maya - Thanks! I see the labels and don't want mess y'all up. So, would like to close this?

**Comment by maya** [comment]
Sure, we can close this. Thanks!
