### ISSUE TITLE
Make sure documentation catalogues dependencies

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1366]
(Part of the new comms plan)

Steps to completion:

- [x] Ask a developer for help reviewing the existing documentation, identifying places that need to be updated, and updating those places.
- [x] Once documentation is factual/up-to-date, review for voice/tone consistency + do copy edits.
- [x] Publish! 

So far, Julia has offered to do the factual review (and thank you, Julia!). We'll start the stylistic review right after that.

**Comment by juliaelman** [comment]
Talked with @kategarklavs and this for after the repo split, https://github.com/18F/web-design-standards/issues/1343.

**Comment by juliaelman** [comment]
The current documentation looks 👌  to me and below are the dependencies for the Standards package, FYR. As mentioned in our meeting earlier today, I'll be taking a first pass at the docs (from a technical standpoint) as we split up the repos.

[Bourbon](http://bourbon.io/)
[Neat](http://neat.bourbon.io/)
[Normalize](https://necolas.github.io/normalize.css/)
[Politespace](https://github.com/filamentgroup/politespace)
[jQuery](https://jquery.com/)**

We also include the following dependencies for our website to work in all browsers. They are NOT required in our package, but want to mention them as recommendations for folks to include on their sites who require various browser support:

- [REM unit polyfill](https://github.com/chuckcarpenter/REM-unit-polyfill)
- [Respond](https://github.com/scottjehl/Respond)
- [selectivizr](http://selectivizr.com/)

** This is a WIP and will most likely be removed once the split is completed. Leaving in for now, but should be removed once the [PR is completed](https://github.com/18F/web-design-standards/pull/1357).

**Comment by kategarklavs** [comment]
@juliaelman Many thanks for your help (and thanks too for the detailed update). Will you ping @jameshupp and I once this documentation is ready for an editorial eye?

**Comment by kategarklavs** [comment]
@juliaelman Went through all the markdown files in web-design-standards-docs and made copyedits + a few stylistic changes. Let me know if you'd like me to make additional edits — going to close this issue, for now, but please feel free to reopen!
