### ISSUE TITLE
[Website] Investigate HTML page template possibilities

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#1379]
## Description

Past research has shown that a number of the WDS users are looking for ways to get their project off the ground quickly using the standards but hit a crossroads when it comes to writing those first few lines of code. By providing a few HTML templates, we may be able to make the standards a little bit less intimidating to use and increase adoption.

Additional research will be necessary to confirm some of these assumptions and ensure this is the right problem to solve, but for now we can do a few things to start moving in that direction.

- [x] Catalog the ways our standards are currently being used, what kind of pages/apps are being built 
- [x] Investigate page template and/or theme options with other popular front-end frameworks
- [x] Ensure that this topic is being covered in the next user listening tour

This issue will be complete when we decide on 2-3 templates to pursue building

**Comment by joshbruce** [comment]
@donjo - Hello! For your reference: https://gsa.github.io/sam-web-design-standards/page-templates/

Cheers.

**Comment by donjo** [comment]
Posting this example of how Gov.uk does page templates that @ericadeahl sent over for future reference/inspiration.

http://govuk-prototype-kit.herokuapp.com/examples/

**Comment by Drakenhart** [comment]
@joshbruce @donjo This is a beautiful idea, and having a repository of downloadable "skins" I suppose you can call them for different content management systems would be a brilliant idea. Even if they just used the very basic styles here.

It would also help reduce government costs in certain areas too. ^.^

My concern in seeing the code portion is... wow that is a LOT of divs where <section> and <article> and <main> could be used instead. ;) (Hard habit to break, I do it too still.)

**Comment by joshbruce** [comment]
@Drakenhart - Agreed. I'm marking this. Because we are actually try to exactly that...including elements and components via kits. We are building one from JavaScript for use on Node.js servers.

Tagging: @ChristyHermansen, @BrianGilmanGSA, @jenbesergsa

Referencing: I created a ticket once about the concept to determine demand probability for other Agencies. I'm marking this as a request. :)

**Comment by donjo** [comment]
I spent some time cataloging the ways that some of our existing users utilize the standards (starting with those listed in [the wiki](https://github.com/18F/web-design-standards/wiki/Websites-that-use-the-Draft-U.S.-Web-Design-Standards)) and noted a few things:

- The colors, grids, and buttons were some of the most widely used components.
- Most users used the actual WDS CSS when using a component from the standards (as opposed to copying the visual styles into their own code) 
- Javascript components are underutilized at this time
- WDS fonts are very popular though not always utilized to the best of their ability
- The WDS are most often used on single or multi-page content-heavy information/marketing sites

I'm not going to spend too much time speculating on the "why" behind these observations right now since the standards are still young and we don't have visibility into internal app usage but I think it provides a little bit of background for our upcoming research and just looking at 20-30 sites using the standards gave me some ideas about how we can increase quality across the board through better documentation/examples (including themes/templates).

**Comment by donjo** [comment]
Re: `#2` on the list of things to do. I spent some time looking at the theme/template sites for other popular front end frameworks to see what style of sites are rising to the top in popularity. While we tend to serve a slightly different user base, I think there are a lot of parallels. 

Some things to look at:
- WrapBootstrap (https://wrapbootstrap.com/) - third-party bootstrap theme site
- Bootstrap Themes (http://themes.getbootstrap.com/collections/all) - first-party themes offered by the bootstrap team
- Foundation Templates (http://foundation.zurb.com/templates.html) - a handful of layout options for Foundation users
    - Foundation Building Blocks: (http://zurb.com/building-blocks) something that exists somewhere between components offered by the front end framework and full-fledged templates
- Pure (http://purecss.io/layouts/) - a handful of layout options for PureCSS

SaaS sales pages, company/agency landing pages, analytics dashboards, web apps, and blogs tend to be the most popular options across these sites. 

Based on what I've seen after looking at all the existing sites utilizing the standards, I think building a documentation layout (not unlike the site the standards themselves are on) and a single-page information site (used for providing details on a new program/event or advertising a small government team) could be some easy wins early on while the standards are still maturing.

**Comment by wslack** [comment]
@donjo we can host these using Federalist if y'all don't mind listing them as sample templates for Federalist users to fork cc @el-mapache @jeremiak @brandocalrissian

**Comment by Journerdism** [comment]
Closing and new issue for post-research discussion will be created by @donjo !
