### ISSUE TITLE
[Select, Radio, Checkbox]: Update select dropdown to use historical figures

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#1382]
## Description

Working on a kit to return HTML from function calls. Noticed a pattern for `radio`, `checkbox`, and `select` elements:
1. A primary label for use in identifying a `select` or (possibly) a `fieldset` (for checkboxes and radios).
2. Each element type has a list of options for a user to choose from.
3. Each option has either a `value` within an `option` or a `value` within the `input`.
4. For `radio` and `select` a user can only choose one option.
5. For `checkboxes` a user can select multiple options.
6. One or more options can be `selected` or `checked` (checkboxes only).
7. `select` as a whole, or one or more options, can be `disabled`.
## Proposal
1. Update the Dropdown element: https://standards.usa.gov/form-controls/#dropdown - to use historical figures to make this pattern more obvious.
2. (not required for proposal) Wrap Radio and Checkbox elements in a `fieldset` with a `legend`.
## Further reading

Having both of these allows for a completely generic solution in generating the HTML via a kit based on a type. For example (JSON):

```
{
  type: 'dropdown',
  label: 'Historical figures',
  options: {
    'truth': 'Sojourner Truth',
    'douglass': 'Frederick Douglass',
    'washington': 'Booker T. Washington',
    'carver': 'George Washington Carver'
  }
  disabled: ['truth'],
  selected: ['carver']
}
```

This creates the base configuration for a single function to flip on the type and return the proper HTML. In the above configuration:

```
If type == 'dropdown'
  // dropdown is disabled
  // carver is selected

else if type == 'radio' || type == 'checkbox'
  // truth is disabled
  // carver is selected
```

No example for multiple select, or multiple disabled, but it's there.

**Comment by maya** [comment]
@joshbruce thanks for opening this issue! We may start work on something to address this in the coming weeks. We'll make sure to keep you posted!

**Comment by joshbruce** [comment]
Thank @maya!

**Comment by maya** [comment]
I don't think we understand the value in changing the select option, closing for now.
