### ISSUE TITLE
[UI component]: Cannot use any twelfth classes besides one-twelfth in 12-column grid

### ISSUE THREAD

**Issue by ducklet** [18F/web-design-standards#1383]
## Description

The 12-column grid can be split into twelfths; usa-width-one-twelfth works, but usa-width-seven-twelfths & usa-width-five-twelfths do not.

I am working on a section that should be larger than one half but smaller than two-thirds, and having to override the default percentages does not seem like the best long-term solution. 

## Steps to reproduce the issue

1. See https://standards.usa.gov/grids/
2. Use inspector to change a class e.g. usa-width-one-twelfth to usa-width-three-twelfths

**Comment by maya** [comment]
Hi @ducklet, thanks so much for opening this issue! Looks like it we may have just missed adding in five-twelfths and seven-twelfths into the grid. @bradnunnally @ericadeahl is that correct that we ought to add in?

> nor do ten-twelfths or five-sixths

`usa-width-five-sixths` should work, it's here in the code: https://github.com/18F/web-design-standards/blob/staging/src/stylesheets/core/_grid.scss#L101...L103

**Comment by maya** [comment]
@ducklet with our grid system based on [Bourbon Neat](http://neat.bourbon.io/), if you're using the Sass version of the USWDS, you can include the grid items on your div with `@include span-columns(5);` and `@include span-columns(7);` at the breakpoint you need.

**Comment by ducklet** [comment]
@maya my fault, five-sixths is working properly, thanks!
