### ISSUE TITLE
Radio/Checkbox - Label

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1386]
Radio/Checkbox - Label
## Description

Radio/Checkbox - Label
If we have multi line label, the alignment is set to checkbox/radio, not to the label.

Can there be options to align the multi-line labels together instead of align to checkbox/radio?

**Comment by maya** [comment]
Hi @dalfaro1, thanks so much for opening this issue! Could you post a few screenshots so we have a better idea of what you're looking for.

**Comment by donjo** [comment]
Closing this for now. Feel free to open with additional information on what you're trying to achieve and we'll take a look.
