### ISSUE TITLE
Distribution: making available on webjars.org

### ISSUE THREAD

**Issue by vjkapur** [18F/web-design-standards#1391]
I wanted to include uswds as a maven dependency and it seemed like getting it added to webjars.org was my best bet, so this is happening shortly: https://github.com/webjars/webjars/issues/1458

In case you want to add that to your list of unofficial distributions.

**Comment by vjkapur** [comment]
And here it is on Maven Central: http://search.maven.org/#search|ga|1|a%3A%22uswds%22

**Comment by maya** [comment]
Added to: https://github.com/18F/web-design-standards/wiki/Distribution-methods

Thank you, @vjkapur!
