### ISSUE TITLE
[Split Repo] Comms strategy for announcing split to user base

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1393]
## Description 
We need to notify everyone of what's happening and how it's going to affect them.

## Acceptance Criteria
- [x] Create the comms strategy for announcing the split to the user base
- [x] Write the language and explanations, update documentation
- [x] Work with Comms team to schedule and hand off announcement

## Additional information
* Related to this epic: https://github.com/18F/web-design-standards/issues/1343#issue-166414812

**Comment by kategarklavs** [comment]
@juliaelman and I are meeting on 8/29 to discuss! Will post updates as we have them.

**Comment by kategarklavs** [comment]
Howdy all — here's a document with the content for different channels (listservs, Twitter, 18F internal newsletter, etc.):

https://docs.google.com/document/d/1_KYKjygTxjiCOWYYBIqLSITAjjR3Qlca1iFhrNzfzUY/edit

@jameshupp and @juliaelman are going to take a look/leave feedback, after which I'll make my revisions. I'll then reach out to comms folks re: getting these tweets out + including this news in the next internal newsletter. (We can handle README updates and listserv messages ourselves -- no comms involvement needed.)

**Comment by kategarklavs** [comment]
Also! @jameshupp updated the documentation, so I checked that item off the Acceptance Criteria list. (And James, I'm happy to take a look at any documentation-related updates if you'd like another set of eyes -- just let me know!)

**Comment by kategarklavs** [comment]
Reached out to @awfrancisco (in #outreach) to find out how to contribute content to the next internal newsletter. As far as tweets go, I can submit them via #tweet-this on the days on which they're to be posted. Other comms efforts fall on us!

**Comment by kategarklavs** [comment]
And, finally, shared the link to the google doc in our channel & asked folks to submit their feedback by COB 9/6 — this will give me time to address any potential changes/make updates, as needed.

**Comment by jameshupp** [comment]
@kategarklavs Pretty sure this is closable now, yeah?

**Comment by kategarklavs** [comment]
@jameshupp Yep! In fact, I'll close it now 🎉
