### ISSUE TITLE
[Split Repo] Update Documentation

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1397]
## Description 
Update documentation

## Acceptance Criteria
- [x] Update documentation around the split repo
- [x] LICENSE, README, and CONTRIBUTING contain consistent (ideally only one set of) references, and they are in line with Comms understanding.
- [x] Coincide with the [Comms strategy for announcing to current user base](https://github.com/18F/web-design-standards/issues/1393)

## Additional information [optional]
* Related to this epic: https://github.com/18F/web-design-standards/issues/1343#issue-166414812

**Comment by kategarklavs** [comment]
@juliaelman Hey! How can I help with updating the documentation? I'm happy to pair write (or review after the first draft is done) — let me know what works best for you 👍

**Comment by juliaelman** [comment]
@kategarklavs yes! Would love your help in thinking about how to construct the content for both the website and the Standards repo. Going to slot some time to touch base with you about that this week! <3

**Comment by kategarklavs** [comment]
@juliaelman Sounds good! My schedule this week is a bit hectic (on account of the listening tour), but my cal is up to date — feel free to reserve some time for us to talk & we can get this task started! 🎉
