### ISSUE TITLE
[Split Repo] Documentation Review

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1398]
## Description 
Update documentation

## Acceptance Criteria
- [x] Review documentation and merge to publish
- [x] Coincide with the [Comms strategy for announcing to current user base](https://github.com/18F/web-design-standards/issues/1393)

## Additional information [optional]
* Related to this epic: https://github.com/18F/web-design-standards/issues/1343#issue-166414812

**Comment by kategarklavs** [comment]
Howdy! Is this documentation ready for review? (If so, I'm happy to start reviewing.)

**Comment by juliaelman** [comment]
@jameshupp adding you to this issue too, as you have already started this work here: https://github.com/18F/web-design-standards/pull/1420 🎉
