### ISSUE TITLE
[Refactor HTML/CSS] Make alerts work without header and with different sizes of text.

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1430]
Refs https://github.com/18F/web-design-standards/issues/1342

**Comment by maya** [comment]
Alerts already work without a heading and just text. Screenshot below. I'm not sure if I understand the problem, can you explain @msecret? 

<img width="771" alt="screen shot 2016-09-01 at 12 27 34 pm" src="https://cloud.githubusercontent.com/assets/5249443/18181345/a5150170-703f-11e6-92f9-1c2e9cf7a565.png">

**Comment by msecret** [comment]
@maya have you tried one with just one line of text. Your only options here have multiple lines of text.

**Comment by maya** [comment]
@msecret here is what it looks like with one line of text. This seems like more of a design problem than a code refactor one. If we want to move forward with it, we'll need some design guidance on this variation.

<img width="871" alt="screen shot 2016-09-01 at 2 59 39 pm" src="https://cloud.githubusercontent.com/assets/5249443/18186008/1ff80a62-7055-11e6-8449-b7c27ad8e961.png">

@Journerdism thoughts on moving forward?

**Comment by maya** [comment]
A possible solution is to add a min-height to the alert. Another is to use a pseudo selector for the icons.

I just want to make sure this issue is in the scope of work for code refactor since it's technically a design issue.

**Comment by maya** [comment]
Dependent on #1418 for this mixin: https://github.com/18F/web-design-standards/pull/1418/files#diff-fced6c74fbf3140d02e92fd710e888eeR88

**Comment by carlosvalle** [comment]
@maya - another solution will be to add a top margin to the paragraph only if it is the first child in `usa-alert-body`

**Comment by maya** [comment]
@carlosvalle thanks for that idea. I'm wondering if that method would add unneeded space when there's a heading above it?

**Comment by carlosvalle** [comment]
@maya - it doesn't - the selector only works if <p> is the first child element of the div ... I created a pull request #1460 - please let me know if you find any issues

**Comment by juliaelman** [comment]
Fixed #1460
