### ISSUE TITLE
[Research] Comparative Analysis of Design Systems

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1438]
## Description

Perform a comparative analysis of design systems to determine the gaps between what the draft web design standards and other more mature design systems available on the web.

**Comment by lauraponce** [comment]
Status as of Tuesday EOD:
-Narrowed comparable sites to Angular Material, Bootstrap, Bourbon, Foundation, MailChimp, Skeleton and Yelp. 
-Spent some time going through each of the sites today to get a feel for the flow.
-Will be looking at these sites from the angles of layout, code snippets, navigation, content order, and a couple more categories TBD.

**Comment by msecret** [comment]
Is there a reason Salesforce Lightning isn't on that list? It's one of the more thorough design systems and we've used it for a lot of inspiration.

**Comment by lauraponce** [comment]
@msecret -- There's no specific reason, I'll add that to the list too.

**Comment by maya** [comment]
Also, an honorable mention to Google's Material Design Lite bc they do code samples pretty effectively: https://getmdl.io/components/index.html

**Comment by lauraponce** [comment]
Added Material Design Lite as well! I'll post a revised list later today after I go through the Google Docs you sent.

**Comment by lauraponce** [comment]
Updated site list: Angular Material, Bootstrap, Bourbon, Foundation, Google Material Design Lite, Salesforce Lightning Design System, MailChimp, and Skeleton. 

Any and all feedback welcome about other additions!

**Comment by bradnunnally** [comment]
I'd say these 8 are good. It represents most if not all of the popular systems out there today and will give us great insight into what they are offering that we are currently missing and vice versa. 

Thanks @lauraponce!

**Comment by lauraponce** [comment]
I'll be focusing on the analysis from the heuristics/components of aesthetics, ease of use, code snippets, navigation, help and documentation, getting started and staying up to date.

**Comment by lauraponce** [comment]
The final results can be found here:
 [KeyFindings.pdf](https://github.com/18F/web-design-standards/files/473824/KeyFindings.pdf)
[Compare.xlsx](https://github.com/18F/web-design-standards/files/473825/Compare.xlsx)
