### ISSUE TITLE
[website] mobile nav bugs

### ISSUE THREAD

**Issue by ericadeahl** [18F/web-design-standards#1439]
Hi! I noticed that the mobile nav on standards.usa.gov is having some issues:

- there's a gray background behind all the nav items
- random nav items are blue (this may be a hover state that's appearing even though I'm on a mobile device?)
- section titles are white
- the accordions are broken!

**Comment by maya** [comment]
oof thanks @ericadeahl! 

Screenshots below for reference:

![img_0713_1024](https://cloud.githubusercontent.com/assets/5249443/18144504/cb88c9c8-6f7b-11e6-80b3-581a774231c8.jpg)
![img_0714_1024](https://cloud.githubusercontent.com/assets/5249443/18144505/cb8dd922-6f7b-11e6-8747-f7b1da4b87d0.jpg)

 
![img_0714_1024](https://cloud.githubusercontent.com/assets/5249443/18144512/d6af34c2-6f7b-11e6-9048-e875d6ade901.jpg)

**Comment by maya** [comment]
I noticed that what we have on staging looks good and is working: https://standards-staging.usa.gov/ @juliaelman if we release soon, maybe this will fix itself?

**Comment by maya** [comment]
We just released `0.12.0` and it seems to have resolved itself in this release! 🎉
