### ISSUE TITLE
Font weight rendering of default buttons is too heavy in Firefox on Mac

### ISSUE THREAD

**Issue by philipashlock** [18F/web-design-standards#1440]
Firefox on Mac appears to be rendering the font weight for default buttons much more heavily than other browsers causing some legibility issues. Including the following CSS as [discussed here](https://css-tricks.com/forums/topic/typekit-fonts-much-bolder-in-firefox/page/3/#post-168082) seems to fix the problem

` -moz-osx-font-smoothing: grayscale;`

Here's a comparison of Firefox 48.0.2 (left), Chrome 52.0.2743.116 (middle) and Safari 9.1.2 (right) on OS X 10.10.5

![screen shot 2016-08-31 at 12 45 01 pm](https://cloud.githubusercontent.com/assets/183402/18138257/f05519a2-6f79-11e6-970b-01610a1d3e90.png)

**Comment by maya** [comment]
@philipashlock Good call, we should add this in. thank you!

**Comment by maya** [comment]
Fixed in #1457.
