### ISSUE TITLE
[Issue/PR templates]: Update to reflect repo split

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1475]
## Description

Update the Github templates on the old repo and point folks to the new repo for website updates.

### This comment section should be updated:

>Please feel free to remove whatever sections/lines in this aren't relevant.

>Use the title line as the title of your pull request, then delete these lines. 

>## Title line template: [Website or UI component]: [Brief description]

>Website: Issues that impact standards.usa.gov look, feel or functionality.
UI component: Issues that impact the look, feel, or functionality of the standards themselves.

Is the `[Website or UI component]` still relevant bc each repo will deal with each one?

draft docs: https://docs.google.com/document/d/1DA411G7E-OCr94OTv86mqkRrdgslZygXOE3G8pNM5Pw/edit#

**Comment by kategarklavs** [comment]
@maya Excellent comment about no longer needing the [Website] and [UI component] tags any more — for both repos, I think [Brief description of issue] will suffice for the title line. 

Taking a look at your document now!

**Comment by juliaelman** [comment]
This issue was resolved here: https://github.com/18F/web-design-standards/pull/1476

Thanks all! 🚀
