### ISSUE TITLE
[Split Repo] [Documentation]: how to make updates given split repos

### ISSUE THREAD

**Issue by jpyuda** [18F/web-design-standards#1478]
## Description

Per our sprint-planning meeting of 9/13, we'll create a set of instructions for how to make updates/run the site locally given the repo split. Here's a general outline of the process:

- [x] Generate a list of issues folks might encounter/questions they might have, and write responses to said questions
- [x] Technical review of info
- [x] Add to relevant part of README
- [x] Also, make sure everyone on the team knows where the draft version of the doc lives

**Comment by maya** [comment]
Documentation here (tested by team): https://github.com/18F/web-design-standards-docs#using-the-latest-version-of-the-uswds-package

**Comment by kategarklavs** [comment]
@maya Ah, you read my mind! (I literally just tagged Julia in a comment in a Google doc asking whether we should spell out the process/whether we should provide only high-level guidance). 

I'll update the README and then ping you for review — sound good?

**Comment by kategarklavs** [comment]
Update: The web-design-standards-docs README has a new section titled "Using the latest version of the uswds package," which has already been reviewed/approved by the team. I talked to @maya, and she confirmed that no updates to the web-design-standards README are necessary. All in all, I think we're in good shape. That said, if you all feel like we need additional documentation, let me know and we can reopen this.
