### ISSUE TITLE
[Research] Dev Stack Survey

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1480]
Create a dev stack survey to be sent out to government employees within federal agencies. The purpose of the survey is to understand what back end and front end systems are being used on other teams in the government.

**Comment by rovo79** [comment]
Will you send out an email with a link to a third-party service hosting the survey?

**Comment by bradnunnally** [comment]
@rovo79 That'll be the plan, but due to some internal constraints on our end the survey will be limited to those with a .gov email address.

**Comment by rovo79** [comment]
That makes sense. I do have a gov email, but not currently using it on here. I was mainly curious to know which service you'll use for the survey.

**Comment by lauraponce** [comment]
The [survey](https://goo.gl/forms/gD2NkVQqYxGIXJ9b2) went out to the dev and news Slack channels on 9/26 and went out to the Web Content Managers listserv on 9/27 at 2:00pm EST

**Comment by rovo79** [comment]
Hello, are the dev and news slack channels open? I couldn't find information on them.

**Comment by bradnunnally** [comment]
Hi @rovo79, @lauraponce was referring to some of our internal slack messages here at 18F. Contractors are allowed to complete the survey if they have signoff from their COR.

**Comment by kcjonesevans** [comment]
@bradnunnally signoff meaning the okay? it is just a google form right?

**Comment by bradnunnally** [comment]
@kcjonesevans  @jpyuda would know more about the process, he was the one who initially gave me that guidance.

**Comment by jpyuda** [comment]
Yes, the ok. It's a short form, but I don't want to get caught "in between" contractors and their COR if there's an objection for some reason.

**Comment by lauraponce** [comment]
Here are the final results from the survey:
[SurveyResultsDoc.pdf](https://github.com/18F/web-design-standards/files/503449/SurveyResultsNotes.pdf)
