### ISSUE TITLE
Clickable Zone for Checkboxes Too Large

### ISSUE THREAD

**Issue by betson** [18F/web-design-standards#1490]
## Description

The default [Checkboxes](https://standards.usa.gov/form-controls/#checkboxes) have a rendered size that extends far to the right of the actual visible element. This means that the element is clickable far outside the visible box and text. Because the element is clickable, the selected status of the item could be mistakenly toggled when the page is clicked outside of the checkbox. Additionally, this extension can bleed on top of other elements, preventing intended clicks on a different target.

This is particularly noticeable if the checkboxes are floated to the left of additional content or links.
## Steps to reproduce the issue

This is visible on the [Documentation Website](https://standards.usa.gov/form-controls/#checkboxes). The checkboxes can be toggled by clicking to the right, outside of the checkboxes. If a link were positioned to the right of the `<fieldset>`, the cursor would not change to a pointer when hovering over the link when it intersects with the fieldset positioning.
## Additional information [optional]

Reproduced on Chrome v52.0 on OSX.

**Comment by betson** [comment]
If I add `z-index: -1;` for `input[type="checkbox"]`, this fixes it for my site. I don't know the impact on other web components.

**Comment by maya** [comment]
Hi @betson, thanks so much for opening this issue! I've started work to address this issue in #1491.

**Comment by betson** [comment]
Fixed in #2002.
