### ISSUE TITLE
Radio button, doesn't support <a href> link inside the radio label

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1493]
Radio button, doesn't support `<a href>` link inside the radio label
## Title line template: [Title]: Brief description

Radio button, doesn't support `<a href>` link inside the radio label
## Description

Using radio button, including a hyperlink inside the label, sometimes the hyperlink works, sometimes not. I think the hover in radio label interfere with href.

**Comment by maya** [comment]
Hi @dalfaro1, thanks so much for opening this issue!

Radio button labels are clickable and control the input of the radio button so adding a hyperlink inside it won't work. However, you can add the link outside the label and it should work as expected.

**Comment by dalfaro1** [comment]
I tried separating the href inside the label.

Hover/clickable link still has a bug. FYI.

Thanks.
