### ISSUE TITLE
JavaScript error for basic header

### ISSUE THREAD

**Issue by jessieay** [18F/web-design-standards#1496]
## Problem with JavaScript for basic header

Website: https://standards.usa.gov/headers/basic/#

## Description

When you view the header in a mobil screen size, clicking the "menu" button opens the mobile menu properly. But clicking the "X" button to close does not work. The menu closes and then re-opens immediately.

## Steps to reproduce the issue

1. Visit https://standards.usa.gov/headers/basic/#
2. Adjust screen size to be mobile
3. Click "menu"
4. Click "x" to close out of menu

## Additional information

Gif of what I am seeing:

![sep-21-2016 12-54-07](https://cloud.githubusercontent.com/assets/601515/18726662/57c8adca-7ffa-11e6-8167-157785c0ca70.gif)

**Comment by maya** [comment]
Noting for debugging: this happens on mobile devices, not on the browser window at small screen sizes.

**Comment by jessieay** [comment]
@maya the gif above was created in chrome on my laptop

**Comment by maya** [comment]
@jessieay yep, the chrome device mode simulates those mobile devices which is where the problem is appearing. Thanks for reporting this issue!
