### ISSUE TITLE
Roadmap for Analytics Strategy

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1549]
## Description

Describe the timeline which the various business objectives will be set up and in what priority.

**Comment by bradnunnally** [comment]
Requires team collaboration to discuss the technical nature of putting the strategy into place.

**Comment by Journerdism** [comment]
@bradnunnally breaking this up a little more into sprint-accomplishable tasks

**Comment by bradnunnally** [comment]
Will be completed once #1566 occurs

**Comment by bradnunnally** [comment]
Meeting scheduled with the team to come up with initial draft.

**Comment by bradnunnally** [comment]
MVP has been defined. The long term strategy needs additional prioritization and alignment with future product development goals.
