### ISSUE TITLE
Refine the new USWDS Design Principles

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1562]
Work with the team to refine the content for the new and revised design principles of the WDS.

**Comment by bradnunnally** [comment]
Revised principles have been drafted and await the teams review.

**Comment by bradnunnally** [comment]
Here are the new design principles. Any updates can be made prior to posting them online. 

**USWDS Design Principles**
Get help when you need it
The Draft U.S. Web Design Standards is a product that is here to support its users build user friendly and modern digital products. The instruction we provide designers and developers both general and customized guidance on how to use, extend, and customize the USWDS. No matter what a team’s skills are, they should be able to use the USWDS. 


**Design for flexibility.**
Our patterns and designs are easy to adapt to support the diverse scope and needs of government digital services. The tools and components provided in the USWDS are focused on performance, both from a technical and team based point of view. To ensure this, everything should be validated for the user by the user. The USWDS wants to empower teams across to government to make the statement “good enough for government work” means something again. 


**Showcase benefits for agency and users**
Teams around the government should easily be able to find inspiration from among their peers. This inspiration can jumpstart many teams own efforts but also lay the groundwork for making the business case for adopting the Draft U.S. Web Design Standards. The success of both USWDS and its users will be cataloged both quantitatively and qualitatively. 


**Make the best thing the easiest thing.**
The Draft U.S. Web Design Standards is the easiest path for teams around the federal government to comply with the latest federal policy for websites and digital services. The USWDS support modern web development practices, such as mobile first and responsive frameworks. By offering open-source, quick-to-download code and assets, the Standards make it easy to deliver the highest-quality government websites to the public.


**Offer accessibility out of the box.**
Every asset we offer should meet the high accessibility standards outlined in Section 508. For teams that need to customize the USWDS to meet their agency needs, guidance will be offered to ensure any extensions and customizations that are made comply with Section 508 guideline.


**Reuse, reuse, reuse.**
Teams should not be burdened with recreating basic components and patterns for every new product they create. The tools, patterns, and components present in the USWDS will be a comprehensive collection of tried-and-true assets that reflect industry best practices. This will enable teams to focus on the unique aspects of their product to ensure the general public is getting the best possible service.
