### ISSUE TITLE
Cook prep for a delicious meeting

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1582]
Trim down all the proposals we've prepped for the 3-4 different models and:
- [x] Prep 1-pager overview and send COB Tuesday
- [x] Prep presentation, "Get to the TL;DR in the first five minutes, and then we'll leave time for Q&A, discussion, etc."

**Comment by acolter** [comment]
The one pager is in PDF format at https://drive.google.com/open?id=0B8dk4rmN4KrvSFdPdWdQODVlUDA

The cost spreadsheet PDF is at https://drive.google.com/open?id=0B8dk4rmN4KrvNXdmMVFZVDBUNE0

**Comment by Journerdism** [comment]
Closing since it's go time! Great job!
