### ISSUE TITLE
Header font size problem in 0.13.2 compiled CSS

### ISSUE THREAD

**Issue by mstanaland** [18F/web-design-standards#1597]
## Description

Looks like there's a bug in the css provided in https://github.com/18F/web-design-standards/releases/download/v0.13.2/uswds-0.13.2.zip

The pixel font-size set on the html element is 16px instead of 10px causing all the rem unit elements in the header to be much too large. For example "An official website of the United States government" appears as 19px instead of 12px. This doesn't appear to affect content outside of the header. 

Downloading the source SASS files and compiling locally doesn't have the same problem.

## Steps to reproduce the issue

1. Download https://github.com/18F/web-design-standards/releases/download/v0.13.2/uswds-0.13.2.zip
2. Create an html file with a link to CSS in zip
3. Add html from any page template

## Additional information [optional]

<img width="1249" alt="screen shot 2016-12-01 at 8 07 48 am" src="https://cloud.githubusercontent.com/assets/3612439/20795069/496c74d4-b79d-11e6-9184-e782c68c7c61.png">

**Comment by juliaelman** [comment]
@mstanaland thank you for opening your issue! This is a known bug in release `v0.13.2`  of the Standards and has been resolved [here](https://github.com/18F/web-design-standards/pull/1591). This solve will be a part of our upcoming release, but we have also attached patch files to the [v0.13.2 release notes](https://github.com/18F/web-design-standards/releases/tag/v0.13.2) if you are unable to upgrade to our upcoming release.

Closing this issue, but please feel free to reach out/open a new issue if you have any further complications.
