### ISSUE TITLE
Include Google Analytics on Website

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1605]
## Description

Using the consolidated web analytics report, manually include the number of users exposed to the WDS, which will include how many of them were new users and how many pageviews.

**Comment by bradnunnally** [comment]
MVP has been created on add-analytics branch of the docs repo. 

https://github.com/18F/web-design-standards-docs/blob/add-analytics/pages/about-our-work/overview.md

**Comment by juliaelman** [comment]
Adding a note here in regards to some Github metrics @bradnunnally requested. 

For the period between **July 30 - September 30, 2016** we have had **507 commits** and **73 forks** to the [web-design-standards](https://github.com/18F/web-design-standards/) code base. We will be adding these metrics as part of the [Google Analytics work](https://github.com/18F/web-design-standards-docs/pull/83), as well as automating these statistics in the future.

**Comment by bradnunnally** [comment]
This information has been submitted in a PR to put on the main site. Next steps is to find a way to automate the data report out in some way, which can be tackled next quarter.
