### ISSUE TITLE
Table element: min-width should not be set

### ISSUE THREAD

**Issue by cherrypj** [18F/web-design-standards#1621]
Adding a table to a page using the Web Design Standards should not take up the entire available width. There are many tables that present only a small amount of tabular information. I'm not sure how readable the tables are when they take up the entire width.

![table-standards](https://cloud.githubusercontent.com/assets/43620/21145512/97c5bec8-c11c-11e6-87c0-089aac6edff2.png)

Tables should expand to fit the width; no further.

Would it be possible to drop the `min-width: 100%` styling?

**Comment by juliaelman** [comment]
Thank you for your interest and contributing to the Draft U.S. Web Design Standards! We have received notification of your contribution and will add it to our backlog for future feature consideration.
