### ISSUE TITLE
Create / update the internal team guidelines and templates for community building for Q2

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1627]
Here's a running start, add strategies around Slack and fostering a community support model:
https://docs.google.com/document/u/3/d/1J9vGJ60_fMROCarYumqwB2RxUb-80LkK4J9AnM3KRI4/edit?ts=57b35cce

This too for tracking:
https://docs.google.com/spreadsheets/d/100KRMxoOO6T4N686MRTuOFmBeLkXl9fLZFtlhhF979M/edit?ts=57b35d32#gid=0

**Comment by acolter** [comment]
Some thoughts around using Slack for developing a community: https://docs.google.com/document/d/1ukx-TXH8GvsRbbIETBKyguJSG0CYh5foplu5xREtxUw/edit#

**Comment by acolter** [comment]
Captured the discussion we had yesterday and added those items to the document. I'm looking for feedback about whether this is what the team needs.

**Comment by Journerdism** [comment]
@acolter This looks good! Can you take a look at the previous guidelines and tracking spreadsheet and see how we might integrate and update that into a cohesive and streamlined community strategy for responding and tracking feedback? Especially if you could propose a workflow and ownership -- I think we'd talked about having someone 'on point' for a week or two owning the communications or at least being a traffic cop for tracking and responding? Maybe we make that a two week stint that rotates to help spread the work around and set the cadence with the sprint assignments.

**Comment by acolter** [comment]
I've added a link to the email guidelines and mentioned the idea of assigning someone to manage each channel or rotating management every two weeks.
