### ISSUE TITLE
Investigate Foundation community

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1632]
Check out Zurb Foundation and how they manage, talk to and organize their community and share with the team how we might do similar things

- [x] Research / check out what they do
- [x] Write up notes
- [ ] Share with the team and make a recommendation, cross-share with this task: https://github.com/18F/web-design-standards/issues/1627

**Comment by lauraponce** [comment]
This is still in progress and will be completed/closed out by end of day today (12/23)

**Comment by lauraponce** [comment]
The research and recommendation around community based on Foundation can be found here: 
[WDS Community Research-Foundation.pdf](https://github.com/18F/web-design-standards/files/671616/WDSCommunityResearch-Foundation.pdf) 
and is in Google Drive here: https://docs.google.com/a/gsa.gov/document/d/1m_tTf9pNeXGl8mzAyl2RXMU-egb7HnFvSVhDC8vhr8U/edit?usp=sharing
