### ISSUE TITLE
Research Q2-Q3-Q4 gov-tech conferences to pitch presenting to

### ISSUE THREAD

**Issue by Journerdism** [18F/web-design-standards#1634]
Dig around and see if there are any upcoming conferences, awards or events to pitch the WDS to for building up more community and leads.

**Comment by lauraponce** [comment]
This is still in progress and will be completed/closed out by end of day today (12/23)

**Comment by lauraponce** [comment]
The gov-tech conference possibility list can be found here: 
[Q2-Q3-Q4 gov-tech conferences.pdf](https://github.com/18F/web-design-standards/files/671574/Q2-Q3-Q4gov-techconferences.1.pdf)
and the doc is in Google Drive here: https://docs.google.com/a/gsa.gov/document/d/1rMfH_KgJPPE6QGsycwsmsbKr2yoeF8ShLD30QwbqkGA/edit?usp=sharing
