### ISSUE TITLE
Google Analytics reporting version 1.0 research

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1635]
Depending on available time, target Laura to investigate pulling (and eventually automating reports with developer support) for:
Desktop vs Mobile Usage - Aggregated data from all known sites using the USWDS that have a google analytics profile through DAP (analytics.usa.gov). This will show the break down of those viewing a site using the USWDS from either a desktop or mobile device.

**Comment by lauraponce** [comment]
I put in a request for access to the Government Wide Account on 12/14, but there is currently a DAP issue and they are not able to grant new access to that account at the moment. It is being looked into, but there is no ETA on when it will be resolved so I am blocked on moving forward with this issue until I receive access to that account.

**Comment by Journerdism** [comment]
Moving to Q2 since this is blocked and out of our hands. :(

**Comment by romkedehaan** [comment]
We aren't sure about this on right now. Will hold till @yowill
