### ISSUE TITLE
Line height between links in Big Footer component

### ISSUE THREAD

**Issue by mariamarrero** [18F/web-design-standards#1637]
Big Footer UI Component

Links that are located under "Topic" headings in big footer component (Secondary link) need line height adjustment. At this point, if those links are long and wrap, the second line of a link appears as if it is a different link and not a continuation of the first line. 

A smaller line height spacing is expected between 1st and 2nd lines for links that wrap. Users can be confused by the labeling of these links.

See attached screen shot as a reference (with "Footer link that is long" long link). 
![screen shot 2016-12-19 at 11 03 27 am](https://cloud.githubusercontent.com/assets/6410374/21319624/fbc0cc10-c5db-11e6-98c7-d11a3dcc1742.png)

**Comment by maya** [comment]
Fixed in #1637.
