### ISSUE TITLE
Prepare presentation for the Web Council and DigitalGov

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1665]
We have dual presentations on 1/25/2017 for both the Web Council and Digital Gov, they will cover similar topics, but DigitalGov might be more close to an hour vs 30 minutes for the Web Council. Notes on that and what to expect are here: https://docs.google.com/document/d/1HFY5nBhLwLBVniGx1o6M_TRXHWYylXtuHyfvBEMXWlc/edit

Create a presentation for these:
- [x] Web Council
- [x] Digital Gov

**Comment by bradnunnally** [comment]
Going to base this off a presentation I gave previously and iterate based on team feedback. First step is to create the outline then get feedback. Once that's complete, a draft presentation will be created.

**Comment by yowill** [comment]
Web council presentation is now limited to 20 minutes (as you probably saw by the email)

**Comment by yowill** [comment]
All done! Great work.
