### ISSUE TITLE
mobile menu formatting bug

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#1666]
## Description

Mobile menu formatting is off when the first navigation item is NOT a menu item.

## Steps to reproduce the issue

1. Go to https://standards.usa.gov/headers/extended/
2. In Chrome dev tools under elements, right-click the first two ```<li>``` under ```<ul class="usa-nav-primary">``` and Delete Element. This puts the first non menu item as the first navigational element.
3. shrink browser window to create the mobile menu.
4. open mobile menu and see the results.

## Additional information [optional]

notice the lack of padding at the top and the gap between elements.
![screen shot 2017-01-04 at 6 23 25 pm](https://cloud.githubusercontent.com/assets/1322063/21662940/fc5e37b2-d2aa-11e6-8073-24f8f4f5d63d.png)

**Comment by maya** [comment]
I know the mobile navigation has changed over time and I'm not able to reproduce this. This is what I see:

<img width="304" alt="screen shot 2017-10-27 at 9 28 13 am" src="https://user-images.githubusercontent.com/5249443/32114769-294bf2fa-baf9-11e7-8967-3640af0ddf70.png">

Feel free to reopen if the error is still present and I did not see this correctly.
