### ISSUE TITLE
Write up pitch to these Q2 events to present on WDS

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1670]
Transforming Local Government
○ http://www.tlgconference.org/
○ April 18-21, 2017
○ Tulsa, Oklahoma
○ “TLG will attract over 500 local government professionals at every level in the
organization across the US and Canada. TLG is recognized for its dynamic
content that encourages freethinking and fosters unprecedented ideas, all within
a relaxed and professional networking and learning environment.”

Summit on Government Performance & Innovation
○ http://www.governing.com/events/Summit-on-Government-Performance-Innovation.html
○ May 24-25, 2017
○ Phoenix, AZ
○ “The third-annual Summit on Government Performance & Innovation is a unique
policy and leadership event focused on strategies and technologies that will
enable government to deliver better service, engage citizens and ultimately
improve performance.”

**Comment by bradnunnally** [comment]
I'm going to start with the summary that @carodew and @colinpmacarthur wrote up from a past conference and update based on where the project is today.

**Comment by bradnunnally** [comment]
Initial draft of two proposals up for team review.

**Comment by bradnunnally** [comment]
These are ready for Outreach review. @yowill do you want to handle that or would like me to?

**Comment by yowill** [comment]
@bradnunnally Please run it through outreach if you can.

**Comment by bradnunnally** [comment]
@elainekamlley is going to review the two proposals - https://docs.google.com/document/d/1vGTAeGAcQgKE1CdiOn9P2qNfwRCgcdY-bpeE8xOuUX4/edit#

Once reviewed, I will reach out to the two conferences listed above ( @elainekamlley do we have any formal connections with either of those events?) to see about presenting at their event.

**Comment by elainekamlley** [comment]
Reviewing the proposals this morning. 

Unfortunately, I don't have contacts with those organizers but would love to maintain a relationship, if you all present there.

**Comment by elainekamlley** [comment]
@bradnunnally @yowill, I took a look and they look strong. I'm also looping in @gboone for review as well. He has been doing more regional stuff for our team and has great perspective.

**Comment by bradnunnally** [comment]
@elainekamlley Sounds great! and Thanks @gboone !!

**Comment by bradnunnally** [comment]
Proposals sent to the above conferences. Closing the issue out.
