### ISSUE TITLE
Update wiki to avoid content dupes with standards.usa.gov

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1674]
## Description

There is currently duplicate information in the wiki that exists on the website already. I think we did this b/c updating the wiki is pretty quick painless. Since the repos are now split, it should be pretty easy to make updates and release website content and design changes.

**Comment by bradnunnally** [comment]
We can remove the release notes guidelines and checklist and the release process pages in the wiki.

**Comment by bradnunnally** [comment]
Content inventory is complete, will need some review and conversation with the team to ensure the accuracy of the audit and the recommended action. This is an initial draft, final draft will be once the team reviews and discusses. 

https://docs.google.com/spreadsheets/d/1PsZhPKdJhZOI1mdAhMNQf3ZAfFV0js8AJDjLGD3by-w/edit#gid=0

**Comment by bradnunnally** [comment]
The team met to review the content audit and the following next steps were defined:

1. Draft up a Content Editorial Process which will inform how the content on the main website will be maintained and how quick edits can be performed without breaking anything from the code base. 

2. Revise the site structure of the main website to find appropriate homes for the content that is moving to the site from the wiki 

3. Create the issues that map to each action that is present in the content audit. 

Issues for these 3 steps will be created for the product backlog.
