### ISSUE TITLE
Update workflow and labeling structure

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1675]
## Description
We currently have a plethora of labels. Let’s pare those down and evaluate the ones we do/don’t use.

## Steps to complete the issue

- [x] Update this wiki page https://github.com/18F/web-design-standards/wiki/Workflow
- [x] Update label glossary https://github.com/18F/web-design-standards/wiki/Label-glossary 
- [x] Clean up the repo tags

**Comment by yowill** [comment]
This task should sync or maybe be done by whomever does this task: https://github.com/18F/web-design-standards/issues/1671

**Comment by yowill** [comment]
Draft for team feedback here: 
https://docs.google.com/a/gsa.gov/document/d/1o4oIdCYQ1a514Kr1l1UVF1IUi0fqj6Mg8GMMloZf-mE/edit?usp=sharing

**Comment by bradnunnally** [comment]
@yowill looks good!

**Comment by yowill** [comment]
Done!
