### ISSUE TITLE
Add service offerings section of the website to homepage

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1677]
## Description

Add micro-copy on the homepage about the service offerings, with a link to email us for more information

**Comment by juliaelman** [comment]
Refs https://github.com/18F/web-design-standards-docs/pull/118

**Comment by juliaelman** [comment]
@shawnbot is doing this work as a part of the 1.0 homepage, which is being tracked in [this issue](https://github.com/18F/web-design-standards-docs/issues/113)

Closing this issue so we can accurately track the work.
