### ISSUE TITLE
New design for homepage 1.0 announcement

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1678]
## Description

Prepare content and design for 1.0 announcement somewhere on the home page
- [x] Take stab and get content in place
- [x] Ask for review visual design huddle and critique groups

**Comment by bradnunnally** [comment]
New splash page concept - https://gsa.invisionapp.com/share/FBAA2B78N#/217289279_1-0_-_Homepage

Thanks to @juliaelman for helping me scale this back and not over think it too much. Ready for review @yowill @shawnbot
