### ISSUE TITLE
Create pitch deck for AP

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1679]
## Description
Based on the WDS 1-pager created in December, create a pitch deck version for AP and us to use to explain the platform and options available for agencies. Make sure there's a Google Docs version available for AP to use (not all have keynote, but keynote can be the base/start).

**Comment by yowill** [comment]
@bradnunnally already rocking out here: https://drive.google.com/drive/u/2/folders/0B0PiNB9rY3lfcmM3NDdmRENNZHc

**Comment by bradnunnally** [comment]
update draft is posted here - https://drive.google.com/open?id=0B7qPjLYzv4b6a1FPUEdXbjFFa0k

The big todos is content review and edits.

**Comment by bradnunnally** [comment]
Updated link to the presentation - https://docs.google.com/presentation/d/1VC5rXAfrczZMqkiIQhNj1gnbkG1hMR2qbL-4AsE0Xm4/edit#slide=id.p30
