### ISSUE TITLE
Collect all the links, organize, create wireframes and IA for the Getting Started section of the site

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1683]
- [x] Quick and dirty wireframes
- [ ] Video integration
- [ ] Add links on the “Getting Started” page to create a single hub for all documentation:

([From this page](https://docs.google.com/document/d/1o4oIdCYQ1a514Kr1l1UVF1IUi0fqj6Mg8GMMloZf-mE/edit#)) 
- Wiki (keep it up to date and drive people to it through links, as much as possible, feed content automatically to website through github so both sources mirror each other)
- Video tutorials (keep a stable of quick tutorial videos for frequently asked questions or overviews. If someone could potentially have a similar question in the future and it’s not a dynamic/constantly changing thing, livestream/record a tutorial and share it in the documentation when possible)
- Release news and notes   add this to the secondary nav after "About Our Work" https://github.com/18F/web-design-standards/issues/1310
- Blog posts (using the WDS tag in the blog)  add this to the secondary nav after "About Our Work"
- Code explanations and philosophy (keep it up to date and drive people to it through links and just in time placement on the site) Good idea. We have this paragraph in our contributing guidelines that we can pull from: https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md#coding-guidelines
- Roadmap (keep it updated at least quarterly as we progress through the high level goals)
- Add a link to the Github milestones or issues for a more granular view of the work
- Link to the completed work and tasks whenever possible in the completed issues

More links and thinks we need to find homes for on Standards.usa.gov
Easy, quick explainer of what is Github:
https://www.youtube.com/watch?v=w3jLJU7DT5E

How to submit a request for the WDS: 
https://www.youtube.com/watch?v=CiIcDXft8jM

Big DigitalGov tutorial on using Github in general: 
https://www.youtube.com/watch?v=1-gLxOjkh4k

WDS Product roadmap: 
https://standards.usa.gov/about-our-work/product-roadmap/

WDS Getting Started guide: 
https://standards.usa.gov/getting-started/

WDS Public slack channel (questions and community support):
https://chat.18f.gov

WDS Wordpress theme from Broadcasting Board of Governors' open sourced: 
https://github.com/BBGInnovate/bbgRedesign

WDS Drupal theme created a while ago from an 18F colleague (not recently updated, but a start if you're looking for one):
https://github.com/18F/web-design-standards-drupal

Sites using WDS (that we know of):
https://github.com/18F/web-design-standards/blob/staging/WHO_IS_USING_USWDS.md

**Comment by bradnunnally** [comment]
My goal with this is to start with a revised sitemap, to figure out exactly what needs to be promoted to the main nav and what should live under getting started. This will be quick. 

From there get the teams 👍  or 👎

**Comment by bradnunnally** [comment]
Here are is the outside for the two pages that would need to be revisited as part of this story (which will need to be broken up to track the work appropriately)

Note: SN is short for it being present in the side navigation component. 
Getting Started
 - Intro
 - (SN) Wiki Call to Action (Phase 1 is linking to the wiki here on Github, Phase 2 can be looking for ways to pull that content into the site directly to avoid duplication)
 - (SN) Video Tutorials 
 - (SN) Code Guidelines
 - (SN) Product Roadmap

What's New
 - Usage Info
 - (SN) Blog
 - (SN) Release Notes
 - (SN) User Research
    - Current Research
    - Research Strategy


Thoughts on this outline for each page? @yowill @juliaelman @shawnbot?

Next step is to break this up into 3-4 different stories.

**Comment by yowill** [comment]
Sounds good, @bradnunnally! Depending on what's on the "Intro" page (there's currently 2 sentences on that page), I might say we should just post the videos there since there will only be 2-3 at this moment and they're an easy, non-technical way to get involved quickly and prominently (and not under a sidebar, 2 navigation structures deep): 

These also need a home somewhere in this structure (from the list above), if you can update where you think they should be placed that would be awesome (most of them are just links over to other resources, but they are frequent resources we site or get asked about): 
- Add a link to the Github milestones or issues for a more granular view of the work
- WDS Public slack channel (questions and community support):
https://chat.18f.gov
- WDS Wordpress theme from Broadcasting Board of Governors' open sourced:
https://github.com/BBGInnovate/bbgRedesign
- WDS Drupal theme created a while ago from an 18F colleague (not recently updated, but a start if you're looking for one):
https://github.com/18F/web-design-standards-drupal
- Sites using WDS (that we know of):
https://github.com/18F/web-design-standards/blob/staging/WHO_IS_USING_USWDS.md

**Comment by bradnunnally** [comment]
Initial take of the What's New page that includes the updated nav bar and footer - https://gsa.invisionapp.com/d/main#/console/9925961/217090294/preview

Please comment directly on the Invision comp. @juliaelman @shawnbot @yowill

**Comment by bradnunnally** [comment]
Updated Getting started page - https://gsa.invisionapp.com/share/FBAA2B78N#/217421484_1-0_-_Getting_Started


Ready for review @juliaelman @shawnbot @yowill

**Comment by juliaelman** [comment]
@bradnunnally this looks good to me!

**Comment by bradnunnally** [comment]
Closing this issue has it's been broken into a bunch of smaller more manageable tasks.
