### ISSUE TITLE
Prep CBP q&a and lessons learned post

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1684]
- [x] Follow up with them for some of the links and examples (Will doing with follow up email)
- [x] Polish up and organize the notes from Q&A with CBP
- [x] Send over to them for their feedback/updates and comms approval
- [x] Send to our comms approval to get in queue for publishing

**Comment by yowill** [comment]
Follow up sent!

**Comment by juliaelman** [comment]
Draft for blog post written up and sent to the team for feedback prior to sending to CBP.

**Comment by juliaelman** [comment]
Blog draft started here: https://github.com/18F/blog-drafts/issues/624
