### ISSUE TITLE
Update -- As in KILL IT -- Component Maturity Lifecycle documentation

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1693]
## Description

The Component Maturity Lifecycle documentation hasn't been updated in a while and our process has likely changed as the platform has matured. Review the documentation, update it and publish so that we have accurate information going into 1.0 (or soon thereafter).

## Additional information [optional]

- [ ] Remove and update this: https://github.com/18F/web-design-standards/wiki/Component-Maturity-Scale
- [ ] Then based on ^, update the blurb here: https://github.com/18F/web-design-standards/wiki/Workflow

**Comment by juliaelman** [comment]
@bradnunnally I think we can close this, no?

**Comment by bradnunnally** [comment]
@juliaelman I'll close it after the pages are taken down and properly archived.
