### ISSUE TITLE
EPA user research / q&a for blog post

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1694]
## Description

The third in our on-going series about agencies using the WDS and what they learned, want improved and how we can serve them better.

## Steps to reproduce the issue

- [x] Set up an interview time with their team (they're game, just had a vacation last time Will tried to set up meeting)
- [ ] Do interview and write up notes
- [ ] Send over to their team for feedback and their comms approval
- [ ] Send over to our team for comms approval

## Additional information [optional]

* Previous notes/questions to start with: https://docs.google.com/a/gsa.gov/document/d/1DUE2GQVz4_2b853JEgVbkGkEiIt4T01PtoOBMblsnyU/edit?usp=sharing

**Comment by yowill** [comment]
(moved back a sprint because of rescheduling)

**Comment by bradnunnally** [comment]
Blog post draft, mostly just the bullet points and placeholder text. https://docs.google.com/document/d/120pSykH4tnyQvu6eUNKPRFBXRtF6yM3Tnf0MWvXp15I/edit

**Comment by bradnunnally** [comment]
@juliaelman @shawnbot @yowill The blog draft is ready for review - https://docs.google.com/document/d/120pSykH4tnyQvu6eUNKPRFBXRtF6yM3Tnf0MWvXp15I/edit

**Comment by juliaelman** [comment]
@bradnunnally comments left!
