### ISSUE TITLE
Revise the site structure

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1709]
Based on the content audit, determine the best structure to model the website under to incorporate all the content we are merging over from the wiki.

**Comment by juliaelman** [comment]
@bradnunnally is this completed?

**Comment by bradnunnally** [comment]
@juliaelman It is not. We should flag it for the next sprint though along with other future website stuff we've been chatting about lately.

**Comment by juliaelman** [comment]
Cool - for some reason I though we had completed this. Thanks for clarifying!

**Comment by bradnunnally** [comment]
Put the initial draft together and I'm going to validate it against the content audit I performed a few sprints ago. Final draft should be ready for team review early next week.

**Comment by bradnunnally** [comment]
Proposed revised sitemap draft. Will require a review by the team and then revision based on feedback. 

![sitemap](https://cloud.githubusercontent.com/assets/12515096/25093852/db909d9a-2359-11e7-909f-8e55ae7fce79.png)

**Comment by bradnunnally** [comment]
Final revision is posted here based on feedback and collaboration with the team - https://gsa.invisionapp.com/share/35BB46989#/229329785_Sitemap
