### ISSUE TITLE
Building the video page

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1715]
After #1711, make it happen, captain.

List of videos to add to page:

## Recent Web Design Standards videos and helpful guides:
**U.S. Web Design Standards 1.0 Launch Update - January 2017**
https://www.youtube.com/watch?v=VUPbn1phbxk

**How to submit a Github issue to the Web Design Standards - December 2016**
https://www.youtube.com/watch?v=CiIcDXft8jM

**What is Github and how does it work (if you're curious)**
https://www.youtube.com/watch?v=w3jLJU7DT5E

## Previous WDS videos:
**Introducing the US Web Design Standards - October 2015**
https://www.youtube.com/watch?v=iLD4Bu6I2I8

**Introducing the Web Design Standards Part II: Developer Focused - November 2015**
https://www.youtube.com/watch?v=eMIWzj_dPvg

**Comment by juliaelman** [comment]
Done! 💥
