### ISSUE TITLE
UX communities of practice email messaging 

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1735]
## Description
As an agency with a not-a-gag comms policy who needs to get information out we need a strategy to spread the word in the streets so that people know about the WDS launch.

## Steps to reproduce the issue
- [ ] Draft a letter
- [ ] Run it by the team 
- [ ] Spread it around the world through email, fliers, carrier pigeons

**Comment by bradnunnally** [comment]
Draft letter here - https://docs.google.com/document/d/1W_Wu99YPZDIFG96wtCkLu3UiAnL6fbAaP2kl1bbZ9bc/edit

Ready for review @yowill @shawnbot @juliaelman
