### ISSUE TITLE
Content communities of practice email messaging

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1736]
## Description
As an agency with a not-a-gag comms policy who needs to get information out we need a strategy to spread the word in the streets so that people know about the WDS launch.

## Steps to reproduce the issue
- [x] Draft a letter
- [x] Run it by the team 
- [x] Spread it around the world through email, fliers, carrier pigeons

**Comment by bradnunnally** [comment]
@yowill Can the message we sent to the UX COP work for this list serv? I'm not a member so I wouldn't be able to post to it.

**Comment by yowill** [comment]
Sent!
