### ISSUE TITLE
Add documentation for Sass users who do not have access to Node

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1739]
The Standards documentation currently only outlines compilation of the Standards using Node and gulp. This solution does not include an option for those who do not have access or cannot install Node. 

And while we do provide the [compiled assets](https://standards.usa.gov/getting-started/download/), Sass is not included in these files. We should create an option for those who are wanting to use Sass, but do not have access to Node.

Thanks to @evetsreklaw who brought up this issue in our public Slack channel!

**Comment by cfuser** [comment]
Thank you for adding this.

**Comment by toolness** [comment]
To clarify, I took a look at the [slack conversation](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1488207621000050) and it seems @evetsreklaw is using Dreamweaver CC, which apparently [supports SASS natively](https://helpx.adobe.com/dreamweaver/using/css-preprocessors.html).  So our solution should be geared not merely towards folks who don't have access to node, but *also* to folks who may be uncomfortable with the command-line in general.

Would it be helpful to just include the SASS files, along with bourbon and neat, in the compiled assets ZIP file?  It seems like Bootstrap and Foundation both require the user to use node/npm if they want to do stuff with SASS, so there's not really any conventions there that we can crib from... Hmm.

**Comment by msecret** [comment]
One (probably small) danger of including the SASS in the zip, is users could think it's OK to edit those files directly, blocking themselves from future upgrades.

**Comment by toolness** [comment]
Hmm, couldn't that happen with the CSS files too, though?  I guess we could put a `README.md` in the SASS directory pointing them to our docs on how best to extend the SASS?

**Comment by evetsreklaw** [comment]
I do think having documentation is a bad idea. I am fairly certain most people understand the risks whether it is SASS, CSS, JS, etc..

**Comment by msecret** [comment]
Good points, I have no actual basis that this would be a problem, it'd be helpful to learn from actual users before worrying about this as a problem.

**Comment by evetsreklaw** [comment]
As the originator of this request, the problem is that systems are locked down as part of the normal security policy and the installation of Node is not an option in many cases. On top of that, 95% of the customization most people are doing is CSS related and access to all the SASS files is what is needed.

**Comment by msecret** [comment]
In that case, I think the best way forward is to include the SASS files in the zip file

**Comment by toolness** [comment]
Ok! I can try taking this on.
