### ISSUE TITLE
develop branch doesn't exist

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#1740]
As referenced in this file:

https://github.com/18F/web-design-standards/blob/staging/RELEASE.md

**Comment by juliaelman** [comment]
@bruffridge thank you for opening this issue and great to hear from you! We are in the midsts of updating for our new documentation and will be making this update shortly.

**Comment by juliaelman** [comment]
Just resolved! [`develop`](https://github.com/18F/web-design-standards/tree/develop) now exists and is the new default branch.
