### ISSUE TITLE
Interview Gray about Pulse and Web Performance

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1741]
## Description

Kicking off the Web Performance project, let's get the lay of the land and information about Pulse and how it works from our genius colleague @gbinal who has offered to help advise and partner with us on this.

**Comment by yowill** [comment]
Ideally if we can make this a group call for the team I think that would be best @lauraponce and it might be tough to get everyone in a room at the same time so we should try to book this as soon as possible

**Comment by lauraponce** [comment]
Scheduled for 3/9 from 3:00-4:00 EST with Gray, Will, Marco, and Shawn plus Brad and Julia as optional.

**Comment by yowill** [comment]
DONE! https://docs.google.com/document/d/1gtuY96eq-JhNwZCusenWFcckQJWodCUKOtlcID2iGts/edit
