### ISSUE TITLE
Design a place to publish Q&A Case Studies on the site

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1743]
## Description
- Should be able to house one new one a month, along with the archive, and make sense in the current site hierarchy
- And the page for what the Q&As look like

**Comment by bradnunnally** [comment]
Reviewed the designs with the team and made the recommended update to the page. The final design for the update listing and the content page for updates are:

Listing page - https://gsa.invisionapp.com/d/main#/console/10194661/222392364/preview

Content page - https://gsa.invisionapp.com/d/main#/console/10194661/222392363/preview
