### ISSUE TITLE
"Federal government websites always use a .gov or .mil domain."

### ISSUE THREAD

**Issue by fulldecent** [18F/web-design-standards#1750]
This line is mentioned on your website templates.

> Federal government websites always use a .gov or .mil domain. 

This is incorrect. The correct statement is:

> U.S. federal government websites always use a .gov or .mil domain. 

---

See a full list here: 

https://github.com/18F/web-design-standards/search?utf8=%E2%9C%93&q=%22Federal+government+websites+always+use+a+.gov+or+.mil+domain.+%22

**Comment by juliaelman** [comment]
@fulldecent thank you for you opening this issue and great timing! We are looking at removing this guidance entirely from the government style banner. You can read more about this in this comment: https://github.com/18F/web-design-standards/issues/1738#issuecomment-283181463
