### ISSUE TITLE
Mandatory standards?

### ISSUE THREAD

**Issue by WayneWhitten** [18F/web-design-standards#1755]
I have not looked at a detailed level yet, but I'm initially concerned about the following:
I'm concerned about whether these standards impose any implementation conflicts.  
I'm also concerned about whether any of them are mandatory, and whether they are noted as such.

**Comment by juliaelman** [comment]
@WayneWhitten thank you for submitting this issue! 

>I'm concerned about whether these standards impose any implementation conflicts.

Can you tell us a little bit more about your specific concerns?

> I'm also concerned about whether any of them are mandatory, and whether they are noted as such.

We had another user [post the same request in our docs repo](https://github.com/18F/web-design-standards-docs/issues/197) and will be addressing this in the coming sprint.

**Comment by WayneWhitten** [comment]
@juliaelman Again, I haven't looked at the code yet, but as a hypothetical example, would a page footer design be required?  The Social Security Administration has its own, as do most other agencies, and I'd like to know whether this would be an issue.  I think the other posting you referenced is roughly the same concern, so thanks for including that.  This really boils down to what would be considered mandatory and whether it poses any conflicts.

**Comment by juliaelman** [comment]
@WayneWhitten thank you for taking the time to clarify - much appreciated! 🎉 

I've added a comment in the original issue posted in https://github.com/18F/web-design-standards-docs/issues/197 to take your comments into consideration as we come up with solutions. Going to close this issue since the objectives are similar.

**Comment by WayneWhitten** [comment]
Thank you.  I’ll follow-up with more details if necessary as I get into the code.
