### ISSUE TITLE
Federal agencies interviews - second round

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1777]
Ongoing:

1. Continue recruiting federal agency partners who will be interviewed.

2. Schedule 30 minute interviews and include @msecret and @shawnbot to provide technical guidance in the conversation.

3. Conduct the interviews, take notes and organize notes in a clear way.

This sprint:

1. Interviews with CFPB, OPP, HHS OIG, and USAGov.

**Comment by yowill** [comment]
I think we have completed this as of Tuesday, closing!
