### ISSUE TITLE
Https Performance Guidance for Standards.usa.gov

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1789]
## Description

- [ ] Distill down our research and feedback from Eric Mill and turn it into a general guidance doc and recommendations for Gov agencies.
- [ ] Write it up, run it by team
- [ ] Publish on Standards.usa.gov web performance section of the site

**Comment by msecret** [comment]
Passed onto Eric for review.

**Comment by msecret** [comment]
Also to note: this became more about HTTP/2 guidance that HTTPS guidance as thats much more relevant to site speed.

**Comment by yowill** [comment]
@msecret Can you post a link to the content in a google doc here so we can get this copy edited and posted? CC @AndreaSigz

**Comment by yowill** [comment]
https://docs.google.com/document/u/1/d/19nb9CG9j49KRfdY6fJlV8HzEdli2K7X6MmCzvCBa4dY/edit# cc @AndreaSigz can you give this a peep for launguage/editing?

**Comment by AndreaSigz** [comment]
Sure. Just requested access
