### ISSUE TITLE
usa-button link color being overwritten when inside usa-section-dark

### ISSUE THREAD

**Issue by saracope** [18F/web-design-standards#1795]
## Description

When using the usa-button style on a link that is inside a section with the class of usa-section-dark the link color is gray instead of white because of the ordering of the styles in the css.

I was expecting the button link text to still be white, even if it is in a dark section.

## Steps to reproduce the issue

Here is an example mockup showing the issue: http://codepen.io/saracope/pen/qrVEVX

## Additional information 
Screenshot of example:
<img width="1454" alt="screen shot 2017-03-16 at 11 49 38 am" src="https://cloud.githubusercontent.com/assets/2197515/24005192/bbd206d0-0a3e-11e7-8173-4170823161fa.png">

**Comment by juliaelman** [comment]
@saracope thank you for opening this issue! I've added it to our next sprint planning to take this into consideration for our next sprint.
