### ISSUE TITLE
Detailed Research Plan

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1819]
Write up the detailed research plan for onsite user interviews and observations for the Spring Research Phase. 

Should include:

- Overview of the research and purpose
- Target users to interview
- Topics and questions
- Expected outcomes from research

**Comment by bradnunnally** [comment]
The draft is 75% of the way done and located here - https://github.com/18F/web-design-standards/wiki/research-plan-spring-2017.

Going to close this issue and create a new one to finalize this once the research effort has been approved.

**Comment by sawyerh** [comment]
@bradnunnally We've spoken to some folks on your team in the past about the design system we're building for HealthCare.gov, which is largely based on the WDS. We'd be happy to continue that conversation and answer any research questions you might have. Just throwing our hat in the ring 😄

**Comment by bradnunnally** [comment]
^ @donjo 

Thanks @sawyerh that's fantastic that ya'll are building out a design system. I'm pinging John, as he is the new design lead for the WDS. Hopefully you two get a chance to connect.
