### ISSUE TITLE
Research Recruitment Methods

### ISSUE THREAD

**Issue by bradnunnally** [18F/web-design-standards#1820]
Determine the best way to recruit users for the spring research and create the messaging. 

Goal will be to recruit 7-10 teams that are willing to meet with us in or around Washington D.C. for about an hour and half.

**Comment by bradnunnally** [comment]
Pulling this back into the backlog and remove it from the sprint. Going to bring it back one the research effort has been approved.

**Comment by donjo** [comment]
Closing this out since spring 2017 has come and gone. will establish a new issue for any future research trips/plans
