### ISSUE TITLE
Press strategies

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1829]
- [x] Come up with 5 press angles for Rob to push on
- [x] Prepare a nut graph, some stats to back it up, and a paragraph pitch on why it's important
- [x] Run by the team and finalize

**Comment by AndreaSigz** [comment]
@yowill As I'm thinking about the strategies, what is your overall goal for this press outreach? I think that will help. Thx

**Comment by yowill** [comment]
@AndreaSigz Sure, I think the general theme is what are the big wins or value delivered from this project, especially anecdotal work (I think our Q&As/case studies have some interesting info that could be used for this). This would be for Rob and GSA comms to help spread to inform more people about the WDS and the value/savings for the country.

**Comment by AndreaSigz** [comment]
Thx. Will start on it

**Comment by romkedehaan** [comment]
@AndreaSigz did you get any movement with this?

**Comment by AndreaSigz** [comment]
Yes, it's actually in #271. Want me to close that one and move the docs here?

**Comment by AndreaSigz** [comment]
@romkedehaan See my comment above.

**Comment by romkedehaan** [comment]
@AndreaSigz yes please do.

**Comment by AndreaSigz** [comment]
Moved this out of issue #271 and closed #271:
https://docs.google.com/document/d/1impxAFfaa1W22LJQZ1mc-ZohXrJjbL5hsOfqkYBNd6Y/edit#

Also, thoughts around publicizing release updates:
For each of the releases (1.1, 1.2, etc), it would be good to have a template/checklist to make sure ppl are aware of the updates each time.

For smaller releases, will need 1-2 sentences summarizing the update and next steps. Larger releases may need a few paragraphs to explain the updates.

Possible outreach points:
Blog/summary paragraph for site
Blog for 18f blog & DigitalGov (with Comms slow turnaround, maybe only do for larger releases)
Public slack channel
Internal slack channels for TTS - News, i-would-tweet-for-you
Mailing list (not sure who is on that)
DigitalGov Community of Practice Managers listserv to send to related/interested communities: open-source, web managers, mobile, social media, UX
Any other missing outlets?

**Comment by yowill** [comment]
All set on this send up the chain.
