### ISSUE TITLE
USAJobs team q&a case study

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1843]
## Description
- [x] Reach out to them to see if they're game
- [x] Set an interview date and time
- [x] Interview and take notes
- [x] Send to them for their edits/comms approval  (A future task will be created for final publishing after they return the q&a)

**Comment by bradnunnally** [comment]
Awaiting response.

**Comment by bradnunnally** [comment]
I'm going to give the USAJobs team until next week to respond, then I'll move this out of the sprint since that's a blocker for it being completed.

**Comment by bradnunnally** [comment]
Followed up about trying to get this done this week.

**Comment by bradnunnally** [comment]
Pulling this into the next sprint as we haven't heard back from the USAjobs team yet.

**Comment by donjo** [comment]
Case study has been written and sent to the USAJOBS team for review
