### ISSUE TITLE
Archive.gov q&a case study

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1845]
## Description
- [x] Reach out to them to see if they're game
- [x] Set an interview date and time
- [x] Interview and take notes
- [ ] Send to them for their edits/comms approval  (A future task will be created for final publishing after they return the q&a)

**Comment by donjo** [comment]
https://docs.google.com/document/d/11yrCDZaE0EUhFsWoPB7jZwjYXRjt8fLz30-Mdw5cZfY/edit?ts=591f537b draft here. will create new task for publishing/approval
