### ISSUE TITLE
Explain web performance in plain language

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1852]
Web performance needs to be explained and framed in plain language as a value-add that be communicated and understood by the whole team and up the chain so they know why resources should be invested and why it should be prioritized.

Research report: https://docs.google.com/document/d/1cUnFVdDi5MJxBkcq2-ueu4IVs5nZtE06fBTwAbdXqSc/edit#heading=h.7f4gck4x214a

**Comment by msecret** [comment]
This would fit in really well with our current nav structure for web performance as defined here: https://github.com/18F/web-design-standards-docs/pull/250.

It could be the first section, titled "What is web performance" or Overview or something else.

**Comment by AndreaSigz** [comment]
Here's a first pass at it:

Web Performance is the speed at which a website loads and appears in your browser when you type in the URL. A site’s performance can be good or bad. Good performance means your users can interact with your site easily, while bad performance can cause your site to not open or your users to leave without taking any action. 

Web performance is affected by many factors, such as: the speed of the network the site’s computer- or your computer- is on; the physical distance between your computer and the site’s server; how modern your computer/laptop/smart phone is. People who build and manage websites track web performance to see if they can improve the number of users completing actions on their site.

**Comment by msecret** [comment]
Thanks @AndreaSigz. I'll work on adding this to the "what" page.

**Comment by AndreaSigz** [comment]
@lauraponce I think my part in this is done.
