### ISSUE TITLE
Create language for integrating web performance into SOWs

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1853]
Government agencies need to have a template for writing web performance into the SOWs/RFPs so that they can easily build performance into the plan.

Research report: https://docs.google.com/document/d/1cUnFVdDi5MJxBkcq2-ueu4IVs5nZtE06fBTwAbdXqSc/edit#heading=h.7f4gck4x214a

**Comment by AndreaSigz** [comment]
Here's a first pass. Borrowed language from acq SOWs:

Additional Requirements:

At sprint-wise intervals, the vendor will open issues that came as the result of usability testing by end-users.

Contractor shall use US Web Design Standards.

As part of the Web Design Standards, contractor shall track web performance with a tool and clearly communicate to the government team when there is slow performance and options they have for improving the site’s performance.

Tool to track web performance shall be free of cost, track a variety of metrics, with multiple implementation options, and a useful results format.

All software code delivered under this order shall comply with the 18F open source policy in effect as of the date of award.

All software code delivered under this order shall comply with the 18F Accessibility Guidelines in effect as of the date of award.

As part of this being purchased off of the Agile Blanket Purchase Agreement (aBPA), work will be conducted in one or two-week sprints and reviewed at the end of each sprint for acceptability per the Quality Assurance Surveillance Plan (QASP).

All software code delivered under this order should be less than 10 mb total size; should complete download within 15 seconds; and should use http2.

**Comment by AndreaSigz** [comment]
Some additional thoughts from Andrew Meier via Slack:

Contractor shall establish, and ensure adherence to, a reasonable performance budget. At a minimum, pages with similar functionality in the new system shall be as performant as they are in the existing system.

Ask for skills in
>- Responsive design
>- “Mobile first” design
>- Progressive enhancement
>- Performance budgeting

**Comment by jpgsa** [comment]
Did someone say mobile? 
We created these SOW guidelines a while back when agencies started to understand mobile. However, we should collaborate on a way to update these. I think they are "valid" but not accurate and the mobile community would have some better guidelines on developer skills for mobile-first, etc.  
https://www.digitalgov.gov/resources/mobile-sow-and-developer-qualifications/

**Comment by AndreaSigz** [comment]
Per the user interview suggestion, we should add something about 'comparing to similar sites.'

**Comment by lauraponce** [comment]
@AndreaSigz how does this look for the addition?:

"The web performance of the site should meet or exceed the performance of 3-6 similar sites, and they should use a preferred tool to run the comparison."

**Comment by AndreaSigz** [comment]
@lauraponce I like it. Could we also add a few words explaining what a similar site would be?

**Comment by lauraponce** [comment]
Good suggestion @AndreaSigz. How does this sound? 

"The web performance of the site should meet or exceed the performance of 3-6 similar sites that roughly compare to what the current product is trying to accomplish. A preferred tool should be used to run the comparison."

**Comment by AndreaSigz** [comment]
Yes, @lauraponce I think this is ready to close. Thanks!
