### ISSUE TITLE
Fix sidenav so active link style doesn't change link length

### ISSUE THREAD

**Issue by romkedehaan** [18F/web-design-standards#1890]
Boldfaced active nav links tend to be longer than their unbolded (non-active) counterparts, which can cause links, when active, to possibly run over extra lines and/or move other navigation items. This can result in a jumpy navigation experience. Can we style active links in such a way that avoids the jumpiness that boldfacing can cause?

**Comment by maya** [comment]
This is the correct way it functions, a bolder text will always be longer than unbold text. The sidenav links have adequate line height and supports running to two lines.
