### ISSUE TITLE
Create sourcemap files for CSS output

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#190]
**Description**
In reference to this comment by @msecret, we should be including source maps for our CSS output. One possible solution is to create script in `./go` to create this output when building the source files.

**Comment by msecret** [comment]
We would have to compile the pattern library SASS separately from the Jekyll compilation, as mentioned in #110

**Comment by mollieru** [comment]
@maya @msecret was this resolved?

**Comment by maya** [comment]
@mollieru No, it was never done bc we would need to change our whole build process which is not in MVP for the project.

**Comment by juliaelman** [comment]
Added here via the new `gulp` workflow task by @rogeruiz! :raised_hands:
