### ISSUE TITLE
Implement recommendations from round 2 interviews

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1902]
A few recommendations came out of the round 2 user interviews, and based on the team voting, here are the things to update:

- [x] On the 'Why track performance' page, add a recommendation for what to do if someone doesn’t know which shows what the 2-5 things are that they should start with that would give the highest ROI

- [x] On the 'Web performance glossary' page, add information about mission of government agencies and include:
  1. Mobile usage statistics
  2. How the primary way citizens interact with government agencies is the web
  3. Better performance improves the user experience and guarantees services are widened more to the larger audience

Google Doc with context and full list: https://docs.google.com/a/gsa.gov/document/d/1qqIdJWHxoA4tV2fJZE46HeT5ICl1PkCnoUkjHnCy9zI/edit?usp=sharing

**Comment by romkedehaan** [comment]
@lauraponce can I get more info on this?

**Comment by yowill** [comment]
Done!
