### ISSUE TITLE
New 1.1 copy needs to updated on the homepage.

### ISSUE THREAD

**Issue by romkedehaan** [18F/web-design-standards#1914]

**Comment by AndreaSigz** [comment]
Here it is:
The Web Design Standards is a library of design guidelines and code to help government developers and designers quickly create trustworthy, accessible, and consistent digital government services.
[bullet] Release 1.1 https://standards.usa.gov/whats-new/updates/2017/04/26/fractal-federalist/
[bullet] Release 1.0 https://standards.usa.gov/whats-new/releases/#version-1-0-0

**Comment by donjo** [comment]
![screen shot 2017-05-03 at 12 36 31 pm](https://cloud.githubusercontent.com/assets/776987/25673821/4d96b248-2ffe-11e7-906f-06fa9e0092dd.png)

Talked this over with @AndreaSigz and we're going with this for now and will revisit things like the hero image and overall structure of the page in a later release.
