### ISSUE TITLE
Current navigation link padding

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#1928]
The current padding left on desktop for usa-current links is 1rem https://github.com/18F/web-design-standards/blob/develop/src/stylesheets/components/_navigation.scss#L211, but I think this value should be 1.5rem to match the left padding on navigation links here: https://github.com/18F/web-design-standards/blob/develop/src/stylesheets/components/_navigation.scss#L125. This will ensure padding is consistent on each side. Otherwise you get a little shift every time you switch pages.

## This is what it looks like:
![](http://g.recordit.co/MMX2vgwavL.gif)

**Comment by donjo** [comment]
fixed in #1971
