### ISSUE TITLE
Release production Fractal

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#1958]
Establish fractal on production. Currently it just builds on federalist for branches. This is a prerequisite to updating the component library and linking to code samples on fractal.

**Comment by donjo** [comment]
Update: releasing production fractal as a subdirectory of standards.usa.gov may not be possible for both technical federalist reasons and the rules of our ATO. Looking into the possibility of serving this content over a URL like standards-components.usa.gov

**Comment by donjo** [comment]
Will be good to go once 18f/dns#122 is merged.

**Comment by yowill** [comment]
All done!
