### ISSUE TITLE
Dropdown menus with internal links don't collapse after link is selected

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#1962]
Hello! @line47 and I were working on [methods.18f.gov](https://methods.18f.gov/) yesterday and trying to solve a problem whereby selecting a link in the header drop-down doesn't collapse the drop-down after selection. This isn't a problem when the header link is on a different page, since the page reload effectively "collapses" the drop-down, but when the link is to an internal link on the same page (e.g. `#design-studio`), the location is navigated-to by the browser but the dropdown doesn't un-collapse.

For the short term, we've implemented a hacky fix in https://github.com/18F/methods/pull/241 whereby we manually toggle `.usa-nav-primary [aria-expanded=true]` and `.usa-nav-primary [aria-hidden=false]` to re-collapse the menu on `hashchange`. However, this may be fragile going forward, so we'd rather use a more well-supported/documented solution.

Is there already a recommended fix for this that we missed?  Or can I somehow help contribute docs and/or code that would help?

**Comment by AndreaSigz** [comment]
Thanks @toolness for letting us know! @donjo or @msecret any thoughts?
