### ISSUE TITLE
Two minor typos on web performance research write-up

### ISSUE THREAD

**Issue by lauraponce** [18F/web-design-standards#1970]
On the https://standards.usa.gov/performance/research/#findings page:

- [ ] For the first pain point, "as it" should be "as is"
- [ ] For the third pain point, "team's" should be "teams"

**Comment by AndreaSigz** [comment]
@yowill do you have access to update since @donjo and @msecret are out? Thx!

**Comment by jgarber623** [comment]
@AndreaSigz Looks like this one's been taken care of and could be closed. 👍
