### ISSUE TITLE
Remove 'draft' from CBP case study?

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards#1978]
Just noticed 'draft' is all over this case study, can we remove it? Guessing it was written before draft was removed from the Standards, but published after. It's confusing to have 'draft' in there.

https://standards.usa.gov/whats-new/updates/2017/03/31/u-s-customs-and-border-patrol-case-study/

**Comment by yowill** [comment]
Remove from other places on the site if any exist
