### ISSUE TITLE
Documentation page on grids lacks example code

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#1980]
Is the [grids page](https://standards.usa.gov/components/grids/) supposed to have code examples? It shows the example rendering, but not the HTML, so I had to visit the "templates" page to find some actual code to make sure I was using it properly.

**Comment by donjo** [comment]
I think it probably should. At the very least let's start with adding a few example grid combinations to Fractal.

**Comment by toolness** [comment]
I'm closing this in favor of #2022, since that one's already assigned.
