### ISSUE TITLE
Refactor UI components in the Sketch file

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1981]
Update the following components with styles and nested symbols for consistency and ease of use:

- [x] Buttons
- [x] Alerts
- [x] Accordions
- [x] Footers 
- [x] Search bar
- [x] Side navigation
- [x] Checkboxes
- [x] Text inputs
- [x] Radio buttons
- [x] Form templates
- [x] Header 
- [x] Header menu
- [x] Mobile menu
- [x] Tables

...

**Comment by rtwell** [comment]
someone should probably review / proof my work. [here's the current version for download.](https://github.com/18F/web-design-standards/files/1225520/Components_sticker_sheet-RT-v4.sketch.zip)

**Comment by yowill** [comment]
Done!
