### ISSUE TITLE
Get Standards mentioned in GSA Today

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1983]
Send them blogs with intro text

**Comment by AndreaSigz** [comment]
Emailed Drew Jack with link to latest release and top blurb explaining why someone at GSA may be interested in learning more

**Comment by AndreaSigz** [comment]
From Drew Jack: This is what I submitted to GSA Today. We should see it in there tomorrow or Friday:

Did you know a GSA team built a library of design guidelines and code to help government quickly create trustworthy, accessible, and consistent digital government services? They are called the Web Design Standards, and they’re like LEGOs for web design: There a number of components, and it's up to you how you want to put them together. Questions? Join the public Slack channel or email the team directly at uswebdesignstandards@gsa.gov. Check out the latest release. Learn More.

**Comment by yowill** [comment]
Finished!
