### ISSUE TITLE
Publish Vets.gov case study 

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards#1986]
Vets.gov team and VA Comms gave us the thumbs up to publish.

Let me know if you want me to add the text right into this issue.

[Vets.govWDSCaseStudyv2.docx.docx](https://github.com/18F/web-design-standards/files/1088735/Vets.govWDSCaseStudyv2.docx.docx)

**Comment by AndreaSigz** [comment]
Is this live? I don't see it yet.

**Comment by donjo** [comment]
@AndreaSigz not yet, it will be included in the next docs site release which we plan to do on Monday. You can check it out on the federalist build of the dev site [here](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/develop/whats-new/updates/)
