### ISSUE TITLE
Expanding lower accordion when accordions contain lots of content is confusing

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2021]
Currently the [VA OI&T Tech Insights page](https://www.oit.va.gov/programs/techstrategies/insights.cfm) has the following accordion on it:

> ![1](https://user-images.githubusercontent.com/124687/28077001-59d6055c-662e-11e7-8a49-bfe6ee1f6ed2.png)

When the user clicks on the first accordion, they see this:

> ![2](https://user-images.githubusercontent.com/124687/28077006-63ec161c-662e-11e7-8e70-660f4d8907e8.png)

Now suppose they scroll down to the last accordion and hover their mouse over it:

> ![3](https://user-images.githubusercontent.com/124687/28077027-7c883afc-662e-11e7-9cd5-e9c15bebb47a.png)

They click, and now they see this:

> ![4](https://user-images.githubusercontent.com/124687/28077033-834fb536-662e-11e7-9fbd-e1b26af77c29.png)

**That's really confusing.** The viewport is now focused at the _bottom_ of the newly-expanded accordion's content.  The user has to manually scroll up the entire length of the accordion's content to see the beginning of it:

> ![5](https://user-images.githubusercontent.com/124687/28077083-b39d1c1a-662e-11e7-8d0c-61338c00d9a3.png)

I think this may be happening because the first accordion is auto-collapsed at the same time that the last accordion is expanded. I'm guessing we could probably easily fix this by just calling [`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) on the accordion button that's just been clicked.

**Comment by toolness** [comment]
Note that this problem doesn't occur with accordions that aren't in the same auto-collapsing group. For example, on the standards site, every example has a "code" and "documentation" accordion, but expanding one doesn't collapse the other, so this bug doesn't occur on them.

**Comment by evetsreklaw** [comment]
Interesting. As you noted, adding aria-multiselectable="true" resolves the issue. Definitely needs to be addressed in the standard accordion.

**Comment by msecret** [comment]
That's great to hear that `aria-multiselectable` actually fixes this. Maybe the fix for this would be to include that property in the HTML documentation?

**Comment by evetsreklaw** [comment]
It is part of the 1.2 update which is why I knew about it, but using the single select, basic version should not have this problem. Focus should be reset to the top of the newly opened panel.   Reference : https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards/develop/components/detail/accordion--multiselectable.html

**Comment by toolness** [comment]
@msecret that's a potential fix, but it means that it'll be impossible/unsupported to create accordions that aren't multi-selectable (i.e., which allow only one accordion to be expanded at a time).  If we do that, we might want to also remove any JS that deals with non-multiselectable accordions. Unless there is a clear UX argument to why non-multiselectable accordions shouldn't be allowed though, it seems like we ought to continue supporting that use case, but make it more usable by fixing this bug...

@donjo do you have any thoughts on the UX of this?

**Comment by toolness** [comment]
I've implemented a potential fix for this in #2025, which you can play around with on the federalist build of that branch's fractal site. See the PR for more details on how to do this.
