### ISSUE TITLE
Start set up for AMA slack chat

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#2044]

**Comment by AndreaSigz** [comment]
- [ ] Sent out calendar invite for team members

- [ ] Create & share with team background doc for AMA flow

- [ ] If consensus on time/date, will publicize in USWDS, general talk Slack channel, listservs, 18f & DG.gov Twitter, GSA Today newsletter

**Comment by AndreaSigz** [comment]
Here's a logistical doc for the AMA: https://docs.google.com/document/d/1Ir_FSeQFcFVqVAKb3SUS74WUhZoBDSvMpRKdqtA8yPo/edit#
Take a look and let me know any issues/questions

**Comment by yowill** [comment]
Done! Great job!

**Comment by AndreaSigz** [comment]
Chat happened on Friday (7/28)! Closing and will start new issue for after-event doc
