### ISSUE TITLE
Decide our percentage of users threshold for browser support

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#2071]
## Description

In order for our browser support to stay up to date with current browser usage, we should pick a threshold where we decide to stop supporting a browser if it goes below a certain percentage. The percentage will be taken from https://analytics.usa.gov/.

**Comment by toolness** [comment]
Related: it looks like [the UK Government's official threshold is 2%](https://gds.blog.gov.uk/2012/01/25/support-for-browsers/).

**Comment by msecret** [comment]
Here's my proposed solution:

I think we should go with the **2% threshold**, taking cues from UK Gov. They're standards is something we've followed before and is generally well researched and trusted.

Going below 2% would also mean we have to support browser's we don't even currently support, and browsers that we don't have data on, and are not commonly supported in web development.

![screen shot 2017-08-28 at 2 39 40 pm](https://user-images.githubusercontent.com/1701077/29794760-3fbbe394-8bfe-11e7-9a56-1ed196014b00.png)

As per the screenshot, going below 2% means we'd have to support IE7, which we don't currently do, meaning we'd have to go back and fix issues. We'd also have to support unknown things like Android Webview, which we don't know anything about.

We should change our documentation on https://standards.usa.gov/getting-started/developers/ to reflect this decision. The documentation should not longer be about which browsers but about the percentage value of 2%.

**Comment by donjo** [comment]
I like this proposal. Would this go into effect with 2.0 or something that we'd start immediately? Like could we tell users in the future "if you need support for IE9, use USWDS 1.3.1 or earlier"

**Comment by msecret** [comment]
I'd go into effect with some release, it should probably be a major release if it'd cause breaking changes.

**Comment by toolness** [comment]
Nice, I like it!

Should we also mention that PRs to add support for < 2% browsers are welcome?  That way if some team *really* needs IE9 support, they could add it to the standards themselves... Though we'd be under no obligation to continue ensuring that our own contributions didn't break that, I suppose.

Anyways, it's an unlikely situation regardless. I like the 2% threshold.

**Comment by yowill** [comment]
Just caught up reading all this -- this seems solid. Let's do it.

**Comment by yowill** [comment]
Done
