### ISSUE TITLE
Header submenu bar (sub-navigation) too tall

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#2072]
Looks like a visual regression.
https://standards.usa.gov/components/headers/extended/

### Current
<img width="1139" alt="screen shot 2017-07-28 at 5 47 36 pm" src="https://user-images.githubusercontent.com/5249443/28740734-6a5736b6-73bd-11e7-858f-ae408c06a63a.png">

### Expected

<img width="836" alt="screen shot 2017-07-28 at 5 50 47 pm" src="https://user-images.githubusercontent.com/5249443/28740729-60fc38aa-73bd-11e7-9cb1-42226fbc468c.png">

**Comment by toolness** [comment]
Good catch! It seems like this may have been introduced with 157b6557bbd7868da50b7e53490c35b4fb8f7d6a, which was part of #2026. The following patch seems to fix it on my end:

```diff
diff --git a/src/stylesheets/components/_header.scss b/src/stylesheets/components/_header.scss
index 0a46c42e..cdc6a827 100644
--- a/src/stylesheets/components/_header.scss
+++ b/src/stylesheets/components/_header.scss
@@ -193,7 +193,7 @@ $z-index-nav:     9000;
       &[aria-expanded=false],
       &[aria-expanded=true] { /* stylelint-disable-line selector-no-qualifying-type */
         @include media($nav-width) { /* stylelint-disable-line selector-no-qualifying-type */
-          background-position: right 1.5rem top 44%;
+          background-position: right 1.5rem top 50%;
         }
       }
     }
diff --git a/src/stylesheets/components/_navigation.scss b/src/stylesheets/components/_navigation.scss
index 0afe7700..35bb1d7d 100644
--- a/src/stylesheets/components/_navigation.scss
+++ b/src/stylesheets/components/_navigation.scss
@@ -159,7 +159,7 @@
     padding: 1.4rem 1.5rem 1rem 1.8rem;
 
     @include media($nav-width) {
-      @include padding(null 3rem 3rem 1.5rem);
+      @include padding(null 3rem 1.9rem 1.5rem);
       color: $color-gray;
       font-size: $h5-font-size;
       font-weight: $font-bold;
```

However, that patch just reverts some of the changes made in the aforementioned commit. I'm sure @msecret had a reason for changing those values in the first place, so I am guessing that this patch just fixes the regression while breaking something else... @msecret do you have any thoughts on this one?
