### ISSUE TITLE
checkbox + radio button style updates

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2082]

**Comment by rtwell** [comment]
### Checkboxes
- [ ] Border radius `2px`
- [ ] Overall spacing consistency
- [ ] Disabled checkbox should be `border: gray-light #aeb0b5, background: gray-lightest #f1f1f1`
- [ ] Disabled state text should be `gray-lighter #d6d7d9`
![image](https://user-images.githubusercontent.com/12564977/29527000-0d8c0f12-865d-11e7-8c3b-258a0a4581aa.png)

**Comment by rtwell** [comment]
### Radio buttons
- [ ] Button should be `20px square`
- [ ] Overall spacing consistency
![image](https://user-images.githubusercontent.com/12564977/29527172-b34df01e-865d-11e7-9831-5f6a499dd0ee.png)
