### ISSUE TITLE
footer design updates

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2087]

**Comment by rtwell** [comment]
## Slim footer
- [ ] link for "info@agency.gov" should be `base`
- [ ] Overall spacing is more compact
- [ ] Return to top receives an underline
![image](https://user-images.githubusercontent.com/12564977/29522676-a39bf9a8-864f-11e7-8e2f-724efd3a3aeb.png)

**Comment by rtwell** [comment]
### Medium footer
- [ ] link for "info@agency.gov" should be `base` (currently not meeting contrast requirements as primary blue
- [ ] circle for agency logo is smaller (82px or 1 col + 1 gutter)
- [ ] Agency name scoots to the right of the logo
- [ ] Agency contact info changes from a stacked design to side-by-side,
![image](https://user-images.githubusercontent.com/12564977/29522791-227e3a1a-8650-11e7-8f77-7995021e3fcb.png)

**Comment by rtwell** [comment]
### Large footer
- [ ]  link for "info@agency.gov" should be `base` (currently not meeting contrast requirements as primary blue)
- [ ] Overall spacing—elements should align to our grid
- [ ] Footer links are `15px (1.5 rem)`
![image](https://user-images.githubusercontent.com/12564977/29523099-70146bae-8651-11e7-8d47-e32099d9c35b.png)

**Comment by rtwell** [comment]
### Mobile footer
#### Slim
- [ ] Overall spacing adjustments
- [ ] Return to top gets an underline
- [ ] Agency contact information does not stack
![image](https://user-images.githubusercontent.com/12564977/29523771-b1099c0e-8653-11e7-8179-b3fce8966d92.png)


#### Medium
- [ ] Overall spacing adjustments
- [ ] Return to top gets an underline
- [ ] Agency logo scales down to a `1 col` width
- [ ] Agency contact information does not stack
![image](https://user-images.githubusercontent.com/12564977/29523696-796d9b88-8653-11e7-99b9-01f66ce85b22.png)


#### Large
- [ ] Overall spacing adjustments
- [ ] Return to top gets an underline
- [ ] Agency logo scales down to a `1 col` width
- [ ] Agency contact information does not stack
- [ ] Secondary links should be `15px`
![image](https://user-images.githubusercontent.com/12564977/29523900-03dea758-8654-11e7-9d2b-95c7b0083bcc.png)
