### ISSUE TITLE
Publish USA.gov case study

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards#2102]
Related to issue 1842

- [x] Final updates received from USA.gov team

- [x] Adding URL of doc in below comment for publishing

- [ ] Publish on News & Updates page: https://standards.usa.gov/whats-new/updates/

**Comment by AndreaSigz** [comment]
https://docs.google.com/document/d/1n-UvXa1pMGnZMQ6O1t0SdO0EimtEv0a4eEpHcPeftes/edit#

**Comment by donjo** [comment]
done!

**Comment by donjo** [comment]
wait, not done. thinking of the wrong thing

**Comment by AndreaSigz** [comment]
This is the last one that didn't publish yet.
