### ISSUE TITLE
Cull down / update typography

### ISSUE THREAD

**Issue by rtwell** [18F/web-design-standards#2106]
We offer too many type choices and pairings, which lead to more design confusion than help. I'd suggest the following changes:
## 1) Pairings and styles:
Delete the **Robust** version. Remove the **Lite** descriptor
![image](https://user-images.githubusercontent.com/12564977/29320817-0885be1e-819e-11e7-9596-4796c60d5032.png)

### A) the fonts offered should be listed as:
```
1. Merriweather Regular 400
2. Merriweather Bold 700
3. Source Sans Pro Regular 400
4. Source Sans Pro Italic 400
```
### B) Delete bullets on all these lists:
![image](https://user-images.githubusercontent.com/12564977/29322668-e6e3f6a8-81a3-11e7-83bf-08098b4765ee.png)

## 3) Update _Merriweather headings and body_
Update "**Merriweather headings and body**" to be _solely Merriweather_ (we snuck Source Sans in as an H6). Fewer fonts to upload, increasing performance, and will now be consistent with the title, meeting expectations. 
### A) Update the accordion on the [docs site](https://standards.usa.gov/components/typography/)
![image](https://user-images.githubusercontent.com/12564977/29321009-b0893398-819e-11e7-83c7-34c94c546e37.png)

### B) Change the H6 _in this pairing_:
**current is** 
![image](https://user-images.githubusercontent.com/12564977/29321253-72d19198-819f-11e7-9e7e-87ed1f2ba00f.png)
**change to** 
![image](https://user-images.githubusercontent.com/12564977/29321355-cef9c92c-819f-11e7-9bc2-8f300ab5b4de.png)
#### snippet here:
```
font-family: ‘Merriweather’
font-weight: 400
font-size: 10px
line-height: 1.5em/15px
text-transform: uppercase
```
### A) Remove the _Display 2_ Header
![image](https://user-images.githubusercontent.com/12564977/29321579-7d282c78-81a0-11e7-82e8-08e9091eabae.png)
### B) Change the Lead paragraph to Source Sans Regular:
![image](https://user-images.githubusercontent.com/12564977/29321954-9fc74150-81a1-11e7-9a46-5855ceb861ba.png)
### C) Update the font listing for this pair:
![image](https://user-images.githubusercontent.com/12564977/29322126-0fdf7d0e-81a2-11e7-81d2-e589a6ce09bf.png)
snippet:
```
1. Source Sans Pro, Regular 400
2. Source Sans Pro, Bold 700
3. Merriweather, Regular 400
4. Merriweather, Italic 400
```

**Comment by msecret** [comment]
This all looks reasonable to me
