### ISSUE TITLE
USDA is listed twice in WHO_IS_USING_USWDS.md

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2109]
It looks like "Department of Agriculture" links to usda.gov, while "USDA.gov" links to a blog post on usda.gov titled [A Complete Redesign with You in Mind](https://www.usda.gov/media/blog/2017/03/06/complete-redesign-you-mind).

@AndreaSigz which of these do you think we should keep?  I think the blog post might be more useful because it's on usda.gov already, and through it readers can potentially learn more about the process the USDA used to adopt the standards.

Can you make a decision and issue a PR that removes one of them?

**Comment by AndreaSigz** [comment]
Hey @toolness It looks like this page isn't consistent on style-has sites listed by URL and by name of site. It would be better to pick one style. I think the URL would be better, but let me know if you feel differently.
If we go with that style (and update the rest of the page), then I think we should remove 'Department of Agriculture' and link USDA.gov to the site usda.gov
What do you think?

**Comment by toolness** [comment]
Hmm, good question... I can think of two potential issues with showing only the URL:

1. Sometimes, for more minor projects, the URL might be long, and just the domain part of the URL might not be very informative. For example, the NASA web style guide is at https://company-76458.frontify.com/d/NZPXDvjOcz5x/nasa-web-style-guide, and "company-76458.frontify.com" isn't very useful.

2. Even if a URL is short, it can still be uninformative for folks who aren't "in the know"--for instance, if someone doesn't know that USDA stands for "U.S. Department of Agriculture", then the domain name may be less helpful than the full name of the agency.

What do you think of maybe putting the full name of the site, followed by the domain name in parentheses if it's short/memorable?  So the USDA site might read as:

> * [Department of Agriculture (usda.gov)](https://usda.gov/)

But the NASA web style guide would just be:

> * [NASA Web Style Guide](https://company-76458.frontify.com/d/NZPXDvjOcz5x/nasa-web-style-guide)

since the domain name for that one isn't helpful?

**Comment by AndreaSigz** [comment]
Yeah, I like that combo. Should I copy/paste the updates into a comment below—or the entire list?

**Comment by toolness** [comment]
Woot! would it be easier for you to edit the `WHO_IS_USING_USWDS.md` file and issue a pull request?

**Comment by AndreaSigz** [comment]
Haha, yes

**Comment by AndreaSigz** [comment]
This is related to #2134, so closing
