### ISSUE TITLE
Some sites in WHO_IS_USING_USWDS.md are 404s

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2110]
The following sites were found by the [uswds-crawler](https://github.com/18F/uswds-crawler) to be 404s (or, in some cases, their hostnames are no longer valid):

> WARNING: Fetching EPA e-manifest form (https://e-manifest.18f.gov/) errored with Error: getaddrinfo ENOTFOUND e-manifest.18f.gov e-manifest.18f.gov:443
WARNING: Fetching National Week of Making (https://weekofmaking.pif.gov/) errored with Error: getaddrinfo ENOTFOUND weekofmaking.pif.gov weekofmaking.pif.gov:443
WARNING: Fetching GSA Presents: Grace Hopper Day Hackathon! (http://open.gsa.gov/grace-hopper-hackathon/) failed with HTTP 404
WARNING: Fetching OGP Payroll Reporting (https://pages.18f.gov/ogp-payroll/) failed with HTTP 404
WARNING: Fetching One page open source (https://pages.18f.gov/onepage-opensource/) failed with HTTP 404
WARNING: Fetching USDA School Meal Application (http://www.fns.usda.gov/school-meals/web-based-prototype/docs/index.html#/) failed with HTTP 404
WARNING: Fetching Climate Labs (https://federalist.18f.gov/preview/18f/climate-labs/microsite/) failed with HTTP 404

@AndreaSigz do you think we should make some effort to find out if these sites have been moved to a different location, or should we just remove them entirely?

**Comment by AndreaSigz** [comment]
@toolness yeah, I'll see if I can find out where these went/why they are getting 404s

**Comment by AndreaSigz** [comment]
@toolness I reached out to Alex Bisker to see if she knew where the 18F sites went, but haven't heard back. Could you ping her?

**Comment by AndreaSigz** [comment]
Didn't hear back from Alex, but I created a first pass at a new order for the list (in #2134). We can close this one.
