### ISSUE TITLE
Visual changes research

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#2135]
Figure out the categories of things to look at (grids, typescale, etc.)

**Comment by rtwell** [comment]
after talking with @msecret we've decided to research a couple topics/issues:
- [ ] @msecret will research how we might improve the WDS grid:
1) make the grid more flexible
2) rethink our breakpoints (esp the outlier 951px for the nav) and make a univeral set of breakpoints
3) reach out the design / engineering communities and see what kind of functionality they might want for the grid
- [ ] Explore what a typescale might look like for the WDS

**Comment by msecret** [comment]
Researched finished here: https://github.com/18F/web-design-standards/issues/2137

**Comment by yowill** [comment]
Done!
