### ISSUE TITLE
Question:  Where do I find instructions/how to with regard to form validation within uswds.js

### ISSUE THREAD

**Issue by njohnson** [18F/web-design-standards#2138]
I  would like to utilize any default client-side form validation that uswds.js provides. I am struggling to find any info on this. 

Can you point me to good form validation? 

Thank you

**Comment by toolness** [comment]
Thanks for contacting us @njohnson! Currently, the standards don't provide much client-side form validation. The closest thing we have to it is this validation component, which is largely used for providing user feedback on different requirements for passwords and such:

https://standards.usa.gov/components/form-controls/#validation

It should be noted that the component is only really useful for providing feedback, in the form of check-marks, to a validation criteria. It doesn't actually prevent the user from submitting the form with invalid input or anything like that.

Aside from that, we have *styling* for what invalid input and error messages should look like visually, e.g. in the [text input section](https://standards.usa.gov/components/form-controls/#text-input), but we don't currently provide any actual client-side logic to make such feedback appear.

**Comment by njohnson** [comment]
Thank you.

Does your company recommend a good accessible validation package?

I have used both https://jqueryvalidation.org/ and
https://github.com/ericelliott/h5Validate    both are based on HTML5
required with customization.

They can be made accessible but wondering if you know of a better tool.

Nancy

**Comment by maya** [comment]
Hi @njohnson, unfortunately we don't have any recommendations for a good accessible validation package, but feel free to let us know if you find one! Closing this as @toolness provided an answer to your initial question.
