### ISSUE TITLE
Link to "18F Code of Conduct" is broken

### ISSUE THREAD

**Issue by danoc** [18F/web-design-standards#2140]
Hello, the link to 18F Code of Conduct is broken in the `CONTRIBUTING.md` file:

https://github.com/18F/web-design-standards/blob/53104f1e4f01004eb72c3da492e945a321e1a9c7/CONTRIBUTING.md#L5

It appears on [`/getting-started/code-guidelines/`](https://standards.usa.gov/getting-started/code-guidelines/).

The broken link is:
https://18f.gsa.gov/code-of-conduct/

**Comment by maya** [comment]
Hi, thanks for opening this issue. This issue is being worked on and should be fixed soon.

**Comment by maya** [comment]
Fixed in https://github.com/18F/18f.gsa.gov/pull/2573. Thanks @danoc!
