### ISSUE TITLE
Fix big button

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#2144]

**Comment by thisisdano** [comment]
@donjo if you can drop a little issue info in here I can take a crack at this

**Comment by donjo** [comment]
I think for this one the idea was to increase the default horizontal padding a bit more on the big button to better differentiate the look and feel from the default buttons. It could probably go from `3rem` to `5rem` or whatever you think feels right.

**Comment by maya** [comment]
Since we have designs from Ryan already, maybe should use that to guide this.
