### ISSUE TITLE
Adjust focus on radio buttons

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#2145]

**Comment by thisisdano** [comment]
@donjo if you can drop some issue context in here I can try to take a crack at this, too.

**Comment by donjo** [comment]
I don't have a mock for this but the idea was to bump the focus outline out by about a pixel on these. The default works well for square things but for something circular like the focus button it creates a square that goes right up against the edge of the radio button circle. It's not a huge deal if the mysteries of CSS make this difficult to achieve but a bit of space between the element and the outline could make it more noticeable.

**Comment by maya** [comment]
Also, as a note, when we used the box-shadow property, the focus was a circle, but outline used now can only do squares.
