### ISSUE TITLE
[Markdown]: Alternative to chjj/marked or take it on via copy + new repo?

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#2149]
## Description

I have a problem. [chjj/marked](https://github.com/chjj/marked) doesn't seem to be maintained any longer, it has a security vulnerability, and a solution. It is used for many client-side Markdown editors. We are wanting to use [sparksuite/simplemde-markdown-editor](https://github.com/sparksuite/simplemde-markdown-editor) for my project.

The fix is actually in place: https://github.com/chjj/marked/pull/844/files - and available on `master`.

However, the latest release 3.6, was released in July 2016 - hope everyone on the project is okay.

See also: https://snyk.io/blog/marked-xss-vulnerability/

## Proposal

1. All I really have on this score is to grab master and make a new 18F or GSA repository and start maintaining it primarily for Federal use and open to the community.
2. Figure out a way to get in touch with the listed owners or the repository.
3. ...something else??

@colinalford-gsa

**Comment by AndreaSigz** [comment]
Thanks @joshbruce for letting us know. @donjo any thoughts?

**Comment by joshbruce** [comment]
I went ahead and made these, but for my program, it would probably easier if GSA did something there, you know?

https://github.com/8fold/marked
https://github.com/8fold/simplemde-markdown-editor

**Comment by maya** [comment]
Hi @joshbruce, glad you resolved this issue. Our team isn't clear how a markdown editor fits into the scope of the Standards. Closing this issue for now.

**Comment by joshbruce** [comment]
@maya: No worries.

For what's it worth, I wasn't thinking of the standards on this one. :)

Instead, thinking Federal Government in general. GSA specifically as GSA IAE uses it. But the program may not feel comfortable taking it on. Might be something worth adding to the 18f suite of federal tech.

**Comment by colinalford-gsa** [comment]
@joshbruce 
Heh, this problem is so widespread, it is included in this video about the worst flaws in Javascript:
https://www.youtube.com/watch?v=0dgmeTy7X3I&feature=youtu.be&t=8m10s

**Comment by joshbruce** [comment]
@colinalford-gsa: Nice. That's another reason I'm wary about JS being used for *everything*; especially data entry on the user side.

Given the Government's security requirements, the use of rich text editors for those who don't "write code", and the universal nature of plain text (a la Markdown) I really do think the Government would be well served (and maybe serve the greater community) by taking something like this on.
