### ISSUE TITLE
Change ID Names to match

### ISSUE THREAD

**Issue by jgacuca567** [18F/web-design-standards#2150]
Under the Headers link https://standards.usa.gov/components/headers/ in the code section, 

change the ul id to be either `side-nav-1` or `side-nav1`, as you are using both types. 

See screenshot. 

<img width="1634" alt="screen shot 2017-09-25 at 6 25 19 pm" src="https://user-images.githubusercontent.com/4000076/30833934-06e17c5a-a21f-11e7-863b-2e04e2c1be09.png">

**Comment by AndreaSigz** [comment]
Thanks @jgacuca567 for the info. @donjo any thoughts?
