### ISSUE TITLE
Headers with "mega-menu" on fractal site non-functional

### ISSUE THREAD

**Issue by JJFranko** [18F/web-design-standards#2157]
See the Fractal components page: https://components.standards.usa.gov/components/detail/header--default.html 

## The header menus for the styles with Mega Menus are fully displayed when resizing the display window so that it invokes the "@media screen and (min-width: 951px)" rule.

When the display size is smaller and the menu resizes to its blue button on the top right, the two mega-menu styles show all the menu links and the "+" and "-" toggles to expand/contract sections don't work.

The Basic and Extended appear OK, but Basic with Mega Menu and Extended with Mega Menu are not working as intended. Occurs on individual  "mega-menu"demo pages but all four smaller menus available  under the blue button on the compare page (https://components.standards.usa.gov/components/detail/header--default.html ) are exhibiting same display-all behavior at smaller width.

**Comment by maya** [comment]
Thanks for letting us know @JJFranko, we're taking a look and will work on a fix ASAP.
