### ISSUE TITLE
[Side navigation]: Hover state

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#2162]
The side navigation used to have a light gray background color on hover but I noticed it's not there anymore. So it's just the text color changing to blue. Was this an intentional design decision?

## Before: 
<img width="249" alt="screen shot 2017-10-04 at 4 11 49 pm" src="https://user-images.githubusercontent.com/5249443/31204138-3bb73882-a91f-11e7-9ff8-f5a0e8b051e7.png">

## Now:
<img width="242" alt="screen shot 2017-10-04 at 4 16 05 pm" src="https://user-images.githubusercontent.com/5249443/31204156-5c7d632a-a91f-11e7-833d-87de692ec732.png">

/cc @donjo @thisisdano

**Comment by donjo** [comment]
I checked with Ryan this morning and they are ok to still have the grey hover states (the old way) so any change to how it is now must have been unintentional 👍

**Comment by maya** [comment]
Fixed in #2161.
