### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards#2174]
## [Zoom issue]: This was from an email to the Google group on Sept 14, that hasn't been followed up on:

I was wondering if there is a fix to the USWDS to address the 'Here's how you know' link from covering the text of 'This is an offical...' text as seen below in the screenshot, when at 500% zoom inside Chrome or 425% while in IE? Any help would be greatly appreciated.

[Pasted Image below]

And from @toolness: regarding use cases for 500% zoom--some folks w/ visual impairments need to zoom-in that much to read the text, and prefer not to use a screen-reader, so we ought to make sure that things are still readable at that size, even if they don't look that great...

![pastedimage](https://user-images.githubusercontent.com/7216264/31454250-d6d9f6b6-ae82-11e7-8fbc-78de8fd04491.png)

**Comment by maya** [comment]
The WCAG requirement is a zoom level of 200% per https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html, so we've met the standard. If there is a high use case for this, feel free to describe it. Closing for now.
