### ISSUE TITLE
[Hero]: Hero component not consistent

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#2176]
There are inconsistencies between the hero component on the homepage, landing page template, and fractal component as the style changes made to the homepage were not scoped to just the homepage and spilled out to the docs site, but weren't implemented on the actual uswds codebase. It's not clear whether the homepage hero component was meant to also be the actual component or not.

## TODO

What's the visual direction we want to go with?

### 1. Home page - https://standards.usa.gov/
<img width="1156" alt="screen shot 2017-10-12 at 9 00 21 am" src="https://user-images.githubusercontent.com/5249443/31506416-3693beee-af2c-11e7-952f-795b3e28f1a7.png">

### 2. Landing page template (docs site) - https://standards.usa.gov/page-templates/landing/
<img width="1156" alt="screen shot 2017-10-12 at 9 01 52 am" src="https://user-images.githubusercontent.com/5249443/31506408-3332c66e-af2c-11e7-8911-f92af44f1d34.png">

### 3. Fractal (actual component) - https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards/develop/components/preview/hero.html
<img width="1136" alt="screen shot 2017-10-12 at 9 00 52 am" src="https://user-images.githubusercontent.com/5249443/31506405-2eaee92e-af2c-11e7-80a0-5e0f19e515c1.png">

/cc @rtwell Do you have any context?

**Comment by bruffridge** [comment]
I was just going to open this bug. The biggest issue is the white button text on white background!

https://standards.usa.gov/page-templates/landing/

**Comment by rtwell** [comment]
Never seen this, or designed that—and i'm no longer on that project, sorry!

On Thu, Oct 12, 2017 at 1:07 PM, Brandon Ruffridge <notifications@github.com

**Comment by maya** [comment]
My bad @rtwell, I thought you designed the new homepage hero.

@bruffridge yep, there's a PR open for that issue: #2175.
