### ISSUE TITLE
Extended header and basic header different underline sizes

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#2177]
Not sure if this was intentional or not, but noticed that the extended header and basic header have different underline sizes on the menu items.
<img width="935" alt="screen shot 2017-10-12 at 2 11 09 pm" src="https://user-images.githubusercontent.com/1322063/31512043-99ee21de-af57-11e7-8c15-0781fee92f9d.png">

**Comment by maya** [comment]
Hi @bruffridge, yes that was an intention design decision. Closing this out for now.
