### ISSUE TITLE
Date input: "pattern" attribute not needed

### ISSUE THREAD

**Issue by sawyerh** [18F/web-design-standards#2200]
The [Date input pattern](https://standards.usa.gov/components/form-controls/#date-input) in the documentation includes a `pattern` attribute on the month/day/year fields, however this attribute is ignored when the `type` attribute is `number`.

Sources:

- https://www.w3.org/TR/html5/forms.html#do-not-apply
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

In the past, using a `pattern` attribute on a `text` input field was a hack to get touch devices to display a number keyboard, so it's possible this is a leftover from then.

**Comment by maya** [comment]
The pattern is also doing some validation (I wrapped it in a form element and added a submit button to test this):
<img width="316" alt="screen shot 2017-10-30 at 1 15 16 pm" src="https://user-images.githubusercontent.com/5249443/32193431-7c9fee02-bd74-11e7-8a07-9d895f87382d.png">
<img width="379" alt="screen shot 2017-10-30 at 1 15 26 pm" src="https://user-images.githubusercontent.com/5249443/32193432-7cbffe40-bd74-11e7-96c0-e82d6630e84c.png">
<img width="503" alt="screen shot 2017-10-30 at 1 15 34 pm" src="https://user-images.githubusercontent.com/5249443/32193434-7cdf7964-bd74-11e7-8f37-e3e11c7fe75c.png">

Wouldn't this be valuable?

**Comment by sawyerh** [comment]
@maya Those particular validation messages are due to the `min` and `max` attributes. Removing the `pattern` attribute would still result in that validation occurring. I agree the validation is nice and definitely don't want to get rid of that functionality 😄

**Comment by maya** [comment]
Ah, that's right! 😅 Sounds good, we can remove the pattern attribute.
