### ISSUE TITLE
Adjust vertical padding in footer component

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2209]
According to the latest homepage designs the footer content should have a bit more padding at the top and bottom. It's currently set to `2rem` via the `$spacing-medium` variable and should be bumped up to 4rem via a yet-to-be-added `$spacing-x-large` variable, at least in the full screen desktop view. 

![screen shot 2017-11-06 at 5 14 31 pm](https://user-images.githubusercontent.com/776987/32468941-fe899f7a-c315-11e7-8d4e-370c0e7c95a3.png)

**Comment by maya** [comment]
Yep, they can be increased: the designs show 3rem top and 4rem bottom padding.

**Comment by maya** [comment]
Is this meant for the docs repo?

**Comment by donjo** [comment]
@maya you're right. Upon further inspection, the actual footer component doesn't need this adjustment because the components inside the footer have their own padding (adding to the footer's padding) so this style should be an override for the custom footer the docs site uses. I'll close this in favor of a docs site issue.
