### ISSUE TITLE
Add Style Guide section in wiki

### ISSUE THREAD

**Issue by AndreaSigz** [18F/web-design-standards#2218]
Add Style Guide section in wiki with item stating the Standards is singular, and any other branding language

**Comment by maya** [comment]
I think the this is how we've referred to it...

When referring to it as a project, it's singular: "The U.S. Web Design Standards is a project," "The U.S. Web Design Standards is a design system" 

When it's abbreviated to "the Standards" meaning a set of standards people should follow, it's plural. 
"The Standards are something to follow."

**Comment by AndreaSigz** [comment]
Thanks @maya! And are ppl going to talk about them as "the Standards" or "the Web Design Standards"?
Also, is this a moment to revisit renaming?

**Comment by maya** [comment]
We've primarily referred to them as the "U.S. Web Design Standards" (full name) and "the Standards" (abbreviated), but not the "Web Design Standards." However, folks may end up calling it many things! I don't think it's the time to revisit re-naming yet, but maybe during the roadmapping workshop.

**Comment by AndreaSigz** [comment]
Totally, that's what I was thinking. Wasn't meaning today :)

Updating the page

**Comment by maya** [comment]
This is done correct?

**Comment by AndreaSigz** [comment]
Yes!
