### ISSUE TITLE
usa-banner content overlaps with banner-button on small screens

### ISSUE THREAD

**Issue by adborden** [18F/web-design-standards#2221]
## Description

I'm seeing this at about 333px. It looks like the screen gets small enough that the content wraps, which overlaps the banner-button. I would expect the wrapped content to pus the banner button down and for the banner container to fit them both.

## Steps to reproduce the issue

1. Open https://standards.usa.gov/
2. Shrink the window down to ~330px

![screenshot from 2017-11-08 14-40-52](https://user-images.githubusercontent.com/509703/32578729-2f421e3e-c493-11e7-9cd2-80d85112231a.png)

**Comment by maya** [comment]
Hi @adborden, thanks for opening this issue. I'm not seeing quite the same thing at 333px. It looks like it's working at 320px or small iPhone sizes.
<img width="410" alt="screen shot 2017-11-09 at 9 09 19 am" src="https://user-images.githubusercontent.com/5249443/32618857-bde553f0-c52d-11e7-859a-34437649f7e8.png">

It's when I go below 320px it start to wrap like that. What devices are you trying to support?

**Comment by adborden** [comment]
Hmm, maybe I was mistaken about the width. It looks like it's happening at 319px. If it works at 320px, then that is good enough for me. Thanks!
