### ISSUE TITLE
[Small screen navigation links overlap close button]: When the first link in the nav does not contain subnav links the close button for the off canvas overlaps the first link.   

### ISSUE THREAD

**Issue by line47** [18F/web-design-standards#2222]
## Description

When viewing the navigation for smaller screens the first link in the navigation overlaps the close button in the menu when it is just a single link and not a dropdown. However if the first link is a dropdown - as seen on the [extended header components page](https://components.standards.usa.gov/components/detail/header--extended.html) this is not an issue. 

## Steps to reproduce the issue

1. Go to the [extended header components page](https://components.standards.usa.gov/components/detail/header--extended.html) 
2. Move the single link `li` from the bottom of the list to the top
3. You will see the first link and the navigation close button are now overlapping. 

### Screenshots 
![screen shot 2017-11-09 at 10 07 44 am](https://user-images.githubusercontent.com/1449852/32612883-67c17f8a-c537-11e7-9444-e40355409ac7.png)

## Possible fix 
A possible fix would be to set a `clear:both;` on the `usa-nav-primary` style while at smaller screen sizes, making sure that whatever is inside of the UL is always below the close button and not overlapping. 
![screen shot 2017-11-09 at 10 09 52 am](https://user-images.githubusercontent.com/1449852/32612903-729a56e8-c537-11e7-9db4-3fb5c44cf28d.png)

**Comment by maya** [comment]
Thanks for finding this issue @line47! I'm thinking if `.usa-nav-close ~ * { clear: both; }` could be a more robust solution so this clears anything immediately after the button.
