### ISSUE TITLE
Date Input double class

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#2225]
```html
<input class="usa-input-inline" aria-describedby="dobHint" class="usa-form-control" id="date_of_birth_1" name="date_of_birth_1" type="number" min="1" max="12" value="">
```

Might be difficult to see:

```html
<input class="usa-input-inline" class="usa-form-control">
```

I could not locate a class `usa-form-control`, but I didn't look very hard.

In my own work slightly related to the USWDS, I'm finding it very difficult to track all the form-related things when it's in the same sections as everything else. Therefore, also recommend maybe encapsulating the form control-related Sass into its own folder.

**Comment by maya** [comment]
Thanks for catching this, @joshbruce! Seems like the unused class can be safely removed.

Feel free to open a new issue to describe the issues you mention using forms, so we can keep this associated with the bug.
