### ISSUE TITLE
Meet to develop a draft vision statement

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards#2233]
Let's talk about where we've been and where we're going. What have we learned in the last year and how can we apply it to our direction for 2018 and beyond?

**Comment by maya** [comment]
I synthesized our vision work and statement [🔒 here](https://docs.google.com/a/gsa.gov/document/d/1KuXLbOPu4OLoKMtuEG0UVNb2Lo8sumIH_RrdjZS2aNE/edit?usp=sharing).

**Comment by thisisdano** [comment]
### USWDS / Where we’ve been and where we’re heading

This was a big year for the U.S. Web Design Standards. In March, we released version 1.0 — the culmination of nearly two years of work researching, designing, building, testing, and iterating. Today our design system is used by over [100 websites and services](https://github.com/18F/web-design-standards/blob/develop/WHO_IS_USING_USWDS.md), reaching tens of millions of users. And our project continues to demonstrate the potential of open source software. Over the lifetime of the project, our community of nearly 400 contributors and commenters from across government and beyond closed over 1000 issues and merged over 1000 pull requests on GitHub, generating over 8000 comments in the process. 🎉 We’re going strong, excited for the future, and ready to do more.

We built the USWDS to help build fast, consistent, responsive, accessible websites from research-strengthened components for the American public. It’s a continuing process of learning: not only from modern best practices, but particularly from the people who use the system and the people who use the sites built with the system. We continue to be humbled and inspired by the intelligence and creativity of those who are building and extending and improving on what we’ve done. We want to keep getting better by helping these builders, designers, and program managers focus on their mission and the challenges that matter.

We’re listening to your feedback and we’re evolving. In 2018 we intend to move forward with some ambitious goals. Here’s some of what we’re planning:

- An easier way to prototype and build consistently and incrementally
- Better support and guidance for Federalist and Jekyll
- Clearer, more specific design and implementation guidance
- Better typographic flexibility and resilience, with or without web fonts
- A more flexible, consistent color system
- A clearer connection between user research and patterns and components
- A clear, reliable way to stay up-to-date and track component changes and status
- A path to contribute components and research back to the system
- Changing our name to more accurately describe what we are and what we do
- Growing our core government communities and our larger open source community

As always, accessibility, research, rock-solid markup, and trustworthy guidance are at the center of what we do — as well as a commitment to remaining completely free and open-source.

We learn when we listen. Feedback matters. The grit sharpens the blade. So let’s keep talking. Is there anything we’re missing? How can we help you build high-quality websites for the American public? Let us know by sending us an [email](mailto:uswebdesignstandards@gsa.gov), joining our [Slack community](https://chat.18f.gov/), or commenting on this very issue 😄 . Onward!
🚀
