### ISSUE TITLE
Issue with Template 1: Landing page

### ISSUE THREAD

**Issue by herrjosua** [18F/web-design-standards#2236]
## Title line template: Issue with Template 1: Landing page: Missing closing tags

I noticed a minor issue with the sample code found on the Page Templates page. There is a missing `</div>` on the search markup and an duplicate `</div>` at the bottom of the page. I included the code bleow.

`...`
`<form class="usa-search usa-search-small  js-search-form">`
`  <div role="search">`
`    <label class="usa-sr-only" for="extended-search-field-small">Search small</label>`
`    <input id="extended-search-field-small" type="search" name="search">`
`    <button type="submit">`
`      <span class="usa-sr-only">Search</span>`
`    </button>`
` .  <!-- Missing the closing div tag --> </div>`
`  </form> `
`...`
`</div>`
`  <ul class="usa-unstyled-list usa-nav-secondary-links">`
`    <li class="js-search-button-container">`
`      <button class="usa-header-search-button js-search-button">Search</button>`
`    </li>`
`    <li>`
`      <a href="">`
`        Secondary priority link`
`      </a>`
`    </li>`
`    <li>`
`      <a href="">`
`        Easy to comprehend`
`      </a>`
`    </li>`
`  </ul>`
`</div>`
` <!-- duplicate closing div -->   </div>`
`  </nav>`
`</header>`
`<div class="usa-overlay"></div>`
`...`

**Comment by maya** [comment]
Thanks @herrjosua, working on a fix in #2252.
