### ISSUE TITLE
Clarify browser compatibility in the contributing guidelines

### ISSUE THREAD

**Issue by scottkellum** [18F/web-design-standards#2251]
## Description

As someone who might be contributing to this project I’d like to understand what the web client target requirements are so that I may not create any regressions in terms of compatibility and test contributions appropriately before sending a PR.

**Comment by maya** [comment]
Thanks @scottkellum. We have a section for browser support on the site's "For developers" page here https://standards.usa.gov/getting-started/developers/#browser-support, but could see how adding it to the contributing file would be useful too. Also, the wording is a little confusing around IE support.

**Comment by maya** [comment]
@thisisdano @donjo is the browser support text still accurate?

>We’ve designed the Standards to support older and newer browsers through progressive enhancement. The Standards will officially support any browser above 2% usage as defined on analytics.usa.gov. This currently means the Standards supports the newest versions of Chrome, Firefox, Safari and Internet Explorer 11 and up. Due to what browsers the Standards originally supported, the Standards will continue to support Internet Explorer 9 and up until the next major release, 2.0.

If so, should we rewrite this to lead with "the Standards supports [...] Internet Explorer 9 and above and will support Internet Explorer 11 and above in the next major release, 2.0." to be more direct about the current support?

**Comment by donjo** [comment]
Well the original one was written in a time when it was assumed 2.0 was going to be the next release (not only the next major release) so the present tense made a bit more sense then. However, since 2.0 isn't quite as imminent as once presumed, I think we could re-write the paragraph to be more clear. I'm thinking something like:

> We've designed the Standards to support older and newer browsers through progressive enhancement. The current major version of the standards, 1.x.x, was designed to support the newest versions of Chrome, Firefox, Safari, and Internet Explorer 9 and up. Upon the next major release, 2.0.0, the Standards will begin following the [2% rule](https://gds.blog.gov.uk/2012/01/25/support-for-browsers/) where any browser above 2% usage as observed by analytics.usa.gov will retain official support. This currently means future versions of the Standards will support the newest versions of Chrome, Firefox, Safari, and Internet Explorer 11 and up.

**Comment by maya** [comment]
That's clearer to me, the only thing that was confusing at first was 1.x.x, I wonder if we can say 1.0 or leave it out? @thisisdano how is this looking to you?

**Comment by thisisdano** [comment]
How's this:

> We’ve designed the Standards to support both older and newer browsers through [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement). The current major version of the Standards (1.0) and subsequent minor and patch releases were designed to support the newest versions of Chrome, Firefox, and Safari, as well as Internet Explorer 9 and up. The next major release (2.0) will follow the [2% rule](https://gds.blog.gov.uk/2012/01/25/support-for-browsers/): we will officially support any browser above 2% usage as observed by analytics.usa.gov at the time of the major release. Currently, this means that Standards v2.0 would support the newest versions of Chrome, Firefox, and Safari, as well as Internet Explorer 11 and up.

**Comment by maya** [comment]
Thanks for the suggestions all, moving this and ongoing edits into a PR.

**Comment by maya** [comment]
@scottkellum this is fixed, thanks again 👍 Looking forward to your (possible) PRs. If you have any more questions around contributing, let us know; we may be revisiting spacing and type scales as well.

**Comment by scottkellum** [comment]
@maya Thanks! I am good with type scales if y’all need help with that. I’m mostly focused on infographic components at the moment

**Comment by thisisdano** [comment]
Thanks @scottkellum I have some thoughts on type scale and whitespace scale coming up that would benefit from your 👀  and 💭 , and am very curious to hear more about infographics and dataviz! (Love your type scale tool btw.)

**Comment by maya** [comment]
@scottkellum sounds good, thanks! Also, a team worked on data viz for the Census for a bit: https://federalist-proxy.app.cloud.gov/site/18f/uswds-data/ https://github.com/18F/uswds-data 

We have this issue that may be relevant: https://github.com/18F/web-design-standards/issues/18 (closed now, but should it be opened @thisisdano?)
