### ISSUE TITLE
JQuery dependency and vulnerability

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#2254]
I was notified during a security scan that JQuery has a security vulnerability. The USWDS has a dependency on JQuery.

Having said that, I thought we took JQuery out of the mix.

**Comment by jchassy** [comment]
Jacob

**Comment by maya** [comment]
Hi @joshbruce, yes jQuery was removed some time ago, which makes this strange. Are you able to find where jQuery was located that gave this warning?

**Comment by joshbruce** [comment]
Hey @maya: The version the program (I'm back on) I'm on was still using 0.13.1...having said that, I see it in the `devDependencies` of the `package.json` file on `master` right now. 

Curious why that's the case.

**Comment by maya** [comment]
Not sure, @donjo @toolness do you know?

**Comment by donjo** [comment]
Looks like it is a dev dependency because it is still being used in our tests (see #1351) even though it is no longer required for UI components. That said, we should probably bump the version in the near term and consider whether we want to re-write those tests in the long term.
