### ISSUE TITLE
small screen hidden usa-nav-secondary items still tabbable

### ISSUE THREAD

**Issue by patrickww71** [18F/web-design-standards#2257]
## Steps to reproduce the issue

1. go to https://standards.usa.gov/components/headers/extended/
2. shrink browser width to below 950px
3. tab through elements (do not click Menu button)

hidden secondary elements are tabbable

**Comment by maya** [comment]
Thanks for opening this and letting us know.

**Comment by maya** [comment]
@patrickww71 I realized this was already documented here: #2257, closing this as a duplicate. Thanks again!
