### ISSUE TITLE
Grid styles not being imported in a Angular CLI project

### ISSUE THREAD

**Issue by herrjosua** [18F/web-design-standards#2260]
## Description

I'm working on incorporating the USWDS into my team's Angular CLI project, but I'm encountering an issue where the `grid` styles are not being imported. I'm using the SASS files. I have setup a sample project on my public [GitHub](https://github.com/herrjosua/uswds-sass-angular-cli) to showcase the issue. It appears that most of the other styles are being correctly imported. 

## Additional information [optional]

![screen shot 2017-12-07 at 08 59 40](https://user-images.githubusercontent.com/1341786/33719662-828b2a24-db2f-11e7-9389-82cbed2ed634.png)

**Comment by maya** [comment]
Not sure what's causing this, but will just add that it seems that the container class or `.usa-grid` is working as the content centered in a 980px container, while the columns (e.g. .usa-width-one-half) are not. Those classes are both in the grid.scss file.

**Comment by herrjosua** [comment]
I'm not sure what is causing the issue. When I run the standard `sass` command in terminal, I'm able to see the missing styles in the complied css.

**Comment by herrjosua** [comment]
@maya With the help of a co-worker I was finally able to resolve the issue. I was missing the `bourbon-neat` package. Once I installed and added to my `scss` file the issue was resolved.
