### ISSUE TITLE
Select input arrow missing in IE10 & IE11

### ISSUE THREAD

**Issue by aileendds** [18F/web-design-standards#2265]
## Description

The arrow on the right side of the select input is missing in IE10 & 11 starting in USWDS V1.4.x
I believe it's actually tiny and not missing. The SVG isn't rendering properly.

## Steps to reproduce the issue

1. Go to https://standards.usa.gov/components/form-controls/ in IE10
2. Scroll down to "dropdown"

![screen shot 2017-12-11 at 4 03 50 pm](https://user-images.githubusercontent.com/29409348/33854304-399149d0-de8f-11e7-81a0-08f5c2182448.png)

**Comment by donjo** [comment]
Thanks for sending this in. I just took a look and it seems like IE isn't falling back to the PNG option for the dropdown icon like it should. I'll look into some possible solutions.

**Comment by maya** [comment]
I remember this worked in those browsers before, so wonder what's going on. Also wonder if it's related to this GSA logo being smooshed or something separate: https://github.com/18F/web-design-standards-docs/issues/331
