### ISSUE TITLE
Choose utility classes to add

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#2272]
Utility classes (or helper classes) provide a lightweight way to customize your markup with single-purpose classes. These classes are simple, composable, and reusable. For example: `.usa-red { color: $color-red; }`, `.usa-h1 { font-size: $h1-font-size; }`. We've seen the web community moving in this direction and think that providing helpful classes can enable teams to quickly remix these basic building blocks. 

## 📣 Tell us what you need! 
**Comment on this issue with utilities you'd like to see added.** 

---

Below are utility classes we've heard people ask for, ordered from most to least requested.

### Top requested
- **color** (text, background)
- **space** (margin, padding)
- **typography** (sizing)

### Also requested
- display (none, inline, block)
- float (left, right)
- typography styles (caps, bold, underline)
- position (relative, absolute)
- border (border-bottom, rounded, etc)
- grid (column sizing at diff viewports)
- size

*Note: We're also aware they can be problematic when taken to the extreme or when teams don't communicate how they'll be using them (and will need to think through how we [document](#2263) this). 

Related #2264, #2214.

**Comment by evetsreklaw** [comment]
This is a good list. If grid is referring to something like bootstrap's breakpoints (xs-6 or md-8) that would be number one for me. Many of the others I have created and I am sure others have too so I hope others share what they have done. Colors - usa-fill- and usa-text- + color at https://github.com/evetsreklaw/USWDS-Extended/blob/master/_colors.scss.

**Comment by maya** [comment]
We have a good sense of which ones to add first, closing this as we begin implementation.
