### ISSUE TITLE
[Page fades on load or refresh]: the usa-overlay is causing page flickering or fading

### ISSUE THREAD

**Issue by line47** [18F/web-design-standards#2274]
## Description

when refreshing a page or navigating to a new page I’m seeing a “fade in” type effect that I think is due to the `usa-overlay`. When I remove the `usa-overlay` div the "fade in" type effect is no longer present. If i comment out or remove the `usa-overlay` div everything works as expected. 

I'd love to find a solution that can keep the `usa-overlay` 

## Steps to reproduce the issue

1. Go to https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/update-uswds/ refresh the page a few times and you will see the "fade in" effect. This repo can be found here - https://github.com/18F/federalist-uswds-template/tree/update-uswds
2. That preview is using [uswds-jekyll](https://github.com/18F/uswds-jekyll) 

## Additional information
![site-flicker](https://user-images.githubusercontent.com/1449852/34049736-7f6a42f0-e186-11e7-9606-632f19c1c1ec.gif)

### A few thoughts from team members 
- @hursey013 - yeah there is some js being applied and if there is a delay then i think you see a flash of it before its hidden - https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/js/components/navigation.js#L31

- @tbaxter-18f - I see this https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/js/components/navigation.js#L16 then this https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/js/components/navigation.js#L30 Perhaps the latter should just be iterating and toggling `NAV` and not `OVERLAY`?

- I tried to mimic what was done here (suggested by @maya Here’s the repo: https://github.com/GSA/dotgov-home) and did not have any success

**Comment by tbaxter-18f** [comment]
To elaborate on my comment above, I think that if we change L16 to 
`const TOGGLES = [ NAV ];` then L30 will only impact the nav onload and the overlay will not be affected. We may need to then add `OVERLAY` back into `TOGGLES` at some point after L30 is first run. My theory is that either OVERLAY is on by default and we're quickly toggling it off, or that the toggle itself is creating a quick show/hide flash.

I also see a 0.2s transition on overlay, so any hide/show won't be instant.

**Comment by hursey013** [comment]
@line47 It looks like updating the `transition` property of `.usa-overlay`to only target `opacity` rather than `all` might fix the issue. 

Preview: https://federalist-proxy.app.cloud.gov/preview/18f/federalist-uswds-template/bh-overlay-fix/

Branch: https://github.com/18F/federalist-uswds-template/commit/f6ebe6c32b202171453d567e80e7c4564050b177

**Comment by line47** [comment]
@hursey013 - interesting - I'm going to give that a go on my branch as well 👍

**Comment by line47** [comment]
That fix worked for me 💯

**Comment by hursey013** [comment]
Awesome, I'll open a PR in this repo so we it can hopefully be fixed upstream.

**Comment by maya** [comment]
Thanks for finding a fix 🎉 

Fixed in #2275. (FYI should be doing a release Monday).
