### ISSUE TITLE
aXe tests fail on CircleCI with error "Document has no main landmarks"

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2284]
[Here is an example CircleCI job.](https://circleci.com/gh/18F/web-design-standards/1958#tests/containers/0)

More information about the violation, which is triggered on every page visited by the aXe test suite, is [on Deque University](https://dequeuniversity.com/rules/axe/2.6/landmark-one-main?application=axeAPI).

@maya @donjo for how long has this error been raised?  Was there a particular changeset that triggered it?

In the worst case, we should be able to add a directive to the [`AXE_OPTIONS` object in `axe-tester.js`](https://github.com/18F/web-design-standards/blob/develop/spec/axe-tester.js#L16-L22) instructing aXe to ignore the rule. Something like this should do the trick:

```diff
const AXE_OPTIONS = JSON.stringify({
  rules: {
    // Not all our examples need "skip to main content" links, so
    // ignore that rule.
    'bypass': { enabled: false },
+   // Nor do all our examples need main landmarks...
+   'landmark-one-main': { enabled: false },
  },
});
```

As with the `bypass` rule we're already disabling, absence of a main landmark is really a problem with the fractal template we're using, not USWDS itself, so it's probably safe to disable the rule regardless.

That said, I am interested to know what happened to make the warning suddenly start being raised when it hadn't been before. Was `package.json` recently updated to use either a different version of aXe or a different version of fractal (or one of its dependencies)?

**Comment by maya** [comment]
>for how long has this error been raised? Was there a particular changeset that triggered it?
It happened recently following an upgrade to CircleCI 2.0 and changes to our `package-lock.json` file.

**Comment by toolness** [comment]
Ah, I bet it's the changes to `package-lock.json` then--it's likely that cd6d7efd0b10c1e25a21e7ba94f949ca877d9342 (from 2 days ago) or even f6a222cffab2427180e93ac8a2ea35fa77a0d7b0 (from 2 weeks ago) might be the culprit.

Additionally, it seems like `landmark-one-main` is a relatively new feature in axe-core, as it was only merged about a month ago: https://github.com/dequelabs/axe-core/pull/498

So, my guess is that the aXe tests weren't failing before because we were using an older version of axe-core which didn't detect for `landmark-one-main`, but then when `package-lock.json` was upgraded, this check was activated, and because the Fractal site never had one main landmark, the aXe tests started to fail.

Unfortunately I don't have the time to issue a PR myself right now, but the above diff I provided *should* do the trick--can you try that and let me know if it fixes the problem?

**Comment by maya** [comment]
@toolness the previous issue seems fixed, but we're getting a different aXe failure now. https://circleci.com/gh/18F/web-design-standards/1963:
```
  94 passing (10s)
  2 failing

  1) fractal component "before all" hook: setup ChromeFractalTester:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) fractal component "after all" hook: teardown ChromeFractalTester:
     TypeError: Cannot read property 'kill' of null
      at ChromeFractalTester.teardown (spec/chrome-fractal-tester.js:105:23)
```

**Comment by toolness** [comment]
It looks like that timeout is just an intermittent failure, likely caused because Chrome might take more than 2 seconds to start up... we should [increase the timeout](https://mochajs.org/#test-level) there.  [I re-ran the CircleCI job](https://circleci.com/gh/18F/web-design-standards/1964) and everything seems to work ok!

**Comment by maya** [comment]
Yay! What do you think is a good timeout amount to set it to?

**Comment by toolness** [comment]
Hmm, maybe like 15 seconds, just in case CircleCI happens to be under a lot of load or something?

**Comment by maya** [comment]
Cool, feel free to open a PR or let me know which file I should change to do that.

**Comment by donjo** [comment]
@toolness is this the timeout you're talking about? looks like it is already set to 20s but is only using 2s as the actual timeout (is that a global default of some sort?) https://github.com/18F/web-design-standards/commit/71a7701a75a9e4f4a50ea3a6e7c29f4208cec943
