### ISSUE TITLE
Federalist builds mysteriously fail

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2288]
See for example [this federalist build log](https://federalist.18f.gov/sites/62/builds/23294/logs), which was created as a result of #2285 being merged. There's absolutely nothing in the code being merged that should affect federalist, but it mysteriously dies after logging some npm installation messages:

```
npm WARN prefer global marked@0.3.7 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
Killed

npm ERR! Linux 4.4.0-104-generic
```

This mysterious death is very similar to some problems I was having in August with https://github.com/18F/web-design-standards-docs/pull/357#issuecomment-321537645, and the solution there seemed to involve upgrading to node 8. So upgrading this repo to use node 8 might fix things here as well, but I'm not sure.

**Comment by jseppi** [comment]
In the logs, I also see `Exit status 137`. I googled around a little and found this issue https://github.com/npm/npm/issues/4008#issuecomment-188495114, which has comments indicating that it might be a memory issue. Our build containers have 1G of memory, which maybe isn't enough for the complex build process of this repo. That's my current hunch, anyway.

**Comment by donjo** [comment]
Update from @jseppi in Slack: seems to be a memory issue as memory usage jumps up to 1.2G during `npm install --dev` and container size on Federalist was set to 1G. Going to close this one out for now and create a new issue to look into slimming down that package list.
