### ISSUE TITLE
[Question]: Linter rules and libraries

### ISSUE THREAD

**Issue by joshbruce** [18F/web-design-standards#2307]
I'm in a weird position:

1. I've been made an owner of the Marked library and am making headway reviving the community to aid dependency issues on my GSA (and personal) project. Recently the idea of linting came up: https://github.com/chjj/marked/issues/999

2. The discussion around linting came up on my GSA project as well and I recommended using the rules here - as they seem sane, researched, and so on.

The community over at Marked mentioned these two libraries, which I had never heard of. The rules don't seem too different from those found here:

1. https://github.com/standard/standard
2. https://github.com/Flet/semistandard

The only real difference between the two apparently being one prefers the use of semicolons while the other does not. The added value with these libraries is that they can automatically clean your code (makes me nervous, but I got trust issues with automatic code manipulation when it comes to the web).

So, curious about the discussions that went into choosing the lint strategy used by the USWDS? Would you consider using either of these libraries? And so on.

(Conversation might be better served in Slack or quick phone call.)

Tagging in @colinalford-gsa as well.

**Comment by maya** [comment]
Hi @joshbruce, unfortunately, I don't think I have a clear answer for you regarding what went into choosing the linter rules as the person who set this up is no longer at 18F. However, thanks to this, I realized we're not using the Airbnb linter, which we should be and opened an issue for it here: #2310

**Comment by maya** [comment]
It's probably a good idea to use a linter, the specifics are likely less important than the consistency of everyone following it, so feel free to use whatever makes the most sense to the team involved. Good luck!
