### ISSUE TITLE
Create coded version of the Date Picker

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#239]
**Description**
We currently only have a placeholder image version of the date picker. This issue to to complete the work to create an actual coded, and responsive, version of the visual design and any UX wireframes (see layout below).

**To Do**
- [ ] Create html and styles (responsive) based off of current structure
- [ ] Run HTML Codesniffer and review for accessibility quality and make any necessary changes
- [ ] Submit pull request when code is ready for review
- [ ] Once reviewed and merged into staging, run by @angel / @mollieru and @carodew / @colinpmacarthur for final approval.
- [ ] Iterate/make changes and re-submit PR with any fixes prior to pushing to production

**Visual Design**
![date_picker_ui_v1](https://cloud.githubusercontent.com/assets/955558/8933200/7cfb8112-350f-11e5-98cf-87bbf862921a.png)

**Comment by juliaelman** [comment]
Referencing https://github.com/18F/govt-wide-patternlibrary/issues/87 for background ideas and feedback.

**Comment by noahmanger** [comment]
We've been working on date inputs on FEC and I came across this really helpful article from GDS: https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html

The main thing is that date pickers aren't always the most usable component, and it really depends on the type of date you're asking for. It might make sense to have a couple different options of date inputs with recommendations for when to use which. 

I don't have the answers, but I found that piece helpful so wanted to share for further discussion.

**Comment by carodew** [comment]
@noahmanger Yep, this is perhaps my favorite style guide page in existence. As in I'd like to print it out and frame it. :heart: 

We haven't written the UX guidelines on this component yet and I'm not sure how many variations we can fit in under the wire, but I'm going to make a card in Trello to consider this.

**Comment by colinpmacarthur** [comment]
Just to pile on here: I think we should definitely encourage folks to use caution with the date picker (for the reasons outlined by GDS, the frontend slack channel and by all smart design people). And I think our "use" guidance will be a great place to do that.

I don't think anyone's arguing against this, but I think we should definitely continue to offer a date picker because:
1. Developers requested them in our initial workshop
2. If we don't offer them, folks will make their own
3. There are a few situations (as GDS points out) where date pickers are actually useful.

**Comment by msecret** [comment]
I'm fine with building a date picker but do think we should be a little careful. We should avoid using a bloated jQuery plugin that comes with it's own styles which are hard to override. This will make more work for us as well as our end user. If possible, I'd opt for a polyfill to the browser date picker over a separate library to use, or ensure we find a library that's not large and intrusive (which might be hard these days).

**Comment by maya** [comment]
@colinpmacarthur "There are a few situations (as GDS points out) where date pickers are actually useful." GDS has only one date picker on their site and that is for prison visit scheduling - A _very_ specialized use case.

**Comment by juliaelman** [comment]
Moving this outside of sprint, as there are some conversations on what is the best direction to go. #271 is adding a more simple date field input for now while we determine what direction to go for the full date picker option.

**Comment by maya** [comment]
@juliaelman After chatting with @msecret and @blacktm, we think this is out of scope for the MVP.

**Comment by juliaelman** [comment]
@maya cool. Removing this issue from the sprint, but am going to keep it open for future development.
