### ISSUE TITLE
ul element has list-style removed by default

### ISSUE THREAD

**Issue by jeremiak** [18F/web-design-standards#321]
I wanted to use an `<ul>` element in my page content (not the nav or any aside and with no classes applied, but by default the element has a style of `list-style: none;` around line 614 on the generated CSS.

Is this supposed to be this way? It seems to me that we don't want to remove the ability of devs to have unordered lists displayed in a common way, especially by default.

**Comment by maya** [comment]
I think this is bc we are using a custom way of displaying our lists, to get perfect alignment of the bullets with the edge of the page and the content after it. However, it should still work as you expect it. This is what a standard list looks like:

![screen shot 2015-08-20 at 3 56 39 pm](https://cloud.githubusercontent.com/assets/5249443/9397672/ec7140e4-4753-11e5-84a9-16c3dd192348.png)

**Comment by carodew** [comment]
@maya is this issue something that can be closed?

**Comment by maya** [comment]
@carodew I couldn't replicate the problem.
