### ISSUE TITLE
As a designer who doesn't code, I want an Illustrator (and Sketch) template to comp up designs using these grids, styles, elements, components.

### ISSUE THREAD

**Issue by jtag** [18F/web-design-standards#330]
Prioritize or delete at will, but wanted to throw this out there.

**Comment by maya** [comment]
@jtag we have a repo for design assets here: https://github.com/18F/usfwds-assets

**Comment by colinpmacarthur** [comment]
I believe Sketch and Omnigraffle templates are coming out soon (thanks @bradnunnally and @esgoodman!). The repo Maya references has all the indesign files.

**Comment by maya** [comment]
@colinpmacarthur We aren't using indesign, that repo has the Adobe Illustrator files.

**Comment by esgoodman** [comment]
@jtag let's set up a time to walk through my Sketch symbol library to see what should be in there.

**Comment by jtag** [comment]
So so good. Thank you.

**Comment by mollieru** [comment]
@esgoodman and @jtag -- would love to listen in to capture designer user
needs

**Comment by carodew** [comment]
+1 @mollieru @colinpmacarthur or I would love to be involved in that.

**Comment by angel** [comment]
@carodew @colinpmacarthur updated assets in this PR: https://github.com/18F/web-design-standards-assets/pull/8. I was wondering for the "download visual style assets" on the typography page should that include the UI components and color files? Right now the zip just includes fonts and pairings for that button. Let me know what you guys think and I can update as needed. Thanks!

**Comment by mollieru** [comment]
@angel i think we resolved this earlier. closing this out!
