### ISSUE TITLE
[Footer] Tap shadow does not appear over social media icons (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#347]
When a user taps a social media icon, the tap shadow does not appear over the icon, but in a small rectangle underneath it. (Photo forthcoming.)

Found on:
- iPhone 6, iOS 8.4, Safari
- iPad 2, iOS 8.4, Safari
- Mote E, Android 4.4, Chrome 44

**Comment by carodew** [comment]
Putting this as a medium but barely a medium, so other medium level bugs should come first.

**Comment by maya** [comment]
This seems like a very low bug to me. I vote to change the label.

**Comment by donjo** [comment]
Closing this one out since it appears to have been fixed at some point.
