### ISSUE TITLE
[Footer] Gov't email link opens new email, but addressed to "0" (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#348]
Gov't email link opens new email, but the To: recipient is shown as "0" instead of the email address.

## Devices
- iPhone 6, iOS 8.4
- iPad 2, iOS 8.4
- Moto E, Android 4.4, Chrome 44

**Comment by msecret** [comment]
Is there an example/fake email address it should open up as?

**Comment by carodew** [comment]
I think maybe just use the sample email – info@agency.gov ?
