### ISSUE TITLE
[Side navigation] side nav dismisses when opening a primary level section, but does not when actually selecting a link

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#349]
Sidebar navigation does not dismiss after selecting a secondary or tertiary level item in mobile device. To replicate: 

1. Tap the menu icon to open the sidebar. 
2. open the "Elements" section. (The sidebar self-dismisses, it should not).
3. Reopen the sidebar. 
4. Tap 'Buttons.' (The Main content area scrolls to Buttons but side nav is still present. It should dismiss at this point.) 
6. Tap in main content area to dismiss side nav. 

Replicated on: 
Motorola Moto E, Android, 4.4.4 Kitkat, Chrome 44
Apple iPhone 6, iOS 8.4, Safari
Apple iPad 2, iOS 8.4, Safari

**Comment by carodew** [comment]
Also replicated on Samsung Galaxy S5, Android 5.0 Lollipop, Chrome

**Comment by maya** [comment]
@carodew That is bc when you go to a primary item, you are going to a new page and when you click on a sub-item, you are scrolling within that page. The behavior you are describing was never defined to us. It's not really a bug it's just how the sidenav has been implemented.

**Comment by jpyuda** [comment]
To a user, this appears to be a bug. Re-classifying as such.

**Comment by maya** [comment]
We no longer have this type of functionality of in-page navigation in the mobile nav.

Closed via #1274.
