### ISSUE TITLE
[Footer] Phone number not tappable (Moto E, Android 4.4, Chrome 44)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#350]
Unlike on iOS, the phone number in the footer is not "tap-to-call." This appears to be because this version of Android doesn't support letters in phone numbers.

**Comment by msecret** [comment]
I think we would have to make the phone number a link of a certain type. Maya and I researched this at a certain point but didn't implement.

**Comment by jpyuda** [comment]
You could potentially make it a link using `tel:1-800-...` but then it would appear as a link on desktop devices.

**Comment by Scotchester** [comment]
You could do that and override the link styling on desktops.

**Comment by colinpmacarthur** [comment]
I think this problem has two roots:
1. Android 4.4 only makes phone numbers that don't include letters tappable (our examples include letters).
2. When Android makes a number tappable, it does not change its formatting (like iOS does).

We could solve problem 1 by changing the default phone number to (800) 555-555. But problem 2 is a little harder.

**Comment by carodew** [comment]
Point 2: How much do we care if the formatting changes as long as it works? And if we do care, can we use CSS to give it our own styles?

**Comment by colinpmacarthur** [comment]
One response to point 2 could definitely be: it stinks that tappable phone numbers don't always look tappable on Android, but that's not our problem. 

Unfortunately, when Android makes phone numbers tappable, it doesn't add any new attributes or elements to the HTML. I suspect that forecloses the most elegant CSS solutions. But I'm really speaking beyond my expertise here.

**Comment by Scotchester** [comment]
If you follow Yuda's suggestion and make it a `tel:` link, then you have
the necessary styling hook to customize the Android formatting.

**Comment by carodew** [comment]
@Scotchester :boom:

**Comment by jpyuda** [comment]
(I don't find this very important at all, though. Very much in the "nice to have" space.)

**Comment by maya** [comment]
Is this issue considered a bug or an enhancement?
