### ISSUE TITLE
[Tables] Example runs off the edge of the screen (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#353]
The example table runs off the edge of the example box:

Android:
![tables run off edge of page](https://cloud.githubusercontent.com/assets/2092076/9480984/869dc9c2-4b54-11e5-9a7c-d01854081603.png)

iPhone:
![table iphone display](https://cloud.githubusercontent.com/assets/2092076/9481039/0a667394-4b55-11e5-979c-f4bfeb5020c5.PNG)

## Devices
- Moto E, Android 4.4, Chrome 44
- iPhone 6, iOS 6
- Samsung S5, Android 5 Lollipop, Chrome

**Comment by carodew** [comment]
We need to decide what the fix is for this.

**Comment by jpyuda** [comment]
Let's make the `<td>` cells white instead of transparent to at least get rid of the border bleeding through.

There may later be additional design changes aiming to fix the margins.

**Comment by joshbruce** [comment]
One option would be to wrap tables in a `div` (or, preferably, different element). See UIKit's "Responsive Table" at the bottom of the page:

http://getuikit.com/docs/table.html

**Comment by maya** [comment]
@jpyuda are you thinking we should make `<td>` cells white for the table component or custom styleguide CSS?

**Comment by msecret** [comment]
@maya the table component. This is something that will come up outside of our docs.
