### ISSUE TITLE
[Contact form] Tapping email link does not open a new email (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#359]
Tapping the email link in the contact form does not open a new email.

Found on:
- iPhone 6, iOS 8.4
- iPad 2, iOS 8.4
- Moto E, Android 4.4, Chrome 44

**Comment by maya** [comment]
This works for me.

**Comment by maya** [comment]
Update: we don't have a contact form anymore.
