### ISSUE TITLE
[Contact form] Email input triggers wrong soft keyboard (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#361]
When the email input on the contact form is tapped, it should open the soft keyboard that contains an "@" sign. At the moment, it opens the generic text soft keyboard that requires the user to tap to other screens to enter an @ sign. 

## Devices
- iPhone 6, iOS 8.4
- iPad 2, iOS 8.4
- Moto E, Android 4.4, Chrome 44

**Comment by cvrebert** [comment]
Not surprising, since it uses `type="text"` instead of `type="email"`.

**Comment by maya** [comment]
The site does not have a Contact Form anymore so closing this.
