### ISSUE TITLE
[Search bar]: the border on the medium search bar is thicker than the others (Moto E)

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#366]
It should be the same thickness as the others. 

![weird formatting med search bar](https://cloud.githubusercontent.com/assets/10144074/9500718/f31b2c02-4bf4-11e5-8252-257c8351be50.png)

Observed on:
Motorola Moto E, Android 4.4.4 Kitkat, Chrome 44

**Comment by carodew** [comment]
@colinpmacarthur is this going to be resolved with the work being done on the search bar right now?

**Comment by carodew** [comment]
The border on the medium search bar should be the same weight as the other two. 

@angel can confirm the specific width.

**Comment by angel** [comment]
@carodew the border should be 1px. I'm not seeing the border difference on my iPhone 5s, but I do see it as rounded!

![search-bar-iphone5s](https://cloud.githubusercontent.com/assets/103496/9592813/e6085084-5014-11e5-8ff1-8a57e6c77d0e.png)

**Comment by colinpmacarthur** [comment]
@angel: Can you file a separate issue for the rounded searchbox problem?

**Comment by colinpmacarthur** [comment]
Unassigning myself. Think this issue contains all the info it needs to be solved.

**Comment by maya** [comment]
@colinpmacarthur's screenshot and @carodew's look like the opposite border width issue is happening. Is that correct? Thicker border on medium vs. small and large and vice versa.

**Comment by maya** [comment]
I just checked on Moto G (don't have access to E) and not seeing this issue:

<img width="331" alt="screen shot 2016-06-09 at 3 02 13 pm" src="https://cloud.githubusercontent.com/assets/5249443/15949125/e6d147fe-2e59-11e6-93b1-7e4b91f80af4.png">

Is this safe to close, cc @bradnunnally.

**Comment by maya** [comment]
Closing for now. Please re-open if this remains a problem.
