### ISSUE TITLE
[Social security number] field does not trigger numerical soft keyboard (multiple devices) 

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#369]
Tapping the social security number field opens the text keyboard, not the numerical one.

Devices affected:
- iPad 2, iOS 8.4
- Moto E, Android 4.4, Chrome 44

**Comment by cvrebert** [comment]
Probably because you have `pattern="^d{8}$"` instead of `pattern="^\d{8}$"` (missing a backslash).

**Comment by maya** [comment]
There's no SSN on the site, so closing.
