### ISSUE TITLE
[Password reset form]: the checkmarks for the 'Passwords must' requirements are not showing up as those requirements are fulfilled. (iOS/Safari)

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#370]
Recreate on iPhone/Safari: 

1. type inside the first password text field, include one capital letter, a number, and at least 8 characters
2. As each of these requirements are fulfilled, a checkmark should appear within the blue box indicating as such. But nothing appears.

Observed on: 
Apple iPhone 6, iOS 8.4, Safari
Apple iPad 2, iOS 8.4, Safari

**Comment by colinpmacarthur** [comment]
This also happens on Windows 7, IE 8.

**Comment by colinpmacarthur** [comment]
This also happens on Windows 7, IE 10.

**Comment by mollieru** [comment]
This is also happening on OS 10.8, Safari 6.2

**Comment by maya** [comment]
Resoved via #505.
