### ISSUE TITLE
Typography Findings from Implementing USFWDS on the Playbook

### ISSUE THREAD

**Issue by cew821** [18F/web-design-standards#371]
Hi all - First off, great work on this! I implemented the typography, color and button styles as well as I could understand them on the Playbook. 

I'm attaching a screen shot of what it looks like. You can compare this to the [current version](https://playbook.cio.gov). One thing I noticed is that the line spacing on the `<p>` and lead paragraph styles feels a little tight to me. I also feel like the weight on the `<h>` styles might be too heavy, or at least the kerning to close (see how the r and the v in Services touch).  One other thing I'm wondering is if the font sizes should change on mobile. Currently, the playbook responsively reduces the `<h>` font sizes on mobile, which I think is helpful.

![playbook_design](https://cloud.githubusercontent.com/assets/1237498/9504714/190f2d5c-4c0c-11e5-9951-62cd333669b6.png)

Again - nice work so far!

**Comment by carodew** [comment]
By the way, we've been in major focus mode on the project, so apologies for not getting back to you earlier. But this looks really great! Thank you for sharing! Also pinging @mollieru and @angel re: your notes on the typography.

**Comment by maya** [comment]
@cew821 just checking in if this is still an issue, we've since made changes to the text height.

**Comment by carodew** [comment]
Closing this issue since we've increased the line height since it was created.

**Comment by cew821** [comment]
I'd love folks to take a look at this PR with a hopefully "shippable" implementation of the standards on the Playbook:

https://github.com/usds/playbook/pull/161
