### ISSUE TITLE
As a designer building a footer for a gov website, I would like the footer elements to be aligned at the baselines.

### ISSUE THREAD

**Issue by jenniferthibault** [18F/web-design-standards#373]
Hi there,

I hope I framed the issue title correctly—but please feel free to relabel. Mostly, I'm here with some feedback on the footer element as we've been implementing it. If there is a better outlet for this feedback, please send me there instead, and thank you for reading.
#### Description

I'm using the early Big/Medium footer layout to design the footer features of the new FEC site. I've found that the suggested placement of the seal and agency name creates a slightly awkward layout. This is perhaps due to 2 things that I can see now: 
- The "Name of Agency" text falls well below the baseline of the corresponding text on the right side of the footer (See screenshots of current & suggested change below). In a footer with few visual elements, my eye is drawn toward bottom alignment to help ground the page, rather than top
- "Name of Agency" Placeholder text perhaps doesn't accurately account for the (long) length of most government agency full names. I could see any agency or group that needs the word "Department of...." having an issue with this as well
- This may be better suited to a separate issue, but when navigating the site to find the footer as a reference, I'm often confused about why "Footer" is not next to "Header" in order. As a result, even after visiting the site at least 3 or 4 times to look at the footer, I have a hard time finding it. (See screenshots below)
#### Ask

Align the Agency Name text with the baseline of the right-side contact text. Consider re-ordering the navigation menu so that "Footer" is immediately after "Headers & Navigation" in order.
#### Additional Info

Footer designed according to template, and with suggested changes (with and without guides shown):
![screen shot 2015-08-26 at 7 00 27 pm](https://cloud.githubusercontent.com/assets/11636908/9508560/8ec4e556-4c24-11e5-9791-efeb3987f299.png)

Current navigation order:
![screen shot 2015-08-26 at 6 51 56 pm](https://cloud.githubusercontent.com/assets/11636908/9508573/b029bc12-4c24-11e5-89b6-18e1e527178a.png)

Here is how we will likely be using the design that accommodates the long agency name, and feels more like a light logo lockup than just text as a title:

![screen shot 2015-08-26 at 7 05 02 pm](https://cloud.githubusercontent.com/assets/11636908/9508627/28a1ae20-4c25-11e5-812e-dac46147462d.png)

Thank you for listening!

**Comment by msecret** [comment]
One solution: we could put a max-height on the logo to ensure the height of both will line up to the content on the right side.

**Comment by colinpmacarthur** [comment]
@jenniferthibault: I can't speak to the design questions, but in response to:

> I'm often confused about why "Footer" is not next to "Header" in order. As a result, even after visiting the site at least 3 or 4 times to look at the footer, I have a hard time finding it. (See screenshots below)

We agree! The next iteration of the project's navigation has the header and footer links next to each other.

cc: @carodew

**Comment by carodew** [comment]
Thanks @jenniferthibault ! I added a link to this GH issue to the relevant Trello card that represents the work to rejigger the side nav.

**Comment by jenniferthibault** [comment]
I should have known you folks would already be on top of it :+1:

**Comment by donjo** [comment]
Version 1.4 came with a number of footer spacing adjustments which can be seen in action [here](https://components.standards.usa.gov/components/detail/footer--big.html) so this issue may no longer be relevant. If there are additional concerns, feel free to re-open or open a fresh issue.
