### ISSUE TITLE
Disabled button tappable on iPad 2 (iOS 8.4)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#392]
When I tap the disabled button on my iPad 2, a tap shadow appears behind it. Active buttons show a tap shadow, but I don’t think the disabled one should.

Video: https://drive.google.com/a/gsa.gov/file/d/0BzVTh-jwYUTHX0gzd1ZCSjhCbFE/view

**Comment by carodew** [comment]
Correct behavior is that the disabled button is not tappable and that no tap shadow appears.

**Comment by carodew** [comment]
Closing this since we're tracking the same issue in #493
