### ISSUE TITLE
[Dropdown] duplicate focus border within dropdown box in Firefox

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#411]
**Steps to recreate:**

In Firefox, click on the dropdown box to set focus. The correct focus styling appears (the blue halo) but another focus style appears as a thin dotted line inside the dropdown box. 

<img width="406" alt="screen shot 2015-09-03 at 1 33 32 pm" src="https://cloud.githubusercontent.com/assets/10144074/9665845/e01cb4ac-5240-11e5-903c-a321c9e287f6.png">

**Expected behavior:**
Would expect that the thin dotted line would not appear on focus, and you would only see the blue halo. 

**Tested in**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by carodew** [comment]
When we do tackle this after MVP we should see if this shows up on other websites.

**Comment by juliaelman** [comment]
Possible solve found here: http://stackoverflow.com/questions/3773430/remove-outline-from-select-box-in-ff

**Comment by maya** [comment]
This can be fixed with:
```
select:-moz-focusring {
    color: transparent;
    text-shadow: 0 0 0 #000;
}
```

via https://stackoverflow.com/questions/19451183/cannot-remove-outline-dotted-border-from-firefox-select-drop-down#answer-19451423
