### ISSUE TITLE
[Range Slider] extra focus border and wrong color on slider bar in Firefox

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#412]
**Steps to recreate:**

In Firefox, click anywhere on the range slider to set focus. The correct focus styling appears (the blue border on the round button slider) but another focus style appears as a thin dotted line surrounding the entire slider. 

Also, the slider bar background color is blue, when it should be gray. 

**Firefox:**
<img width="954" alt="screen shot 2015-09-03 at 1 41 54 pm" src="https://cloud.githubusercontent.com/assets/10144074/9666053/d877d7a8-5241-11e5-9d12-9139894992b9.png">

**Expected behavior:**
Focus state should not have a thin line around the entire slider. 
Slider bar should be gray, not blue. We're using blue to indicate an active state, which does not apply to the slider bar. 

(see screenshot from Chrome below for reference)

<img width="497" alt="screen shot 2015-09-03 at 1 45 17 pm" src="https://cloud.githubusercontent.com/assets/10144074/9666079/0f17e528-5242-11e5-987e-4ef4f3ea7a24.png">

**Tested in**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by maya** [comment]
The site doesn't include a range slider anymore so closing this out.
