### ISSUE TITLE
[Reset Password Form] Show/hide my typing toggle only works on one password field

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#414]
**Steps to recreate**

On the reset password form, fill in both fields and click on the show/hide toggle. Only the top password field toggles between showing and hiding the text. 

![password-show-typing-bug-ff](https://cloud.githubusercontent.com/assets/10144074/9668473/b30d36da-524f-11e5-9208-8046a51acc05.gif)

**Expected behavior**
Both fields should toggle between text visible and masked. 

**Tested in**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by maya** [comment]
@carodew I just tested this and didn't see the issue like you did. Can you confirm if you're still getting this?

![](http://g.recordit.co/xW9AWAfxhv.gif)

**Comment by carodew** [comment]
Seems to be fixed, closing the issue. Thanks for following up!
