### ISSUE TITLE
[Buttons] do not have rounded corners on IE 8

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#426]
**What happens:**
On IE 8, the buttons have rectangular (non rounded corners):

*Buttons in the header*
<img width="311" alt="screen shot 2015-09-02 at 9 25 04 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693029/353dad94-531b-11e5-8ce7-14e0304688db.png">

*Buttons in "button" section*
<img width="110" alt="screen shot 2015-09-02 at 9 34 53 pm" src="https://cloud.githubusercontent.com/assets/2092076/9692980/ceb018a0-531a-11e5-872b-714402e1ee84.png">

**What I expect to happen**
Buttons to be formatted like they are on other browsers:

<img width="305" alt="screen shot 2015-09-04 at 3 38 07 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693001/f4ad0a40-531a-11e5-811a-27c11be7e71d.png">

<img width="99" alt="screen shot 2015-09-04 at 3 38 20 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693020/214cb370-531b-11e5-9b4c-7473d015dbda.png">

**Found on:**
- Windows 7, Internet Explorer 8 emulated on SauceLabs

**Comment by cvrebert** [comment]
IE8 doesn't support `border-radius` for native CSS rounded corners: http://caniuse.com/#feat=border-radius

**Comment by maya** [comment]
Correct, and also: http://dowebsitesneedtolookexactlythesameineverybrowser.com/

**Comment by maya** [comment]
Closing bc this is the expected behavior in IE8. Thank you @cvrebert.
