### ISSUE TITLE
[Labels] don't have rounded edges in IE 8

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#429]
**On IE 8:**
<img width="61" alt="screen shot 2015-09-02 at 9 37 04 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693456/9caf5ad8-531e-11e5-8e7c-c50ffd3ca5e4.png">

**Expected (from Chrome 44):**
<img width="70" alt="screen shot 2015-09-04 at 4 04 41 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693466/ac6458de-531e-11e5-8526-110bd5837157.png">

**Found on:**
- Windows 7, IE 8, emulated on Sauce Labs

**Comment by cvrebert** [comment]
IE8 doesn't support `border-radius` in the first place: http://caniuse.com/#feat=border-radius

**Comment by maya** [comment]
Correct, and also: http://dowebsitesneedtolookexactlythesameineverybrowser.com/

**Comment by maya** [comment]
Closing bc this is the expected behavior in IE8. Thank you @cvrebert.
