### ISSUE TITLE
[Checkboxes] don't appear in IE 8

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#434]
**On IE 8:**
<img width="199" alt="screen shot 2015-09-03 at 4 55 16 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693890/f707e204-5321-11e5-861c-000a28771f88.png">

**Expected (from Chrome 44):**
<img width="588" alt="screen shot 2015-09-04 at 4 28 51 pm" src="https://cloud.githubusercontent.com/assets/2092076/9693900/145b71ea-5322-11e5-8e74-157119db4657.png">

**Found on:**
- Windows 7, IE 8 on Sauce Labs

**Comment by robinwhittleton** [comment]
This also affects radios. I’ve made a PR that fixes this issue in IE8: https://github.com/18F/web-design-standards/pull/692
