### ISSUE TITLE
[Side navigation] Side navigation has horizontal scroll bar at the bottom in IE 11

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#442]
**Steps to reproduce**

Open the site in IE 11. Look to the bottom left corner. There is a disabled horizontal scroll bar on the side navigation. 

<img width="888" alt="screen shot 2015-09-08 at 12 14 12 pm" src="https://cloud.githubusercontent.com/assets/10144074/9740619/a73d36d4-5623-11e5-96b9-c7b8af40b170.png">

**Expected behavior**
I would not expect a horizontal scroll bar to appear there since there is no horizontal scroll on the side nav.

**Tested on**
IE 11 
Windows 10 
in SauceLabs

**Comment by maya** [comment]
I'm not seeing this in IE11 on Browserstack. Is it still an issue?

<img width="825" alt="screen shot 2016-02-05 at 5 15 52 pm" src="https://cloud.githubusercontent.com/assets/5249443/12863552/3aeda8fe-cc2c-11e5-967d-af553da0a249.png">
