### ISSUE TITLE
[Typography] Vertical line spacing seems tight in specific areas in IE11

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#445]
**Steps to recreate**

Open the site in IE 11 and navigate to the Typography section. Open one of the accordion sections for the type pairing options. Look at the Web Hierarchy header – it seems too close to the list above it. Look at the code snippets. The top of this feels too close to the horizontal bar above. 

<img width="889" alt="screen shot 2015-09-08 at 1 16 46 pm" src="https://cloud.githubusercontent.com/assets/10144074/9742072/0bd61e96-562c-11e5-9153-f81c13d7da6d.png">

**Expected**
I would expect more vertical spacing in these areas. 

**Tested on**
IE 11
Windows 10
SauceLabs

**Comment by jpyuda** [comment]
To my eye, there's also not enough spacing in Chrome (though it's not as extreme as the screenshot above)

**Comment by maya** [comment]
@carodew this a standards site-only issue and a style issue and would move it to "low". This is not browser specific. 

It's bc @msecret implemented a margin-bottom = 0 for `last-child` elements in order to get consistent spacing for the last items in the accordion to the bottom of the accordion. This works for flat structure in accordions, but not when we start adding grid items into it. I'll defer to @msecret to decide the best course of action forward.

**Comment by carodew** [comment]
My concern is that if the site itself is buggy, users will consider that an indication of the quality of code that went into the component. That would be a shame, because I know how much effort you've put into it, but people make these knee jerk judgements all the time. 

We thought this warranted a medium because it is a typographic problem on the typography page, which seemed to make it more problematic than it would be had it appeared in another part of the site.

**Comment by jpyuda** [comment]
True that it affects the site more than the components, but:
* given that it's the typography page, poor typography makes us lose credibility
* this would affect any structured content within an accordion... which seems like something people would do with the components

**Comment by maya** [comment]
@jpyuda definitely, for the second bullet. Going to assign this to @msecret for the reasons above.

**Comment by carodew** [comment]
And @angel can probably consult on the issue as well.

**Comment by msecret** [comment]
Fixed by https://github.com/18F/web-design-standards/pull/506
