### ISSUE TITLE
[Text inputs] Focus halo is very faint in IE 11

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#447]
**Steps to replicate**

1. Open the site in IE11 and navigate to form controls/text inputs
2. Click into any text box
3. observe that the blue halo is very faint. 

<img width="548" alt="screen shot 2015-09-08 at 1 55 20 pm" src="https://cloud.githubusercontent.com/assets/10144074/9742903/4e50cad2-5631-11e5-88f7-36719b0cf731.png">

**Expected behavior**
I would expect the blue halo to be more obvious, like it is in Chrome. 

<img width="501" alt="screen shot 2015-09-08 at 1 57 38 pm" src="https://cloud.githubusercontent.com/assets/10144074/9742955/9a4a749c-5631-11e5-8b04-082bf0257032.png">

**Tested on**
IE 11
Windows 10
SauceLabs

**Comment by carodew** [comment]
Possibly related to #443

**Comment by maya** [comment]
@carodew this is also a browser specific issue with how IE renders box-shadows. I think we either implement a different focus style for all or leave this be. Will defer to @angel for alternate styles. 

I'm not sure if this feels like a medium level too.

**Comment by carodew** [comment]
We left it at medium because we worry that IE11 could be difficult for keyboard users if they can't clearly see the focus outline. 

I'm still digging into the issue—I saw this on an emulator in SauceLabs and ideally we could see what it looks like on the native browser. I don't suppose anyone has access to IE11? Thoughts @jpyuda @mollieru ?

**Comment by carodew** [comment]
@mollieru to check this at work.

**Comment by mollieru** [comment]
@carodew on IE11 the focus state appears as designed. No faintness.
