### ISSUE TITLE
[Range slider] slider button does not display correctly in IE 11

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#448]
**Steps to recreate**

1. Open the site and navigate to the range slider. 
2. Observe that the slider button top and bottom are cut off. 
3. Move the button around the slide and observe that the display is still incorrect. 

![ie 11 range slider](https://cloud.githubusercontent.com/assets/10144074/9743064/4985d71c-5632-11e5-8599-3dd5fbaff694.gif)

**Expected**
I would expect the range slider button to appear as a whole button.

**Tested on**
Windows 10
IE 11
SauceLabs

**Comment by colinpmacarthur** [comment]
Replicated in IE 10:

![](https://s3.amazonaws.com/f.cl.ly/items/283j1U3G1z290M0i1G2i/Image%202015-09-10%20at%207.36.48%20PM.png)

**Comment by maya** [comment]
The site doesn't have a range slider anymore so closing this.
