### ISSUE TITLE
[Date input] Show error validation on date input

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#449]
**Steps to recreate**
1. Open the site in IE 11 and navigate to the date input. 
2. Type in a number greater than 12 in the month box, or a number greater than 31 in the day box. 
3. No error validation appears (in the screenshot below, 20 is not a valid input for month). 

<img width="309" alt="screen shot 2015-09-08 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/10144074/9743550/fa9b9cec-5634-11e5-8206-6781cba43dd3.png">

**Expected**
Not sure. In a predictable world, I would expect a red outline to appear to show that there is an invalid input. However the above may be the expected behavior in an IE 11 world. 
**Tested in**
IE 11
Windows 10
SauceLabs

**Comment by carodew** [comment]
Changing this to an enhancement since (per our discussion) it hasn't been implemented yet.

**Comment by jpyuda** [comment]
This seems like the expected behavior, but doesn't appear to have ever been implemented. We can discuss whether we can fit in any enhancements on the off chance that we have a light finding of bugs. (Or, we might decide that certain enhancements are relatively easy and more important than some purely cosmetic bugs)

**Comment by bensmoif** [comment]
Verified on Chrome as well. 
Inputs like these (multiple fields on a single line for example: social security #s, phone #s, dates) could be termed "inline inputs"
I'm unsure what the error state should be if any one of these inline inputs. Does the red left border show on the line? Does the one offending input get the red border? How do we direct the user to the one or multiple problematic inputs that are part of the same set of input (on the same line)?

**Comment by carodew** [comment]
Related to #751

**Comment by maya** [comment]
Fixed in #1251.
