### ISSUE TITLE
[Search bar] Search bar input is not wide enough on IE 11 on 1024x768 screen

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#459]
**Steps to recreate**
1. Open the site in IE11 and navigate to the search bar (set screen to 1024x768). 
2. Type in the phrase "how all these mistaken ideas" into each search bar. The entire phrase is 27 characters long, about what we'd want to be able to see at once in the search bar. 
3. Note that IE 11 inserts an "&times;" symbol to clear the input, which takes up additional space. 

<img width="352" alt="screen shot 2015-09-09 at 10 21 48 am" src="https://cloud.githubusercontent.com/assets/10144074/9764540/9f581b0e-56dd-11e5-8b40-b26fc2f2b3a9.png">
<img width="335" alt="screen shot 2015-09-09 at 10 21 38 am" src="https://cloud.githubusercontent.com/assets/10144074/9764539/9f57ecba-56dd-11e5-9c4a-68a9bdc465d7.png">
<img width="311" alt="screen shot 2015-09-09 at 10 21 28 am" src="https://cloud.githubusercontent.com/assets/10144074/9764541/9f6131b2-56dd-11e5-9493-014e39dacb42.png">

**Expected behavior**
I would expect to be able to read the entire phrase. 

**Tested in**
IE 11
Windows 10
SauceLabs

Chrome

**Comment by iluvtatortots** [comment]
I'd like to take a look into this :)

**Comment by bradnunnally** [comment]
@iluvtatortots Awesome! Let me know how it goes and if you have any questions.

**Comment by iluvtatortots** [comment]
@bradnunnally Help! How do I bug you? Are you in the slack channel?

**Comment by bradnunnally** [comment]
@iluvtatortots Just wave at me! I'm sitting over by the wall.

**Comment by donjo** [comment]
These search bars are more responsive now which I believe resolves some of the issues. Also a greater min-width may have been added at some point because I was able to see the entire text and then some with a 900px wide window.
