### ISSUE TITLE
Figure out why selectivisr.js is not working

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#462]
This will allow us to use CSS3 properties, like `last-child`.

See: http://selectivizr.com/

This effects the grids issue: https://github.com/18F/usfwds/issues/428 as well as anything using the grid in **IE8**, like the footers #473.

**Comment by msecret** [comment]
I think we should time box searching for a solution to this to about 3/4 of a day. If we haven't found a solution in that amount of time, I think we should actually have a conversation about dropping IE8 support for the MVP and first release.
