### ISSUE TITLE
[Buttons] Not all buttons are the right width at mobile screen sizes

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#463]
The disabled button and big button don't expand to full width like the rest:

![buttons_not_100__full_width](https://cloud.githubusercontent.com/assets/2092076/9772356/aa3eeec2-5709-11e5-84c0-631c864fdedf.png)

Found by @maya in the Chrome 44 mobile device emulator.

**Comment by maya** [comment]
@msecret since you worked on buttons, would you like to take this one on?

**Comment by colinpmacarthur** [comment]
This also appears on the home page:
![screen shot 2015-09-15 at 11 10 10 am](https://cloud.githubusercontent.com/assets/2092076/9884246/c5e5f1b4-5bac-11e5-82b7-a8ebc0e4dcc2.png)

**Comment by maya** [comment]
@colinpmacarthur the homepage outline button was resolved in #608.

The big button and disabled button are still issues.

**Comment by chinaowl** [comment]
I started to take a look at this, but got stuck. It seems like the width of the button depends on how many buttons there are inside `button_wrapper`. In the image below, I added another default button and another big button. The width of the big button now looks correct, but the default button is a little bit too short:

![image](https://cloud.githubusercontent.com/assets/2628718/14335042/2b0e5fee-fc0d-11e5-8b19-1e707789f544.png)

Now when I add another default button for a total of three, the width for default buttons looks correct:

![image](https://cloud.githubusercontent.com/assets/2628718/14335079/7c70d0e2-fc0d-11e5-901e-c2d5c087141f.png)

Removing `display: table` from `button_wrapper` makes the width consistent regardless of the number of buttons, but doing that has other side effects.

I don't have a solution, just wanted to share what I discovered.

@maya @msecret

**Comment by brendansudol** [comment]
this actually isn't a disabled / big button specific issue. When there are less than **3** button elements within a  `button_wrapper`, the widths are not 100%; changing the `button_wrapper` display property from `table` to `block` should fix this (I don't see any ill side effects).

**Comment by chinaowl** [comment]
@brendansudol thanks, I can try that out and submit a PR.

**Comment by maya** [comment]
Fascinating, thanks so much @chinaowl and @brendansudol, this was a total mystery to us! :tada:

**Comment by maya** [comment]
Fixed in #1101.
