### ISSUE TITLE
[Text input] box with error is not correct width at mobile screen sizes

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#464]
The "error" text input box is not the same width as the other text inputs at mobile screen sizes:

![error_input_not_100__full_width](https://cloud.githubusercontent.com/assets/2092076/9772402/fd793f20-5709-11e5-86d5-519ae2c63943.png)

Found in Chrome 44 mobile device emulator by @maya.

**Comment by jpyuda** [comment]
If you open a desktop browser and change width, you'll notice the error field shrinks a bit sooner than the other ones.
