### ISSUE TITLE
Background images not showing in old IE

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#472]
The background-image property does not exist in IE8, so we need to figure out another way to get it to show.

One idea was to use this rule for old IE:
`background: url('/images/cartWhite.png') 18px 11px no-repeat;`

This effects the following issues:
#436 
#431 
#430
#434

**Comment by carodew** [comment]
@jpyuda and I discussed in triage and still think we should fix things in IE 11 first (as it has the highest number of visits to DAP sites by far) and work through other versions as those are completed.

**Comment by maya** [comment]
Closing as we do not support older IE anymore.
