### ISSUE TITLE
Tweak alignment in of text site footer

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#477]
Align left-justified footer with left edge of page content (I believe that's a 51px margin)

Also, @angel  can you advise on where you think the right edge of the footer text should end? We've got kind of a jagged thing going at the moment where it's lining up w neither the accordion nor right edge of buttons in the header. (screenshot below for reference).

Context of the convo here: https://trello.com/c/DDVfZ94q/297-1-component-page-revise-page-layout-to-match-v2-designs

**Comment by angel** [comment]
@mollieru did you want the "As a work of the government..." to right align with the button?

**Comment by carodew** [comment]
We'll be taking a fresh look at the footer design based on new feedback and information, so issues related to the current footer will be moot moving forward. Closing these out for now.
