### ISSUE TITLE
[visual style guide] reduce spacing between 'download' button and small text underndeath

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#478]
There should be 10px margin between the bottom of the button and top of the text. 

@maya says "There's weird p tag getting inserted that's causing this. It's a bug that we'll have to investigate further down the road. Only happens on this page."

Current spacing:
![screen shot 2015-09-10 at 10 56 51 am](https://cloud.githubusercontent.com/assets/3680494/9791754/aecc1c2a-57aa-11e5-8bef-de61eda02381.png)

Spacing as designed:
![image](https://cloud.githubusercontent.com/assets/3680494/9791741/99198502-57aa-11e5-9d0d-6f91f68be6e0.png)

**Comment by maya** [comment]
I think there is likely an unclosed HTML tag on this page bc it sounds similar to: https://github.com/jekyll/jekyll/issues/2313

**Comment by maya** [comment]
Closed via #838.
