### ISSUE TITLE
"Skip to content" link does not bring focus to content

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#482]
**Steps to replicate:**
1. Open http://pages-staging.18f.gov/usfwds
2. Hit tab until the "Skip to main content" link appears.
3. Push return or the space bar.
4. Hit tab again. The focus will not travel to content in the main section of the page, but to the download buttons in the header. If you hit tab repeatedly, you'll be hitting the navigation.

**Ideal behavior:** When you hit tab, the focus would be taken to the next focus-able element in the content of the page.

**Video:**
http://cl.ly/image/1K1x321J0E1r

**Found on:**
- IE 10, Windows 7 on Sauce Labs
- Chrome 44, Mac OS X Yosemite

**Comment by jpyuda** [comment]
This seems to work _inconsistently_ for me in Chrome. Sometimes it scrolls, sometimes it does not.

**Comment by carodew** [comment]
@maya, @msecret, @vgvg – if you know what's going on right away feel free to tackle this as you are able. If it's slightly unclear what is going on and what the fix is, let @jpyuda @colinpmacarthur and I investigate further for you.

**Comment by maya** [comment]
@colinpmacarthur I fixed the link in #498. Correction, you wouldn't hit spacebar, you'd hit enter. Part of the content gets hidden but that's bc we have a fixed header that covers it up. 

I don't think skipnav has anything to do with tabbing, it just skips you to the main content area of the page, visually skipping through navigation, but not even sure if it makes sense bc the content starts immediately, and we have a fixed header.

**Comment by jpyuda** [comment]
It needs to move focus to the beginning of `#main`, not just visually move it. The primary use case is screen reader users (so they don't have to tab through a couple dozen links).

In general, we need to make sure we're moving focus to the correct part of the page when doing things in javascript. Not correctly managing focus is a common accessibility problem.

**Comment by maya** [comment]
@jpyuda are you saying we should implement this with JavaScript? Can you send over an example that does it in the way you describe?

**Comment by jpyuda** [comment]
Not at all! If we just implement it with the standard HTML behavior, we should get the focus shift for "free". More making a note in case there are places where we're overriding that behavior with js.

**Comment by maya** [comment]
@jpyuda I thought this was being implemented in the standard HTML way. Is there something that looks off to you with how it's done?

**Comment by jpyuda** [comment]
I was assuming we were doing something with JS based on the fact that the focus is not correctly moving. Are we sure there's an `id="main"` on every page?

**Comment by KimberlyMunoz** [comment]
There's a webkit bug that causes focus not to [move correctly on skip links](https://www.nczonline.net/blog/2013/01/15/fixing-skip-to-content-links/). It looks like the issue has been [fixed in Chromium nightly](https://code.google.com/p/chromium/issues/detail?id=37721), but I haven't seen it pushed out to the latest stable version and [we're using JS from the myRA project](https://github.com/18F/myra/blob/gh-pages/static/js/init.js#L19) to move the focus for now.

**Comment by maya** [comment]
Thanks so much @KimberlyMunoz! We are adding that in https://github.com/18F/web-design-standards/pull/519.

**Comment by maya** [comment]
Fixed via #519.
