### ISSUE TITLE
[Password reset] Submit button jumps when show/hide password is toggled in Chrome

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#484]
**Steps to reproduce**
1. Go to password reset form
2. Click on the show/hide toggle. 
3. The Reset Password button changes position. 

![jumpingbutton](https://cloud.githubusercontent.com/assets/10144074/9801330/6403b8a2-57e0-11e5-822f-4fe64ff6aea3.gif)

**Tested in**
Chrome
Does not happen in Firefox

**Comment by maya** [comment]
Adding a `display: block` to the button should resolve this.

**Comment by maya** [comment]
Just looked again and not seeing this issue. This is what I see:

![](http://g.recordit.co/EKnMdU6jIX.gif)

**Comment by carodew** [comment]
@maya it's on the password reset form, not the sign-in form. :)
