### ISSUE TITLE
[Buttons] disabled button is clickable

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#493]
**On IE 10,** the disabled button is clickable:

![IE 10](https://s3.amazonaws.com/f.cl.ly/items/031i3w3g2814102L082p/Screen%20Recording%202015-09-10%20at%2002.58%20PM.gif)

Found on:
* IE 10, Windows 7, Sauce Labs
* iPad
* iPhone

**Comment by jpyuda** [comment]
Button does not appear to actually have `disabled="disabled"` set

**Comment by carodew** [comment]
Would be higher if we knew it submitted a form on accident but we don't know that at this point.

**Comment by maya** [comment]
@colinpmacarthur this is the default behavior for buttons in IE, to shift when clicked. Do you want it removed for all? We don't do this in any other browsers.

**Comment by maya** [comment]
Also this is only for button elements, so maybe you can add something in the documentation, that they need to add the `disabled` attribute?

We wanted this to be usable for any way someone want to use a button, and many people use anchor links and want this style. Another idea is we switch all of our buttons to use anchor links in the example. Bc we don't want that attribute in anchor links. cc @jpyuda

**Comment by jpyuda** [comment]
Links that look like buttons (and vice versa) can be a whole thing, because buttons and links actually behave slightly differently in the browser. Hmm..

**Comment by maya** [comment]
I actually think we should add `disabled` attribute here bc that demonstrates it's unusable and un-clickable.

**Comment by carodew** [comment]
+1

**Comment by patrickcate** [comment]
I would suggest adding `pointer-events: none` to the `usa-button-disabled` class and button `disabled` attribute so hover and click events are not registered. Browser support for the CSS property is pretty good:
http://caniuse.com/#feat=pointer-events
