### ISSUE TITLE
[Log in] after show/hide, number of dots in password field doesn't match length of what's entered in IE10

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#494]
**Steps to reproduce**
1. Open https://pages-staging.18f.gov/usfwds/form-templates/#login-form in IE 10
2. Type a password into the box.
3. Push the "Show password" link.
4. Push the "Hide password" link.
5. The number of dots in the password field does not match what was entered.

**Ideal behavior**
The number of dots stays the same after showing and hiding.

**Video**
![](https://s3.amazonaws.com/f.cl.ly/items/0u2N0Q0L1j1o2J0q1G37/Screen%20Recording%202015-09-10%20at%2007.49%20PM.gif)

**Found on**
- IE 10, Windows 7 on SauceLabs

**Comment by maya** [comment]
Something strange happens, the dots cut off. I typed in 5 characters in the top and 4 on the bottom field. You can see they're partially hidden.

<img width="404" alt="screen shot 2016-02-05 at 5 07 29 pm" src="https://cloud.githubusercontent.com/assets/5249443/12863457/1d5d52a4-cc2b-11e5-8994-e47ad9a134d7.png">

**Comment by maya** [comment]
I just tested again in IE 10 and not seeing this problem. 

![](http://g.recordit.co/bdSt3xAEKB.gif)
