### ISSUE TITLE
[Footer] Focus disappears after tabbing to each social media icon

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#495]
**Steps to reproduce:**
1. Tab to the Facebook icon in the footer.
2. Push tab again.
3. The focus disappears.
4. Push tab again and the focus reappears on the next icon.

**Ideal behavior:**
Push tab once to move between icons.

**Video:**
![](https://s3.amazonaws.com/f.cl.ly/items/3n0h1o3h321g0b343O2c/Screen%20Recording%202015-09-10%20at%2008.05%20PM.gif)

**Found on:**
- Chrome 44, Mac OS 10.10.5 on SauceLabs
- IE 10, Windows 7 on SauceLabs

**Comment by carodew** [comment]
None of us could replicate this during triage, so Colin is going to try again and see if we can replicate it. If not, will close.

**Comment by colinpmacarthur** [comment]
I can no longer replicate. Closing.

**Comment by carodew** [comment]
Weird thing – I just replicated it on IE 11 in SauceLabs. ¯\_(ツ)_/¯
