### ISSUE TITLE
Figure out if it's possible to create 60px padding above certain h3s f

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#503]
A few of the h3s on the site still have only 30px space between them and the element above. The space should be 60px total to allow for comfortable breathing room. 

![screen shot 2015-09-11 at 2 30 02 pm](https://cloud.githubusercontent.com/assets/3680494/9823022/c6b40da6-5891-11e5-80c8-d87c1e61cb17.png)

Here are the instances of h3 that could use additional space above:

> Typefaces
> Pairings + Styles
> Palette
> Form Controls/Accessibility
> Form Templates/Accessibility

**Comment by lmarkzon** [comment]
I'm looking into this issue!

**Comment by bradnunnally** [comment]
@lmarkzon Awesome! Let me know how it goes and if you have any questions.

**Comment by llolly** [comment]
unsubscribe

‏في الجمعة، ١٧ يونيو، ٢٠١٦, Brad Nunnally <notifications@github.com> كتب:

> @lmarkzon <https://github.com/lmarkzon> Awesome! Let me know how it goes
> and if you have any questions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/web-design-standards/issues/503#issuecomment-226804912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKoR4XaLDjQP8QvWRhvYrmrrS8A-d1qvks5qMsDVgaJpZM4F8A1Y>
> .
>


-- 
❤️llolly

**Comment by fureigh** [comment]
@llolly Hey there! If you'd like to unsubscribe from notifications, click the `Watch` button in the upper right and select `Not watching` or `Ignoring`.

<img width="1003" alt="screen shot 2016-06-17 at 11 06 11 am" src="https://cloud.githubusercontent.com/assets/1244599/16156539/68a8bd0e-347a-11e6-85d9-c6699408f3d3.png">

**Comment by lmarkzon** [comment]
@bradnunnally or whoever knows - Question regarding the local setup instructions on the contributing.md page: 

after the commands to download npm/gulp do you need to enter "gulp build" **and** "gulp website:build" before gulp:website serve? Or just one of the commands?

**Comment by juliaelman** [comment]
@lmarkzon great question and apologies for the confusion!

It depends on what you are trying to do. If you are only wanting to build the site itself, just run `gulp website:build`. To be able to view the compiled site locally, run `gulp website:serve` which is what you will use to view any changes you make. It also watches as you make changes/save files and re-compiles the site when that happens.

**Comment by lmarkzon** [comment]
@juliaelman Thank you, so what's the difference between `gulp build` and `gulp website:build` ? Sorry for all the questions - just curious!

**Comment by juliaelman** [comment]
@lmarkzon no worries and happy to answer questions anytime! 😄 

`gulp build` builds the distribution directory.

`gulp website:build` builds the [Jekyll](https://jekyllrb.com/) website and compiles the assets needed for the site.

**Comment by lmarkzon** [comment]
@juliaelman thank you! that makes sense!

**Comment by maya** [comment]
Closed via #1284.
