### ISSUE TITLE
Focus disappears after tabbing to "View the standards" button on the homepage

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#525]
**Steps to recreate**
1. Open http://pages-staging.18f.gov/web-design-standards in IE 10
2. Hit the tab key until the focus is on the "View the standards" button.
3. Hit tab again; the focus disappears.
4. Hit tab again; the focus reappears in the next "View the button" component.

**Expected behavior**
When focus is on the first "View the standards" button, hitting tab again should move the focus to the "Download the components" button.

**Found on**
- SauceLabs, Windows 7, IE 10

**Comment by carodew** [comment]
Also IE 11. I'm guessing this is not a browser specific bug.

**Comment by jpyuda** [comment]
Also does this in Firefox.

**Comment by carodew** [comment]
Possibly related to #539

**Comment by carodew** [comment]
The issue seems to be on the Download the Components button: 

<img width="771" alt="screen shot 2015-09-18 at 3 51 19 pm" src="https://cloud.githubusercontent.com/assets/10144074/9969575/4438510c-5e1d-11e5-8892-1da151ad4b76.png">

**Comment by maya** [comment]
This is an issue with using box-shadow for the outlines, will look into it.
