### ISSUE TITLE
[homepage] focus style appears in wrong place for example sites

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#528]
**Steps to recreate**
1. on the homepage, tab to the examples section. 
2. note that focus halo appears as a seemingly random bar underneath the example image

<img width="838" alt="screen shot 2015-09-15 at 11 22 07 am" src="https://cloud.githubusercontent.com/assets/10144074/9881035/3cacfdb2-5b9c-11e5-923a-d50f37ac5012.png">

**Expected behavior**
I would expect the focus halo to be around the example URL above the image, and/or on the image itself. 

**Tested on**
SauceLabs
Windows 10
IE 11

Also on Chrome

**Comment by colinpmacarthur** [comment]
Also happens on Windows 7, IE 10.

**Comment by maya** [comment]
I think this may be bc we have a heading inside of the anchor link.

**Comment by jpyuda** [comment]
We'll want to fix this one once we have examples that are using the style guide. But I don't want to prioritize fixing it until we need it -- we can just delete the section if we have no examples.

(I hope we have examples.)

**Comment by mollieru** [comment]
@jpyuda now that examples are in, should we fix this?

**Comment by maya** [comment]
Not an issue anymore since we are linking the text only.
