### ISSUE TITLE
Javascript error on page load in Firefox

### ISSUE THREAD

**Issue by jpyuda** [18F/web-design-standards#529]
The error is:
`Empty string passed to getElementById().`

**Comment by maya** [comment]
@jpyuda It says it's coming from jQuery.

**Comment by jpyuda** [comment]
It's throwing the error in jQuery, but it's very unlikely that it's an issue in jQuery. Most likely we're not correctly setting a variable somewhere and are passing in `null` when we think we're passing in a string.

**Comment by vgvg** [comment]
Turns out that `$("#")` will cause this in FF (but not Chrome). However, `$("")`, `$("idonotexist")` or `$(null)` do not.
