### ISSUE TITLE
[Sidebar] Focus does not move to link target when using via keyboard secondary link in sidebar

### ISSUE THREAD

**Issue by jpyuda** [18F/web-design-standards#530]
To reproduce:

1. Open any style guide page that has second-level navigation (i.e. Form Templates)
2. Tab to a link in the sidebar (i.e. Address Form)
3. Hit enter - the page will scroll to that anchor, but focus stays in the sidebar. It should move to the anchor.

**Comment by jpyuda** [comment]
The same thing we did for the skip navigation link should work for this -- just need to generalize it.

**Comment by maya** [comment]
Fixed via #621.
