### ISSUE TITLE
[Homepage] "Learn More" link in header doesn't go anywhere

### ISSUE THREAD

**Issue by jpyuda** [18F/web-design-standards#535]
The one related to being in alpha.

**Comment by carodew** [comment]
should go here: https://18f.gsa.gov/dashboard/stages/#alpha

**Comment by jpyuda** [comment]
<img width="286" alt="screen shot 2015-09-15 at 4 22 40 pm" src="https://cloud.githubusercontent.com/assets/552095/9888968/0cc19f48-5bc6-11e5-96f2-9b7a485acadb.png">

This link. Only on the homepage.

**Comment by mollieru** [comment]
@colinpmacarthur can you recall how you'd recommended we resolve this?

**Comment by colinpmacarthur** [comment]
Hmm. Don't think I ever weighed in on this one (but I could be forgetting). I agree with the link Carolyn suggests.

**Comment by maya** [comment]
Resolved in #602.
