### ISSUE TITLE
[Homepage] "or view the standards" link in 'Contribute' section doesn't go anywhere

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#538]
Last link below the button at the bottom isn't working:
![screen shot 2015-09-15 at 3 17 14 pm](https://cloud.githubusercontent.com/assets/3680494/9887317/f7001d8c-5bbc-11e5-9985-2d3b9ee30242.png)

*Expected behavior:*
Should go to https://pages-staging.18f.gov/web-design-standards/getting-started/

**Comment by jpyuda** [comment]
The "Contribute on Github" link also doesn't work.

**Comment by maya** [comment]
Resolved in https://github.com/18F/web-design-standards/pull/597
