### ISSUE TITLE
[Component Page] 'close' documentation accordion action behaving oddly on Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#542]
Steps to reproduce
1. Navigate with a mouse on any component page
2. Click 'code' and followed by 'documentation' accordion. The very first time you do this, the close action for 'documentation' is dropping the user at a jarring higher place up the page. (I think onto the 'code' spot).

http://screencast-o-matic.com/watch/coQoYhfdxX

Expected behavior
On click, the 'close' documentation accordion link should only close the accordion, not move the user anywhere else on the page.

*Test on *
OX 10.8
Safari 6.2

**Comment by jpyuda** [comment]
I think this is because when closing that accordion, the page is too short -- since the footer stays at the bottom of the window, there's not much we can do about the change in scroll position.
