### ISSUE TITLE
[Homepage] Underline under viewed links are purple not blue

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#543]
If you CMD+Click or Ctrl+Click on a link on the homepage, the underline when you hover over a link  is purple rather than blue. See below for an example.

![image](https://cloud.githubusercontent.com/assets/6335546/9888404/eb3de5aa-5bc2-11e5-9ece-c8d8e2b8d11e.png)

**Comment by jpyuda** [comment]
I believe the issue is that when you mouse over a link that does not have an underline by default, the hover state adds a border. That border appears to have the `visited` style when the link doesn't have said style.

**Comment by jpyuda** [comment]
Calling this one a medium because it is both very obvious and on the home page.

**Comment by maya** [comment]
@jpyuda that's bc I'm forcing that link to be blue, but not the hover. Do we want the whole thing to have the visited style or blue underline even if it's been visited before?

**Comment by jpyuda** [comment]
I don't know.

**Comment by carodew** [comment]
@jpyuda @maya IMO, the underline should be blue. I think it would look weird to have purple headers. 

But I think it's probably a call for visual design. @angel ?

**Comment by maya** [comment]
The reason to do purple is to be consistent with the visited treatment we're recommending for links, since it is a link. However it is the homepage so could see a case for having it always be blue.

**Comment by angel** [comment]
@carodew Accessibility-wise, would it be ok if we have the link be the primary-darker always instead of the normal primary colored links? /cc @maya @mollieru
