### ISSUE TITLE
[Homepage] Text does not fill the width of a content container

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#545]
Large text blocks draw a lot of attention to the fact that text doesn't extend to the full width of the content columns. For example, in the section below there is some awkward grey space to the right of the text.

I assume the reasoning behind this has to do with line-length and readability. 

Some potential solutions:

- Center the text in the container
- Extend the text width to the full width of the container

![image](https://cloud.githubusercontent.com/assets/6335546/9888263/0e2c29d8-5bc2-11e5-82df-74d16459e500.png)

**Comment by maya** [comment]
This was by design and for legibility.

**Comment by angel** [comment]
Thanks for your feedback @KHarshawat! As @maya stated above this is by design. We are recommending that line-length be no more than 75 characters for desktop and to left align text both for optimal legibility: https://playbook.cio.gov/designstandards/visual-style/#typesetting.
