### ISSUE TITLE
[Component Pages] Sub-nav drop links to some h2 + h3s showing end of previous paragraphs on Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#546]
_Steps to reproduce_
1. Use the sidenav to navigate to 'Typefaces', 'Pairings+Styles,' 'Palette,' 'Text Accessibility', 'Login Form', 'Password Reset Form,' 'Big Footer,' 'Medium Footer' and 'Slim Footer'
2. Note the text, stroke and/or color block that appears at the top of the page when each of these links are navigated to. 

A few examples: 
![screen shot 2015-09-15 at 4 22 26 pm](https://cloud.githubusercontent.com/assets/3680494/9889016/5ca6bef8-5bc6-11e5-95af-6ba9a11a0eb1.png)
![screen shot 2015-09-15 at 4 22 48 pm](https://cloud.githubusercontent.com/assets/3680494/9889018/5e6cb47c-5bc6-11e5-89dd-e9791d82701d.png)
![screen shot 2015-09-15 at 4 25 04 pm](https://cloud.githubusercontent.com/assets/3680494/9889022/6443ac20-5bc6-11e5-9815-a0288b5cafca.png)

_Expected behavior_
Ideally, all links in sub-nav would lead user to a Header with only white space above, like this:
![screen shot 2015-09-15 at 4 28 22 pm](https://cloud.githubusercontent.com/assets/3680494/9889098/d60dce1c-5bc6-11e5-8471-9a0ec9767df4.png)

*Test on *
OX 10.8
Safari 6.2

**Comment by jpyuda** [comment]
I'd rather give it a little extra space rather than too little (which was the previous situation).

**Comment by maya** [comment]
All headings have a `margin-top: 1.5em` which is proportional to the font size. So a smaller heading of h3 will have less margin top that a larger heading like an h2. We don't want to change our type system just to acomodate this. 

We can either target each issue selectively and add a little more padding. Or we can wrap each section in a div and add a margin.

**Comment by mbmoore** [comment]
I am going to take a look at this issue.

**Comment by maya** [comment]
This seems to have gotten fixed at some point and is no longer an issue.
