### ISSUE TITLE
[Homepage] Accessability icon looks like Dropbox

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#547]
The accessibility "out of the box" image looks a lot like the Dropbox icon. Consider changing the color of the box to a tan or a brown.

![image](https://cloud.githubusercontent.com/assets/6335546/9888530/9a4115e0-5bc3-11e5-800b-d5d49f9ddffe.png)
![image](https://cloud.githubusercontent.com/assets/6335546/9889085/bf414db2-5bc6-11e5-942e-43d549f7ca26.png)

**Comment by mollieru** [comment]
@angel ^^ we can tweak this early next week. looks like it's still reading a lil too 'dropbox-y'

**Comment by maya** [comment]
Resolved in #708.
