### ISSUE TITLE
[Homepage] Amazing Visual Design

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#549]
The visual design of the homepage is fucking awesome. I love the header with the blue browser/flag-window and the little example mocks for Developers and Designers. The color palette rocks. The buttons stand out against the page very nicely. I'm a really big fan of the bg-colors used across the homepage.

**Comment by angel** [comment]
@KHarshawat Haha, yay! Glad you like it! Thanks Kavi! You are awesome! :)

**Comment by mollieru** [comment]
<3 <3
