### ISSUE TITLE
Help text under buttons looks great

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#550]
I'm a really big fan of the help-text under buttons. Great job!

![image](https://cloud.githubusercontent.com/assets/6335546/9888676/5b4f9464-5bc4-11e5-9c2a-30d925557b41.png)

**Comment by mollieru** [comment]
@angel @colinpmacarthur @carodew  huzzah! :trumpet:

**Comment by angel** [comment]
Thanks @KHarshawat!
