### ISSUE TITLE
[Homepage] Fix text link under Contribute on Github button

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#552]
The spacing of the link under the `Contribute on Github' button looks a little weird. Consider the following options: 

- add more padding between it and the button above
- put the link inline with the button so it reads more like a sentence:

![image](https://cloud.githubusercontent.com/assets/6335546/9888733/a253ae86-5bc4-11e5-8537-71e97199ae5f.png)

**Comment by maya** [comment]
Resolved via #845.
