### ISSUE TITLE
[SideNav] Sidenav scrolling stuck when sidenav sections w children/sub-children are open in Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#553]
*Steps to reproduce*
1. Navigate to and open the 'Visual Style,' 'Form Controls' and/or 'Form Templates'  
2. Scroll up and down in the sidenav
3. Click into the content area of the page, scroll up and down
4. Move curser back to sidenav and attempt to scroll up and down

http://screencast-o-matic.com/watch/coQoYzfdy1

*Expected Behavior*
When curser is positioned over the sidenav, expected that sidenav would scroll instead of content area

*Tested on *
OS 10.8
Safari 6.2

**Comment by jpyuda** [comment]
Firefox does this too (but not consistently).

**Comment by carodew** [comment]
Wondering if this is a browser bug or something based on how we've built it?

**Comment by colinpmacarthur** [comment]
I too can replicate in Chrome and Firefox, but both inconsistently. I cannot replicate on other websites, but it's hard to find other sites that mimic our exact navigation style.

**Comment by jpyuda** [comment]
consumerfinance.gov/eregulations/1005

**Comment by colinpmacarthur** [comment]
Thanks @jpyuda. Same issue happens on that site. I suggest we close this issue because it seems to be a browser problem?

**Comment by carodew** [comment]
Seems to be an issue with how browsers handle scrolling, so closing.
