### ISSUE TITLE
[Table] Table cell text line height is inaccurate

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#554]
*Steps to reproduce*
1. Open Tables component
2. Resize browser until line breaks occur; note the tightness of lines in body text

![screen shot 2015-09-15 at 5 12 16 pm](https://cloud.githubusercontent.com/assets/3680494/9890321/4ae1fa1e-5bcd-11e5-92f5-bad494685055.png)

*Expected Behavior*
Body text line-height should be 1.5 (per typography section guidance)

*Tested on*
OS 10.8
Safari 6.2

**Comment by jpyuda** [comment]
This appears to affect only tables, and is not limited to Safari (Chrome, at least, does it too)
