### ISSUE TITLE
[Footer] Menu bar collapses into accordion at mobile screen size (check both horizontal and vertical orientations)

### ISSUE THREAD

**Issue by JuliaWinn** [18F/web-design-standards#558]
Menu bar does not collapse into an accordion when the screen is horizontal.

This is on iPhone 6, Safari, most recent OS.

**Comment by jpyuda** [comment]
Good catch -- the breakpoint on this is actually just slightly smaller than the iPhone resolution in landscape. Expected behavior, and something we should have noted in the test procedures.
