### ISSUE TITLE
[Components Pages] Links in lists are not underlined

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#563]
Links in lists should be underlined since there is surrounding text as stated in our list rules on the site. See Getting Started page is an example of where the links should be underlined.

**Comment by carodew** [comment]
@angel can you provide a screenshot and be more specific on where you're seeing this issue?

**Comment by carodew** [comment]
In lists: 

<img width="662" alt="screen shot 2015-09-17 at 4 16 30 pm" src="https://cloud.githubusercontent.com/assets/10144074/9944780/7ddd5acc-5d57-11e5-8815-4553cd379034.png">

Not in lists: 
<img width="734" alt="screen shot 2015-09-17 at 4 16 50 pm" src="https://cloud.githubusercontent.com/assets/10144074/9944785/8680c592-5d57-11e5-83c2-6fda84e6cdb0.png">

**Comment by maya** [comment]
If we add this rule then all lists get the underline like the sidebar.

![screen shot 2015-09-17 at 1 41 37 pm](https://cloud.githubusercontent.com/assets/5249443/9945432/1862e1e0-5d42-11e5-9b06-fef0a57c430f.png)
