### ISSUE TITLE
[Components Page] Padding should be 30px around between the element and example box.

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#564]
Right now the top and bottom padding does not match the sides.

Below are some examples:
#### Buttons:
![image](https://cloud.githubusercontent.com/assets/103496/9892983/f2f259e2-5bc8-11e5-9e0e-5b69f3bc7b92.png)

#### Labels: 
![image](https://cloud.githubusercontent.com/assets/103496/9892995/01d03466-5bc9-11e5-850d-f12d92965558.png)

#### Alerts: 
![image](https://cloud.githubusercontent.com/assets/103496/9892316/71a26eb4-5bc2-11e5-9db1-bc9baae25e9c.png)
![image](https://cloud.githubusercontent.com/assets/103496/9892320/7ae9415a-5bc2-11e5-941a-6b339b9abd41.png)

#### Tables:
![image](https://cloud.githubusercontent.com/assets/103496/9893019/325308b6-5bc9-11e5-9ca4-998fd8f089b6.png)

#### Accordions:
![image](https://cloud.githubusercontent.com/assets/103496/9892974/d58ae45a-5bc8-11e5-887c-2ba7caf6de45.png)
![image](https://cloud.githubusercontent.com/assets/103496/9892977/df4bb0d2-5bc8-11e5-85c8-e836abc85a7a.png)

**Comment by elarenee** [comment]
@jovchinnikova and @elarenee are working on this!

**Comment by bradnunnally** [comment]
@elarenee Awesome! Let me know how it goes and if you have any questions.

**Comment by maya** [comment]
Closed via #1274.
