### ISSUE TITLE
[Login and Password Reset] Pressing sign in or reset password button takes you to original anchor

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#568]
@colinpmacarthur @carodew not sure what is suppose to happen, but depending on how I got to the Login or Password reset, when I press the sign in or or reset password button, it will take me to that page. So if I clicked on Name form and then scrolled down to sign in or reset password when I press on one of those buttons, it'll take me back to the top of Name form. I'm testing on Chrome.

**Comment by carodew** [comment]
The problem is the same as in #595 – because these are live forms the submit button wants to do something.
