### ISSUE TITLE
[Sign-in and Password Reset] Links in the pattern should have no underlines

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#569]
Since these links do not have surrounding text, they should not have underlines. 

(referencing our own guidelines: https://pages-staging.18f.gov/web-design-standards/visual-style/#links )

![screen shot 2015-09-16 at 4 55 45 pm](https://cloud.githubusercontent.com/assets/3680494/9918270/cfbdddc2-5c93-11e5-9e10-aee354f2173e.png)
![screen shot 2015-09-16 at 4 55 27 pm](https://cloud.githubusercontent.com/assets/3680494/9918271/d04e83b8-5c93-11e5-9dc8-942a4bf258fc.png)

**Comment by maya** [comment]
Related to #812.

**Comment by carodew** [comment]
Related to the accessibility issue in #812 mentioned above, the underlines help with accessibility and shouldn't be removed. We may need to update the visual guidance for links.
