### ISSUE TITLE
[Password Reset] Space between confirm password input box and button should be the same as the login component.

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#571]
![image](https://cloud.githubusercontent.com/assets/103496/9894743/2cd9e626-5bdc-11e5-8a65-dffd71796316.png)
vs. 
![image](https://cloud.githubusercontent.com/assets/103496/9894748/375f6cce-5bdc-11e5-97a2-b87b07cf5825.png)

**Comment by juliaelman** [comment]
Issue resolved via #903, see screenshots below for verification.

![screen shot 2016-05-20 at 12 07 20 pm](https://cloud.githubusercontent.com/assets/955558/15434140/7f193440-1e83-11e6-873d-91af04b7f0ab.png)

![screen shot 2016-05-20 at 12 07 48 pm](https://cloud.githubusercontent.com/assets/955558/15434139/7f1575b2-1e83-11e6-99be-0f956b2624bc.png)
