### ISSUE TITLE
[Homepage] outlined button looks taller than the view standards button.

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#576]
![image](https://cloud.githubusercontent.com/assets/103496/9895994/244153a0-5beb-11e5-8ede-18a265015a2e.png)

**Comment by mollieru** [comment]
@angel is this on multiple browsers or just 1?

**Comment by angel** [comment]
@mollieru I only checked on Chrome, but looks like Safari:
![image](https://cloud.githubusercontent.com/assets/103496/9912618/6b3d0534-5c5d-11e5-94be-7b6e8a58bc2a.png)
and Firefox as well:
![image](https://cloud.githubusercontent.com/assets/103496/9912657/941d3618-5c5d-11e5-8c3a-a7731c1b2577.png)

**Comment by maya** [comment]
Fixed in #608.
