### ISSUE TITLE
[Homepage] Icons (arrow, download, GitHub) on buttons and external links

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#577]
Here are the icons:
http://fortawesome.github.io/Font-Awesome/icon/arrow-right/
http://fortawesome.github.io/Font-Awesome/icon/github/
http://fortawesome.github.io/Font-Awesome/icon/download/
http://fortawesome.github.io/Font-Awesome/icon/external-link/

**Comment by carodew** [comment]
We're going to revisit icons for and buttons again pretty soon, will revisit.
