### ISSUE TITLE
[Search Bar] iPhone 5/Safari: Search Big, Search Medium, and Search Small all display the same, show rounded corners

### ISSUE THREAD

**Issue by jjoteal** [18F/web-design-standards#578]
Not sure what the correct output should be, but this does not seem right, as all the different sizes are the same.  Additionally, the input field and button are likely not displaying as intended

*Steps to replicate*
1. Navigate to 'Search bar' on iPhone/Safari
![image](https://cloud.githubusercontent.com/assets/12192706/9908723/f2c1eda8-5c62-11e5-8e0a-baad5bf3f7c1.png)

*Expected behavior*
should all search bar sizes collapse to the same search icon? in either case, this is what the input fields should look like:

![screen shot 2015-09-16 at 2 22 32 pm](https://cloud.githubusercontent.com/assets/3680494/9914144/62d06898-5c7e-11e5-8d3a-1f3ff18ddba2.png)

*tested on*
iPhone 5 
Safari

**Comment by carodew** [comment]
Marked as a "high" to fix the rounded corners styling in iPhone. 

That they all appear the same on mobile is as expected, the main difference between the three of them is most apparent on desktop. 

Thanks!

**Comment by maya** [comment]
Is this on other text inputs as well? Or just search? Looks like safari is adding their own styles.

**Comment by angel** [comment]
@maya just search. When I click inside and type it actually turns to what it's suppose to look like:
![image_3](https://cloud.githubusercontent.com/assets/103496/9921559/98a64dec-5c93-11e5-80df-01335d76da3c.jpg)

**Comment by maya** [comment]
@angel thanks, what a weird thing that it changes. Hopefully #603 fixes this.

**Comment by carodew** [comment]
This seems to be fixed now.

**Comment by maya** [comment]
Thanks for checking @carodew. Closing via #603.
