### ISSUE TITLE
[Accordions] iPhone 5/Safari: After page loads, clicking on expand for an unopened section brings you to the bottom of that section rather than the top

### ISSUE THREAD

**Issue by jjoteal** [18F/web-design-standards#580]
When I load the Accordians landing page, the Apple Pie accordion is open. When I then click on Strawberry Pie the accordion opens, but it jumps me to the bottom of the fully expanded accordion rather than the top label of the accordion.

Steps to reproduce:
On iphone 5...
1) Go to Accordions
2) Click on "Strawberry Pie" in the Borderless section
3) See that when you expand Strawberry Pie, it jumps you to the bottom of the Strawberry Pie accordion rather than the top

Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9909075/98007086-5c64-11e5-84ce-4d5dfe8d1808.png)

**Comment by colinpmacarthur** [comment]
This issue was logged in Android in #352. I'm going to close this issue and mention that this happens in iPhone in the other. Thanks!
