### ISSUE TITLE
[Side navigation] Header looks inappropriate at mobile screen sizes

### ISSUE THREAD

**Issue by JuliaWinn** [18F/web-design-standards#582]
*Steps to reproduce* 

Navigate to any component page on iPhone 6 in landscape. The menu tab is very bloated. 

![image](https://cloud.githubusercontent.com/assets/821557/9910397/f6e3142c-5c6a-11e5-8153-0c8f23ac4db4.png)

**Comment by carodew** [comment]
This will be addressed when we implement the new header.

**Comment by maya** [comment]
Fixed in #635. Thank you.
