### ISSUE TITLE
[Homepage] No obvious link to homepage on mobile

### ISSUE THREAD

**Issue by JuliaWinn** [18F/web-design-standards#583]
This is on iPhone 6, in both vertical and horizontal views. Unlike with web view, the "U.S. Federal Web Design Standards" text is not visible. This may be a similar issue to the Github buttons not being viewable.

The only way I was able to access the homepage was by directly modifying the url.

![image](https://cloud.githubusercontent.com/assets/821557/9911233/16fd8b26-5c6f-11e5-9bf4-b3890ec8a685.png)

![image](https://cloud.githubusercontent.com/assets/821557/9911241/297967c0-5c6f-11e5-8e87-83e7590e15d2.png)

**Comment by carodew** [comment]
We'd like to see "Home" added back to the side nav for MVP.

**Comment by maya** [comment]
I think just displaying the site title would resolve this.
