### ISSUE TITLE
[component page] backwards tabbing through page does not consistently bring focused component into view on the screen

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#588]
**Steps to recreate**
1. On the Form Templates page, set the focus on one of the links in the footer. 
2. `Shift+Tab` to move focus backwards through elements on the page.
3. Notice that sometimes, the focused element remains beyond the top of the visible area. (It's a little bit hard to see with no visible focus styles on the accordion headers for code and documentation).

![backwards-tabbing](https://cloud.githubusercontent.com/assets/10144074/9912919/fdcb2f2e-5c77-11e5-8b03-669ddad4a9f3.gif)

**expected behavior**
I would expect the element that has focus to be brought within view, even wen tabbing backwards. 

**Tested in**
Chrome

SauceLabs
Windows 10
IE 11

**Comment by carodew** [comment]
Also when I hit the "Skip Content" the top of the page is hidden behind the fixed header.

**Comment by maya** [comment]
Just tested on IE 10 and 11 and not seeing the problem. Closing for now, feel free to reopen if it pops up again.
![](http://g.recordit.co/gVm1V46kYi.gif)
