### ISSUE TITLE
[Homepage] Principles section on mobile is not consistently displayed

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#591]
On Chrome on my iPhone 5s, when I go to the homepage and then scroll down to the Principles section, I see this:
![image](https://cloud.githubusercontent.com/assets/103496/9913564/591dc186-5c62-11e5-9a81-869200497654.png)
![image](https://cloud.githubusercontent.com/assets/103496/9917498/ca7f81a2-5c76-11e5-8b32-92901eaaaf3a.png)
![image](https://cloud.githubusercontent.com/assets/103496/9917502/ceec9298-5c76-11e5-885d-3bc423965491.png)

It should look like this instead:
![homepage_principles](https://cloud.githubusercontent.com/assets/103496/9913576/64ff75c6-5c62-11e5-8aef-60c156806a46.png)

**Comment by carodew** [comment]
@mollieru reports there is another section that looks more broken, screenshot to be added.

**Comment by mollieru** [comment]
@angel can you add a screenshot of this whole section (not just the first two principles)?

**Comment by angel** [comment]
@mollieru @carodew added two more screenshots above.
