### ISSUE TITLE
[Mailing Address] autofill switches to dropdown when user types a 'space' on Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#592]
*Steps to replicate*
1. Tab through fields into the autofill State field
2. Try to type 'New York'
3. Note that after typing `N`-`E`-`W`, when you enter `space`, the dropdown pops up, and when you enter `Y`, you're taken down to `Wyoming`

Video shows what happens when you do the above ^ (hard to tell that's what I'm typing, FYI)
http://screencast-o-matic.com/watch/coQDFjfdWJ

*Expected behavior*
You should be able to type a state w a space and have it autofill correctly

(Note: user is still able to select their state when the dropdown appears)

*Tested on*
OS 10.8
Safari 6.2

**Comment by carodew** [comment]
Calling this a Safari bug and closing.
