### ISSUE TITLE
[Homepage] Add more space between GitHub link and page title on mobile

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#593]
On Chrome on my iPhone 5s, when I go to the Homepage it looks like this:
![image](https://cloud.githubusercontent.com/assets/103496/9913652/bc593a14-5c62-11e5-86dc-f33871e980fb.png)
The "View on GitHub" link is really close to the "U.S. Federal Web Design Standards". 20 more pixels above the title would give it sufficient breathing room:
![image](https://cloud.githubusercontent.com/assets/103496/9913845/bd6aa69e-5c63-11e5-83a0-ff44690f2e25.png)

**Comment by mollieru** [comment]
Also appears like this on iPhone Safari
