### ISSUE TITLE
[Search bar] reduce font size in 'Medium' and 'Small' bars

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#594]
Given that the input fields for 'medium' and 'small' search bars have less vertical height, consider reducing input font-size from `1.7rem` to `1.5rem` for cleaner input layout. 

Currently:

![screen shot 2015-09-16 at 2 29 54 pm](https://cloud.githubusercontent.com/assets/3680494/9914343/6b8655be-5c7f-11e5-90ad-a6d2561dc582.png)

W reduced font size:

![screen shot 2015-09-16 at 2 29 41 pm](https://cloud.githubusercontent.com/assets/3680494/9914345/730a4534-5c7f-11e5-9f14-925defbc1d1e.png)

**Comment by PilgrimMemoirs** [comment]
ON IT! 💃

**Comment by kamxhmartin** [comment]
Working with above! :100:

**Comment by msecret** [comment]
The font size of the medium and small search bars is currently `1.4em`, meaning this was likely completed. I'll close this issue for now, please re-open if more work can be done related to this.
