### ISSUE TITLE
[Buttons] Disabled Button Shows Focus/Active State in iPhone Safari

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/web-design-standards#596]
*To recreate*
On 'buttons' page, click on 'default' button under 'Disabled Button" section.  Button shows active state/I am able to click on it and it flashes.   
![img_7565](https://cloud.githubusercontent.com/assets/3680494/9918564/93372686-5c95-11e5-9372-a1a5ab9dbe3c.PNG)

*Expected behavior*
No action should result from clicking on default button

*Tested on*
iPhone 5
Safari

**Comment by colinpmacarthur** [comment]
Closing this because it's mentioned in #493. Thanks!
