### ISSUE TITLE
[Component page] Code and Documentation titles missing '+' and '-' sign to open close on Safari iPhone

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/web-design-standards#599]
*To recreate*
On any component pages, the Code and Documentation + and - signs are missing to show that if you click those tabs you can get more information.  

![img_7567](https://cloud.githubusercontent.com/assets/3680494/9918700/3f5fb95a-5c96-11e5-8f09-83e3a017ed98.jpeg)

*Expected behavior*
Next to 'code' there should be a + and when you click code there should be a - by the title.
Next to 'documentation' there should be a + and when you click documentation there should be a - by title. 

*Tested on*
iPhone 5
Safari

**Comment by carodew** [comment]
Hi @NatalieEMoore – you beat us to it. We had a brief issue yesterday evening when some files were restructured and temporarily broke the links to the icon font across the site (issue #600). It's been fixed, just to be sure I double checked on my phone and everything looks ok now. 

Thanks!
