### ISSUE TITLE
Icons missing throughout the standards

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#600]
**Steps to reproduce**
1. Visit the pages for any of the following components:
- alerts
- accordions
- dropdowns
- search icon
2. There are no icons where there were before.

*Alerts:*
![screen shot 2015-09-16 at 5 12 54 pm](https://cloud.githubusercontent.com/assets/2092076/9918695/342d7432-5c96-11e5-8b7e-15285019549e.png) 

*Accordions:*
![screen shot 2015-09-16 at 5 13 13 pm](https://cloud.githubusercontent.com/assets/2092076/9918698/38c83572-5c96-11e5-9409-eba0328f12d2.png)

*Dropdown:*
![screen shot 2015-09-16 at 5 13 57 pm](https://cloud.githubusercontent.com/assets/2092076/9918703/526ca74c-5c96-11e5-85da-0ba33b9a3ffa.png)

*Search bar:*
![screen shot 2015-09-16 at 5 14 28 pm](https://cloud.githubusercontent.com/assets/2092076/9918716/6a97af10-5c96-11e5-97b4-2c06587ee7db.png)

**Found on**
Chrome 44, OS 10.10

**Comment by maya** [comment]
I changed all background image sources from `../img/picture.png` to `/assets/img/picture.png` to get it to work locally. Looks like it stopped working on the live site.

**Comment by angel** [comment]
@colinpmacarthur @maya same for staging on safari on my iPad mini.

**Comment by mbland** [comment]
All the links internal to the site, images included, need to start with `{{ site.baseurl }}`, in this case `{{ site.baseurl }}/assets/img/...`. Let me know if that doesn't do the trick, or y'all need a hand, etc. I'm heading home now, but can pick it up either a little later tonight or first thing tomorrow if you need me to.
