### ISSUE TITLE
[Labels] Code on labels page is cut off on iphone safari

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/web-design-standards#601]
To recreate
On 'labels' page, click on 'Code' tab. The text is cut off on iPhone safari.

Expected behavior
All code text should be present/visible on page.

Tested on
iPhone 5
Safari

**Comment by mollieru** [comment]
I think related to https://github.com/18F/web-design-standards/issues/599 (and the issue about text cutoff in the 'documentation' as well)

**Comment by carodew** [comment]
Same as #598, for the code this is expected behavior. 

I'm still looking into the issue of documentation text cut offs though.
