### ISSUE TITLE
[Typography] br tags improperly used in typography section; causing weird line breaks

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#615]
**Steps to replicate**
1. On an iPhone 5, navigate to the Typography page and expand the default typography pairings accordion. 
2. Scroll down until you see the example of paragraph body copy. 
3. Note that the forced line breaks cause the example to wrap erratically. 

<img width="364" alt="screen shot 2015-09-17 at 4 40 13 pm" src="https://cloud.githubusercontent.com/assets/10144074/9945381/f436ccaa-5d5a-11e5-9c06-0a614551125f.png">

**Expected behavior**
Forced line breaks don't work well with responsive design, I would expect the paragraphs to wrap naturally according to the screen width. 

**Tested in**
iPhone 5 simulator (Chrome dev tools)

**Comment by carodew** [comment]
Just checked again given the new margins and this looks the same to me so far. Since this is marked as a low I think we should pick this back up after launch.

**Comment by jpyuda** [comment]
Is this still a thing?

**Comment by carodew** [comment]
yep.

**Comment by jpyuda** [comment]
Oh hey, there are `br` tags there. Take those out.

**Comment by juliaelman** [comment]
Fixed in #1214
