### ISSUE TITLE
Browser support language for Getting Started

### ISSUE THREAD

**Issue by konklone** [18F/web-design-standards#644]
@maya asked me to suggest some language for the Getting Started page re: IE8 and browser support. Here's an initial suggestion:

> These standards are designed to support both older and newer browsers through progressive enhancement, and officially support Internet Explorer 9 and up. Internet Explorer 8 and below generally see quite low usage today, and most agency websites should be able to safely begin support at Internet Explorer 9.

**Comment by maya** [comment]
cc @jpyuda

**Comment by konklone** [comment]
Here's a slightly longer version that acknowledges the security aspect:

> These standards are designed to support both older and newer browsers through progressive enhancement, and officially support **Internet Explorer 9 and up**. Internet Explorer 8 and below generally see very low usage today, and most agency websites should be able to safely begin support at Internet Explorer 9. Because IE8 is the last version of IE available on Windows XP, beginning support at IE9 also allows an agency to more easily adopt [modern security standards](https://https.cio.gov/sni/).

**Comment by mollieru** [comment]
Thank you @konklone !!

**Comment by konklone** [comment]
Thank **you**!

**Comment by maya** [comment]
Added in https://github.com/18F/web-design-standards/pull/662. Thanks @konklone!
