### ISSUE TITLE
[Visual Style Guide] Update words + Fix placement of 'download styles' button 

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#667]
@maya in these 3 PRs https://github.com/18F/web-design-standards/pull/657, https://github.com/18F/web-design-standards/pull/659, https://github.com/18F/web-design-standards/pull/658, I am trying to update the text and placement of 'download styles' button on the Visual Style Guide page. 

The button should be place beneath the intro lead paragraph text under 'Visual Style Guide' and again under the intro text of the 'Color' section. It should be removed from the 'Typography' section.

The button text should read:
_Download the design files_

and the text underneath should read:
_Download a zip file with font files and color swatches._

**Comment by maya** [comment]
Resolved via #676.
