### ISSUE TITLE
Feature request: content section/style guide

### ISSUE THREAD

**Issue by ErieMeyer** [18F/web-design-standards#67]
Hi folks!

I submitted some pull requests today because we've got a variety of ongoing projects that would love to be working from the same working style guide.

- https://github.com/18F/govt-wide-patternlibrary/pull/66
- https://github.com/18F/govt-wide-patternlibrary/pull/65

The strategy is to use the amazing content style guide that data.gov was already using, which was informed by lot so amazing research by the GDS team, and is simple, brief, and already in the public.

Hosting this here will help all of the existing efforts which are currently fractured re-use some of the great work public servants have already done by strengthening this third version of a style guide rather than creating a new one.

Thank you for your awesome work, team style guide!

**Comment by mollieru** [comment]
Thank you @ErieMeyer !! We're excited excited by this and will discuss and get back to you shortly!

**Comment by mollieru** [comment]
updated to title to better reflect the request.

**Comment by mollieru** [comment]
@ErieMeyer we're into it! The team is super jazzed and excited for what you produce! Merging in the pull request. Let's sync up about timelines offline. Thank you for leading this charge!! :racehorse:

**Comment by mollieru** [comment]
+ @kategarklavs who has been working on some cool stuff related to this as well!  

@ErieMeyer hoping y'all can make some content magic together <3

**Comment by mollieru** [comment]
Plus @deepa7 who's been noodling on this stuff a bit at USDS HQ.

**Comment by kategarklavs** [comment]
Thanks for tagging me, @mollieru!

**Comment by Scotchester** [comment]
Looks like this can be closed? I've got a couple thoughts about the content of the content style guide, but those probably belong in a new issue.

**Comment by juliaelman** [comment]
@Scotchester a pull request has been opened to integrate this into the site, but is awaiting feedback from @ErieMeyer https://github.com/18F/govt-wide-patternlibrary/pull/106

**Comment by colinpmacarthur** [comment]
@juliaelman: May I close this issue because of the pending pull request?

**Comment by juliaelman** [comment]
@colinpmacarthur let's keep open until that we have some feedback first - thanks!

**Comment by juliaelman** [comment]
@mollieru assigning this to you, as you've been in contact with @kategarklavs on integrating the 18F content style guide into the site. What is the current status of that work?

**Comment by mollieru** [comment]
Resolved, as 18F created a content guide, which we link to in the web designs standards.
