### ISSUE TITLE
Link to open source license for recommended typefaces

### ISSUE THREAD

**Issue by konklone** [18F/web-design-standards#682]
If the recommended typefaces are released as open source, they should have some declaration/license somewhere to that effect. Linking to that would provide assurance that they are open source, and that there are no restrictions on agency use (e.g. attribution, commercial use, etc.).

**Comment by mollieru** [comment]
@konklone thoughts on this language/linkery? 

_All fonts used in this design system are free, open source typefaces available on [Google Web Fonts] (https://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro:400,300,400italic,700,700italic|Merriweather:400,300,400italic,700,700italic), licensed under the [SIL Open Font License] (http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).

**Comment by konklone** [comment]
:+1:, as long as my reading of [their FAQ](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web) is correct and there are no extra requirements on websites that use it (like attribution). It looks like the attribution requirements of the OFL are for those distributing derived works, rather than embedding websites.

So looks all good to me!
