### ISSUE TITLE
Wrong link to 'Mockup of VA Appeals Modernization Screen?'

### ISSUE THREAD

**Issue by lukefretwell** [18F/web-design-standards#688]
The "Mockup of VA Appeals Modernization Screen" link on https://pages.18f.gov/designstandards/ directs to [this image](https://pages.18f.gov/designstandards/assets-styleguide/img/home/example_voteUSAgov.png), which I assume is a bug.

**Comment by mollieru** [comment]
Thanks for the catch @lukefretwell !  Last night was a soft launch to help catch these very things. Much obliged!

**Comment by mollieru** [comment]
resolved in https://github.com/18F/web-design-standards/pull/694
