### ISSUE TITLE
[Homepage] Fix phrasing of intro paragraph 

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#689]
From @mogul : 

Is this sentence missing some punctuation?
_Built and maintained by a team of U.S. Digital Service and 18F designers and developers, this resource is built on the highest standards of 508 compliance, reuses best practices of existing style libraries and modern web design to guide us in creating beautiful and easy-to-use online experiences for the American people._

Maybe drop the word “reuses” to make the sentence readable?

**Comment by maya** [comment]
I think putting an "and" between "compliance, reuses" would make this a grammatically correct sentence. cc @awfrancisco

**Comment by awfrancisco** [comment]
Agreed. Would also add "the" after "reuses."

**Comment by carodew** [comment]
It would still be a mouthful, and a bit of a run-on sentence even if it's technically correct. 

Also I don't think we're using the 'highest' standards of 508 compliance, aren't we using one version under the most strict? 

How about something like:

"Built and maintained by a team of U.S. Digital Service and 18F designers and developers, this resource follows high standards of 508 compliance, and reuses the best practices of existing style libraries and modern web design. It serves as a guide in creating beautiful and easy-to-use online experiences for the American people."

**Comment by mollieru** [comment]
@carodew perfecto. Will update accordingly. Thanks all!

**Comment by maya** [comment]
Yeah I was wondering why we have that. Do we even need to say "high standards"? Can't we just say we follow 508 compliance?

**Comment by maya** [comment]
@mollieru After chatting with the writing lab, we think we should be changed to "industry-leading 508 compliance".

**Comment by maya** [comment]
Some more feedback...

"Start 'A team of U.S. Digital Service and 18F designers and developers built this resource to the highest standards of accessibility.'

"Otherwise you're starting two separate clauses about the same thing by describing it as "built"
- @jameshupp 

"Yes, I'd divide the intro into a few sentences" 
-@kategarklavs

**Comment by mollieru** [comment]
This has been resolved.
