### ISSUE TITLE
Website just disappeared?

### ISSUE THREAD

**Issue by alex** [18F/web-design-standards#693]
For a couple seconds, maybe a minute, the entire website just disappeared. on the root url (`https://pages.18f.gov/designstandards/`) I got the standard nginx "you have nginx installed" page, and other pages were 404s.

Sorry this bug isn't super descript, I'm not sure what else I can share.

**Comment by mbland** [comment]
Sorry, it's back now. Had to tweak the nginx config on our side to get it working properly with the proxy forwarding from playbook.cio.gov. See 18F/hub#444.
