### ISSUE TITLE
[Footer] Darker gray does match on of our colors and blue links on light gray not 508 compliant

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#699]
As I was updating the footer in the components page. I found that the darker gray is #e0e0e0 which doesn't match any of our colors, in which case the primary color will not pass with our gray-lighter either:
![image](https://cloud.githubusercontent.com/assets/103496/10059739/9bd78044-6201-11e5-8d02-3f38f2b86f54.png)

and the primary color on our gray-lightest background #efefef does not pass 508 compliance for the big footer:
![image](https://cloud.githubusercontent.com/assets/103496/10059888/5dba5b1e-6202-11e5-992e-50c19a8268b5.png)

If we change gray-lightest to #f1f1f1 then the contrast will pass. 

/cc @maya @mollieru

**Comment by mollieru** [comment]
@maya can you add this to the list of final bugs to tackle on Thurs? feels
important to make sure our components pass our 508 standards.

**Comment by maya** [comment]
Fixed in #699.
