### ISSUE TITLE
[Search Results] design draft

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#703]
Our second iteration of a Search Results page layout, not included in v.8 release:

![search_results_ui_v2](https://cloud.githubusercontent.com/assets/3680494/10060107/d170e9a0-621c-11e5-92b2-55d082e2e1ad.png)

**Comment by ErieMeyer** [comment]
Just want to +1 that this feature would be super helpful! I have to go to the repo to search instead of even being able to do control-F in the design standards.

**Comment by maya** [comment]
@ErieMeyer this issue is around a search results pattern that would eventually be added into the design standards. But I think what you're asking is that it's hard to find things on the website?

**Comment by ErieMeyer** [comment]
Yes! Was specifically looking for the word "tab" or "tabbed" and couldn't figure out how to search quickly -- other than going to the code itself.

Hope that helps!

**Comment by maya** [comment]
@ErieMeyer there's a not widely known page (..shhh): https://playbook.cio.gov/designstandards/all/ that you should be able to control-F to your :heart: s content!

**Comment by Drakenhart** [comment]
What I find most useful on this mock, that I don't see on the website, is the reference to the white space. I had to dig through code to find the padding and the margins, before. ^.^

When working with type, white space is very very important. ^.^

**Comment by jpyuda** [comment]
Closing pending a future search milestone.
