### ISSUE TITLE
[Page layouts] design draft

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#704]
Our second iteration of page layout templates, not included in v.8 release:
![layouts_ui_v1](https://cloud.githubusercontent.com/assets/3680494/10060285/fde6e3a8-621d-11e5-8444-e92212355bb7.png)

**Comment by donjo** [comment]
@mollieru Hey Mollie! A few of us are starting to take a look at building some HTML templates that folks can use with the standards and I came across this issue. Do you have any research or other resources that inspired some of the directions shown above that we should take into consideration?

**Comment by juliaelman** [comment]
Closing this issues, as we now have page templates in production 🎉 

See https://standards.usa.gov/page-templates/
