### ISSUE TITLE
[Header+ top navigation] design draft

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#705]
Our second iteration of a Header layout with top navigation design for desktop and mobile, not explicitly included in v.8 release:

_Tip: click on image for full size_
![headers_navigation_ui_v3](https://cloud.githubusercontent.com/assets/3680494/10060406/9bafd950-621e-11e5-813f-d1ca8b9a5741.png)

**Comment by maya** [comment]
Closing as worked is moved to #1312.
