### ISSUE TITLE
[Footer] design update

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#706]
v.8 release includes a Footer component. This is our second iteration of that design based on user feedback, which hasn't been updated in the v.8 code:

_Tip: click for full size_

![footers_ui_v2](https://cloud.githubusercontent.com/assets/3680494/10060537/6e6d06d8-621f-11e5-82ee-1cf643333151.png)

**Comment by carodew** [comment]
As with the other footer issues, we'll be incorporating new feedback into the footer design so there are some forthcoming changes. Closing to prevent confusion.
