### ISSUE TITLE
ARIA attributes in code samples

### ISSUE THREAD

**Issue by norrishung** [18F/web-design-standards#727]
Not sure whether you guys talking about this or not but there's a discrepancy between the accessibility documentation and the code samples in some elements. (https://playbook.cio.gov/designstandards/alerts/)

Should attributes like aria-roles be placed in code samples by default so it encourages people to use them? (especially if they are copying and pasting)

**Comment by maya** [comment]
@norrishung that's a good point. A few things to keep in mind: 
- the alert role is fairly aggressive and intrusive. 
- screen readers will announce the alert no matter where a user is on the page and uses a strong, assertive voice. 
- also, it announces “alert” before each message. 
- I think it’s meant to be used for dynamic changes too.

“...the alert role must be used sparingly and only in situations where the user's immediate attention is required.” -[MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role)

There are other less aggressive methods like:

`aria-live="polite"` (uses a friendlier tone)

or

`role=status, aria-live=assertive, and aria-relevant=all`
>This combination of attributes works reliably across all browsers and ATs that support ARIA, and causes messages inserted within the Span tag to be announced in succession without speech interruption, and does not cause the word "Alert" to be announced every time. https://www.linkedin.com/grp/post/4512178-138612399

So I think there's some nuance there, and not sure if our code samples should make any assumptions, when developers may need to decide on a per case basis what experience they want. But I agree that some examples would be useful. But we need to make sure the alert role is not abused or used incorrectly, which could happen if we added it in the code, and people copied and pasted without knowing what it's for.

**Comment by djKianoosh** [comment]
Re: @maya `But we need to make sure the alert role is not abused or used incorrectly, which could happen if we added it in the code, and people copied and pasted without knowing what it's for.`

True. But at the same time, something is better than nothing. So it's important to try to agree on a sane default for code examples. Can't worry too much about misuse, and these guides are as much about teaching developers as anything, right? ;-)

**Comment by maya** [comment]
For reference, here's a screenshot of the four alerts we provide:

![screen shot 2015-10-02 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/5249443/10257816/60d2e056-690e-11e5-8476-6ed6cf176824.png)
