### ISSUE TITLE
Separate website from base SCSS / JS

### ISSUE THREAD

**Issue by maclover7** [18F/web-design-standards#732]
It would make it easier to contribute to the web design standards if the core SCSS, etc. were separated out from the website, maybe into the master branch? It's kind of hard to decipher right now where the actual precompiled assets are. Happy to send in a PR. :)

**Comment by mollieru** [comment]
Thanks for the suggestion @maclover7 ... Feel free to send a PR and we'll take a peak. 

cc @maya

**Comment by maya** [comment]
Currently the styles for the components are in `assets` and the website styles are in `assets-styleguide`. Can you clarify what you mean?

**Comment by maclover7** [comment]
Might be easier for contributing and organization to move assets folder to the master branch (separate from the site)

**Comment by maya** [comment]
@maclover7 Ahh yes, we've talked about doing this. We'll have to see how it gets added on our project priorities in the coming weeks. Thanks for the feedback!

**Comment by maya** [comment]
Complete in #978. Assets are now in `src`. Thanks @maclover7!
