### ISSUE TITLE
Design Standards webpage not displaying properly when using HTTPS

### ISSUE THREAD

**Issue by drewrwilson** [18F/web-design-standards#733]
![image](https://cloud.githubusercontent.com/assets/4324656/10141789/6dd54f8a-65dc-11e5-9fca-73088ede16c0.png)

This page: [https://playbook.cio.gov/designstandards/](https://playbook.cio.gov/designstandards/)

**Comment by mollieru** [comment]
Thank you for catching this!  We are working on patching this up -- seems like a few folks were getting similar errors. Should be resolved shortly.

**Comment by carodew** [comment]
@mollieru we fixed, correct?

**Comment by BrianLefler** [comment]
Pretty sure this was the same issue with the MAX.gov proxy buckling under load (throwing a lot of 503s -- this error is only unusual in that the first request succeeded and it was the assets that 503'd).  In that case, we did nothing and it seems to have recovered on its own.

We don't own the first hop in the chain, so permanently fixing this will either require us to roll our own proxy server or to work with MAX.gov to bulletproof the proxy server we're currently using.  We are using a proxy in the first place to support https, as described here by konklone: https://github.com/isaacs/github/issues/156

**Comment by mollieru** [comment]
This has been resolved and the site shouldn't be serving up these errors anymore. Do let us know if you have any other issues!
