### ISSUE TITLE
Couple of spelling issues in the announcement

### ISSUE THREAD

**Issue by HobokenMartha** [18F/web-design-standards#735]
https://18f.gsa.gov/2015/09/28/web-design-standards/

Financial and centered are misspelled.

Some shining examples include those of the Consumer Financal Protection Bureau (CFPB), US Patent and Trademark Office (USPTO), and Healthcare.gov.

We’ve taken an iterative, user-centred approach to ensure we’re addressing the needs of our users as well as government designers and developers.

**Comment by carodew** [comment]
@melodykramer

**Comment by melodykramer** [comment]
Just fixed and deployed to staging. @awfrancisco, mind pushing go?

**Comment by maya** [comment]
Resolved in https://github.com/18F/18f.gsa.gov/pull/1206. Thanks!
