### ISSUE TITLE
Font rendering on Contribute section of main page

### ISSUE THREAD

**Issue by kendaleiv** [18F/web-design-standards#737]
Font rendering seems a bit off on the **Contribute** section of the main page with Windows 10 in Chrome and Firefox (Chrome on left, Firefox on right).

Perhaps there's a way to improve it?

![image](https://cloud.githubusercontent.com/assets/1012917/10150633/7f14fe44-660e-11e5-80b2-a68b23a29566.png)

**Comment by mollieru** [comment]
Thanks for the feedback! We'll check it out. Stay tuned.

**Comment by maya** [comment]
Resolved via #848.
