### ISSUE TITLE
can't clone the repo - seems a public key problem

### ISSUE THREAD

**Issue by codepo8** [18F/web-design-standards#739]
git clone git@github.com:18F/web-design-standards.git
Cloning into 'web-design-standards'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by landaire** [comment]
This would probably be an issue on your end. Make sure the public key for your related private key is added to the account or try cloning over HTTPS. I was able to clone the repo just fine over SSH.

**Comment by codepo8** [comment]
This is the line in the docs - that's why I filed it. Using the repo URL I was able to clone and build fine. Maybe replace it with the full URL or the zip download link?

**Comment by DJMcK** [comment]
@codepo8 Looks like you're attempting to clone using SSH without first adding the SSH key to your Github account. See [this help document](https://help.github.com/articles/generating-ssh-keys/) for more.

**Comment by maya** [comment]
@codepo8 were you able to work this out based on the previous feedback? Let us know if you need our help.

**Comment by carodew** [comment]
@codepo8 – also is there something in our documentation that we should revisit?

**Comment by maya** [comment]
@codepo8 hope the above comments were helpful. Let us know if you need anything else!
