### ISSUE TITLE
Remove "javascript:void(0)" href values

### ISSUE THREAD

**Issue by kangax** [18F/web-design-standards#743]
These should be made into real links or at least "#" (as the universal and arguably better alternative)

**Comment by kowdermeister** [comment]
I tend to skip the `href` attribute completely in these situations. This also has the effect, that if the link is fake, underline and mouse pointer should be added via CSS. 

If using a # the problem is that if no `preventDefault` is called in the handler function, then the page will jump to the top.

**Comment by kfranqueiro** [comment]
`preventDefault` should be specified either way, even with `javascript:void(0)` links, as there is a [somewhat obscure yet infamous bug](https://connect.microsoft.com/IE/feedback/details/802397/ie9-ie10-events-can-be-sent-to-the-wrong-listeners) in IE9-10 (maybe also 11?) where event handlers registered with `addEventListener` get completely juggled when a link that doesn't actually navigate anywhere is clicked.

**Comment by dylanvalade** [comment]
If the primary goal is "Make the best thing the easiest thing" then `#` is easier than `javascript:void(0)`.

**Comment by maya** [comment]
Thanks for your feedback. We were also grappling with this same issue erlier when deciding how to write our anchor links on the standards site. 

We found that when using `#`, if a user of the website clicks on a link, it jumps to the top of the page, creating an abrupt and unpleasant experience (like @kowdermeister pointed out).

We ended up going with `javascript:void(0)` bc it still functions like a link, except it does jump to the top of the page. We noticed Bourbon.io also did this. Do you have any other suggestions?

**Comment by dylanvalade** [comment]
An event handler attached to the document can handle links added both when the DOM renders and after dynamic DOM changes.


```javascript
function handleDisabledLinks() {
  
  $(document).on('click', 'a[href="#"]', function (event) {
  
    // Stop default browser action which would likely return to the top of the page
    event.preventDefault();
  });
}
```

Then call `handleDisabledLinks()` in `document.ready` here:
https://github.com/18F/web-design-standards/blob/18f-pages-staging/assets/js/components.js#L334

**Comment by msecret** [comment]
I agree with @dylanvalade solution.

**Comment by maya** [comment]
@dylanvalade @msecret wouldn't we want to call it in `assets-styleguide/styleguide.js` since this is just for styleguide presentation and we wouldn't need to bundle it in the `component.js`.

**Comment by dodojero6** [comment]
After We Collided Full Movie

https://after95b.substack.com/p/after-we-collided2020-lfull-movie
https://after95b.substack.com/p/full-watch-123movies-after-we-collided-2ed
https://after95b.substack.com/p/full-watch-123movies-after-we-collided
https://after95b.substack.com/p/after-we-collided2020-lfull-movie-d62
https://after95b.substack.com/p/watch-after-we-collided2020-lfull
https://after95b.substack.com/p/watch-stream-after-we-collided2020
https://after95b.substack.com/p/stream-watch-after-we-collided2020
https://after95b.substack.com/p/after-we-collided2020-lfull-film
https://after95b.substack.com/p/watch-after-we-collided2020-lfull-22b
https://after95b.substack.com/p/watch-stream-after-we-collided2020-9f2
