### ISSUE TITLE
Where is the `dist`?

### ISSUE THREAD

**Issue by Sequoia** [18F/web-design-standards#752]
It appears that if users wish to consume this front-end boilerplate/framework, they need to install ruby & get run jekyll. Is there a reason for this? It seems like an unnecessary barrier to entry for the front-end dev/designer who simply wants to include this framework like bootstrap & use the styles. I don't understand why I should need to build the entire static site in order to consume the css & js in my project.  For users who want to hack on or extend the framework itself this makes sense, but not for consumers (imho).

# Expected
I can download (or `bower install`) a directory that contains the assets necessary to start using this framework, copy it to my site's assets directory, add link/script tags & start using this framework.

# Actual
There is no `_sites` directory (as referred to in [Getting started](https://github.com/18F/web-design-standards#getting-started)), I can't find the built assets anywhere, I have to install ruby etc. etc..

# Recommendation
Add a `dist` directory that contains a build artifact, or put it in another repo & publish it to bower.

**Comment by jcbelanger** [comment]
I personally don't like committing build assets to source control.  I suggest creating a github "release" of the dist folder.  Then there will be a download link that people can use without having to download the entire source, which seems to be what you'd want.  However, many javascript front end frameworks end up committing dist anyway.

**Comment by Sequoia** [comment]
OK maybe a link to there in the "getting started" section then :smile_cat:

**Comment by maya** [comment]
There's a discussion already around bower, so stay tuned. See #745 for more updates.

**Comment by msecret** [comment]
@Sequoia thanks for the recommendation. This has been something we've previously thought about (splitting the site and lib into two separate repos).

**Comment by edwelker** [comment]
So it would seem that a /dist directory has been created, and the add-npm branch points to the contents.  Can the documentation be updated if this is indeed the case?

**Comment by maya** [comment]
@Sequoia we now have a `dist` here: https://github.com/18F/web-design-standards/tree/18f-pages-staging/dist. Thanks!
