### ISSUE TITLE
jekyll-coffeescript dependency error resolved with gem 'json'

### ISSUE THREAD

**Issue by jesconstantine** [18F/web-design-standards#754]
Thanks for this fantastic resource!  Just wanted to share (in case anyone has the same issue) that I had to add `gem 'json'` to the Gemfile to resolve a Dependency error after initializing and attempting to serve the library via `./go serve` 

Here's the error I was getting:
```
Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- json' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
```

`./go init` did indeed install jekyll-coffeescript, as indicated by `bundle show jekyll-coffeescript` return, and it was just that I didn't have another dependency installed.  

I'm on: Windows 7, using ruby v2.2.2p95 via cygwin + zsh

Hope this helps and again, thanks, I look forward to playing around with this!

**Comment by maya** [comment]
Thanks! We'll look into it.
