### ISSUE TITLE
"usa-" prefix missing from typography CSS selectors, possibly more

### ISSUE THREAD

**Issue by MickeyKay** [18F/web-design-standards#758]
Is there a reason the `usa-` prefix is absent from many of the typography CSS selectors (e.g. `.text-tiny`, `.typography-sans-intro`, `.preview`)?

For consistency, as well as to avoid class naming collisions with any future CSS and/or 3rd party CSS, it seems like a best practice to prefix _all_ CSS selectors.

**Comment by maya** [comment]
@MickeyKay those are for styleguide-specific styles in styleguide.scss, not included in the assets you'll download in the library. I know if can be confusing not knowing this! Does that make sense?

**Comment by maya** [comment]
@MickeyKay didn't hear back from you, so hope my answer sufficed!

**Comment by MickeyKay** [comment]
Yep, got it. Thanks maya!

**Comment by maya** [comment]
:+1:
