### ISSUE TITLE
Example HTML

### ISSUE THREAD

**Issue by paultag** [18F/web-design-standards#759]
Thanks for all your work on this!

It'd be fantastic if there were some example markup for folks to get an at-a-glance (the docs do a great job of covering all the specifics), so designers and developers can get a quick look at what best practice looks like

Something analogous to http://getbootstrap.com/getting-started/#examples

**Comment by msecret** [comment]
Hey @paultag, I would say right now, checking on the actual web standards website is an OK example. There's also a template somebody else on our 18f team made that would make a good example: https://github.com/18f/federalist-modern-team-template.

I think we should keep this issue open as advice to add this in a more formal way in the future.

**Comment by joewiz** [comment]
:+1:

**Comment by skonzem** [comment]
In addition to an example of the HTML, it would be very useful to see an example of how to manage a project incorporating these standards over time. As improvements and bugfixes are made to the standards, it seems like a user will want to update their entire standards assets directory periodically. Basically, the standards assets directory would be vendored in, and any custom assets that aren't part of the standard would probably live somewhere else.

The Federalist Modern Team Template is a helpful example of how to use the elements, but it doesn't appear to make use of this exact code. I'm not sure whether it's an older version or a superset. For example, I noticed that the Modern Team Template defines styling for the skip-nav element, but that's not present here. If the Modern Team Template were refactored into the part that's these standards and the part that's added on, then it would provide better guidance on how to structure the project directory and update it over time.

**Comment by rogeruiz** [comment]
The examples contained on the Draft Web Design Standards site are available as examples of HTML. They are markdown files with HTML embedded in them. I agree that these HTML examples should be available to non-technical users that would rather have code to work with rather an going through the docs or building the project locally.

I see including example HTML files within a `dist` directory for users of the standard something that we could do to support this.

**Comment by juliaelman** [comment]
@paultag we now have page templates where folks can view some example html: https://standards.usa.gov/page-templates/

We also recently updated our documentation to clearly outline how to link the Standards assets into your project: 

[Download method](https://github.com/18F/web-design-standards#download)
['npm' install method](https://github.com/18F/web-design-standards#install-using-npm)

Closing this issue, but feel free to open a new one if there are other examples that might be helpful to you!
