### ISSUE TITLE
Language for describing the standards/why they should be used during intro calls with 18F.

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards#761]
It would be lovely to have some language to use when agencies call me and want to hear about what 18F offers. The specific point will be what it means for these to be standards - what is the right language for describing why they should be adopted?

**Comment by awfrancisco** [comment]
Let me know if you'd like help editing on this.

**Comment by wslack** [comment]
Will do. Filed this for Mollie and others; will defer to them for how it should be drafted.

**Comment by awfrancisco** [comment]
+1

**Comment by maya** [comment]
@wslack @awfrancisco I'm wondering if there's another repo about project intake or outreach that would be better suited for this issue. It doesn't really pertain to this repo.

**Comment by wslack** [comment]
I filed it here at Mollie's request; we can chat about it on another platform if you prefer.

**Comment by juliaelman** [comment]
Agreeing with @maya.

@wslack @awfrancisco closing this in favor for opening it in https://github.com/18F/intake.

**Comment by wslack** [comment]
@juliaelman I don't think its an issue for the Intake repo; just wanted talking points for why the draft standards are useful like:
* Provide common tools
* Accessible
* Easy to deploy
* Reflect 18F researched best practices

**Comment by jpyuda** [comment]
I think if the intake team wants to come up with language/talking points about why 18F might want clients to use the standards, that's up to the intake team. I'm not interested in pressuring 18F clients into using them or not.

**Comment by wslack** [comment]
@jpyuda I apologize for not being clear. It's not my desire to have talking points. I was asked on calls about why the draft standards should be used by agencies, and I wanted to be responsive to the request. There's no pressure implied here - just being responsive to the question. As of right now, I'll plan to say we have found them useful in our work and will point them to https://playbook.cio.gov/designstandards/.
