### ISSUE TITLE
[Sidebar nav] Mobile experience 

### ISSUE THREAD

**Issue by dylanvalade** [18F/web-design-standards#763]
On iOS 8 with Chrome the mobile sidebar menu has varying success. When the nav is expanded sometimes swiping up and down scrolls the nav items and other times the page content scrolls and nav incorrectly stays fixed.

Most people are right handed. Putting the menu button in the top left corner of the screen is furthest from the dominate thumb's natural position to expand the nav.  It may even require two hands to use that UI control position depending on the scale of device to the user's hand.

**Comment by maya** [comment]
@dylanvalade it seems like there are two parts to your issue. A design/usability preference about the menu button in the first paragraph. And a bug in the second. Could you split this into two issues?

**Comment by dylanvalade** [comment]
@maya  Good call.  I've broken them out to #782 and #783.

**Comment by maya** [comment]
:+1:

**Comment by mollieru** [comment]
Thanks for the input! We're working on this and will keep you posted! Stay tuned.
