### ISSUE TITLE
Months and Days should limit input to two characters.

### ISSUE THREAD

**Issue by imthatoneguy** [18F/web-design-standards#764]
You should reject dates like the month '8318801' inside of say a birthday field.

**Comment by Kireyin** [comment]
That and validate only if numbers are inputed.

**Comment by maya** [comment]
@imthatoneguy @Kireyin The `maxlength` attribute is not supported for number inputs. Do you have any other suggestions? I've included a min and max attribute in #777.

**Comment by maya** [comment]
Resolved in #777.
