### ISSUE TITLE
[Sidebar nav] Mobile scrolling bug

### ISSUE THREAD

**Issue by dylanvalade** [18F/web-design-standards#782]
On iOS 8 with Chrome when the mobile nav is expanded sometimes swiping up and down scrolls the nav items and other times the page content scrolls and nav incorrectly stays fixed.

This was originally mentioned in #763

**Comment by mollieru** [comment]
thanks for flagging @dylanvalade -- looking into this now.

**Comment by maya** [comment]
Fixed in: #1274.

View on: https://standards-staging.usa.gov/.
