### ISSUE TITLE
[Sidebar nav] Mobile usability preference

### ISSUE THREAD

**Issue by dylanvalade** [18F/web-design-standards#783]
Most people are right handed. Putting the mobile menu button in the top left corner of the screen is furthest from the dominate thumb's natural position to expand the nav. It may even require two hands to use that UI control position depending on the scale of device to the user's hand.

I suggest moving the mobile menu UI control to the right side of the screen.

This was originally mentioned in #763

**Comment by MsWebGirl** [comment]
+1

**Comment by mollieru** [comment]
Thanks @dylanvalade and @MsWebGirl -- we're taking a look at this and considering it for a future release. stay tuned!

**Comment by nitos** [comment]
Yes, right side please. 
http://www.uxmatters.com/mt/archives/2013/02/how-do-users-really-hold-mobile-devices.php

![Image of mobile use]
(http://www.uxmatters.com/mt/archives/2013/02/images/HoldPhones_Figure-2.png)

**Comment by juliaelman** [comment]
This will be solved via an updated layout that @carodew and @ericadeahl have completed.

Leaving open until that new layout is implemented - thanks!

**Comment by donjo** [comment]
Closing this out since the new layout has been implemented!
