### ISSUE TITLE
Aww crap another jQuery Bootstrap

### ISSUE THREAD

**Issue by thednp** [18F/web-design-standards#784]
Why don't you quit using jQuery once and for all and push for the real web standards?

**Comment by msecret** [comment]
Our main reason for using jQuery was to ensure we had old IE browser support while developing the standards in a relatively tight timeline.

That being said, it's not being used excessively right now so we do have interest in removing it in the future.

**Comment by csakis** [comment]
What's wrong with JQuery? Have I missed something?

**Comment by thednp** [comment]
What's wrong? "jQuery - Write less do more" is no longer a valid sentence. Also for old IE there's a ton of polyfill, users may opt to use or not. So yes, crap.
