### ISSUE TITLE
Expand grid for breakpoints

### ISSUE THREAD

**Issue by Taitrnator** [18F/web-design-standards#787]
expand on grid for different widths at different screen sizes as foundation or bootstrap implements. 

rather than breaking 1/6 and 1/12 into 1/3 and 1/6 respectively at medium width, I think it would be preferable to fully define different breakpoints with classes. 

probably best to do this by removing -width- from classes, which I don't see an immediate need for right now. 

`usa-width-one-twelfth` becomes `usa-medium-one-twelfth` 

*expanding on the grid notation in another issue* ^

**Comment by maya** [comment]
The idea of using breakpoints is that you just have to use the single class and it resizes based on the breakpoint. I'm not sure that I understand your question.

**Comment by Taitrnator** [comment]
I think the breakpoint system is good but its somewhat unique. It forces people to respect responsive a bit more but limits the options. 

I just think lots of people are accustomed to adding classes for different sizes. 

for instance a dev might want: 
`usa-medium-one-half usa-large-one-fourth` 

Id like to see the grid as it is, automatically respecting the breakpoints but also extended with some classes to override that behavior.

**Comment by maya** [comment]
Oh I _think_ I'm understanding better now after looking at your examples. When we initially made the grid, we sought to create something easy enough to drop in a class and have the grid work in a reasonable way. For our super users, we're including Neat, so people can add custom grid settings when our solution doesn't work for them.

Grids have their limits and you have to know when to use something else :smile: 

We'll definitely keep this thought in mind, as we continue to build out and see what works for people.
