### ISSUE TITLE
use integers for grid for more consistent usage 

### ISSUE THREAD

**Issue by Taitrnator** [18F/web-design-standards#788]
its hard to keep up with "one-sixth" and "two-sixths" for instance, and I think it will cause people frustration when using markup. I experienced that when misspelling "twelfth" earlier for instance. 

I'd suggest using numbers here to keep it concise and easy to use. 

`usa-width-one-sixth` becomes `usa-width-1-6`

or, to combine with my last issue, `usa-medium-1-6` or `usa-small-1-6` for instance

**Comment by maya** [comment]
"two-sixths" reduces down to "one-third". I think it's probably a good thing to learn how to spell twelfth :) I find that spelling out the ratio is more explicit than the numbers and easier to grasp, although I've used something like that in the past!

**Comment by Taitrnator** [comment]
better yet, what about just going with one number:

`usa-one` = 1/12 
`usa-six` = 1/2 
or 1/3 as you mention becomes `usa-four`

then those can be rounded up one for smaller screens.  where the intention is to use 6 columns.

`usa-one` rounds up to `usa-two` for medium screens 

or `usa-seven` rounds up to `usa-eight`

**Comment by maya** [comment]
Thanks for your input! It’s useful to get other perspectives. We’ll stick with this as designed, but we can always look at this again later. If you want to modify this for your personal use, please feel free to fork it and go ahead!
