### ISSUE TITLE
caption for data table

### ISSUE THREAD

**Issue by goetsu** [18F/web-design-standards#791]
https://playbook.cio.gov/designstandards/tables/
at least the accessibility text in documentation must say that you need to use `<caption>` element inside the `<table>` if you want to have text used as title or heading for the table cf http://www.w3.org/TR/WCAG20-TECHS/H39.html

**Comment by maya** [comment]
Thanks for catching this. Let's add something like:
>When adding a title to a table, include it in a `<caption>` tag inside of the `<table>` element.
