### ISSUE TITLE
using h4 in footer

### ISSUE THREAD

**Issue by goetsu** [18F/web-design-standards#794]
https://playbook.cio.gov/designstandards/footers/#big-footer

Currently on the code example you use an h4 element inside an ul element and it's not conforming to html who only allow li element inside ul element. You need to move the h4 before the ul element or use two levels lists.
Furthermore, using h4 may break the document outline if you don't use h1, h2 or h3 before it

**Comment by maya** [comment]
Thanks again.

TODO: add this to the documentation:

`Ensure the heading level starts from highest to lowest so that you do not break the document outline.`

**Comment by KimberlyMunoz** [comment]
I found that http://khan.github.io/tota11y/ was a great tool to test the heading levels when I was doing an accessibility check across our project.

**Comment by mollieru** [comment]
Thanks @goetsu and @KimberlyMunoz -- looking into this now, we'll keep you posted. 

// cc @maya

**Comment by maya** [comment]
Fixed in #1183.
