### ISSUE TITLE
Update Source Sans Pro fonts to the latest version

### ISSUE THREAD

**Issue by miguelsousa** [18F/web-design-standards#802]
The Source Sans Pro font files in `assets/fonts` are [version 1.050, which was released in April 2013](https://github.com/adobe-fonts/source-sans-pro/releases/tag/1.050R). The [current versions](https://github.com/adobe-fonts/source-sans-pro/releases) are 2.020 (uprights) and 1.075 (italics), and were released last month.

Updating to the latest version of the fonts will likely fix issue #737, reduce the fonts' footprint, and get the assets in sync with the latest and greatest.

I'm one of the maintainers of the [Source Sans Pro repository](https://github.com/adobe-fonts/source-sans-pro) and I'm willing to submit a PR to update the fonts. **But before I do any work, I'd like to know if there's any interest in getting the fonts updated?** I ask this because the original font files will require some amount of post-processing to get them down-sampled to match the same set of characters and features that is supported by the current files in `assets/fonts`. In other words, the PR is not as simple as submitting the original font files (although I can certainly do that, but it will come with a performance hit).

**Comment by maya** [comment]
@miguelsousa thanks so much for reaching out! 

We're very interested in using the latest and greatest fonts (the current ones are just what was offered via Google Fonts). We'd want to consider performance impact as well, so optimizing it like you mentioned sounds like a good idea.

A few questions:
- Can you let us know what the file size difference would be?
- What's new in those files?

Thanks again!

**Comment by miguelsousa** [comment]
@maya happy to learn that you welcome this improvement.

The file size will be comparable to the current one. I won't know the exact number until I work on it, but the new font files may actually come in slightly smaller because we took out the license's full text from the fonts.

In terms of differences, the design got a bit more polish (intermediate weights are better interpolated; the diacritics were resized), and the TrueType hints were redone from scratch (a [comment from a TrueType expert](https://twitter.com/mickduggan/status/649151849732419584) was actually what prompted us to reach out). The font family received other improvements, such as the addition of Greek and Cyrillic, but these are not relevant for your project.

Feel free to assign me to this issue. I'll report back once I have more news.

**Comment by maya** [comment]
@miguelsousa I think we can only assign issues to collaborators/team members on the project. However, feel free to submit a PR and we'll be happy to review it.

**Comment by mollieru** [comment]
@miguelsousa awesome, let us know when you've got something for us to look and we will merge it in! Thanks so much for keeping us up to speed :ok_hand:

**Comment by miguelsousa** [comment]
@maya @mollieru the PR is ready for your review.

**Comment by maya** [comment]
Closing via #848. 

Thank you @miguelsousa!

**Comment by maya** [comment]
Hi @miguelsousa, just wanted to check in since it's been 2+ years since updating Source Sans Pro fonts. Are there any significant changes to Source Sans Pro since then that would benefit updating them once again?

**Comment by arvalarva** [comment]
Last Source Sans Pro update was 2014. 2.0.1.0 http://www.adobe.com/products/type/font-information/Source-Sans-Pro-Readme-file.html

**Comment by miguelsousa** [comment]
@maya there have not been any changes. The fonts that I submitted to this repository were based on Roman v2.020 and Italic v1.075; these are still the [latest releases](https://github.com/adobe-fonts/source-sans-pro/releases).
