### ISSUE TITLE
[Documentation] Color codes for secondary-darkest and secondary-dark are swapped

### ISSUE THREAD

**Issue by timbonicus** [18F/web-design-standards#803]
Looking at the [palette documentation](https://playbook.cio.gov/designstandards/visual-style/#palette), it shows secondary-darkest as hex #cd2026, and secondary-dark as #981b1e. These are backwards, as evidenced by the swatches above using the opposite hex code.

**Comment by maya** [comment]
Thanks for catching this!

**Comment by carodew** [comment]
This will be fixed in our next push to production, thanks!

**Comment by maya** [comment]
Fixed in #808.
