### ISSUE TITLE
Duplicative selectors in _buttons.scss?

### ISSUE THREAD

**Issue by rhewitt22** [18F/web-design-standards#805]
It appears that you've duplicated three attribute selectors in the [buttons partial](https://github.com/18F/web-design-standards/blob/890640d73f598ccdc9bade37b073ff0130f3c230/assets/_scss/elements/_buttons.scss#L12-L17).

```css
.usa-button,
.usa-button-primary,
.usa-button:visited,
.usa-button-primary:visited,
button,
[type="button"],  <=
[type="submit"],  <=
[type="reset"],   <=
[type="button"],  <=
[type="submit"],  <=
[type="reset"],   <=
[type="image"] {
  ...
}
```

**Comment by msecret** [comment]
Good catch!
