### ISSUE TITLE
Spring framework? 

### ISSUE THREAD

**Issue by njohnson** [18F/web-design-standards#806]
How can we include this into a spring framework?

**Comment by buckaroogeek** [comment]
Nancy

I have not used Spring for almost 10 years now, but I would image it would
entail writing a build task that builds a template based on this standard
in whatever template format your Spring implementation is consuming.

Brad

**Comment by mollieru** [comment]
@njohnson could you tell us a little bit more about what you're looking for? Thanks so much for your input!

**Comment by njohnson** [comment]
The engineer is actually using Spring Boot as a middleware into a war file. We may go to a standalone in the future as we move to a cloud based application.  We are looking a possibly using angular as the JQuery library and I would like to move to bourbon using either node or rails for presentation.  His solution is the same as buckaroogeek.  

Thank you.

**Comment by mollieru** [comment]
@njohnson thanks for the suggestion! We won't be able to support this right now, but we encourage you to fork and create a spring framework for your projects.
