### ISSUE TITLE
Footer language about open source license should be consistent with the actual license.

### ISSUE THREAD

**Issue by ultrasaurus** [18F/web-design-standards#810]
It currently says "As a work of the United States Government, this project is in the public domain within the United States."  However, the actual license is Universal Public Domain, which is consistent with 18F policy.

Propose changing to:  "This project is in the public domain"
Or "This work of the United States government is dedicated to the public domain"

**Comment by mollieru** [comment]
@ultrasaurus any chance we could get you to submit this as a PR? will reward you w puppies and rainbows? :dog: :rainbow:

**Comment by maya** [comment]
cc @brittag

**Comment by brittag** [comment]
I'd suggest the simple modification of "As a work of the United States Government, this project is in the public domain." I like that this provides a tiny bit of context for the license.

A bunch of embedded components by non-government people are not in the public domain (mostly MIT licensed), so I believe "This project is in the public domain" wouldn't provide enough information.

**Comment by mollieru** [comment]
Thanks @ultrasaurus and @brittag for flagging these good points. We'll work in coming up w some better language!

**Comment by brittag** [comment]
Tiny point while this footer is up for discussion: looking at [18F's content guide for capitalization](https://pages.18f.gov/content-guide/capitalization/), it recommends not capitalizing "government".
