### ISSUE TITLE
Include readme and license info in the "download code" zip

### ISSUE THREAD

**Issue by brittag** [18F/web-design-standards#816]
As a user, when I click "download code" on a project, I like finding some metadata included in that downloaded folder on my desktop - so that if I look at it later, I can easily remember what it is, where I got it from, and what the license is. :)

This would also help comply with the licenses of the included MIT-licensed works, since a condition of the license is for the license text to be included with all copies of the works.

**Comment by mollieru** [comment]
Cool, thanks @brittag! We'll include this in a future release.

**Comment by maya** [comment]
We probably should add the change log too.

**Comment by maya** [comment]
Related to https://github.com/18F/open-source-guide/issues/27

**Comment by juliaelman** [comment]
Adding a note about a possible template we can leverage for adding LICENSE information when incorporating the WDS into one's project:

From @brittag:
> While chatting with @coreycaitlin about updating the LICENSE file for the 18F website, we realized that since the site repository includes Web Design Standards files that have a mix of license statuses, the LICENSE file should state that: https://github.com/18F/18f.gsa.gov/blob/dev/LICENSE.md. This may be helpful as a base for a recommended LICENSE template for projects that use the standards

**Comment by brittag** [comment]
Thanks @juliaelman! I'd encourage including a template LICENSE file in the download zip file, or otherwise making a template LICENSE file prominently available from https://standards.usa.gov/download/ and https://standards.usa.gov/getting-started/developers/

Looking at this thread, I'd encourage considering the related original issue in this thread a bug and not an enhancement, since carefully complying with open source license requirements is part of our obligation as open source community members.

**Comment by juliaelman** [comment]
Done here https://github.com/18F/web-design-standards/pull/1691

**Comment by brittag** [comment]
Hooray, thank you @juliaelman!

**Comment by juliaelman** [comment]
@brittag no problem! I also added the `CONTRIBUTING.md` file too, since it is referenced a few times in the `README.md`.
