### ISSUE TITLE
Times size multipler for classes that have different sizes.

### ISSUE THREAD

**Issue by bohl3r** [18F/web-design-standards#821]
Instead of offering a "big and small" alternative for most classes, such as buttons. Maybe it would be better and allow more functionality of this framework would be a times multiplier for different size classes. Am example, Instead of "big or small" - refer to chart.

Size | Class | Use | Code Example
--- | --- | --- | ---
Default | one-times | General use |  ```<button class="usa-button one-times" type="button">One Times Button</button>```
2x Default | two-times | General use |  ```<button class="usa-button two-times" type="button">Two Times Button</button>```
3x Default | three-times | Bigger pages|  ```<button class="usa-button three-times" type="button">Three Times Button</button>```
4x Default | four-times | Even bigger pages | ``` <button class="usa-button four-times" type="button">Four Times Button</button>```
5x Default | five-times | Even even bigger pages |  ```<button class="usa-button five-times" type="button">Five Times Button</button>```

**Comment by maya** [comment]
@bohl3r Interesting idea! I think our current nomenclature relies on the big/small variants. However, we'll keep this in mind in case this seems to be a need for our govt partners. Thanks again.
