### ISSUE TITLE
Playbook - incorrect citation on accessibility

### ISSUE THREAD

**Issue by rusty1992** [18F/web-design-standards#823]
@ https://playbook.cio.gov/designstandards/getting-started/

"All of the designs meet the WCAG 2.0 AA accessibility guidelines and are compliant with Section 508 of the Americans with Disabilities Act. If you choose to customize them, ensure they continue to meet the requirements listed in the “Accessibility” section of each design."

One Correction - the correct reference is Section 508 of the Rehabilitation Act of 1973. Section 508 is not a section of the American's with Disabilities Act.

**Comment by fureigh** [comment]
Thanks for the correction, @rusty1992!

**Comment by nickbristow** [comment]
@rusty1992 Thanks for the correction, 

We were looking around, and it is written in several different ways. Not sure which of these is the best to go with in this context. It would be great to have your input on this. 

Section 508 of the Rehabilitation Act of 1973
Section 508 of the Rehabilitation Act - 29 U.S.C. § 798
Section 508 of the Rehabilitation Act of 1973, as amended (29 U.S.C. § 794 (d))
Section 508 of the Rehabilitation Act of 1973, as amended in 1998

**Comment by maya** [comment]
@rusty1992 or even simpler....

Section 508 of the Rehabilitation Act

What do you recommend?

**Comment by rusty1992** [comment]
that's fine   "Section 508 of the Rehabilitation Act"


More importantly, going forward, we need to ensure we have the CIOC
 Accessibility Community of Practice (ACoP) engaged in going forward.  Who
should I be engaging with on 18F to make this happen?

On Wed, Oct 14, 2015 at 1:35 PM, Maya Benari <notifications@github.com>
wrote:

> @rusty1992 <https://github.com/rusty1992> or even simpler....
>
> Section 508 of the Rehabilitation Act
>
> What do you recommend?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/web-design-standards/issues/823#issuecomment-148128339>
> .
>



-- 
John J. Sullivan,
Director, Information Resources Management Division
Office of Information, Integrity, and Access, Office of Government-wide
Policy, and
Program Director, Government-wide Section 508 Program
U.S. General Services Administration
1800 F St, NW, Washington, D.C. 20417
(o) 202-501-1983

**Comment by maya** [comment]
@rusty1992 great, thank you. 

I think @nickbristow would be the point of contact regarding engaging the the CIOC Accessibility Community of Practice (ACoP) going forward.
