### ISSUE TITLE
Bundler is not listed as a requirement

### ISSUE THREAD

**Issue by andreskytt** [18F/web-design-standards#826]
Local installation depends on packages that need to be installed using bundler. But bundler is not listed as a environment requirement. A good solution would be to mention it in the README.md

**Comment by mbland** [comment]
[The `./go` script will try to install Bundler](https://github.com/18F/web-design-standards/blob/18f-pages-staging/go#L15) if it isn't already installed.

**Comment by brittag** [comment]
Perhaps it would be helpful for this readme to briefly summarize what the go script will install for this project, to help people have more confidence before running it (and to have a tiny bit more context about how this project works internally, in case they're interested in modifying it)?
