### ISSUE TITLE
Add menus to the standards

### ISSUE THREAD

**Issue by tdlowden** [18F/web-design-standards#828]
Would love to see menus similar to 'li class="usa-menu-item"' that are used on https://cloud.gov. This particular example offers a great hover effect.

**Comment by maya** [comment]
@tdlowden yep! that was grabbed from this WIP PR: https://github.com/18F/web-design-standards/pull/308

**Comment by tdlowden** [comment]
@maya oh sorry I missed it. Awesome. Look forward to the merge. I'll close. Thank you!
