### ISSUE TITLE
IE 8 [various]

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#834]
We officially support IE 9 and above so will be closing the issues related to IE 8. 

Documenting here for reference in case it's ever a priority to revisit and reopen. Also added the [`consider later`](https://github.com/18F/web-design-standards/issues?utf8=%E2%9C%93&q=label%3A%22consider+later%22+is%3Aclosed+ie+8) tag to them.

https://github.com/18F/web-design-standards/issues/473
https://github.com/18F/web-design-standards/issues/466
https://github.com/18F/web-design-standards/issues/465
https://github.com/18F/web-design-standards/issues/437
https://github.com/18F/web-design-standards/issues/436
https://github.com/18F/web-design-standards/issues/435
https://github.com/18F/web-design-standards/issues/434
https://github.com/18F/web-design-standards/issues/432
https://github.com/18F/web-design-standards/issues/431
https://github.com/18F/web-design-standards/issues/430
https://github.com/18F/web-design-standards/issues/428
https://github.com/18F/web-design-standards/issues/427
https://github.com/18F/web-design-standards/issues/425
https://github.com/18F/web-design-standards/issues/424

Also, I think that some actually should be closed out bc were addressed with polyfills.

**Comment by juliaelman** [comment]
Putting this issue on hold for the time being, while our research team digs in to see overall usage. See Trello card below.

https://trello.com/c/BRjAt3aT/19-is-ie8-still-in-heavy-use-at-libraries-senior-centers-and-other-public-computer-labs-and-do-we-have-an-obligation-to-support-it-

**Comment by jpyuda** [comment]
We'll re-open this if research points us in the direction of IE8 support.
