### ISSUE TITLE
expand feedback options 

### ISSUE THREAD

**Issue by gbinal** [18F/web-design-standards#844]
This issue may be a duplicate but if not it'd be great to add an option for those who want to get in touch but aren't comfortable using github.  Email seems the easiest solution to add, but there are other good options, I'm sure.

**Comment by brittag** [comment]
This email address would be nice to mention <a href="https://github.com/18F/web-design-standards#got-feedback">in the README</a> as well.

**Comment by gbinal** [comment]
+1 - expanding the pull request to do that
