### ISSUE TITLE
Clarify the role and status of this project in the homepage text

### ISSUE THREAD

**Issue by brittag** [18F/web-design-standards#846]
Currently the project homepage can prompt a few questions for visitors who work on government websites and have prior experience with the term "standards" in various contexts (such as "Section 508 standards" that are mandatory). The project homepage could help readers by answering some common questions more clearly in its copy. Suggested questions to answer on the homepage:

1) Are these standards mandatory for new government websites?

It may help to explicitly say these are not mandatory, and follow that with appropriate phrasing about being a "best practices guide", "model for standards that agencies and offices can adopt", "suggested pattern library", or similar. For example, the site could continue after "It provides a guide for creating beautiful and easy-to-use online experiences for the American people." with "It is not mandatory, instead serving as a pattern library that anyone can choose to build upon for their websites." (Maybe "any division" or “any agency or office” instead of "anyone"? I'm not sure what the best general term is.)

In context:

![image](https://cloud.githubusercontent.com/assets/391313/10613570/9b1cab02-770a-11e5-8fce-d5e814d2ee74.png)

2) Are these standards complete and ready to use? (How should we send feedback?)

The top right says "This site is currently in alpha. Learn more." but readers can miss that while scanning the homepage, and the page it links to may be confusing since it has a general explanation of alpha stages rather than a specific explanation for this project. It could help to restate this with more context in the main text, such as saying "These standards are in an early stage of development, and your input and contributions are welcome." I'm not sure where this would go, since it would be nice to mention somewhere near the top, but one option is to improve the "Contribute" section at the bottom:

"The web design standards alpha was created during the summer of 2015 by designers and developers at the U.S. Digital Service and 18F.

This project is in an early stage of development, and we welcome input and contributions from the public and maintainers of government websites. To contribute a comment, <a href="https://github.com/18F/web-design-standards/issues">open an issue on GitHub</a> or email us at <a href="mailto:uswebdesignstandards@gsa.gov">uswebdesignstandards@gsa.gov</a>. You can also contribute code and content to the project on GitHub.

We will continue to maintain and update these resources as we learn what works best for the people we serve."

The top-right “Learn more” link could even go to that “Contribute” section, since it has all this context, and then “alpha” in that section could link to the general 18F-wide description of what alpha means.

As another nod to this, the top-right “View on GitHub” button could be “View and contribute on GitHub”. In context:

![image](https://cloud.githubusercontent.com/assets/391313/10613591/ac8ebc7c-770a-11e5-8225-f752298e91e6.png)

3) How will we hear about updates?

I'm not sure where or how this should be answered, but the homepage could help readers by linking to a changelog or another way to learn about updates as they happen, since it’s an alpha. The “Download the components” button could also mention the version number, to help set the expectation that this project has versions and will change.

**Comment by gboone** [comment]
Big :+1: to this. We have been getting many of these exact questions on the content managers listserv. We can (and we plan to) write a blog post that answers these but clarity on the site will go much further. Specifically to the definition of alpha: many people have different ideas about what that specific word means and assume it means these are mostly broken and not to be trusted until <something after alpha> happens.

> the page it links to may be confusing since it has a general explanation of alpha stages rather than a specific explanation for this project.

The 18F/Dashboard team is currently researching the "stages" and what these terms mean for 18F and how they need to be reworked to better reflect our products. Hopefully we can get input from this team during that research.

**Comment by brittag** [comment]
Thanks, that adds to the importance of explaining on this homepage what "alpha" means to this project. :)

As an alternate bolder way of communicating that these standards are not mandatory, the lead could include a bit more information, such as adding " — model standards that any website can adopt and build upon":

![screen shot 2015-10-20 at 2 42 49 pm](https://cloud.githubusercontent.com/assets/391313/10621983/0d6cf260-7739-11e5-85a8-4a305f86d19f.png)

**Comment by kategarklavs** [comment]
What about this?

" — model standards anyone can adopt and build upon" (?)

The first portion of the statement identifies that these components/guides are for the purpose of building beautiful experiences across websites; a second mention of websites doesn't seem totally necessary. (And I'm also in favor of reworking to communicate that people are doing the work!)

**Comment by maya** [comment]
Since we're changing the whole name to Draft U.S. Web Design Standards, can/should we still use the phrasing "model standards"?

@kategarklavs @gboone @brittag

**Comment by maya** [comment]
Hi @brittag, our homepage has changed a lot since this was opened and wanted to followup to see if the current homepage (https://standards.usa.gov/) addresses your concerns. Thanks!

**Comment by brittag** [comment]
Oh wow, this was a long time ago! Looking again at the site, the answer to "Are these standards mandatory for new government websites?" is still unclear to me, and "How will we hear about updates?" takes some digging (I see that the release notes are visible, but I wouldn't immediately know how to subscribe to notifications of new releases).

I don't know though whether these two questions are still important (I don't know whether people still ask them).

**Comment by maya** [comment]
Yes, it was quite some time ago! I think we address some of those questions:

>"Are these standards mandatory for new government websites?"

The new tagline hopefully addresses that's it's just a design system federal agencies can use "The Standards are a design system that allows federal agencies to quickly prototype and deploy digital products using a baseline of design patterns."

>"How will we hear about updates?" 

The new "What's New" page in the main nav also hopefully addresses this, as well as the contribution section in the bottom. If we ever have a newsletter we'll be sure to include it too.

Closing out for now, thanks again!
