### ISSUE TITLE
Rename 'main' file(s) with namespace to prevent conflicts

### ISSUE THREAD

**Issue by fureigh** [18F/web-design-standards#847]
What if we changed `main.scss` to, say, `usa-main.scss`?

The inspiration for this suggestion: in [a Flask app](https://github.com/18F/site-data) into which I just incorporated the USWDS, pulling main.scss down threatened to overwrite application-specific code in preexisting SCSS files. Namespacing the `main.scss` file (and possibly others) is one way to guard against this problem.

**Comment by fureigh** [comment]
(cc @maya and @baccigalupi)

**Comment by msecret** [comment]
This generally sounds like a good idea.

**Comment by maya** [comment]
Hi @fureigh, just wanted to follow up on this issue. the main scss file is now called `uswds.scss` (https://github.com/18F/web-design-standards/blob/develop/src/stylesheets/uswds.scss). Does that resolve this issue?
