### ISSUE TITLE
Form elements UI/UX improvements

### ISSUE THREAD

**Issue by kottenator** [18F/web-design-standards#860]
Hi!

First I want to say that you're doing great job! US government sites indeed require UI/UX improvements and unification.

I'm considering to use your framework. However, I have few remarks and ideas. I've created [my own form styles](http://jsbin.com/ruwuwi/2) some time ago and some parts of it may be useful for your framework:
- you have different border-width for normal/error/success state of an input field. This could affect other layout (when I expect exact height for the field). I assume that you wanted to emphasize the state of the field in this way. I think it could be done without changing the box size (e.g. box-shadow or outline instead of border-width). IMO, box size should remain the same
- _(minor)_ I don't 100% agree with "flat" design for text inputs (Win 8/10 -like). Without "volume", input looks the same as a "transparent" button. In my example, I've added some shadows to distinguish an input from a button.
- I think that form input box shadow could be improved (as well as the same box shadows in other UI elements like menus, but that's a separate case). Especially how they look'n'feel together with different border colors of input boxes (e.g. blue shadow with "default" black border, or with red "error" border - _looks too rough_). In my example, I've made box shadow similar to the one in OS X Yosemite, and with different color for normal/error input states
- also in my example there is a kind of "micro-grid" for multiple inputs in a row, you may take a look - `.field-group`

I understand that you've thought-out and made much more than I. And most of my remarks are minor. But they still may be valuable.

I haven't created a pull-request to your project because I'm not sure if you agree with my ideas and is it worth creating at all. If you do, I can create one.

Anyway, thanks for your project, there is definitely a need for it

**Comment by carodew** [comment]
It would be interesting to test the flat design/drop shadow question with hard-to-serve populations. We did initial user testing on our form fields and found that folks had no issues understanding the `<label> <box>` configuration, but testing different populations may yield different results. I'd be interested to see any related research about that. Thanks!

**Comment by kottenator** [comment]
Hi!

I've created a [pull-request](https://github.com/18F/web-design-standards/issues/878) with new `box-shadow` implementation for form inputs. @carodew mentioned that shadow _inside the field_ requires some research and proof, so I've not added it for now. What I've changed is the _outer glowing shadow_.

See my comments about what has been done - inside the PR.

I'm not sure where the discussion should go - here or in pull-request comments?

**Comment by maya** [comment]
@kottenator just to followup, it will be easier for us to evaluate the issue if it's one item per issue, rather than several (This guidance will also be added to our contributing doc). Can you break this out?

Also our contributing doc encourages the use of images (before + after), which is a way we can involve our visual designers more easily as well.

**Comment by kottenator** [comment]
Hi!

Sure, everything you say sound reasonable. I will decouple this issue (and my pull request) into several

**Comment by bradnunnally** [comment]
This issue has some relation to the PR #1118. We are closing that PR and will pick all this up at a later date when we look to enhance the form elements design.

**Comment by joshbruce** [comment]
Was going through critical priorities today - was going to tackle this one: #1094

After researching the previous PR made on it - saw the PR associated with this ticket. Is the aforementioned issue something I should skip in my consideration until the core team determines a way forward? Maybe close #1094 and reference this one, which appears to be a consolidation issue.

Would that turn this ticket into critical, given the priority of #1094?

**Comment by maya** [comment]
@joshbruce Feel free to skip this in relation to the other issue you mentioned. This will need consideration and review from our UX team. Critical bugs are the thing to look at tackling: https://github.com/18F/web-design-standards/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Bug%22+label%3A%22%5BPriority%5D+Critical%22

**Comment by maya** [comment]
We have a new design for our form elements and will be following this approach in #2136.

**Comment by kottenator** [comment]
What about focused state?
