### ISSUE TITLE
example images on landing page are too large, messes w/ page width

### ISSUE THREAD

**Issue by cathydeng** [18F/web-design-standards#863]
can I just start by saying that I *love* these standards? such rad work all around.

anyways, to the issue - there's a lotta whitespace to the right of the content, due to the size of the images in the examples down the page

<img width="921" alt="screen shot 2015-10-23 at 2 11 34 pm" src="https://cloud.githubusercontent.com/assets/1406537/10702568/235e6ffa-7990-11e5-8240-fd697e6acd94.png">

**Comment by colinpmacarthur** [comment]
Thanks for the kind words and raising the issue @cathydeng! 

I'm having trouble replicating this, but maybe I'm not doing the right thing? Could you post a little screen cast or suggestions on how to replicate?

**Comment by cathydeng** [comment]
I'm using firefox & see this issue at all window sizes. here's a gif:

![18f_issue](https://cloud.githubusercontent.com/assets/1406537/10704681/294cc93a-799e-11e5-9dc4-89a54fe751d8.gif)

**Comment by colinpmacarthur** [comment]
Thanks for the gif! @maya and @msecret - thoughts? This seems to be firefox specific.

**Comment by maya** [comment]
This appears to be a Firefox bug: "max-width:100% is not respected within auto-width inline blocks":

https://bugzilla.mozilla.org/show_bug.cgi?id=932996

**Comment by maya** [comment]
I found this issue to exist for IE as well - in IE9 and IE10 on Browserstack. 

I think we need to include IE in the fix in #864.

**Comment by maya** [comment]
Fix via #940.
