### ISSUE TITLE
First Column of Illustrator file out of alignment

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#872]
Copied from an issues from @rtwell on the `asets` repo: https://github.com/18F/web-design-standards-assets/issues/16

@mollieru I noticed that the 1. 2. 3. etc listing below the Merriweather headings and body are out of alignment in both the Typography_v.8.ai and the Typography_v.8.eps files. Screen shot attached for your reference. 

![image](https://cloud.githubusercontent.com/assets/3680494/10854791/4bbbd706-7f14-11e5-9917-4df4c268b0cd.png)

**Comment by maya** [comment]
@mollieru going to leave discussions for this in the other repo.
