### ISSUE TITLE
Add email address in footer

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#873]
**Description**

Folks who aren't comfortable with Github may not even be able to find our email address here. I suggest we add our address to the footer of each of our pages.

**Ask**

Add our contact email address (uswebdesignstandards@gsa.gov) to the footer on homepage and the interior pages.

**Comment by maya** [comment]
Already completed in https://github.com/18F/web-design-standards/pull/845.

**Comment by colinpmacarthur** [comment]
Blerg. Sorry I didn't check staging.

On Fri, Oct 30, 2015 at 10:10 PM, Maya Benari <notifications@github.com>
wrote:

> Closed #873 <https://github.com/18F/web-design-standards/issues/873>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/web-design-standards/issues/873#event-450987791>.
>



-- 
*Colin MacArthur*
Experience Design, 18F
(617) 283-8166
