### ISSUE TITLE
WDS Variations specifically for applications

### ISSUE THREAD

**Issue by rickleegit** [18F/web-design-standards#876]
First of all, it has been a JOY using the design standards! The sticker sheets in many formats and the patterns for FE are amazing!

- For content pages, the approaches work extremely well. For webapps, we are needing to create new patterns (totally fine!!) and customize a fair bit  for interaction groups (also fine!), specifically for form/field interactions that are dense in quantity.

- type treatments are extremely readable and nicely lead and spaced, however these also present a challenge, out of the box, for apps with high information densities.

- For apps, if we keep all of the out of the box styling, we are creating a scroll:task-value deficit. (I know scrolling isn't a usability measure we use any longer, but in apps its a little different than in content heavy screens. If I can only complete 3 elements of a complete workflow without scrolling, my workflow develops that scroll:task-value deficit. (unnecessary effort to complete the workflow). There are other ways around this such as the wizard approach of small element groups presented in a linear workflow, but that is often not  the best solution for every app workflow.

- Wondering if it is worth having a look at creating a subset of WDS specifically designed for application development?

**Comment by maya** [comment]
@rickleegit thanks so much, we're glad you're finding the design standards useful!

We created this with websites and web apps in mind, so it's fascinating to here you're thinking of using it for apps.

Question: What kind of apps are you looking to create with it (platforms, etc)?

**Comment by rickleegit** [comment]
We already are, actually. We are applying it to the GI Bill Comparison Tool
at DSVA.

The app is relatively simple, but the large form elements and spacing,
while nice and clean, do present challenges when the application relies
heavily on user inputs.

**Comment by maya** [comment]
@rickleegit What platform is the application on (iOS, Android, etc...)?

Is there any way to take a look at how you're using it -- like the use cases you mentioned above?

**Comment by rickleegit** [comment]
Rails app. Responsive. Will have a production version in a few days and I
will post the link at that time!

**Comment by maya** [comment]
Ah so it is still a web app. Each use case may have slightly different needs that should be developed specifically for that and tested with users. We may add general guidance about app flows in the future, but do not have that at this time. 

Looking forward to seeing what you're working on!

**Comment by carodew** [comment]
@rickleegit If you're available, would you (or one of the front end developers on your team) be willing to talk to myself and @colinpmacarthur for about an hour about your experiences working with the standards in your project? If so, what is the best way for me to send you more information? Thanks!

**Comment by rickleegit** [comment]
I dm'd contact info via slack.

**Comment by carodew** [comment]
We'll not be focusing on anything app-specific in the next few months but are focused on making sure everything is responsive and we will be looking at form interactions and patterns more closely. Stay tuned!
