### ISSUE TITLE
Distribution of the web design standards [List]

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#877]
This is to keep track of all the different distribution implementations of the standards that have been made. 

| Type  | Author | URL |
| ------------- | ------------- | ------------- |
| Ruby gem  | @mbland  | https://github.com/18F/us_web_design_standards_gem  |
| npm | 18F  | https://github.com/18F/web-design-standards#using-npm  |
| A node-sass based NPM package  | @openbrian  | https://github.com/openbrian/18f-contrib-web-design-standards  |
| Django  | @paultag (USDS)  | https://github.com/department-of-veterans-affairs/django-designstandards |
| NuGet package  | [Abdul Ahad Monty](https://www.nuget.org/profiles/montyaahad)  | https://www.nuget.org/packages/web-design-standards/ |

:warning: **Some of the above are not affiliated with and have not been tested by the core team so use at your own discretion.**

If you know of more, leave a comment and we will update the above.

Eventually, this list will find a more permanent home.

**Comment by paultag** [comment]
:confetti_ball: thank you!

**Comment by paultag** [comment]
@maya mind updating the URL to https://github.com/department-of-veterans-affairs/django-designstandards ? Moved it this afternoon

**Comment by maya** [comment]
@paultag done, thanks!

**Comment by BrianDiggs** [comment]
I am not affiliated with this packaging except as user:

Type: NuGet package
Author: Abdul Ahad Monty (https://www.nuget.org/profiles/montyaahad)
URL: https://www.nuget.org/packages/web-design-standards/

**Comment by maya** [comment]
@BrianDiggs Added the NuGet package to the list. Thanks! :tada:

**Comment by maya** [comment]
Moving this to the wiki: https://github.com/18F/web-design-standards/wiki/Distribution-methods
