### ISSUE TITLE
Rethink developer documentation reference to _site/assets

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#885]
We are guiding people to download assets from the `_site` directory although people need to run the `./go serve` command (which runs jekyll) to get this locally. The reason we're doing this is bc you have to run jekyll in order to get compiled CSS. The assets folder includes everything except compiled CSS. 

Also we currently have all assets as a zip file, so should we update the instructions to have them get it from there?

References #875.

**Comment by maya** [comment]
Idea: instruct people to download the zip.

**Comment by garrypolley** [comment]
I like the idea of the zip download.  Could tell developers to go to the releases page: https://github.com/18F/web-design-standards/releases

**Comment by maya** [comment]
@garrypolley currently the zip file in github releases in the entire repository. We'd ilke them to download the assets `assets/releases/wds-v0.8.1.zip` on the repo or https://playbook.cio.gov/designstandards/assets/releases/wds-v0.8.1.zip
