### ISSUE TITLE
Sass folder naming preference: sass or scss?

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#887]
Our Sass is located in `assets/scss`, but do people prefer this folder be called `sass` instead? Sass means both the preprocessor and its own syntax. While it's true we're using scss syntax, I've seen most people call the folder by the language name, not syntax.

Thoughts?

**Comment by maya** [comment]
cc @alexose @vgvg @msecret @Scotchester

**Comment by vgvg** [comment]
No preference for me, I've seen it used both ways, I've even seen it in an assets/stylesheets folder.
