### ISSUE TITLE
Websites that use the Web Design Standards [Tracking]

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#895]
Here's a list of websites that use the Web Design Standards:

- US Digital Service Playbook - https://playbook.cio.gov
- Vets.gov - https://www.vets.gov/
- EPA e-manifest form - https://e-manifest.18f.gov/web
- Federal Election Commission (FEC) - https://beta.fec.gov/
- Social and Behavioral Sciences Team (SBST) - https://sbst.gov/
- Voter Registration - https://vote.usa.gov/
- USAJOBS - http://usajobs.github.io/design-system/
- USDA New Farmers - https://newfarmers.usda.gov/
- Template Tool - http://alexose.github.io/experiments/correspondence/
- USGS Earthquake Hazards Program - http://earthquake.usgs.gov/theme/ http://earthquake.usgs.gov/earthquakes/eventpage/ci37272591#general_summary 

Note: these websites are in different states of completion (e.g. prototype, MVP, live) and use the design standards at different levels of involvement (e.g. fonts, colors, components, frontend code).

Add a comment below to add another website to the list.

**Comment by juliaelman** [comment]
@maya added a new wiki page with this list here: https://github.com/18F/web-design-standards/wiki/Websites-that-use-the-Draft-U.S.-Web-Design-Standards

Since we have not had a lot of activity on this issue, 👍  to close in favor for the wiki page?

**Comment by maya** [comment]
@juliaelman yep! that works. Closing now. Wondering if we should add a note for people to email us new ones to add.
