### ISSUE TITLE
Rethink repo organization

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards#904]
Currently, we have a bunch of jekyll files mixed in with our downloadable assets. This makes our repo pretty confusing to to understand and work with. 

@jeremiak came up with this idea that we place all jekyll files in a single docs folder. That way we'll have two folders: docs (styleguide specific things) and assets (downloadable assets). It looks like this is what Google Material Design does too with their framework: https://github.com/google/material-design-lite

Previously, we mentioned separating out the assets and styleguide into their own repo but I think this approach works well. cc: @msecret + @juliaelman 

Related to #732.

**Comment by d3netxer** [comment]
Is this a Jekyll based site? Is this site built with a static site generator? This is something I would like to find out, I don't see it mentioned in the documentation.

**Comment by maya** [comment]
@d3netxer Yes, the styleguide site is built with Jekyll (the `./go` script does this for you). We thought people will mostly want to use the assets for their own projects and the styleguide site as secondary, which is why we didn't mention it in Getting started or the Installation. Maybe we could make this clearer!

**Comment by maya** [comment]
Closing in favor of #974.
