### ISSUE TITLE
Update licenses and attributions in 2016

### ISSUE THREAD

**Issue by melodykramer** [18F/web-design-standards#920]
Just a reminder to update any licenses/attributions to include year 2016 in January [here](https://github.com/18F/web-design-standards#a-few-parts-of-this-project-are-not-in-the-public-domain)

**Comment by melodykramer** [comment]
This [tweet](https://twitter.com/tieguy/status/675007171189321729) indicates that year may not be necessary. IANAL but think it's worth checking if it will prevent the need for yearly updates.

**Comment by maya** [comment]
Correct, the year is optional and not required. Neither is the © symbol. More info here: http://www.copyright.gov/circs/circ03.pdf 

It seems as though we should remove these since it's used in multiple places.

HT @brittag

**Comment by maya** [comment]
Closed via #922.
