### ISSUE TITLE
Create a WordPress Theme

### ISSUE THREAD

**Issue by bbertucc** [18F/web-design-standards#926]
**Description**
There is currently no WordPress theme that's specifically built to integrate the Web Design Standards

A well built WordPress theme will give users the ability to quickly launch a website or blog that integrates the Web Design Standards. Developers can further customize the theme, using it as a starting point or a parent for Child Theme customizations.

**Ask**
What would a USWDS WordPress theme look like?

How could the Standards educate the structure and theme elements?

What kind of features can enable consistency and beautiful user experiences across U.S. federal government websites?

**To Do**
- [ ] Attract collaborators to QA and build a USWDS theme
- [ ] Identify best practices for WordPress theming
- [ ] Build the USWDS Theme
- [ ] Test test test
- [ ] Submit theme to WordPress Theme Directory
- [ ] & Maintain

**Comment by bbertucc** [comment]
Started a repo with development roadmap for a USWDS theme: https://github.com/bbertucc/us-web-design-standards-wp

**Comment by jflowers45** [comment]
Thanks for starting this!

**Comment by colinpmacarthur** [comment]
Thanks for starting this @bbertucc! We're excited to keep an eye on this effort.

**Comment by carodew** [comment]
The focus of work for the product team in the near term will be to focus on providing a core set of web patterns that could be applied across frameworks – unfortunately creating themes for difference CMSs isn't in scope at the moment. But happy to follow the effort linked to above!
