### ISSUE TITLE
Create jumbotron-esque component

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#927]
@adelevie asked how to use the standards to make a container with different colored background with centered, large and padded text. I think this lines up well with Bootstrap's Jumbotron component: http://getbootstrap.com/components/#jumbotron.

I think a similar component in the standards (maybe with a different name) would help build this common design element without having to write specific and custom CSS.

**Comment by donjo** [comment]
This exists now at least in a basic form as the Hero component https://components.standards.usa.gov/components/detail/hero.html
