### ISSUE TITLE
Illustrator color swatch file suggestion

### ISSUE THREAD

**Issue by rtwell** [18F/web-design-standards#933]
I noticed that the file **web-design-standards-colors.ai** is essentially an empty Illustrator file with the USWDS swatches preloaded. I have 3 suggestions for this file:

1) Swatches in Illustrator should be Global Colors. This radically enhances how designers control color in Illustrator. Adobe has a [7 minute tutorial video here](https://helpx.adobe.com/illustrator/how-to/process-and-global-colors.html).

2) The AI color file could have objects pre-colored for designers to effortlessly load a few colors at a time into their documents instead of importing all of the USWDS colors. I would suggest something like this:
![possibleai](https://cloud.githubusercontent.com/assets/12564977/11902362/c7a96ec2-a576-11e5-839e-30b3fbc733be.png)
Then designers have a choice on how they want to add colors to their AI docs. I have created an AI file with all of these changes—I'm happy to provide if you're interested.

3) Some of the naming conventions used for the colors are counter-intuitive for designers. "Primary-alt" getting grouped with the Secondary colors doesn't make sense to me.

**Comment by Drakenhart** [comment]
Every designer has different patterns of behavior when it comes to their work flow. Not everyone is going to realize that the color swatches are pre-loaded.

I realized this myself a bit late and opted to create my own color boxes.

It makes it easier to have colored objects (circles or rectangles for example) on a Layer inside and Ai document.

So I agree and support @rtwell 's suggestion.

**Comment by carodew** [comment]
I'm all for this. :+1:

**Comment by carodew** [comment]
I think it might also be valuable to include the color contrast pairings for typography in the colors file (or the typography file). Thoughts?

**Comment by rtwell** [comment]
I think that is a great idea!

**Comment by Drakenhart** [comment]
Agreed @carodew that would also be helpful.

**Comment by carodew** [comment]
The original suggestion has been implemented, the current illustrator file has the color palette drawn out on the artboard and global colors. I'll create a separate issue for adding the color contrast pairings.
