### ISSUE TITLE
Errors in Typography_v.8.ai

### ISSUE THREAD

**Issue by rtwell** [18F/web-design-standards#934]
I noticed a few errors in the Typography_v.8.ai file included with the USWDS.

1) the word "copy" is misspelled as "capy" in several places. However reading this page with a Boston accent is hilarious. 
![screen shot 2015-12-18 at 11 18 53 am](https://cloud.githubusercontent.com/assets/12564977/11902660/2220dad2-a579-11e5-9143-cc0b07b8419e.png)

2) This type is misaligned (it should all be aligned to the left guide):
![screen shot 2015-12-18 at 11 22 01 am](https://cloud.githubusercontent.com/assets/12564977/11902728/950d24f6-a579-11e5-8252-f697e7db4950.png)

3) The guides are off (if someone wanted to use this file as a starting point—which is how I discovered FWIW)
![screen shot 2015-12-18 at 11 33 05 am](https://cloud.githubusercontent.com/assets/12564977/11902963/252aad0a-a57b-11e5-82a6-38b02014105c.png)

4) Length is misspelled:
![screen shot 2015-12-18 at 11 26 12 am](https://cloud.githubusercontent.com/assets/12564977/11902809/2f9d438e-a57a-11e5-9837-3bb07525532b.png)

**Comment by colinpmacarthur** [comment]
Re # 1: How did you know it wasn't purposeful, @rtwell? :)

**Comment by maya** [comment]
@rtwell @colinpmacarthur should we move this over to https://github.com/18F/web-design-standards-assets since it deals with the design assets?

**Comment by rtwell** [comment]
up to you. i knew that repo existed but couldn't find it…seems simpler to
keep all things USWDS in one repo, but i'm not github power-user either.

**Comment by maya** [comment]
@rtwell good point, we may end up updating how things are organized too, so no worries.

**Comment by carodew** [comment]
@rtwell What's going on with the guides preview? Are the pink boxes indicating where the guides should be located?

**Comment by carodew** [comment]
Eeenyway – fixed all of these issues except the guides alignment issue in this PR: https://github.com/18F/web-design-standards-assets/pull/20

**Comment by juliaelman** [comment]
Fixed via https://github.com/18F/web-design-standards-assets/pull/20 and https://github.com/18F/web-design-standards-assets/pull/25
