### ISSUE TITLE
Add support for an HTML table with headers along the top and left side

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards#941]
User story:
I am making a website that links to documents. I have 150 documents available in three categories over 50 years, I would want to display those in a 4x51 table that indicates the year and type of document as categories/headers.

**Comment by maya** [comment]
I chatted with @wslack about this and he was not using USWDS for the project but just looking if he could use something from here. He's looking for additional table styles.

**Comment by maya** [comment]
I believe there was an independent solve for this, so closing this out.

**Comment by wslack** [comment]
@maya I didn't solve it with an additional style, but it's not a vital feature for me. :)
