### ISSUE TITLE
Auto-508-compliant text colors

### ISSUE THREAD

**Issue by rossdakin** [18F/web-design-standards#945]
Half baked feature request.

Motivation: https://css-tricks.com/reverse-text-color-mix-blend-mode/

It would be awesome if there were some facility for automatically 508-compliant text colors (i.e. if text could automatically become sufficiently contrasted with its background color).

This may be unnecessary if the suggested foreground/background colors are explicitly adhered to, but could be useful perhaps as a "just in case" fallback.

**Comment by maya** [comment]
@rossdakin it's definitely important that people use accessible colors, but I'm not sure if the experience of colors changing before your eyes will provide a good experience and enough control. The colors that the design standards provide, if used per the documentation, will be accessible. If people choose to use different colors from the provided palette, we recommend you to test color combinations compliance using color contrast tools.

**Comment by carodew** [comment]
This is a really cool idea but out of scope for what we're doing. The roadmap will be made public soon, stay tuned!
