### ISSUE TITLE
Disabled Outline Buttons

### ISSUE THREAD

**Issue by bbertucc** [18F/web-design-standards#947]
**Description:**
There is no "disabled" style for buttons with the classes `usa-button-outline` or `usa-button-outline-inverse`.

**Ask/To-Do:**
- [ ] Add a `usa-button-outline-disabled` and `usa-button-outline-inverse-disabled` class or amend the `usa-button-disabled` class to include style that updates all button classes.

**Additional Info:**
A disabled outline button could contain a lightened white border and text color for the standard button, and lightened black for the inverted button. 

Here's are example buttons with `rgba(0, 0, 0, .3)` for the standard version and `rgba(255, 255, 255, .3)` for the inverted version:
<img width="114" alt="screen shot 2016-01-10 at 1 59 28 pm" src="https://cloud.githubusercontent.com/assets/46652/12223641/6eb8adc6-b7a2-11e5-8563-747a4ce0cde8.png">

**Comment by maya** [comment]
Related to https://github.com/18F/web-design-standards/issues/944.

**Comment by maya** [comment]
@bbertucc Thanks for your request! We'll take a look at this and let you know if it's something that we see as a need to build out. Stay tuned!

**Comment by donjo** [comment]
The outline buttons have been updated in v1.4 so you can check out the current styles [here](https://components.standards.usa.gov/components/detail/buttons--secondary.html) under the "Secondary" and "Secondary Inverse" styles.
