### ISSUE TITLE
Download link in README broken

### ISSUE THREAD

**Issue by jessieay** [18F/web-design-standards#951]
When I click on https://playbook.cio.gov/designstandards/assets/releases/wds-v0.9.0.zip in the README, I see this:

![screen shot 2016-01-12 at 2 39 22 pm](https://cloud.githubusercontent.com/assets/601515/12279136/4202ed98-b93a-11e5-9cd0-030c3a7826b2.png)

**Comment by maya** [comment]
Thanks @jessieay. When when the staging branch gets pushed to production this will be resolved.

**Comment by maya** [comment]
Fixed via https://github.com/18F/web-design-standards/pull/966.
