### ISSUE TITLE
Dropdown Alignment and Box height

### ISSUE THREAD

**Issue by 20Fourteen** [18F/web-design-standards#957]
I noticed that the dropdown input is slightly higher than standard input boxes, also when used in a form the dropdown is not perfectly aligned with the other inline input boxes.

![1](https://cloud.githubusercontent.com/assets/8763290/12324220/0cd7f7a0-bab9-11e5-8d9c-0344814fbd3b.gif)

**Comment by maya** [comment]
Thanks so much for opening this issue! Based on the gif, it looks like you observed this in Firefox?

Note: in Chrome (below), the height is 44px:
![screen shot 2016-01-25 at 3 48 12 pm](https://cloud.githubusercontent.com/assets/5249443/12568569/c3e18c3e-c37b-11e5-8198-1fbe525c280f.png)

**Comment by 20Fourteen** [comment]
I tested this again in Chrome (using latest version and with no extensions), here is the result. Note that I'm using the zip file from https://playbook.cio.gov/designstandards/all/ if this has been fixed since, then you can close this issue.

Based on the fonts, your image seems to be an updated version of the code

![123](https://cloud.githubusercontent.com/assets/8763290/12580615/e520dee2-c428-11e5-97c4-32e1f220f782.gif)

**Comment by maya** [comment]
@20Fourteen I think you're original post is right on! I just wanted to specify that the issue only occurs in Firefox and not in Chrome. So we will have to debug this for Firefox.

**Comment by maya** [comment]
Fixed in #1099.
