### ISSUE TITLE
[ npm-publish ] Should the uswds package be scoped to @18f

### ISSUE THREAD

**Issue by rogeruiz** [18F/web-design-standards#961]
Reading about [npm-scope here](https://docs.npmjs.com/misc/scope) and seeing it
in [another 18F npm package that was recently published](https://github.com/18f/private-eye),
should this package be scoped under the 18F organization?

If we should scope it to 18F, then we'd just need to update the name in the
`package.json` along with updating the documentation around installation to
include the `@18f/` scope when installing. The following is an example:
`npm install --save @18f/uswds`

**Comment by maya** [comment]
Good point, cc: @juliaelman @msecret @mbland

**Comment by juliaelman** [comment]
:+1: let's do it!

**Comment by msecret** [comment]
I'm actually not sure I agree with this.

**Comment by maya** [comment]
@msecret what would you recommend?

**Comment by rogeruiz** [comment]
For this project in particular, I don't think it's necessary to scope it. There also seems to be some `npm` related errors to linking and scoped packages that would require the documentation to be updated. So I'm going to be closing this issue for now.
