### ISSUE TITLE
[Grid] De-nest usa-width-* classes in _grids.scss to decrease file size

### ISSUE THREAD

**Issue by webinista** [18F/web-design-standards#971]
Nesting `usa-width-*` classes inside of the `.usa-grid, .usa-grid-full` block adds more bytes than necessary to achieve the result.

This SCSS:

    .usa-grid,
    .usa-grid-full {
        @include outer-container();
        max-width: $site-max-width;

        @include media($medium) {
              .usa-width-one-whole {
                   @include span-columns(6);
           }
          // ... etc.
    }

Compiles to:

     @media screen and (min-width: 600px) {
        .usa-grid .usa-width-one-whole,
        .usa-grid-full .usa-width-one-whole {
             // rules removed.
        }
    }

Since those `.usa-width-one-whole` styles are the same regardless of their parent, there's no need to nest them within a `.usa-grid, .usa-grid-full` ruleset. 

**To Fix**

- Add a closing `}` on line 5
- Remove the closing `}` on line 108.

**Comment by maya** [comment]
Agree that if we don't need the nesting then we should remove.
