### ISSUE TITLE
[Question] Are the .usa-button-hover, .usa-button-focus, .usa-button-active, and .usa-button-disabled classes necessary?

### ISSUE THREAD

**Issue by webinista** [18F/web-design-standards#973]
I think pseudo-classes `:hover`, `:active`, and  `:focus` are supported for buttons as far back as Internet Explorer 7. `:disabled` is supported by Internet Explorer 9. Do we need to include separate classes for `.usa-button-hover`, `.usa-button-focus`, `.usa-button-active`, and `.usa-button-disabled`? 

I see that these classes are being used on the [style guide demo pages](https://playbook.cio.gov/designstandards/buttons/). However, they seem redundant for production-ready CSS.

**Comment by maya** [comment]
@webinista In addition to those classes being used to display the styles on the styleguide website, I think it was kept in the production CSS so you could easily use the selectors with JS.

@msecret is that correct?

**Comment by msecret** [comment]
Yes, the idea was that you could manipulate those classes with JavaScript in certain circumstances.

**Comment by webinista** [comment]
Makes sense.
