### ISSUE TITLE
Updating structure for the web-design-standards Github repository

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#974]
## User Story 
https://trello.com/c/jPnKDPnl/36-as-a-developer-on-the-wds-i-want-to-be-able-to-clearly-understand-the-file-structure-of-the-wds-repo-at-a-glance

## Acceptance Criteria

- [ ] History of the original repo should be maintained and not lost.
- [ ] The maintenance between the public-facing website and the developer-focused package should be easily done without having to sync or copy files between the two

**Comment by maya** [comment]
Related to #752.
