### ISSUE TITLE
Question: Why wrap grid rows?

### ISSUE THREAD

**Issue by bbgvisualjournalist** [18F/web-design-standards#982]
Hi. not sure if you prefer questions in GitHub issues or elsewhere - let me know if there's a better place.

In the documentation you say, "To use the grid, wrap each grid row in a <div> with the usa-grid class."

Because we're using Bourbon/Neat for the grid, why do we need to wrap it? This is my first time using Neat, but it seems like we should be able to use nth-child to handle the rows and wrapping without the additional div container.  We prefer not to wrap every row as it complicates the markup.

.gallery .item:nth-child(4n) { margin-right: 0; }
.gallery .item:nth-child(4n+1) { clear: left; }

Thanks!

**Comment by maya** [comment]
Thanks for your question!

You need a container to apply a max-width and margins to. Neat just allows you to do it to a semantic container. 

The second reason is wrapping it allows us to trigger the correct nth child for responsive layouts where we need to remove margins on different screen sizes. Without it, we wouldn't be able to call the correct column bc the child numbers would get mixed up with the rows below and above it. Note: we started trying to do it without the grid wrapped but ran into issues for this reason.

We use GitHub so everything is in the open and everyone can benefit from discussion. Someone else might have this question too. If you prefer to email us, we're at uswebdesignstandards@gsa.gov, but this type of question is good for GitHub.
