### ISSUE TITLE
"Return to top" link in footers

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards#990]
I can't promise I know what I'm talking about, but the "return to top" links on https://playbook.cio.gov/designstandards/footers/ don't actually return me to the top of the page. However, the links on https://github.com/18F/web-design-standards/blob/18f-pages-staging/docs/_components/footers.md, where the code lives, do return me to the top. That's confusing.

Separately, in looking for "return to top" links in the wild, I didn't see any sites using them. Do we need to have these in the code if they aren't being used?

**Comment by maya** [comment]
That's a good catch @wslack! We disabled the ability for clicking the hash `#` to return to the top of the page bc we're using it as a fake link on the footer links and didn't want someone to accidentally click a link and it go to the top. I didn't realize that by doing this, we removed the functionality of hitting the top of the page on the button it's meant to. That seems like it could be confusing!

To fix this we need to add a class to our JS to only target this function on `usa-footer-primary-section` class and anywhere else we'd like that behavior.

**Comment by wslack** [comment]
Thanks @maya! If you do know of sites using that link, would like to see how that looks in practice.

**Comment by carodew** [comment]
You know, we overrode that behavior without really considering whether or not people wanted to be able to test the functionality. It might be worth thinking about undo-ing that, or it might be something we think about including in page templates.

**Comment by Drakenhart** [comment]
Return to top is sometimes used in FAQs if the list is long.
With Government websites as complex as they are sometimes, they often have massive FAQ lists.

Something to think about. ^.^

**Comment by j-ta** [comment]
I am working on this.

**Comment by bradnunnally** [comment]
@j-ta Awesome! Let me know how it goes and if you have any comments you'd like to share. I'm sitting over by the wall.
